{
  "formatVersion": "1.1",
  "component": {
    "group": "com.vickyleu.kotlinx",
    "module": "kotlinx-rpc-krpc-ktor-core",
    "version": "0.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "com.vickyleu.kotlinx",
          "module": "kotlinx-rpc-krpc-core",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-websockets",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-rpc-krpc-ktor-core-metadata-0.6.1.jar",
          "url": "kotlinx-rpc-krpc-ktor-core-0.6.1.jar",
          "size": 2764,
          "sha512": "e24ad028e55fbe34f2e590f6cdbdd0cd72e37300281f015a282cf19be9bab498b797c0eb584b1a99f6059f25964b1310c139a71eefa7af7d445364d78b8a6868",
          "sha256": "ed1ed8399d5ba0798b3fb54d7a3105a4645080ab62a7f82a848dce7cc68c0ad0",
          "sha1": "5ed9e4863f611d5c756359b7d8ed1067f41c73d8",
          "md5": "6251a9db652c7cc4c446e09921fe60e9"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kotlinx-rpc-krpc-ktor-core-kotlin-0.6.1-sources.jar",
          "url": "kotlinx-rpc-krpc-ktor-core-0.6.1-sources.jar",
          "size": 1686,
          "sha512": "44a6419ceeecc94824e017b415f80765af8cc82ace7dbba25d407260aa1f6546e5dd8a9e15c6c2b27edc556796806416ca68703a672c6e50506675500e897dd9",
          "sha256": "aa04308edf1ce343ee7e2a5cb3d1ea2beb1ab591731d87a71e47c7b54722b900",
          "sha1": "dc97cf7530cf4d5450e912d6cf9e0d58199ee9bc",
          "md5": "6d8d30484c72ad16bc70dcdb8c6a7a16"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-iosarm64/0.6.1/kotlinx-rpc-krpc-ktor-core-iosarm64-0.6.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-iosarm64",
        "version": "0.6.1"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-iosarm64/0.6.1/kotlinx-rpc-krpc-ktor-core-iosarm64-0.6.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-iosarm64",
        "version": "0.6.1"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-iosarm64/0.6.1/kotlinx-rpc-krpc-ktor-core-iosarm64-0.6.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-iosarm64",
        "version": "0.6.1"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-iossimulatorarm64/0.6.1/kotlinx-rpc-krpc-ktor-core-iossimulatorarm64-0.6.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-iossimulatorarm64",
        "version": "0.6.1"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-iossimulatorarm64/0.6.1/kotlinx-rpc-krpc-ktor-core-iossimulatorarm64-0.6.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-iossimulatorarm64",
        "version": "0.6.1"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-iossimulatorarm64/0.6.1/kotlinx-rpc-krpc-ktor-core-iossimulatorarm64-0.6.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-iossimulatorarm64",
        "version": "0.6.1"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-iosx64/0.6.1/kotlinx-rpc-krpc-ktor-core-iosx64-0.6.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-iosx64",
        "version": "0.6.1"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-iosx64/0.6.1/kotlinx-rpc-krpc-ktor-core-iosx64-0.6.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-iosx64",
        "version": "0.6.1"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-iosx64/0.6.1/kotlinx-rpc-krpc-ktor-core-iosx64-0.6.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-iosx64",
        "version": "0.6.1"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-js/0.6.1/kotlinx-rpc-krpc-ktor-core-js-0.6.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-js",
        "version": "0.6.1"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-js/0.6.1/kotlinx-rpc-krpc-ktor-core-js-0.6.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-js",
        "version": "0.6.1"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-js/0.6.1/kotlinx-rpc-krpc-ktor-core-js-0.6.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-js",
        "version": "0.6.1"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-jvm/0.6.1/kotlinx-rpc-krpc-ktor-core-jvm-0.6.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-jvm",
        "version": "0.6.1"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-jvm/0.6.1/kotlinx-rpc-krpc-ktor-core-jvm-0.6.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-jvm",
        "version": "0.6.1"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-jvm/0.6.1/kotlinx-rpc-krpc-ktor-core-jvm-0.6.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-jvm",
        "version": "0.6.1"
      }
    },
    {
      "name": "linuxArm32HfpApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm32_hfp",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-linuxarm32hfp/0.6.1/kotlinx-rpc-krpc-ktor-core-linuxarm32hfp-0.6.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-linuxarm32hfp",
        "version": "0.6.1"
      }
    },
    {
      "name": "linuxArm32HfpSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm32_hfp",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-linuxarm32hfp/0.6.1/kotlinx-rpc-krpc-ktor-core-linuxarm32hfp-0.6.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-linuxarm32hfp",
        "version": "0.6.1"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-linuxarm64/0.6.1/kotlinx-rpc-krpc-ktor-core-linuxarm64-0.6.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-linuxarm64",
        "version": "0.6.1"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-linuxarm64/0.6.1/kotlinx-rpc-krpc-ktor-core-linuxarm64-0.6.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-linuxarm64",
        "version": "0.6.1"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-linuxx64/0.6.1/kotlinx-rpc-krpc-ktor-core-linuxx64-0.6.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-linuxx64",
        "version": "0.6.1"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-linuxx64/0.6.1/kotlinx-rpc-krpc-ktor-core-linuxx64-0.6.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-linuxx64",
        "version": "0.6.1"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-macosarm64/0.6.1/kotlinx-rpc-krpc-ktor-core-macosarm64-0.6.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-macosarm64",
        "version": "0.6.1"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-macosarm64/0.6.1/kotlinx-rpc-krpc-ktor-core-macosarm64-0.6.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-macosarm64",
        "version": "0.6.1"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-macosarm64/0.6.1/kotlinx-rpc-krpc-ktor-core-macosarm64-0.6.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-macosarm64",
        "version": "0.6.1"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-macosx64/0.6.1/kotlinx-rpc-krpc-ktor-core-macosx64-0.6.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-macosx64",
        "version": "0.6.1"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-macosx64/0.6.1/kotlinx-rpc-krpc-ktor-core-macosx64-0.6.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-macosx64",
        "version": "0.6.1"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-macosx64/0.6.1/kotlinx-rpc-krpc-ktor-core-macosx64-0.6.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-macosx64",
        "version": "0.6.1"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-mingwx64/0.6.1/kotlinx-rpc-krpc-ktor-core-mingwx64-0.6.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-mingwx64",
        "version": "0.6.1"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-mingwx64/0.6.1/kotlinx-rpc-krpc-ktor-core-mingwx64-0.6.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-mingwx64",
        "version": "0.6.1"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-tvosarm64/0.6.1/kotlinx-rpc-krpc-ktor-core-tvosarm64-0.6.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-tvosarm64",
        "version": "0.6.1"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-tvosarm64/0.6.1/kotlinx-rpc-krpc-ktor-core-tvosarm64-0.6.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-tvosarm64",
        "version": "0.6.1"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-tvosarm64/0.6.1/kotlinx-rpc-krpc-ktor-core-tvosarm64-0.6.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-tvosarm64",
        "version": "0.6.1"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-tvossimulatorarm64/0.6.1/kotlinx-rpc-krpc-ktor-core-tvossimulatorarm64-0.6.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-tvossimulatorarm64",
        "version": "0.6.1"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-tvossimulatorarm64/0.6.1/kotlinx-rpc-krpc-ktor-core-tvossimulatorarm64-0.6.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-tvossimulatorarm64",
        "version": "0.6.1"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-tvossimulatorarm64/0.6.1/kotlinx-rpc-krpc-ktor-core-tvossimulatorarm64-0.6.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-tvossimulatorarm64",
        "version": "0.6.1"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-tvosx64/0.6.1/kotlinx-rpc-krpc-ktor-core-tvosx64-0.6.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-tvosx64",
        "version": "0.6.1"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-tvosx64/0.6.1/kotlinx-rpc-krpc-ktor-core-tvosx64-0.6.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-tvosx64",
        "version": "0.6.1"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-tvosx64/0.6.1/kotlinx-rpc-krpc-ktor-core-tvosx64-0.6.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-tvosx64",
        "version": "0.6.1"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-wasm-js/0.6.1/kotlinx-rpc-krpc-ktor-core-wasm-js-0.6.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-wasm-js",
        "version": "0.6.1"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-wasm-js/0.6.1/kotlinx-rpc-krpc-ktor-core-wasm-js-0.6.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-wasm-js",
        "version": "0.6.1"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-wasm-js/0.6.1/kotlinx-rpc-krpc-ktor-core-wasm-js-0.6.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-wasm-js",
        "version": "0.6.1"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-watchosarm32/0.6.1/kotlinx-rpc-krpc-ktor-core-watchosarm32-0.6.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-watchosarm32",
        "version": "0.6.1"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-watchosarm32/0.6.1/kotlinx-rpc-krpc-ktor-core-watchosarm32-0.6.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-watchosarm32",
        "version": "0.6.1"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-watchosarm32/0.6.1/kotlinx-rpc-krpc-ktor-core-watchosarm32-0.6.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-watchosarm32",
        "version": "0.6.1"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-watchosarm64/0.6.1/kotlinx-rpc-krpc-ktor-core-watchosarm64-0.6.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-watchosarm64",
        "version": "0.6.1"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-watchosarm64/0.6.1/kotlinx-rpc-krpc-ktor-core-watchosarm64-0.6.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-watchosarm64",
        "version": "0.6.1"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-watchosarm64/0.6.1/kotlinx-rpc-krpc-ktor-core-watchosarm64-0.6.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-watchosarm64",
        "version": "0.6.1"
      }
    },
    {
      "name": "watchosDeviceArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-watchosdevicearm64/0.6.1/kotlinx-rpc-krpc-ktor-core-watchosdevicearm64-0.6.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-watchosdevicearm64",
        "version": "0.6.1"
      }
    },
    {
      "name": "watchosDeviceArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-watchosdevicearm64/0.6.1/kotlinx-rpc-krpc-ktor-core-watchosdevicearm64-0.6.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-watchosdevicearm64",
        "version": "0.6.1"
      }
    },
    {
      "name": "watchosDeviceArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-watchosdevicearm64/0.6.1/kotlinx-rpc-krpc-ktor-core-watchosdevicearm64-0.6.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-watchosdevicearm64",
        "version": "0.6.1"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-watchossimulatorarm64/0.6.1/kotlinx-rpc-krpc-ktor-core-watchossimulatorarm64-0.6.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-watchossimulatorarm64",
        "version": "0.6.1"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-watchossimulatorarm64/0.6.1/kotlinx-rpc-krpc-ktor-core-watchossimulatorarm64-0.6.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-watchossimulatorarm64",
        "version": "0.6.1"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-watchossimulatorarm64/0.6.1/kotlinx-rpc-krpc-ktor-core-watchossimulatorarm64-0.6.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-watchossimulatorarm64",
        "version": "0.6.1"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-watchosx64/0.6.1/kotlinx-rpc-krpc-ktor-core-watchosx64-0.6.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-watchosx64",
        "version": "0.6.1"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-watchosx64/0.6.1/kotlinx-rpc-krpc-ktor-core-watchosx64-0.6.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-watchosx64",
        "version": "0.6.1"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-watchosx64/0.6.1/kotlinx-rpc-krpc-ktor-core-watchosx64-0.6.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-watchosx64",
        "version": "0.6.1"
      }
    }
  ]
}
