{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-rpc-krpc-client/0.5.1/kotlinx-rpc-krpc-client-0.5.1.module",
    "group": "com.vickyleu.kotlinx",
    "module": "kotlinx-rpc-krpc-client",
    "version": "0.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.vickyleu.kotlinx",
          "module": "kotlinx-rpc-krpc-core",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-rpc-krpc-client-jvm-0.5.1.jar",
          "url": "kotlinx-rpc-krpc-client-jvm-0.5.1.jar",
          "size": 56988,
          "sha512": "bd86fa65e63ae5d1e85378d71d42ddcea75688ac75204087e3c9c39b8ef52ff05d77261131c907caf8360b3a38c100b0e0d21b91b41606fc4467c62996227950",
          "sha256": "cb22a229c3b3b9687c5afa08812505063f50652f8f12cc84e0decb1e456d2abe",
          "sha1": "af46021b99d40b819672a677d3ee7abf166d98e2",
          "md5": "1b50ebb04c1ae3482239a300f8e306c5"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.vickyleu.kotlinx",
          "module": "kotlinx-rpc-krpc-core",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.kotlinx",
          "module": "kotlinx-rpc-krpc-logging",
          "version": {
            "requires": "0.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-rpc-krpc-client-jvm-0.5.1.jar",
          "url": "kotlinx-rpc-krpc-client-jvm-0.5.1.jar",
          "size": 56988,
          "sha512": "bd86fa65e63ae5d1e85378d71d42ddcea75688ac75204087e3c9c39b8ef52ff05d77261131c907caf8360b3a38c100b0e0d21b91b41606fc4467c62996227950",
          "sha256": "cb22a229c3b3b9687c5afa08812505063f50652f8f12cc84e0decb1e456d2abe",
          "sha1": "af46021b99d40b819672a677d3ee7abf166d98e2",
          "md5": "1b50ebb04c1ae3482239a300f8e306c5"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlinx-rpc-krpc-client-jvm-0.5.1-sources.jar",
          "url": "kotlinx-rpc-krpc-client-jvm-0.5.1-sources.jar",
          "size": 5885,
          "sha512": "338def426f7ced906ef667ec8bb6cc2b2577df18db9419ff6c4d9a22c8e59c00cd9b33cb61fe7e7401f9e794bc6c720200b032d996a1c72859bd3f5423213ab7",
          "sha256": "4688f68db5017c4014e0ae8ce45ffeb7d8cc9dd563a322c8fbd605af66e919a4",
          "sha1": "5e65539788c0377b4da18cdfaf675b21fbf79dfe",
          "md5": "5ea56adac91bb44418b14dbdea2b8cd2"
        }
      ]
    }
  ]
}
