{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-host-common/3.1.2-SNAPSHOT/ktor-server-host-common-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-server-host-common",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-host-common-macosArm64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-host-common-macosarm64-3.1.2-SNAPSHOT.klib",
          "size": 3449,
          "sha512": "d96c9918802c9619963e5bf2a1eeb62335374229a1fe6c810aea3481085c8a4646cdc0a7676575825a4cfcd8436abb035f7b05d2212665e0060717f3355b4619",
          "sha256": "8b877daf762a50971b97c7e4c4fb3c13f36fff08126b797e732cd74f2cc33816",
          "sha1": "9d9fa199856825d32af14cff97d85bd21507adb1",
          "md5": "3f184dd8e562103118b61813aac4d353"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-server-host-common-macosarm64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-server-host-common-macosarm64-3.1.2-SNAPSHOT-sources.jar",
          "size": 621,
          "sha512": "f04f945d6a7d30a53537aa03c5b9ff5f72e60e4150cc04bec3114161649c0177f6ef2d801ca541f66ae5e2a12a40c6f5560f6c166f14e70f3731a9b77361aced",
          "sha256": "8f1b77aa660fed1302454fd2a303ab07ab29a5d52029c98850cedff554c454f0",
          "sha1": "ee19f777cd0f857f7e5bccd5eacb04c7496d9a13",
          "md5": "5b14dfc1ec7145751b60a8479edee37d"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-host-common-macosarm64-3.1.2-SNAPSHOT-metadata.jar",
          "url": "ktor-server-host-common-macosarm64-3.1.2-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "6756e4f4d75e0a5439ee31eec1dc50634e7a1395ecfafa2a611311e4c4217f894d598a4964416a8324dade2ef3adb8e35d9a2f006cdfc6935d8c4ab1736d0f54",
          "sha256": "4ae9538557db631c64d81d1caf258bbee59e839dd9825504d12aa1b6507c6357",
          "sha1": "941afe4f2da1ecaf724a316c0d1e040c0d326185",
          "md5": "7ee9936e9a8bff63d993877e94076199"
        }
      ]
    }
  ]
}
