{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-client-encoding/3.1.2-SNAPSHOT/ktor-client-encoding-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-client-encoding",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "linuxArm32HfpApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm32_hfp",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-encoding-linuxArm32HfpMain-3.1.2-SNAPSHOT.klib",
          "url": "ktor-client-encoding-linuxarm32hfp-3.1.2-SNAPSHOT.klib",
          "size": 22838,
          "sha512": "9429a296c5064c96d6096eafab8f399a727c2787ff5b012df5ecaa27cf2466a3e82dab3ae68492984c2bad71025522b3a8562b7c04174f2e238191094bf9e2f3",
          "sha256": "a471695fcab686b4b3c3eb3e8fb9751938f30672bb81a557988f6a012c69830e",
          "sha1": "324583ac814fd9b67437002a7430f52a1f5dca87",
          "md5": "9aa1bb343e0076af2a62a983875a3a39"
        }
      ]
    },
    {
      "name": "linuxArm32HfpSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm32_hfp",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-client-encoding-linuxarm32hfp-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-client-encoding-linuxarm32hfp-3.1.2-SNAPSHOT-sources.jar",
          "size": 3218,
          "sha512": "7485eb61a1380e1be058b38bf5f7cd4c225d67f57dc2883cd701b61404ebad36414d8f1089bd641680c2b0f8e5a3156676e90cbc416f2b4a4bb76acf52100a47",
          "sha256": "ce606b2cdc86a8287c01e12dff5a721fe8a37f2bd41ab69926fe1b5b5f4b252e",
          "sha1": "80c2638ddc263fb7183f816fa964a5a798a82d8f",
          "md5": "cf21e5d120a76f6aacb7059c0245091d"
        }
      ]
    }
  ]
}
