{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-io/3.1.2-SNAPSHOT/ktor-io-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-io",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "linuxArm32HfpApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm32_hfp",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-io-linuxArm32HfpMain-3.1.2-SNAPSHOT.klib",
          "url": "ktor-io-linuxarm32hfp-3.1.2-SNAPSHOT.klib",
          "size": 193253,
          "sha512": "1d0853bb5035682a13223caa70bdeb1c0a0df1b5f8ac6fdc1ed56c4079ad7a8cb928eddd13338eebd937ca87a80c7e0b134f4a81c1b31f8501bc1976d5220c50",
          "sha256": "48c4c961dd7b754d0a0508e85ca4f9a1c0353b52fd57c6c2c2c3423bb079a524",
          "sha1": "a107d1f2089926ba9065ead95c5ee52f0924cad2",
          "md5": "ebd7cec5957a0b667f8f262eabd20d88"
        },
        {
          "name": "ktor-io-linuxArm32HfpCinterop-mutexMain-3.1.2-SNAPSHOT.klib",
          "url": "ktor-io-linuxarm32hfp-3.1.2-SNAPSHOT-cinterop-mutex.klib",
          "size": 10160,
          "sha512": "cf3776d853c54a76139cb0b8630b729b4338ebec181015457ff858c439823fdbc346f13d7e23efa6c3b552d637e3e14915d8ebff078dcbfcf643d80179778bc3",
          "sha256": "7b5f0284270f37268848a49bef60b66e4b137e1ebc4503e9333f0bd850488d51",
          "sha1": "e3ce183209ba5338e02f33e23e160467380381a9",
          "md5": "47672b9f513d167c639195a90f7e6c9f"
        }
      ]
    },
    {
      "name": "linuxArm32HfpSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm32_hfp",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-io-linuxarm32hfp-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-io-linuxarm32hfp-3.1.2-SNAPSHOT-sources.jar",
          "size": 57110,
          "sha512": "3898c18058caacb1dd6254fa2d4c9d92a332eb1d66bc77340d113c9d5b0052bbaf714208e16d813878f4cb0d52a91a79700f5ef01ea9a0a68576eae5cfbf92a2",
          "sha256": "3f289f9319e0b38373925750e6308efb19938a30174a70d1a1e7697992a21bac",
          "sha1": "ccd5ae5efee1c69403a4264ac134616da9f44c6b",
          "md5": "07f63bc3a563fa72204d81f01a336f83"
        }
      ]
    }
  ]
}
