{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-sse/3.1.2-SNAPSHOT/ktor-server-sse-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-server-sse",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-sse",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-sse-mingwX64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-sse-mingwx64-3.1.2-SNAPSHOT.klib",
          "size": 23272,
          "sha512": "759df4671a3ad070785032ccf13289425f190ccee1c29e2bdfb288175231427ef72465f60335502109fe20d445e9027225a2b3d02faeb6384c46f9cf45044df9",
          "sha256": "e4501ae569f765b632494732aeab0746be5d0f61bc2889eb2b8261b2314aa524",
          "sha1": "2240866302892afc95203754e992e3d58b42c4a8",
          "md5": "4cdec54ea50499c555041dda6e93661a"
        }
      ]
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-server-sse-mingwx64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-server-sse-mingwx64-3.1.2-SNAPSHOT-sources.jar",
          "size": 6935,
          "sha512": "2c60830cbfd64fdfe911bf6596423bf094ca25deaa77cdd05fd9b32fba0e03bf4e182187b3bc49f7841a94bada60934b9c6a726018b3d4b186da30c21572f8bc",
          "sha256": "513c0f6d91cdb398573389889266a510caee1f0b119540317d64758b2f815e87",
          "sha1": "1da279d6d7eaecc69e64e993585290081a3530b5",
          "md5": "f30f88f85270b7ada2d49798e4f33cac"
        }
      ]
    }
  ]
}
