{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-rpc-krpc-ktor-core/0.6.1/kotlinx-rpc-krpc-ktor-core-0.6.1.module",
    "group": "com.vickyleu.kotlinx",
    "module": "kotlinx-rpc-krpc-ktor-core",
    "version": "0.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.vickyleu.kotlinx",
          "module": "kotlinx-rpc-krpc-core",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-websockets",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-rpc-krpc-ktor-core-watchosArm32Main-0.6.1.klib",
          "url": "kotlinx-rpc-krpc-ktor-core-watchosarm32-0.6.1.klib",
          "size": 6327,
          "sha512": "1cc8ab041a5ad209317a315640a06bb0cdf4a657d49c7466e02fc4d065c51bf33cccf2f79c51251fb3999ec099181c687cc12f5c1990253f761d467d5e7e17a8",
          "sha256": "9f31396b3abb3c4671bdf2502f2457311c33d3754d75702aeb1525b930faabc9",
          "sha1": "c7c4c6281d4634eda3c678e5fc5416010fb54204",
          "md5": "cf61d0f6e1c875dc8151f6b605231900"
        }
      ]
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-rpc-krpc-ktor-core-watchosarm32-0.6.1-sources.jar",
          "url": "kotlinx-rpc-krpc-ktor-core-watchosarm32-0.6.1-sources.jar",
          "size": 1686,
          "sha512": "44a6419ceeecc94824e017b415f80765af8cc82ace7dbba25d407260aa1f6546e5dd8a9e15c6c2b27edc556796806416ca68703a672c6e50506675500e897dd9",
          "sha256": "aa04308edf1ce343ee7e2a5cb3d1ea2beb1ab591731d87a71e47c7b54722b900",
          "sha1": "dc97cf7530cf4d5450e912d6cf9e0d58199ee9bc",
          "md5": "6d8d30484c72ad16bc70dcdb8c6a7a16"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.vickyleu.kotlinx",
          "module": "kotlinx-rpc-krpc-core",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-websockets",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-rpc-krpc-ktor-core-watchosarm32-0.6.1-metadata.jar",
          "url": "kotlinx-rpc-krpc-ktor-core-watchosarm32-0.6.1-metadata.jar",
          "size": 261,
          "sha512": "8ea634e043cdc987a78ae65ade11df005c69971ec4d661a294d0f9b56e8b53f15f692ec8b8835b4940048e22ab2d99f0b67401707421045044d8b3258efec420",
          "sha256": "b6dc11feb30bfd1b88844ae0534e8b4173b7631e9f8e68fe52cf9ff40e14e67e",
          "sha1": "cf25ec42da0d38294d0d1aa003ac6f978d2a79ed",
          "md5": "a782f503381f809e4e375a26e7f1d8bc"
        }
      ]
    }
  ]
}
