{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-rpc-grpc-core/0.5.1/kotlinx-rpc-grpc-core-0.5.1.module",
    "group": "com.vickyleu.kotlinx",
    "module": "kotlinx-rpc-grpc-core",
    "version": "0.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.vickyleu.kotlinx",
          "module": "kotlinx-rpc-core",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "com.vickyleu.kotlinx",
          "module": "kotlinx-rpc-utils",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-rpc-grpc-core-macosArm64Main-0.5.1.klib",
          "url": "kotlinx-rpc-grpc-core-macosarm64-0.5.1.klib",
          "size": 27120,
          "sha512": "2c14674c2b4699f7b1f5c2ce60cd36cd18cb80390ad7207e720cd7ca8c84936b5db4ab560c1857cb071514534c74991750dcdf66144c6d3b408671599f8a234d",
          "sha256": "aa80702c46a5f7471b1431434cbc7b04590713e48344ae443539eac3a0333b24",
          "sha1": "b99f274fd112404c373d42432c9c71b5c00f9245",
          "md5": "c223913080ced9b62b4bec33e64ae30e"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-rpc-grpc-core-macosarm64-0.5.1-sources.jar",
          "url": "kotlinx-rpc-grpc-core-macosarm64-0.5.1-sources.jar",
          "size": 12685,
          "sha512": "1c028a19fcfe6aa96896f204810f2073d503f0d030843f776c7affbe138fb776ff48e5d6af12a8cd273c3a54c356bc036812279d381c7bab02b5df0cc6f4c4e4",
          "sha256": "5069a1611d0c6a54088696a489c52ca25f1c8783b0271f3c22903cf05dfbce9a",
          "sha1": "ef560803272fe29a47d3260da2b2b1680534a72a",
          "md5": "fc8a57bd8f4e13920a47454c0b84ba7e"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.vickyleu.kotlinx",
          "module": "kotlinx-rpc-core",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "com.vickyleu.kotlinx",
          "module": "kotlinx-rpc-utils",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-rpc-grpc-core-macosarm64-0.5.1-metadata.jar",
          "url": "kotlinx-rpc-grpc-core-macosarm64-0.5.1-metadata.jar",
          "size": 261,
          "sha512": "4fc6cb94ce9be72988451a3b47cf926d13f03444f3eed07eb73443bb7859cde5e324277b2a93b8a744333d52bf1bdaaa59c51991043dabbd48795ae0e3b27490",
          "sha256": "05bdff6f5c25ee67e9a6351848da3a786d8237bfef4895229005ac8a8565ed53",
          "sha1": "a4d9aa2d42a638d235b7ab005b28d0ebf9175cfa",
          "md5": "309db054e604a70efe7d046351806423"
        }
      ]
    }
  ]
}
