{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-websockets/3.1.2-SNAPSHOT/ktor-websockets-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-websockets",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "linuxArm32HfpApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm32_hfp",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-utils",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-websockets-linuxArm32HfpMain-3.1.2-SNAPSHOT.klib",
          "url": "ktor-websockets-linuxarm32hfp-3.1.2-SNAPSHOT.klib",
          "size": 80867,
          "sha512": "ef8f621478cd4b925d76e67287f329e2e550cdcced2d611b50db8b2c30a2378d599e3be5c887c3a0d96df9b7fc9f7a75b36e03df1b643fb92ea590a8839c4d5c",
          "sha256": "b17c93e392bd847e62b7b38918bbaf67d5d1c8d5e186e6267baf3c6cdbd16658",
          "sha1": "cca91f9a94944bdd24ae4aa9d0f8e839611de0c3",
          "md5": "6315a3458f79540e2906e116cd3b4c49"
        }
      ]
    },
    {
      "name": "linuxArm32HfpSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm32_hfp",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-websockets-linuxarm32hfp-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-websockets-linuxarm32hfp-3.1.2-SNAPSHOT-sources.jar",
          "size": 22517,
          "sha512": "17310a80b992d7521157b511cabede739e63351cf15409a1fe7eab1785aa952834b310d222e546f1df73b6a53fa9a833cb0dfe3a1bf21d7635e85bc3a41c3158",
          "sha256": "1fb0a916b326441833905a3001d9f9ead5cf786aa47fc93ee327da0c046885c4",
          "sha1": "4377deafb26380e886431d1851d2af0c581e57f7",
          "md5": "19f80aad00d806e3fa2f41d27d66c47d"
        }
      ]
    }
  ]
}
