{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-metrics/3.1.2-SNAPSHOT/ktor-server-metrics-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-server-metrics",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "io.dropwizard.metrics",
          "module": "metrics-core",
          "version": {
            "requires": "4.2.30"
          }
        },
        {
          "group": "io.dropwizard.metrics",
          "module": "metrics-jvm",
          "version": {
            "requires": "4.2.30"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-metrics-jvm-3.1.2-SNAPSHOT.jar",
          "url": "ktor-server-metrics-jvm-3.1.2-SNAPSHOT.jar",
          "size": 20900,
          "sha512": "e0fc09e07aa3a8b91a25a05a6cfdb75d68547207fab732df3432d6d91e48765bbb54defe304a1b32152b1458022053f17489ab3e12e8b4a539393b50c73663bd",
          "sha256": "2980cc0509bb84c9e11add4aa434e06890f1d4ef15feabb7c778656389b5a48e",
          "sha1": "2e734052fb887435ad82281a84b0453bdce73480",
          "md5": "3ed0371f4efe9ffb85dacc2acc6c602d"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "io.dropwizard.metrics",
          "module": "metrics-core",
          "version": {
            "requires": "4.2.30"
          }
        },
        {
          "group": "io.dropwizard.metrics",
          "module": "metrics-jvm",
          "version": {
            "requires": "4.2.30"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-metrics-jvm-3.1.2-SNAPSHOT.jar",
          "url": "ktor-server-metrics-jvm-3.1.2-SNAPSHOT.jar",
          "size": 20900,
          "sha512": "e0fc09e07aa3a8b91a25a05a6cfdb75d68547207fab732df3432d6d91e48765bbb54defe304a1b32152b1458022053f17489ab3e12e8b4a539393b50c73663bd",
          "sha256": "2980cc0509bb84c9e11add4aa434e06890f1d4ef15feabb7c778656389b5a48e",
          "sha1": "2e734052fb887435ad82281a84b0453bdce73480",
          "md5": "3ed0371f4efe9ffb85dacc2acc6c602d"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ktor-server-metrics-jvm-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-server-metrics-jvm-3.1.2-SNAPSHOT-sources.jar",
          "size": 3202,
          "sha512": "aa6afeb0d3d8f66cb7391185d13c24c63debf20464a4aa532a79e9a9424376112a52fb1ab266c94e65ebd1cd78d510db48a3d768c47aad307e8c2b583e5f7178",
          "sha256": "69f9b74d3c15f8bff0c589e134bb40ac62e6b3a1bbd7465b134adc1a28fdf1da",
          "sha1": "b05be7f3fd09ef27148ae570095050b71361002a",
          "md5": "ebdd6aa08e2c15e8bc20e60ee0a5087c"
        }
      ]
    }
  ]
}
