{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-utils/3.1.2-SNAPSHOT/ktor-utils-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-utils",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-io",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-utils-wasm-js-3.1.2-SNAPSHOT.klib",
          "url": "ktor-utils-wasm-js-3.1.2-SNAPSHOT.klib",
          "size": 276183,
          "sha512": "44171a64ea1b6d9db4b79e9b551c7cea63248b0fac5899d32459fccc36baf10850f919d029e59523697916164026d7df49b23f9c11c45212cd0093b420242b8e",
          "sha256": "cdbeeaeec981adfdf0e749d198554e1bece7096dbefdaf6e38799b90f80384d3",
          "sha1": "cbc9f2567015549669095425fe7428becd1bfcef",
          "md5": "0028f835c9d8b22785eb006a8b2f3496"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-io",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-browser",
          "version": {
            "requires": "0.3"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-utils-wasm-js-3.1.2-SNAPSHOT.klib",
          "url": "ktor-utils-wasm-js-3.1.2-SNAPSHOT.klib",
          "size": 276183,
          "sha512": "44171a64ea1b6d9db4b79e9b551c7cea63248b0fac5899d32459fccc36baf10850f919d029e59523697916164026d7df49b23f9c11c45212cd0093b420242b8e",
          "sha256": "cdbeeaeec981adfdf0e749d198554e1bece7096dbefdaf6e38799b90f80384d3",
          "sha1": "cbc9f2567015549669095425fe7428becd1bfcef",
          "md5": "0028f835c9d8b22785eb006a8b2f3496"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "ktor-utils-wasm-js-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-utils-wasm-js-3.1.2-SNAPSHOT-sources.jar",
          "size": 73742,
          "sha512": "8ec260c2d2ac2507d27b3baf9e4ea3496270c1bb7253d4859f1f10df9628e8a61ba61b94d2810d8b4970822ba4b2f5d07744353699bbe71c93409ff3766c0470",
          "sha256": "446cba404c84c09a535066e5f0aa4ef3b2c94d93b6fead14bc41671e4d74d1bf",
          "sha1": "a649e930eae5708789ed3aa4b6c032b4864f3d96",
          "md5": "579829a1d3268f9be25a51a17d07ad39"
        }
      ]
    }
  ]
}
