{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-html/0.12.0/kotlinx-html-0.12.0.module",
    "group": "com.vickyleu.kotlinx",
    "module": "kotlinx-html",
    "version": "0.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "wasmWasiApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-html-wasm-wasi-0.12.0.klib",
          "url": "kotlinx-html-wasm-wasi-0.12.0.klib",
          "size": 472180,
          "sha512": "f08ddf5c26c6b295a7c5e067a27f915f278d8402e590ff98306e1b21bae21686b5d2a32025c0b3c92234e6f399e72693c459837d611ad0e4b8fc23dadfa375f4",
          "sha256": "593a814b2a9fe0c6bad054a4cfd9844a630939e295aa504d501edec36aa198e2",
          "sha1": "0ba571003a281c9852e1cc19b99a4c2236e2f03a",
          "md5": "ad20dda1f9a09790709c3d654f52d947"
        }
      ]
    },
    {
      "name": "wasmWasiRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-html-wasm-wasi-0.12.0.klib",
          "url": "kotlinx-html-wasm-wasi-0.12.0.klib",
          "size": 472180,
          "sha512": "f08ddf5c26c6b295a7c5e067a27f915f278d8402e590ff98306e1b21bae21686b5d2a32025c0b3c92234e6f399e72693c459837d611ad0e4b8fc23dadfa375f4",
          "sha256": "593a814b2a9fe0c6bad054a4cfd9844a630939e295aa504d501edec36aa198e2",
          "sha1": "0ba571003a281c9852e1cc19b99a4c2236e2f03a",
          "md5": "ad20dda1f9a09790709c3d654f52d947"
        }
      ]
    },
    {
      "name": "wasmWasiSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "files": [
        {
          "name": "kotlinx-html-wasm-wasi-0.12.0-sources.jar",
          "url": "kotlinx-html-wasm-wasi-0.12.0-sources.jar",
          "size": 55182,
          "sha512": "2e93e2e404e4299369ce34a2e77a402d54c3914062b9971c67bd2ef79a2740d558662b0d4a1b4f8fdd5bf1cb229b5ee01495d2022feae4b7a6e305086b281fd2",
          "sha256": "fd11fd1e62e866bf3dd16c0b9b7c02831354304ac2561666bc25a2541442a38a",
          "sha1": "be73ad8f359a059a9f2559af56a87c77ceaaa6eb",
          "md5": "8c71f78f1667e22e9145013bd6dc297e"
        }
      ]
    }
  ]
}
