{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-html-builder/3.1.2-SNAPSHOT/ktor-server-html-builder-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-server-html-builder",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-html-builder-androidNativeX86Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-html-builder-androidnativex86-3.1.2-SNAPSHOT.klib",
          "size": 16159,
          "sha512": "db79541b0ef420664c6c6d85085cdc3d77a27b569a124019f561b2e833b61250a59b2f729053a2c6409310944d662017a1b4f69723e2ef0a22f9f9e687e945fd",
          "sha256": "91b6c65af10215dbe984c2cccf6cc6850af0dab6deef56e605760cc7a81f288f",
          "sha1": "c2053a544ccccd41d4d9aeef8d63fac46dc0a880",
          "md5": "b2fc34e4e6f54029b6d9a2e36e9d2ced"
        }
      ]
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-server-html-builder-androidnativex86-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-server-html-builder-androidnativex86-3.1.2-SNAPSHOT-sources.jar",
          "size": 3624,
          "sha512": "ae49215733d475fb2907f74f88eb3a35d19aa7c1d551ead30ccd2d249fe7c7f6202b56f068d0c446585d364c73dc6a5d4a3f40c3f6db5b4a8aacb7e68e620324",
          "sha256": "a99b379ad0a12c0b88263bed2344f4912bafc8b2a1fad50426b7af85dbd6a831",
          "sha1": "ba1b0434aaade1511092dd908b61086894bdf31e",
          "md5": "a33f6166580925e7c3c33680a951369b"
        }
      ]
    }
  ]
}
