{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-rpc-krpc-test/0.5.1/kotlinx-rpc-krpc-test-0.5.1.module",
    "group": "com.vickyleu.kotlinx",
    "module": "kotlinx-rpc-krpc-test",
    "version": "0.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-rpc-krpc-test-watchosSimulatorArm64Main-0.5.1.klib",
          "url": "kotlinx-rpc-krpc-test-watchossimulatorarm64-0.5.1.klib",
          "size": 3592,
          "sha512": "2746f091de1327ca4d5195bda0ada01a52e6ff2d2988bd37d9ac1ecf92ca926fd5909a43498e1c17a97b8436d092bae2cef0d6dcf855954b7afc69c3aa0c88ee",
          "sha256": "2c44a16636d2caab6ac64455593d23e69ff760e9df737986f444e2d77208bbbd",
          "sha1": "260f9ceef70cabfaf974d5029e7fd7441e99c8c2",
          "md5": "747b76614dea3619567a4ab0488f4e83"
        }
      ]
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-rpc-krpc-test-watchossimulatorarm64-0.5.1-sources.jar",
          "url": "kotlinx-rpc-krpc-test-watchossimulatorarm64-0.5.1-sources.jar",
          "size": 644,
          "sha512": "16b83ce79591b095adf720df482abb2e14da3f3fd40a3c1a46ba59becf28f1d094aaf1ff99fc772f864e59e8b105e930693159fd80ae6d94f9eb24806a9ce020",
          "sha256": "b3145b4e01e1f3412d297a56c86209350d08be1ba36a31a6126e98de2a006f25",
          "sha1": "4c87a2cd579bf018fe4db89f467db3a78d0bbf97",
          "md5": "fcbb59b898de6c68f8351d4bebbb2bfd"
        }
      ]
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-rpc-krpc-test-watchossimulatorarm64-0.5.1-metadata.jar",
          "url": "kotlinx-rpc-krpc-test-watchossimulatorarm64-0.5.1-metadata.jar",
          "size": 261,
          "sha512": "e13d04e1c8a7a4093900e866b1859fb1bfeb18a45b919218fad7de65f42e1e72b094e4d320bb87c67f72947d569ba8c4216b263e9d7542cd3cf9f4a2f7b85dbe",
          "sha256": "f3f356c12ea0cf833ce0de7d682a716ba28a24f10b97784ce7e460b50b259993",
          "sha1": "a5f1735464ecd4c422dae3bd1107d51646b8fe77",
          "md5": "8ac4140995ba00624c12531e24d6b0e5"
        }
      ]
    }
  ]
}
