{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-http-cio/3.1.2-SNAPSHOT/ktor-http-cio-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-http-cio",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-io",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-http-cio-androidNativeX64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-http-cio-androidnativex64-3.1.2-SNAPSHOT.klib",
          "size": 131185,
          "sha512": "76bb1abcce1cb49066fca1698901c2700782a1fa0432a311679c91c9ec43ca2e77ab9c869894862964d961994b68f270f3777db48e2f0128bd818aa0f7d835cd",
          "sha256": "0cec8c4954ed307987e36490be087d44a520be95367bcc6c4161edd37df04f48",
          "sha1": "5a28451e28378e2ff3cb47e6e6af77f45e427e35",
          "md5": "550c45e52e216b9a846e553b0e83caa0"
        }
      ]
    },
    {
      "name": "androidNativeX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-http-cio-androidnativex64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-http-cio-androidnativex64-3.1.2-SNAPSHOT-sources.jar",
          "size": 28012,
          "sha512": "eeb1e5f41eaea9d570e2adf80131ce15fdb6ff7b485161e918b5307ddecf61639d983d5085b81afc80570d615410c340633ddf326be4ccf6895cf5949f9037d4",
          "sha256": "354c235d3b5e2c1b658a98372fa714e879f1cc6a7b68ff5e0ad0dbdb8f27a2b9",
          "sha1": "5e1f9da60d6952c974b3958af3c6761c307d2761",
          "md5": "92216b961edd779fabbaea1a5ad7a1a6"
        }
      ]
    }
  ]
}
