{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-client-json/3.1.2-SNAPSHOT/ktor-client-json-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-client-json",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-json-jvm-3.1.2-SNAPSHOT.jar",
          "url": "ktor-client-json-jvm-3.1.2-SNAPSHOT.jar",
          "size": 22409,
          "sha512": "25d023f402bf4f841645afe81457c111ba4cab629c950217df858615465f8e5971e7e2351f21ee8182f1f1f192ae7ee9b7448cd92d5e9da0d9393dc7b6426fce",
          "sha256": "25599cce6b13a60078ec6e31d5a97a17e6a237303b6dae1b0f7b45fd08a41b7c",
          "sha1": "fc41cf7d8d6e0cb0ee77afa8829e0c70442c08f4",
          "md5": "aac1857a558ecb60cd2a8b8969b8697f"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-json-jvm-3.1.2-SNAPSHOT.jar",
          "url": "ktor-client-json-jvm-3.1.2-SNAPSHOT.jar",
          "size": 22409,
          "sha512": "25d023f402bf4f841645afe81457c111ba4cab629c950217df858615465f8e5971e7e2351f21ee8182f1f1f192ae7ee9b7448cd92d5e9da0d9393dc7b6426fce",
          "sha256": "25599cce6b13a60078ec6e31d5a97a17e6a237303b6dae1b0f7b45fd08a41b7c",
          "sha1": "fc41cf7d8d6e0cb0ee77afa8829e0c70442c08f4",
          "md5": "aac1857a558ecb60cd2a8b8969b8697f"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ktor-client-json-jvm-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-client-json-jvm-3.1.2-SNAPSHOT-sources.jar",
          "size": 6718,
          "sha512": "8c435649e52917b6f906e93a87a2522b88829454e440660f445013e3646b578d93557a376d00cff6dc02a38b7f4996c3ef4c11539d36d27f4e1cb6dd09b535fa",
          "sha256": "f09c56ba45b9954bc162a81d75c79d4126bd415c3cf57038f79c8ba30550db82",
          "sha1": "3e7f33086a94cb8a44e86b5c986050d7c421ce3f",
          "md5": "9bcaeb51e16c7896a07d03631d8ba589"
        }
      ]
    }
  ]
}
