{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-core/3.1.2-SNAPSHOT/ktor-server-core-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-server-core",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-utils",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-serialization",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-events",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-http-cio",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-websockets",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-core-macosX64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-core-macosx64-3.1.2-SNAPSHOT.klib",
          "size": 441372,
          "sha512": "7a46d710ac7b1580ace8e44226710c508ce14eed151b3a2eba138e81a7841cd847cba0ce9dbc1a6a69916d3c47194368bcbfb59d30b6fa5a3b8889e29a7a775b",
          "sha256": "e632e3f4bd1408b6b41d2cfddf4e505c13eeb51adb10028deb45313929f11ada",
          "sha1": "0dd5caed991cd3d6480e5fdc19975d045357b130",
          "md5": "7013b052e651ae8619b2e04eada88fc4"
        },
        {
          "name": "ktor-server-core-macosX64Cinterop-host_commonMain-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-core-macosx64-3.1.2-SNAPSHOT-cinterop-host_common.klib",
          "size": 6385,
          "sha512": "5bdff1e788072a5e322e3bc6d31c8538222ec5dc63c0d4e6cbd5e0baecccb73f01cad96161a58fc451483f73de9205efe6f7269c21d8f6a21fa71e03c6e5a83d",
          "sha256": "1f2bdf34780a1e8866c7fce71c2283b9197096a976e2250bb3f5519fe1f04270",
          "sha1": "153b00618e4321efff3ded051e9886c5c341f72b",
          "md5": "f0dbfdfa3c54ee1c6d20baf28437700c"
        }
      ]
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-server-core-macosx64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-server-core-macosx64-3.1.2-SNAPSHOT-sources.jar",
          "size": 118184,
          "sha512": "3954a0402e48412c976eac690b449da7e00574a9208578aad5e16344875f3989bd04aaf3191481605855b648c08f650e5406998cac79cd3c5354ff194db14ea9",
          "sha256": "c6c2fb9c28a5a23297ea55815de1a6edb2dd38308e5cf3825b2ceb18141c16cc",
          "sha1": "7cf6719011753c1c649b70251351eba85af08300",
          "md5": "38c7f2c8265bbd690f532f905b9d3e56"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-utils",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-serialization",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-events",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-http-cio",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-websockets",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-core-macosx64-3.1.2-SNAPSHOT-metadata.jar",
          "url": "ktor-server-core-macosx64-3.1.2-SNAPSHOT-metadata.jar",
          "size": 28145,
          "sha512": "65ea7b83e631bf8ed68cc60119a1d2d265bcd47a5278fc4c9f528cdd7d9283b3f1e46205a899d22335c13e6f04e95518a1ea2dc690fd982e860d7fca074a6b63",
          "sha256": "37ab5e21179c8082315e9172d8edd743ba5ad95d61cc5e7d4ab9faa0f1a59687",
          "sha1": "dc23be8e7a22fa6a7a8d27d27daf6512fe6702e6",
          "md5": "1f5f7a2ecaa498af8e78d6470a03c573"
        }
      ]
    }
  ]
}
