{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-data-conversion/3.1.2-SNAPSHOT/ktor-server-data-conversion-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-server-data-conversion",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-data-conversion-wasm-js-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-data-conversion-wasm-js-3.1.2-SNAPSHOT.klib",
          "size": 5399,
          "sha512": "b190dd08af2a6e2e07a04522b56d0ee7069cfc09fbf60293ccaac792a2580070cf326a5254ae7b054c5e4f2af03032ecd94a695b69297fd4ee68e7c713dbe380",
          "sha256": "8166f0ddf9ed35964ef5e173c0c9aafec0530c4fef389d7a78b419c2616aa988",
          "sha1": "5ab46080dfbeecf2ca21d5cbeed08eac3f0b488b",
          "md5": "4d2de31fab2fbc8b7078ef75be1dcc9f"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-browser",
          "version": {
            "requires": "0.3"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-data-conversion-wasm-js-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-data-conversion-wasm-js-3.1.2-SNAPSHOT.klib",
          "size": 5399,
          "sha512": "b190dd08af2a6e2e07a04522b56d0ee7069cfc09fbf60293ccaac792a2580070cf326a5254ae7b054c5e4f2af03032ecd94a695b69297fd4ee68e7c713dbe380",
          "sha256": "8166f0ddf9ed35964ef5e173c0c9aafec0530c4fef389d7a78b419c2616aa988",
          "sha1": "5ab46080dfbeecf2ca21d5cbeed08eac3f0b488b",
          "md5": "4d2de31fab2fbc8b7078ef75be1dcc9f"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "ktor-server-data-conversion-wasm-js-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-server-data-conversion-wasm-js-3.1.2-SNAPSHOT-sources.jar",
          "size": 1782,
          "sha512": "2ff57d536c9be84fccc877003df07119317b8dd33b443d78785c72c4cc2eba967743937f5b062b166a792836747cae6b9f810ff888664b148f2d910404f96cff",
          "sha256": "a6d9710261dd2448519c7fe4dbe020a5c903270d4d1bcd83c5adbf322909e1f8",
          "sha1": "38acec474a03563944b2137996b9cb0634f8df94",
          "md5": "705b84a0b2dcce15e9264010650192ac"
        }
      ]
    }
  ]
}
