{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-html-builder/3.1.2-SNAPSHOT/ktor-server-html-builder-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-server-html-builder",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-html-builder-macosArm64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-html-builder-macosarm64-3.1.2-SNAPSHOT.klib",
          "size": 16159,
          "sha512": "fe149138041b679db5a325079156d853a147de86fe7f3fba8a39b28c77c407c67b7a4b2cbfff77a20da117ada33ede4c3d22edf6a6f92ed98debef5db241e125",
          "sha256": "e12ede6a4fbc00414039500e773b88a4bfad3d861ede336e9c9a989984272d28",
          "sha1": "9e82cf490eb43d825902a66db993c494887b7719",
          "md5": "3ee2417fe8ded55297050e1eefbb1f24"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-server-html-builder-macosarm64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-server-html-builder-macosarm64-3.1.2-SNAPSHOT-sources.jar",
          "size": 3624,
          "sha512": "ae49215733d475fb2907f74f88eb3a35d19aa7c1d551ead30ccd2d249fe7c7f6202b56f068d0c446585d364c73dc6a5d4a3f40c3f6db5b4a8aacb7e68e620324",
          "sha256": "a99b379ad0a12c0b88263bed2344f4912bafc8b2a1fad50426b7af85dbd6a831",
          "sha1": "ba1b0434aaade1511092dd908b61086894bdf31e",
          "md5": "a33f6166580925e7c3c33680a951369b"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-html-builder-macosarm64-3.1.2-SNAPSHOT-metadata.jar",
          "url": "ktor-server-html-builder-macosarm64-3.1.2-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "2e83e1f6bff29cdd8695cc09f4b7c6d13c3753bbd68e7ba12bf48500e33c69b54fae1e68b0c49f62634baf92a7de793b5846df3002c2b6bc706b0e48130114cb",
          "sha256": "db257244ecad3fada16f96b84a9c909e2478f9f2fbd0ee819df64e623aa75577",
          "sha1": "646eb36055fd9789b08ab399c2f9fc33afb50383",
          "md5": "ce717c15d199ef8eb16a568b180689c8"
        }
      ]
    }
  ]
}
