{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-coroutines-core/1.10.1-SNAPSHOT/kotlinx-coroutines-core-1.10.1-SNAPSHOT.module",
    "group": "com.vickyleu.kotlinx.coroutines",
    "module": "kotlinx-coroutines-core",
    "version": "1.10.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.26.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.23.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-core-watchosSimulatorArm64Main-1.10.1-SNAPSHOT.klib",
          "url": "kotlinx-coroutines-core-watchossimulatorarm64-1.10.1-SNAPSHOT.klib",
          "size": 885247,
          "sha512": "94a33d499560948f640d2f57c58eeefab3aaad61602361343819a3b48fb2e42846e8e6e3c6603babcb60c52378eeb736fdbdb35ebf84ee95e1df7c012eefa1ec",
          "sha256": "ab52b22fdbae21d048e857c613b61ee3bb48c00bcd24ee24b58d1dbfad1b07bd",
          "sha1": "604aece0af219d47abb7c2eb4c28e04c853f65a0",
          "md5": "3a97bc99b8f20d822f06ed6e231cb238"
        }
      ]
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-coroutines-core-watchossimulatorarm64-1.10.1-SNAPSHOT-sources.jar",
          "url": "kotlinx-coroutines-core-watchossimulatorarm64-1.10.1-SNAPSHOT-sources.jar",
          "size": 326899,
          "sha512": "9d4892499ed632b3500f8915664100dd1d6a4ba9e4b54d70be3bc03b11e4448a6621bb39b5a807ad5b33fad948d8dedf651d33220b1b73aa9efdbcfe6292a354",
          "sha256": "d15395d2dd17ba38c6bbce79c6f0b596d092e29f220b9aec5e0df85aee4f9afd",
          "sha1": "0a289e9827a7dad4daf501d658ee05922a0479ac",
          "md5": "e2d0cc73ef6f4d7fd7aca63892d36eb1"
        }
      ]
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.26.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.23.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-core-watchossimulatorarm64-1.10.1-SNAPSHOT-metadata.jar",
          "url": "kotlinx-coroutines-core-watchossimulatorarm64-1.10.1-SNAPSHOT-metadata.jar",
          "size": 3537,
          "sha512": "fd45254eee0dec9ba2c87059501a2caa9ba5dbe10398b5a25cc6c5b6987a5949a61b5195de0e7712e9865c19bbc70845c05a9dcf6cb7608142fa307ae919b1ca",
          "sha256": "e32737e4adc2ee616cb512d117bcc416279279f190bc6db5a279e0ae21f98bf2",
          "sha1": "0e495c3cf18987b7feb1490fcbb06a6694d1cfb5",
          "md5": "11cdab48fbab7085c9e987bf63f086e0"
        }
      ]
    }
  ]
}
