{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-rpc-krpc-serialization-json/0.5.1/kotlinx-rpc-krpc-serialization-json-0.5.1.module",
    "group": "com.vickyleu.kotlinx",
    "module": "kotlinx-rpc-krpc-serialization-json",
    "version": "0.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "watchosDeviceArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.vickyleu.kotlinx",
          "module": "kotlinx-rpc-krpc-serialization-core",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-rpc-krpc-serialization-json-watchosDeviceArm64Main-0.5.1.klib",
          "url": "kotlinx-rpc-krpc-serialization-json-watchosdevicearm64-0.5.1.klib",
          "size": 5899,
          "sha512": "eb638a391ef287a158429cf07e3fde00941ab8e0d72cf93b157537956724f2435d561ead8c0bfe5eabaaa2d3a0c2c004e1fd6755ee193818c908aa872a54aaf1",
          "sha256": "9b47f29b13c906bae776a2ea7d34455269d83792ebdc59a96ce8d9046df6da03",
          "sha1": "b3d299f3f3364ebae9f8cfbba5b50a7d8592e7af",
          "md5": "39f63ed52a7b8cac3817fa0e3deff14f"
        }
      ]
    },
    {
      "name": "watchosDeviceArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-rpc-krpc-serialization-json-watchosdevicearm64-0.5.1-sources.jar",
          "url": "kotlinx-rpc-krpc-serialization-json-watchosdevicearm64-0.5.1-sources.jar",
          "size": 1798,
          "sha512": "2086cb1b4aa13165230f4850920c3783e81ec5b7d6d05eebec712926fceae449d210fd1dd28c6f59389ca75cf2e5a0fa7bb39ed0a41349f4891530b2b0d1dccb",
          "sha256": "3b20394fe01bd912868a137d96fe034c69bfc12f367bd9bacfc3347bb79f65b7",
          "sha1": "83fe9f452dc22cdb84ef05410f92df7278351cea",
          "md5": "a5805796c60dcf233c8fd6b4187ac2a3"
        }
      ]
    },
    {
      "name": "watchosDeviceArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.vickyleu.kotlinx",
          "module": "kotlinx-rpc-krpc-serialization-core",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-rpc-krpc-serialization-json-watchosdevicearm64-0.5.1-metadata.jar",
          "url": "kotlinx-rpc-krpc-serialization-json-watchosdevicearm64-0.5.1-metadata.jar",
          "size": 261,
          "sha512": "22e683c223a71e5a94b476e7bb65502dab003ac730a84c31fa2d3d941cbe5885b0656449490b70014a2b498a435966192d257cbdef62fdead8899312758ee871",
          "sha256": "7bb22f6cd85ac823410949be9e9997c1790e1a18f367134b54f8f3c865c6e61e",
          "sha1": "530428e00da870b891474d0f137b3ea2be2532a5",
          "md5": "c8095b471feb8dbbcedc0f8de71d3757"
        }
      ]
    }
  ]
}
