{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-client-websockets/3.1.2-SNAPSHOT/ktor-client-websockets-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-client-websockets",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-websockets-macosX64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-client-websockets-macosx64-3.1.2-SNAPSHOT.klib",
          "size": 3713,
          "sha512": "2f285a2a68af26a127cd2518269eca20cb9bdc5603c9921f09d9ded6125ec49cc5d92edde54ccb350237809cd4be20a29dee79fff7241ca76105075164a51452",
          "sha256": "82501647845733e2e0aed7d6d25415052bf283f8934c5c43c345c8beadd25b19",
          "sha1": "43f84248591d8c0782c75748510649d3bd7a7422",
          "md5": "2515ee399ae9fb2abc550d99aeb7fac8"
        }
      ]
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-client-websockets-macosx64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-client-websockets-macosx64-3.1.2-SNAPSHOT-sources.jar",
          "size": 666,
          "sha512": "650a692ac4cd6f78ef41dae8b3a928357b0dac4f313bbf08f31fecf8548ddd8c4fe65d1cfadad9d09c0e597190e6a4be0d09a2ef04af2796d783e73343592b25",
          "sha256": "75d7ca238e3c1dd7fcc8929934521558abe14de2c3643766b9354b61fb8af5b6",
          "sha1": "d2442500ed8df341322651a00b716cf873a2373d",
          "md5": "65de3258033d8237cefbef68a927643d"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-websockets-macosx64-3.1.2-SNAPSHOT-metadata.jar",
          "url": "ktor-client-websockets-macosx64-3.1.2-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "4c710234a0196ea39189a64d4f05422a7336ae7f06805d988342d30377055e30e07e32b32529a6fb8c734a659a5ffd7e53127111ec534c1ba80aa6afe1f74f34",
          "sha256": "0ad91c530838a55c584e58976bd52a402785e0ce8977dc12f32695eb54552d07",
          "sha1": "34cd439ac540b083599e7bb25103e5c1c1465c21",
          "md5": "e092a194a260d22905bb88b17e8eeadd"
        }
      ]
    }
  ]
}
