{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-serialization-kotlinx-cbor/3.1.2-SNAPSHOT/ktor-serialization-kotlinx-cbor-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-serialization-kotlinx-cbor",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-serialization-kotlinx",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-cbor",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-serialization-kotlinx-cbor-iosX64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-serialization-kotlinx-cbor-iosx64-3.1.2-SNAPSHOT.klib",
          "size": 5142,
          "sha512": "8fa6bab0607b1c22157ac0c55367df260ad042e49a96d34e41ace72d09ac54bce27c668b18b7b5e2fd5fea45bdc7662707fd482c8d53453a7a57995eda471b0c",
          "sha256": "4fff7b3e83d3653ebd95a221c193f6cb9cb90644fb4845040078f98fc9902b3b",
          "sha1": "4e7b462466a0570f1a9a2394978c982416667a50",
          "md5": "7fb250e4c11d70c57d40c3d7d9ec04c6"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-serialization-kotlinx-cbor-iosx64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-serialization-kotlinx-cbor-iosx64-3.1.2-SNAPSHOT-sources.jar",
          "size": 1870,
          "sha512": "6527ba6b86a11193af0974c540bcd1153547c67ca907b3f669e620b95f121efe55a4c9add5935df90079b7c56419e572f4357298da1087183803e527463b4065",
          "sha256": "e2f73880e358d8e66a29281ba5e2c3f36753ab6d6e055ac2c47b18faa226b06f",
          "sha1": "20f0173fafbc1c6b72488a503626e2dcc77f65cf",
          "md5": "4ea1beebfdfdba67e54875899da0c7fc"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-serialization-kotlinx",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-cbor",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-serialization-kotlinx-cbor-iosx64-3.1.2-SNAPSHOT-metadata.jar",
          "url": "ktor-serialization-kotlinx-cbor-iosx64-3.1.2-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "2aa09a2de96b06b53b9f59bb7dcffb9c56b120554a6a825b3675ff37461e848fd7a2ebe31e1e138f838a087fe757762b8045b8a8813fd34219082aabb7f04b83",
          "sha256": "befa2c1c58dab5c2ae19fdc2e70f4c2434ee30c39516639b1938e18a535b5da5",
          "sha1": "e698bc9f3e43e08c9ecc80ca22b9b6bb22bb0296",
          "md5": "1f79e75174fd22f9bbb54cb147fba103"
        }
      ]
    }
  ]
}
