{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-body-limit/3.1.2-SNAPSHOT/ktor-server-body-limit-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-server-body-limit",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-body-limit-mingwX64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-body-limit-mingwx64-3.1.2-SNAPSHOT.klib",
          "size": 10550,
          "sha512": "8ac6827992fd9b4b5980c6d59412a035879d34e918904af0fa1424ede7ea79e611f547d1ab703d039a6733b01e76478e8581e1b0238e8e0d3802bb9f287e1f33",
          "sha256": "fb3d8c6f2c614b2e9688d4e0f1f77f8c8b1ab3279d7656dd1350edf36259dad1",
          "sha1": "3532a589faa2bcb9b2d30340e762f917e18f76f0",
          "md5": "6f61d49809fecfa8d7ae4a1bbce52fb4"
        }
      ]
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-server-body-limit-mingwx64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-server-body-limit-mingwx64-3.1.2-SNAPSHOT-sources.jar",
          "size": 2302,
          "sha512": "1fe49fe1e96d0841045bb151fc8490f761c5c575cb7acad2a5bf076e41e418f7029490236ef35f81dfa0d15187fccb77f80a894aea42ea16b8ed7171b9b2f7a3",
          "sha256": "826cb7e25738122cd5bbc4a6b31bcaea147fd77d806e27211858dc6bc1bc3158",
          "sha1": "407d1eb0bf5b46fac46965247f4f147c5d6ec0fb",
          "md5": "84968e6e84e9497c4ef4155c8e3b5e68"
        }
      ]
    }
  ]
}
