{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-network/3.1.2-SNAPSHOT/ktor-network-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-network",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-utils",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-network-tvosArm64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-network-tvosarm64-3.1.2-SNAPSHOT.klib",
          "size": 150190,
          "sha512": "2401cc4c2f1dbe4243619956eb94ba5bbb37084d8a20602b63f690df24bfd096fb5bc41d65e1a9e987d34fd269390e28d9d1b5267d61e17cad80427bf4e14376",
          "sha256": "a4efd04942db311c41e3aee0e73b8ec0f2de9987cb00ec03ab710910a7ffa587",
          "sha1": "c776edb33bc7cbc5c0dd7808c1d31be30aea94d5",
          "md5": "63e1b8811ade4555d9847728278555be"
        },
        {
          "name": "ktor-network-tvosArm64Cinterop-networkMain-3.1.2-SNAPSHOT.klib",
          "url": "ktor-network-tvosarm64-3.1.2-SNAPSHOT-cinterop-network.klib",
          "size": 8874,
          "sha512": "8d549c780a7902f1b076f622a49fca46fb382cb9dd239741b5c65621aaf41136aa292131d3adc9b193a3009f3628e5f9971d7873fe3d5b4808fc137bbf43657a",
          "sha256": "16609fd6e72c3be609c782673a6b057b5bb8ef5235e28f62c350c40124562892",
          "sha1": "32518a6cd7018753eaacc0e3060b910f379cffc1",
          "md5": "c520745592ee008383649cdec3c16aa5"
        },
        {
          "name": "ktor-network-tvosArm64Cinterop-unMain-3.1.2-SNAPSHOT.klib",
          "url": "ktor-network-tvosarm64-3.1.2-SNAPSHOT-cinterop-un.klib",
          "size": 5911,
          "sha512": "6311483c57f598df8cb6dce581b91686ba7cc43d9782cec6915803ace5bda794611941847dbff7bd8a9c70a8dec5556d76a09a5a3ab02cdc15e83fac914bc5e6",
          "sha256": "e210b11f12ecbe5f643c036fee0ecb6e2e3d6a1a1f9a8dadf2c0e27b1448966e",
          "sha1": "0ee377ba48959502bb5ec2e5cf3a7994b5f67b82",
          "md5": "40e5a47d86ba3920424ccce0b2b7e0bc"
        }
      ]
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-network-tvosarm64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-network-tvosarm64-3.1.2-SNAPSHOT-sources.jar",
          "size": 43793,
          "sha512": "b5969533e0ad9bed1bb5bdfa81b663ae5d13215ceb23de36f753a2243b3e45239ae4db8cb3577bd33d5a8636a547f443276282771947e3a01d21a801040bd238",
          "sha256": "48adc28547f0a572adc26861a33caec12ab04e4fdbb28a19984353769f777a2e",
          "sha1": "78ba3a7e5c9716aaf3072c7e91cb675312c1403c",
          "md5": "39a08ae0fec08890f023cd50d7c8ef30"
        }
      ]
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-utils",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-network-tvosarm64-3.1.2-SNAPSHOT-metadata.jar",
          "url": "ktor-network-tvosarm64-3.1.2-SNAPSHOT-metadata.jar",
          "size": 64049,
          "sha512": "07660c825bc6babf199671de1f9833e3d8c27b5bf1e1d978c25fa8d9263e88a6dccc27b29f092626bcbcf56831ab4e163252621714af4d988207ab5b3196a1ab",
          "sha256": "678e649eca7bc2b3024fbfb800a962982610ffe4f2c2bd78607b34d34231f6ee",
          "sha1": "daed12c51445b6001e5ae503fb74ba3b22f48a29",
          "md5": "c82f4fde73ff1ef9545c314b79578273"
        }
      ]
    }
  ]
}
