{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-forwarded-header/3.1.2-SNAPSHOT/ktor-server-forwarded-header-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-server-forwarded-header",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-forwarded-header-js-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-forwarded-header-js-3.1.2-SNAPSHOT.klib",
          "size": 32209,
          "sha512": "6c0582f2f2a8d99c93d980489e097440b24bedb3100044e5b8f0029c2448112ca574845c2c29a5a155b44d6cf352cde60fbe911e221fe296786e80a3ebaa84dc",
          "sha256": "4a515e42ebfa75fdcd44be313a75d515ff6884dfb4bd400b23816cb2ad527281",
          "sha1": "3d51ae24c200cb4b6ad6dc0163427990d38a1b2c",
          "md5": "756a98ceddbb5f5a88560f8ae5447f6a"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-forwarded-header-js-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-forwarded-header-js-3.1.2-SNAPSHOT.klib",
          "size": 32209,
          "sha512": "6c0582f2f2a8d99c93d980489e097440b24bedb3100044e5b8f0029c2448112ca574845c2c29a5a155b44d6cf352cde60fbe911e221fe296786e80a3ebaa84dc",
          "sha256": "4a515e42ebfa75fdcd44be313a75d515ff6884dfb4bd400b23816cb2ad527281",
          "sha1": "3d51ae24c200cb4b6ad6dc0163427990d38a1b2c",
          "md5": "756a98ceddbb5f5a88560f8ae5447f6a"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "ktor-server-forwarded-header-js-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-server-forwarded-header-js-3.1.2-SNAPSHOT-sources.jar",
          "size": 6006,
          "sha512": "6389ee2f9b2451d2bc4010a57b55da9b4141d7c05942af4bf7f6d313b56656bb65b4f697bb27f625adc227ab662a3fb2de63b81b699d18ddc669c3d9e4746f4c",
          "sha256": "f77620772e68ab778496a721b74f72b18a49af31d4a2d70fef4a01905e7a843e",
          "sha1": "107437c6c54d22d520d41c370ab1f9ff9a90c18f",
          "md5": "4087cdfda73964219e7183cfeb3a0f2e"
        }
      ]
    }
  ]
}
