{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-serialization-kotlinx/3.1.2-SNAPSHOT/ktor-serialization-kotlinx-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-serialization-kotlinx",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-serialization",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-serialization-kotlinx-tvosSimulatorArm64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-serialization-kotlinx-tvossimulatorarm64-3.1.2-SNAPSHOT.klib",
          "size": 24363,
          "sha512": "e260177dbcfd8b9703e2e30fd9d2ac7dd3fc98d4331cb2997ef844c9c34d390dc9ffefe4b2b5d1e765ff5fa59fb7d0bfb695cc951d6fcaac953dc4eaea80d758",
          "sha256": "c5e5f4d4c97a3ca6d472fca376deff01ccf4c37caf7d9e95b93816ae4a8b0d4a",
          "sha1": "8aa18c0a97f6005fac54eb0af5e0450c6def035e",
          "md5": "c521406235e15aee2fcbcf0eb7482273"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-serialization-kotlinx-tvossimulatorarm64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-serialization-kotlinx-tvossimulatorarm64-3.1.2-SNAPSHOT-sources.jar",
          "size": 6796,
          "sha512": "da0898e6d6250bc2b13fa90ae6dfd3e9ddf3cdb9b0b929dc7e5cd6740a829cc9ab91a4305e59c79d6d2f1171b9610478692a6252934c00ce9618b0ceef106a23",
          "sha256": "154373a2e865760e6ba4622dfc2acce2ff82943d1cdcc8de19d325cf90645335",
          "sha1": "44d6b1f0bcf4e302f36afcf9117332b3fb2cb295",
          "md5": "a365b7b81d888d4a0e5eaec42fd103fd"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-serialization",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-serialization-kotlinx-tvossimulatorarm64-3.1.2-SNAPSHOT-metadata.jar",
          "url": "ktor-serialization-kotlinx-tvossimulatorarm64-3.1.2-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "7145a0e5231f399ac240b8d0f89fb958259621dc5f24348605381378a2f21a7a614ac272015b303ee4a66c5540f010ce1003c467a1dd72df5cd0046ffacc9935",
          "sha256": "aecb99d8acb9ecd16ef2b62e4206d4d6851052eb68fe9a03f549f9796696d050",
          "sha1": "52425bba6a33ee5c4256f4f19a44a467a2cf3d7c",
          "md5": "ccd51c2d447a0936448ac25ad99a7851"
        }
      ]
    }
  ]
}
