{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-client-json/3.1.2-SNAPSHOT/ktor-client-json-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-client-json",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-json-wasm-js-3.1.2-SNAPSHOT.klib",
          "url": "ktor-client-json-wasm-js-3.1.2-SNAPSHOT.klib",
          "size": 20619,
          "sha512": "a8cb741bf8d3bc6a7df242c104e6bc1351921451ab2a100c61c88e683b5574c98130b60b3aad5e39f72e2bf3845d579877a5e29806055dc9c4335c1c46c76b9e",
          "sha256": "10cfd7587552cad5581b008e5a59c19c5797529fe8c90df54848eb83eeb7f041",
          "sha1": "700c73fa93a47b4e2b9df85e3747bcc1d89b2f23",
          "md5": "056208a598f789a2656fa610e77b16ff"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-browser",
          "version": {
            "requires": "0.3"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-json-wasm-js-3.1.2-SNAPSHOT.klib",
          "url": "ktor-client-json-wasm-js-3.1.2-SNAPSHOT.klib",
          "size": 20619,
          "sha512": "a8cb741bf8d3bc6a7df242c104e6bc1351921451ab2a100c61c88e683b5574c98130b60b3aad5e39f72e2bf3845d579877a5e29806055dc9c4335c1c46c76b9e",
          "sha256": "10cfd7587552cad5581b008e5a59c19c5797529fe8c90df54848eb83eeb7f041",
          "sha1": "700c73fa93a47b4e2b9df85e3747bcc1d89b2f23",
          "md5": "056208a598f789a2656fa610e77b16ff"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "ktor-client-json-wasm-js-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-client-json-wasm-js-3.1.2-SNAPSHOT-sources.jar",
          "size": 6828,
          "sha512": "c82ad83ef67fe2c4a889233c8f9828c4a2a3f28f6b82a2363dca8026bfe10735942255fb7e5c2f43beab9cec1d790f673a9f8710a15b2ef3c8d4bed3232dd4a7",
          "sha256": "8b5c9d7020c3101c5f84519ee9b56dd3b174fce0be713f856f11d1f4a0a5e315",
          "sha1": "b6f4ff2fcf39bf407650edbd48c41210c8d8f4d5",
          "md5": "085f5eec84299cb1a9c44a108adbbd6b"
        }
      ]
    }
  ]
}
