{
  "formatVersion": "1.1",
  "component": {
    "group": "com.vickyleu.annotation",
    "module": "annotation-linuxarm64",
    "version": "9999.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotation-linuxArm64Main-9999.0.0-SNAPSHOT.klib",
          "url": "annotation-linuxarm64-9999.0.0-SNAPSHOT.klib",
          "size": 27542,
          "sha512": "ea5fe95c6ef7557eb7a42af25b1896834920288c9e5b5896154c25127cad4e9d86a57be2d81c513337fc38302d126eb47cdc14211337215145460f5a367f4713",
          "sha256": "3c835c9fbf84dc3941ff4bb6efb1d7c8d23612eafb166cc26148550be1335ee6",
          "sha1": "93fc2e3809b5513d66b5297c5ddc63712004ae34",
          "md5": "c234c33731ee9b05e767930ccf85fcda"
        }
      ]
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "annotation-linuxarm64-9999.0.0-SNAPSHOT-sources.jar",
          "url": "annotation-linuxarm64-9999.0.0-SNAPSHOT-sources.jar",
          "size": 25046,
          "sha512": "25798f3568df31f81eb0bcfe18a3fa8a0af36e38200f0a8b5887c8c3daf38e7202c107e404930ec54065d2cd021ef1a2a43f26a88094e56af7d365435611ed95",
          "sha256": "768b81005ebd26d9441a064ef52c02dc98df7490585701af8d81e8e15828510f",
          "sha1": "8f7d0a0ea94eac1d3a340eb0cb69887af6b6f2f0",
          "md5": "6d417dcec41447c8575ccb2a429ba141"
        }
      ]
    }
  ]
}