{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-http-redirect/3.1.2-SNAPSHOT/ktor-server-http-redirect-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-server-http-redirect",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-http-redirect-linuxX64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-http-redirect-linuxx64-3.1.2-SNAPSHOT.klib",
          "size": 9186,
          "sha512": "85dfdef74fe309a903447ac7a6f61943ca4ef4760f041119602c20b78c240dd3d1a1c2a070b40aa1f48ab77e1c6a2798125f100e060f0322d938dcac03849173",
          "sha256": "f1ce593ac2c80e2f17acdb4faea9ae696396d10a5a2b8db4da05f83899d57248",
          "sha1": "75e9634141aa3068b73f0a0c735ed376ed09604b",
          "md5": "6fded78f38531f53b6a20a23490f6817"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-server-http-redirect-linuxx64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-server-http-redirect-linuxx64-3.1.2-SNAPSHOT-sources.jar",
          "size": 2310,
          "sha512": "061b03df84e56c8c04b20feb0be9c45fdc5d1a5b274b7739f30b05a73cc4f902ea92b7231c63472efe772bb92295544179947c96f5fb1e587ac8e5547dc5639c",
          "sha256": "0c00540fd6da40f611568a886aa44b9e2655bb66696f76f203cca10f9e3afd6a",
          "sha1": "ff99ba0cf98cd46e5bf40848715540cf941163a1",
          "md5": "bd681ac1a10519c780f969859d2d528a"
        }
      ]
    }
  ]
}
