{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-host-common/3.1.2-SNAPSHOT/ktor-server-host-common-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-server-host-common",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-host-common-androidNativeX64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-host-common-androidnativex64-3.1.2-SNAPSHOT.klib",
          "size": 3449,
          "sha512": "2d474586eab3c9f8c2c713183ea35dd0c1594eac7d6a5b60b7627c293d393379f14ca36e03f26293f06ef6f76525f8e74d64ee94d9245f199cf54b3120ec7c15",
          "sha256": "3a884f12e5f83648dc07e9b182a4d0e8a87c952f61d2cf8b5567fb892510f735",
          "sha1": "efffa47319cae3f3a9e13b71facd3555922e9361",
          "md5": "7719a1ca36fb9892df00d7ad9f6cc6a7"
        }
      ]
    },
    {
      "name": "androidNativeX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-server-host-common-androidnativex64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-server-host-common-androidnativex64-3.1.2-SNAPSHOT-sources.jar",
          "size": 621,
          "sha512": "f04f945d6a7d30a53537aa03c5b9ff5f72e60e4150cc04bec3114161649c0177f6ef2d801ca541f66ae5e2a12a40c6f5560f6c166f14e70f3731a9b77361aced",
          "sha256": "8f1b77aa660fed1302454fd2a303ab07ab29a5d52029c98850cedff554c454f0",
          "sha1": "ee19f777cd0f857f7e5bccd5eacb04c7496d9a13",
          "md5": "5b14dfc1ec7145751b60a8479edee37d"
        }
      ]
    }
  ]
}
