{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-client-darwin/3.1.2-SNAPSHOT/ktor-client-darwin-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-client-darwin",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-network-tls",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-darwin-watchosArm32Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-client-darwin-watchosarm32-3.1.2-SNAPSHOT.klib",
          "size": 111647,
          "sha512": "a5e8ac6f0cd9fc5f18902ed66f26481402f592a58185a51a393142c75258b9f3e2a8661becdf49fe71b536b55f8b77a48db9f9d5eab99e7a451d6bd4c6298654",
          "sha256": "fb1869fe8a89c390dbcddd9eb8d1d97809e6d833ae6f9393e4c58042245f53ad",
          "sha1": "631f7f5a77a5cb6c899366c75967e11ad0c44440",
          "md5": "56ee041aafc4f37ac47d0b129759d555"
        }
      ]
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-client-darwin-watchosarm32-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-client-darwin-watchosarm32-3.1.2-SNAPSHOT-sources.jar",
          "size": 25756,
          "sha512": "6a79a18326d64480f49a4b28afa8068aab391d8414e33107f2ee18adcf4c5d6cdf2f58c66db7dfd7ce143b288abf091bf04117eb420b571ab6ec73181eb375fe",
          "sha256": "94e655fe3ec0a92636a4f92d9ad06d7f7b56913e1b40552a92e543d294024cfe",
          "sha1": "f9e5bf929004fbb9ac5c1f78dd11c80ee7ca3137",
          "md5": "a48e87b79ff187f2a2b1e3a2dc37816f"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-network-tls",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-darwin-watchosarm32-3.1.2-SNAPSHOT-metadata.jar",
          "url": "ktor-client-darwin-watchosarm32-3.1.2-SNAPSHOT-metadata.jar",
          "size": 17906,
          "sha512": "426af25f96c8a50f0c80e96ea7086cae11690065f53fca94df8fe0238059f9228e6c98d0ee59f06506a19609c80969f2165b4d2b44b51bf988d172392acc7a15",
          "sha256": "ad6f34d7c067c23a270364ea472307a2b07143fecc8b8be7a8bb4197238413b8",
          "sha1": "b2324d669b08b002c9f68e3c28a16cec02ac5dd4",
          "md5": "d6a584ed8de2b8f8b6021b3844e80a1b"
        }
      ]
    }
  ]
}
