{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-rpc-krpc-serialization-json/0.6.1/kotlinx-rpc-krpc-serialization-json-0.6.1.module",
    "group": "com.vickyleu.kotlinx",
    "module": "kotlinx-rpc-krpc-serialization-json",
    "version": "0.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.vickyleu.kotlinx",
          "module": "kotlinx-rpc-krpc-serialization-core",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-rpc-krpc-serialization-json-watchosX64Main-0.6.1.klib",
          "url": "kotlinx-rpc-krpc-serialization-json-watchosx64-0.6.1.klib",
          "size": 5820,
          "sha512": "5de907eb1dd47529c5f9f202fde4828582534afd121eb8cdccbdeb1228b8e34fb1623848081e9ce6537fa6fa2cb231e3c5cb40feb1693ca4018e1a14c75ca81e",
          "sha256": "64e6e97299be55d4917df282493cda7cba009aaa2f323372ad1874476021146d",
          "sha1": "066c8c47ae17bc7f6edd0522fa5b2d75cadadb7a",
          "md5": "eb15f88927746b7820c9a78c3ed1f80c"
        }
      ]
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-rpc-krpc-serialization-json-watchosx64-0.6.1-sources.jar",
          "url": "kotlinx-rpc-krpc-serialization-json-watchosx64-0.6.1-sources.jar",
          "size": 1798,
          "sha512": "2086cb1b4aa13165230f4850920c3783e81ec5b7d6d05eebec712926fceae449d210fd1dd28c6f59389ca75cf2e5a0fa7bb39ed0a41349f4891530b2b0d1dccb",
          "sha256": "3b20394fe01bd912868a137d96fe034c69bfc12f367bd9bacfc3347bb79f65b7",
          "sha1": "83fe9f452dc22cdb84ef05410f92df7278351cea",
          "md5": "a5805796c60dcf233c8fd6b4187ac2a3"
        }
      ]
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.vickyleu.kotlinx",
          "module": "kotlinx-rpc-krpc-serialization-core",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-rpc-krpc-serialization-json-watchosx64-0.6.1-metadata.jar",
          "url": "kotlinx-rpc-krpc-serialization-json-watchosx64-0.6.1-metadata.jar",
          "size": 261,
          "sha512": "2b63e7bd20520c4646478defef809a152ea003741da460e65bf4cd72c26d08500246ee1fbc85a4bd4432ecd0558b167b67f9b110f376bde314244150ce65093a",
          "sha256": "ee5e53469793b2d0308bfd6351f83ecf2ef3d9b513ef576ec5d4af742f71390e",
          "sha1": "ee730897867cbfe9782a9fad0881ab81dc348887",
          "md5": "734a54b772f48b4b48b286e3e2300bf1"
        }
      ]
    }
  ]
}
