{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-rpc-krpc-serialization-protobuf/0.5.1/kotlinx-rpc-krpc-serialization-protobuf-0.5.1.module",
    "group": "com.vickyleu.kotlinx",
    "module": "kotlinx-rpc-krpc-serialization-protobuf",
    "version": "0.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.vickyleu.kotlinx",
          "module": "kotlinx-rpc-krpc-serialization-core",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-protobuf",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-rpc-krpc-serialization-protobuf-iosSimulatorArm64Main-0.5.1.klib",
          "url": "kotlinx-rpc-krpc-serialization-protobuf-iossimulatorarm64-0.5.1.klib",
          "size": 6150,
          "sha512": "b10f9d0f0dc09b326cbcfc1498101c7ff0350b4ae114f63228296048104bd410e1473cf3736c128cc399e158a72a4a80d4d184a3d534e6be708d207238d99d81",
          "sha256": "3e39bf9c0bcf49df16367f9ccb462a23c6b610e8ccce924a812ed1666db4f18d",
          "sha1": "520d2e9aab4906cbbc3ad9261ef1aa2002f85f99",
          "md5": "8b5179c8dfaab5f830ea8f19c8bb1368"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-rpc-krpc-serialization-protobuf-iossimulatorarm64-0.5.1-sources.jar",
          "url": "kotlinx-rpc-krpc-serialization-protobuf-iossimulatorarm64-0.5.1-sources.jar",
          "size": 1873,
          "sha512": "e9209f4cf666a4cf8edf6f7fa2532f7658ee28a96d1db5084cfad28bde3eea4abf92ab5d0052fac4af52dbd24ec16ee2498b534fb72da8ca1f8f313d5c52a537",
          "sha256": "cf4fbd9c6889287af2dd983a3d478b0b1e1440e824a93c119c4a1355d069e58c",
          "sha1": "991b37a09103cabb1c76cb78ae3b8128d73f88c1",
          "md5": "d39b8e13e9f676f9ac005fdc9fdd0578"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.vickyleu.kotlinx",
          "module": "kotlinx-rpc-krpc-serialization-core",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-protobuf",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-rpc-krpc-serialization-protobuf-iossimulatorarm64-0.5.1-metadata.jar",
          "url": "kotlinx-rpc-krpc-serialization-protobuf-iossimulatorarm64-0.5.1-metadata.jar",
          "size": 261,
          "sha512": "89bcdc3bad364231699a8537e6d71e55007a99affbbec1fa2d4f2364305b955a860f1c4771bb6a5236412853d95c4657163162ab5657cf3c32280426138d7b90",
          "sha256": "6279c24b129384a2ce87530a7cd7d07f204e00a1aea5be0b2ea57f7a225f0360",
          "sha1": "9a60eb20f7c9cf58a9e208d5b97e8617cc54201c",
          "md5": "4333df0857799e8c01084e1a5a242697"
        }
      ]
    }
  ]
}
