{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-resources/3.1.2-SNAPSHOT/ktor-server-resources-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-server-resources",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-resources",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-resources-tvosArm64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-resources-tvosarm64-3.1.2-SNAPSHOT.klib",
          "size": 16986,
          "sha512": "3dafc721b5e48ea802e45bc1b22e3465406fe8d664a30f94b5b45f00c2526e62ae8946fb98b7727d8eee7a66d739bbcfed0af227cb2798ee5eb3dc9e8af94514",
          "sha256": "33700be6c61bb613195da8fc82d2370a7631693ed091a28c94940462e4e8d90d",
          "sha1": "577c0136fa93fe229329dde0922bec5d18c48592",
          "md5": "e6474455603794642ff1b71eb0425aac"
        }
      ]
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-server-resources-tvosarm64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-server-resources-tvosarm64-3.1.2-SNAPSHOT-sources.jar",
          "size": 3456,
          "sha512": "341b4a578b9ebeed6779043103d69d05421cbc4f4bd4575e0ed2cbf927bb7247ea2af1e63e213bdd82aa48c7ae94be811bcb59fbc18ddf44ecdfd436a088801e",
          "sha256": "24beedbded7f80205153da78b2c26ceab9b9e0e89cef05ecec6756495b3c34ce",
          "sha1": "522c7027cc1a26709d34e1ab38ad8973928954ba",
          "md5": "d2961fdc8ea23431eea4362eb89b3637"
        }
      ]
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-resources",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-resources-tvosarm64-3.1.2-SNAPSHOT-metadata.jar",
          "url": "ktor-server-resources-tvosarm64-3.1.2-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "8742967e4db268f35a286f8b289ab9af53dd6cca01ad589c8984ae269f8e8e554ce6df68effdf1f8fff00c0f1dd101e9c85c710323b415699599e9b627121def",
          "sha256": "f80a4271efb6987ac1f6030d3a3b951b3e6a9b61711f9f52391f3f5e8a69e7d0",
          "sha1": "7b069ca8c9556deae46578bd9bb633dbc3e09f65",
          "md5": "70768d598a23eacc15ea3fd72c9d8455"
        }
      ]
    }
  ]
}
