{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-client-core/3.1.2-SNAPSHOT/ktor-client-core-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-client-core",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-http-cio",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-events",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-websocket-serialization",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-sse",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-core-iosArm64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-client-core-iosarm64-3.1.2-SNAPSHOT.klib",
          "size": 525320,
          "sha512": "33a19c59472a0b9fc0c3abe937f652321307749f58543595782a627f691c464377fceebb081d4d8fd2c6c458213fb66208d8b67e53ddd83513f040b3f516e9e1",
          "sha256": "ddf5f0cf2fe6ddde6bc6ddfe922499d482cb91741ec0f5ef0aea346a320eba73",
          "sha1": "a52b9037afd57626daefb960f83b19671c34affc",
          "md5": "f417004d53c18b76cd211a660f0185f3"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-client-core-iosarm64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-client-core-iosarm64-3.1.2-SNAPSHOT-sources.jar",
          "size": 133211,
          "sha512": "546183eee26150400e907e0baf8d8853abe4962caf82459c02a483dc7138a102829fa117b7d54f20636059f4371337d65b630dc7db67fbf27e9e59ec2552bcc2",
          "sha256": "ce74e184062264f5413aaee18ac4a87f703c390802094932caacb4a8138cc7bf",
          "sha1": "6e77c97475829bd32b0b5bbd3b8061aff50fd686",
          "md5": "5805ce6bf741495e612fe5b6f6ed6c68"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-http-cio",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-events",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-websocket-serialization",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-sse",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-core-iosarm64-3.1.2-SNAPSHOT-metadata.jar",
          "url": "ktor-client-core-iosarm64-3.1.2-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "7b55b7b73343777e1508538c76c71afaed7646c8733e07d3916fd79d4ba69ff43d89b8a2b77d0d04f834323e000d71c1ccaf2ffeaf941b2ad19d98ce844d323b",
          "sha256": "e32f418b7b7888afc1c3d11f0671f9fdab60075aa1aa6af2781fbdc1a1134a85",
          "sha1": "8ab00c962f8e412e78eab6d71a86ba2d030e4f07",
          "md5": "747c037f256122490ad12fbcb06ce85d"
        }
      ]
    }
  ]
}
