{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-rpc-krpc-serialization-core/0.5.1/kotlinx-rpc-krpc-serialization-core-0.5.1.module",
    "group": "com.vickyleu.kotlinx",
    "module": "kotlinx-rpc-krpc-serialization-core",
    "version": "0.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "com.vickyleu.kotlinx",
          "module": "kotlinx-rpc-utils",
          "version": {
            "requires": "0.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-rpc-krpc-serialization-core-linuxArm64Main-0.5.1.klib",
          "url": "kotlinx-rpc-krpc-serialization-core-linuxarm64-0.5.1.klib",
          "size": 9068,
          "sha512": "fb07670160292a02b7a5b01132068ab1f9b53ca3b67aabad20646ed5d6c82439dfea2e43b39fdc02531ec4b19d8a6ac56e5f385fc1f1909ec1e42abe976f058f",
          "sha256": "5090f7a39d2931f0b56d5500a6068958bae6271f66162cbd80696b5f2a8e1dde",
          "sha1": "ced263a4ead9ead173d2c9c0ec29e76a95bae092",
          "md5": "69c52928d529d00f6f62a2d2d9147ef8"
        }
      ]
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-rpc-krpc-serialization-core-linuxarm64-0.5.1-sources.jar",
          "url": "kotlinx-rpc-krpc-serialization-core-linuxarm64-0.5.1-sources.jar",
          "size": 2900,
          "sha512": "632cf30f421c4f5d16c7e4cfdb7abceadadb2aa6b78f6b9883b21724e62cdcb0f03a5959ba1d3538d2d101bca870066fa5ce211bbe0fcf2a6c0e1b1e453abea9",
          "sha256": "e7aaa7fe1f037413fe15ae7491dd1d2cdd9596b170cf6973c5a2bde1fd269065",
          "sha1": "e3f669e66041adc3c2f9c3ff8133a2a28410ec5d",
          "md5": "b949ed5d91c37e620fb383140fc50e77"
        }
      ]
    }
  ]
}
