{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-default-headers/3.1.2-SNAPSHOT/ktor-server-default-headers-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-server-default-headers",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-default-headers-watchosArm32Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-default-headers-watchosarm32-3.1.2-SNAPSHOT.klib",
          "size": 10157,
          "sha512": "5b7936c11a1795438e32d3dec61c0a3e9c803ac183312079ce4636504fcc3329c3ca44c028af18692a01d3cad6c5d42353852c762bd775b8a4c24aec055ea2a8",
          "sha256": "46406849ba0c13a69b9826cc2683907483b8ba82824bcb2d1ed47239ddf706fe",
          "sha1": "8bd25872a661e46c49e77a145d4e30fa65c1820f",
          "md5": "7f4656b408b5c141c99be69ff13d7501"
        }
      ]
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-server-default-headers-watchosarm32-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-server-default-headers-watchosarm32-3.1.2-SNAPSHOT-sources.jar",
          "size": 2812,
          "sha512": "8422caef99b6bef79d3fafb4c92701db0ca43ad43a03e5a92ded4233154a1b60c1e4c493ba5b9ffbe5f85f56961ed0a58d044619758e09ca032168f55a454f3d",
          "sha256": "b3cfc2a852b6a7f401cd817f3183251ca58b056d1c0e6709461d15182a9445fb",
          "sha1": "436b39c7dbb729f24456514c39bd09ec3a7b2403",
          "md5": "0be796bd549efa2bdeb94a525c2b57d2"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-default-headers-watchosarm32-3.1.2-SNAPSHOT-metadata.jar",
          "url": "ktor-server-default-headers-watchosarm32-3.1.2-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "617ad41284165ce3bb79ea95068d57446a76f919ce4cacd5d5c9eb41d201180bd534baaffb070d1a3f8885fcad50d87b256c5712c6d23f308fbb39711430b766",
          "sha256": "f616f2df99ca3bf02c5a1b4072cae3baa9823343e2bb3db1eb493f631a82e4bf",
          "sha1": "ea00f873346dff04239f114e1a034ab359c89b2b",
          "md5": "e387b25ba4046ebc9348356958182b7f"
        }
      ]
    }
  ]
}
