{
  "formatVersion": "1.1",
  "component": {
    "group": "com.vickyleu.kotlinx",
    "module": "kotlinx-rpc-krpc-test",
    "version": "0.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-rpc-krpc-test-metadata-0.5.1.jar",
          "url": "kotlinx-rpc-krpc-test-0.5.1.jar",
          "size": 2312,
          "sha512": "d9f066d66d4994bc326c76ccd345cc1d350eac34dbb8752ebc1a29d86c1e8205960f38c5e66642415827692a91598f7347977b880c20200eac190636fb8667b1",
          "sha256": "3ff9506476e5d2baae02fafbfc582c890ea5d8cd40213ad5472d3df9cb304d6b",
          "sha1": "778a0fab2d225a312ba5879e7bcf67853ce1f06b",
          "md5": "ed9eac946410bee28b7c048eff3195ed"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kotlinx-rpc-krpc-test-kotlin-0.5.1-sources.jar",
          "url": "kotlinx-rpc-krpc-test-0.5.1-sources.jar",
          "size": 644,
          "sha512": "16b83ce79591b095adf720df482abb2e14da3f3fd40a3c1a46ba59becf28f1d094aaf1ff99fc772f864e59e8b105e930693159fd80ae6d94f9eb24806a9ce020",
          "sha256": "b3145b4e01e1f3412d297a56c86209350d08be1ba36a31a6126e98de2a006f25",
          "sha1": "4c87a2cd579bf018fe4db89f467db3a78d0bbf97",
          "md5": "fcbb59b898de6c68f8351d4bebbb2bfd"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-test-iosarm64/0.5.1/kotlinx-rpc-krpc-test-iosarm64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-test-iosarm64",
        "version": "0.5.1"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-test-iosarm64/0.5.1/kotlinx-rpc-krpc-test-iosarm64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-test-iosarm64",
        "version": "0.5.1"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-test-iosarm64/0.5.1/kotlinx-rpc-krpc-test-iosarm64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-test-iosarm64",
        "version": "0.5.1"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-test-iossimulatorarm64/0.5.1/kotlinx-rpc-krpc-test-iossimulatorarm64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-test-iossimulatorarm64",
        "version": "0.5.1"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-test-iossimulatorarm64/0.5.1/kotlinx-rpc-krpc-test-iossimulatorarm64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-test-iossimulatorarm64",
        "version": "0.5.1"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-test-iossimulatorarm64/0.5.1/kotlinx-rpc-krpc-test-iossimulatorarm64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-test-iossimulatorarm64",
        "version": "0.5.1"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-test-iosx64/0.5.1/kotlinx-rpc-krpc-test-iosx64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-test-iosx64",
        "version": "0.5.1"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-test-iosx64/0.5.1/kotlinx-rpc-krpc-test-iosx64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-test-iosx64",
        "version": "0.5.1"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-test-iosx64/0.5.1/kotlinx-rpc-krpc-test-iosx64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-test-iosx64",
        "version": "0.5.1"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-test-js/0.5.1/kotlinx-rpc-krpc-test-js-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-test-js",
        "version": "0.5.1"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-test-js/0.5.1/kotlinx-rpc-krpc-test-js-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-test-js",
        "version": "0.5.1"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-test-js/0.5.1/kotlinx-rpc-krpc-test-js-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-test-js",
        "version": "0.5.1"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-test-jvm/0.5.1/kotlinx-rpc-krpc-test-jvm-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-test-jvm",
        "version": "0.5.1"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-test-jvm/0.5.1/kotlinx-rpc-krpc-test-jvm-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-test-jvm",
        "version": "0.5.1"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-test-jvm/0.5.1/kotlinx-rpc-krpc-test-jvm-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-test-jvm",
        "version": "0.5.1"
      }
    },
    {
      "name": "linuxArm32HfpApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm32_hfp",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-test-linuxarm32hfp/0.5.1/kotlinx-rpc-krpc-test-linuxarm32hfp-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-test-linuxarm32hfp",
        "version": "0.5.1"
      }
    },
    {
      "name": "linuxArm32HfpSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm32_hfp",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-test-linuxarm32hfp/0.5.1/kotlinx-rpc-krpc-test-linuxarm32hfp-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-test-linuxarm32hfp",
        "version": "0.5.1"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-test-linuxarm64/0.5.1/kotlinx-rpc-krpc-test-linuxarm64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-test-linuxarm64",
        "version": "0.5.1"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-test-linuxarm64/0.5.1/kotlinx-rpc-krpc-test-linuxarm64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-test-linuxarm64",
        "version": "0.5.1"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-test-linuxx64/0.5.1/kotlinx-rpc-krpc-test-linuxx64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-test-linuxx64",
        "version": "0.5.1"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-test-linuxx64/0.5.1/kotlinx-rpc-krpc-test-linuxx64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-test-linuxx64",
        "version": "0.5.1"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-test-macosarm64/0.5.1/kotlinx-rpc-krpc-test-macosarm64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-test-macosarm64",
        "version": "0.5.1"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-test-macosarm64/0.5.1/kotlinx-rpc-krpc-test-macosarm64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-test-macosarm64",
        "version": "0.5.1"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-test-macosarm64/0.5.1/kotlinx-rpc-krpc-test-macosarm64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-test-macosarm64",
        "version": "0.5.1"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-test-macosx64/0.5.1/kotlinx-rpc-krpc-test-macosx64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-test-macosx64",
        "version": "0.5.1"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-test-macosx64/0.5.1/kotlinx-rpc-krpc-test-macosx64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-test-macosx64",
        "version": "0.5.1"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-test-macosx64/0.5.1/kotlinx-rpc-krpc-test-macosx64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-test-macosx64",
        "version": "0.5.1"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-test-mingwx64/0.5.1/kotlinx-rpc-krpc-test-mingwx64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-test-mingwx64",
        "version": "0.5.1"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-test-mingwx64/0.5.1/kotlinx-rpc-krpc-test-mingwx64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-test-mingwx64",
        "version": "0.5.1"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-test-tvosarm64/0.5.1/kotlinx-rpc-krpc-test-tvosarm64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-test-tvosarm64",
        "version": "0.5.1"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-test-tvosarm64/0.5.1/kotlinx-rpc-krpc-test-tvosarm64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-test-tvosarm64",
        "version": "0.5.1"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-test-tvosarm64/0.5.1/kotlinx-rpc-krpc-test-tvosarm64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-test-tvosarm64",
        "version": "0.5.1"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-test-tvossimulatorarm64/0.5.1/kotlinx-rpc-krpc-test-tvossimulatorarm64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-test-tvossimulatorarm64",
        "version": "0.5.1"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-test-tvossimulatorarm64/0.5.1/kotlinx-rpc-krpc-test-tvossimulatorarm64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-test-tvossimulatorarm64",
        "version": "0.5.1"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-test-tvossimulatorarm64/0.5.1/kotlinx-rpc-krpc-test-tvossimulatorarm64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-test-tvossimulatorarm64",
        "version": "0.5.1"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-test-tvosx64/0.5.1/kotlinx-rpc-krpc-test-tvosx64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-test-tvosx64",
        "version": "0.5.1"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-test-tvosx64/0.5.1/kotlinx-rpc-krpc-test-tvosx64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-test-tvosx64",
        "version": "0.5.1"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-test-tvosx64/0.5.1/kotlinx-rpc-krpc-test-tvosx64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-test-tvosx64",
        "version": "0.5.1"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-test-wasm-js/0.5.1/kotlinx-rpc-krpc-test-wasm-js-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-test-wasm-js",
        "version": "0.5.1"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-test-wasm-js/0.5.1/kotlinx-rpc-krpc-test-wasm-js-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-test-wasm-js",
        "version": "0.5.1"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-test-wasm-js/0.5.1/kotlinx-rpc-krpc-test-wasm-js-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-test-wasm-js",
        "version": "0.5.1"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-test-watchosarm32/0.5.1/kotlinx-rpc-krpc-test-watchosarm32-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-test-watchosarm32",
        "version": "0.5.1"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-test-watchosarm32/0.5.1/kotlinx-rpc-krpc-test-watchosarm32-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-test-watchosarm32",
        "version": "0.5.1"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-test-watchosarm32/0.5.1/kotlinx-rpc-krpc-test-watchosarm32-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-test-watchosarm32",
        "version": "0.5.1"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-test-watchosarm64/0.5.1/kotlinx-rpc-krpc-test-watchosarm64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-test-watchosarm64",
        "version": "0.5.1"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-test-watchosarm64/0.5.1/kotlinx-rpc-krpc-test-watchosarm64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-test-watchosarm64",
        "version": "0.5.1"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-test-watchosarm64/0.5.1/kotlinx-rpc-krpc-test-watchosarm64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-test-watchosarm64",
        "version": "0.5.1"
      }
    },
    {
      "name": "watchosDeviceArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-test-watchosdevicearm64/0.5.1/kotlinx-rpc-krpc-test-watchosdevicearm64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-test-watchosdevicearm64",
        "version": "0.5.1"
      }
    },
    {
      "name": "watchosDeviceArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-test-watchosdevicearm64/0.5.1/kotlinx-rpc-krpc-test-watchosdevicearm64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-test-watchosdevicearm64",
        "version": "0.5.1"
      }
    },
    {
      "name": "watchosDeviceArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-test-watchosdevicearm64/0.5.1/kotlinx-rpc-krpc-test-watchosdevicearm64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-test-watchosdevicearm64",
        "version": "0.5.1"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-test-watchossimulatorarm64/0.5.1/kotlinx-rpc-krpc-test-watchossimulatorarm64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-test-watchossimulatorarm64",
        "version": "0.5.1"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-test-watchossimulatorarm64/0.5.1/kotlinx-rpc-krpc-test-watchossimulatorarm64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-test-watchossimulatorarm64",
        "version": "0.5.1"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-test-watchossimulatorarm64/0.5.1/kotlinx-rpc-krpc-test-watchossimulatorarm64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-test-watchossimulatorarm64",
        "version": "0.5.1"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-test-watchosx64/0.5.1/kotlinx-rpc-krpc-test-watchosx64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-test-watchosx64",
        "version": "0.5.1"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-test-watchosx64/0.5.1/kotlinx-rpc-krpc-test-watchosx64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-test-watchosx64",
        "version": "0.5.1"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-test-watchosx64/0.5.1/kotlinx-rpc-krpc-test-watchosx64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-test-watchosx64",
        "version": "0.5.1"
      }
    }
  ]
}
