{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-serialization-kotlinx-cbor/3.1.2-SNAPSHOT/ktor-serialization-kotlinx-cbor-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-serialization-kotlinx-cbor",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-serialization-kotlinx",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-cbor",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-serialization-kotlinx-cbor-watchosArm64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-serialization-kotlinx-cbor-watchosarm64-3.1.2-SNAPSHOT.klib",
          "size": 5194,
          "sha512": "c3873c5c5a86382d22bda4aaea8e097852c9f91125e96bcb6cc0587f964c1368603a1cceaa40292fc0a3178e68640e091929f4e7c12a2d143106d6957ec9de45",
          "sha256": "40c5068d11e82a4417e49ea01801adcbc61643888c16d53c3f11ffc762178dd9",
          "sha1": "c586e80ee9ece96bab8412ae196df92702756a6a",
          "md5": "06fb4e6d4d373ccd2f7c194fce97348d"
        }
      ]
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-serialization-kotlinx-cbor-watchosarm64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-serialization-kotlinx-cbor-watchosarm64-3.1.2-SNAPSHOT-sources.jar",
          "size": 1870,
          "sha512": "6527ba6b86a11193af0974c540bcd1153547c67ca907b3f669e620b95f121efe55a4c9add5935df90079b7c56419e572f4357298da1087183803e527463b4065",
          "sha256": "e2f73880e358d8e66a29281ba5e2c3f36753ab6d6e055ac2c47b18faa226b06f",
          "sha1": "20f0173fafbc1c6b72488a503626e2dcc77f65cf",
          "md5": "4ea1beebfdfdba67e54875899da0c7fc"
        }
      ]
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-serialization-kotlinx",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-cbor",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-serialization-kotlinx-cbor-watchosarm64-3.1.2-SNAPSHOT-metadata.jar",
          "url": "ktor-serialization-kotlinx-cbor-watchosarm64-3.1.2-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "4185b0e90d1797cece6f4ca9a565786d0297c9f907190b60faeb9d45b7f01c67fce76eda07378c9d7debd2a86e2427873eab91d27c2fa721dfa8f37ee894b684",
          "sha256": "93d724e0763e44993d39d76b4fd290588b19bd68eb6f5c54c2f649477b283333",
          "sha1": "ea9a2cf3fbe45861c26ef39756ad237e7c453d49",
          "md5": "8a6517fe00f98dae828cf1cbaa84eaab"
        }
      ]
    }
  ]
}
