{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-http-redirect/3.1.2-SNAPSHOT/ktor-server-http-redirect-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-server-http-redirect",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-http-redirect-androidNativeArm64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-http-redirect-androidnativearm64-3.1.2-SNAPSHOT.klib",
          "size": 9219,
          "sha512": "7b949ee9f99245571ef59139f86497b9ac732fd08106e19b69ee9bfd271444ac26ed33c48faf6f93c7f38d43ee6164a99b213d21834d2bddddd5b3b8c6e84fed",
          "sha256": "26c0668660cd21f6f1cf4df0ae4639c2e289942c95b71c3946217abcbeb8b09a",
          "sha1": "de1830c70e58e0c4af196c4b2b57f9f9732e19ed",
          "md5": "7eaac3f4c9576313ecc2428c27a79b31"
        }
      ]
    },
    {
      "name": "androidNativeArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-server-http-redirect-androidnativearm64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-server-http-redirect-androidnativearm64-3.1.2-SNAPSHOT-sources.jar",
          "size": 2310,
          "sha512": "061b03df84e56c8c04b20feb0be9c45fdc5d1a5b274b7739f30b05a73cc4f902ea92b7231c63472efe772bb92295544179947c96f5fb1e587ac8e5547dc5639c",
          "sha256": "0c00540fd6da40f611568a886aa44b9e2655bb66696f76f203cca10f9e3afd6a",
          "sha1": "ff99ba0cf98cd46e5bf40848715540cf941163a1",
          "md5": "bd681ac1a10519c780f969859d2d528a"
        }
      ]
    }
  ]
}
