{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-websockets/3.1.2-SNAPSHOT/ktor-server-websockets-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-server-websockets",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-websockets",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-websocket-serialization",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-websockets-linuxX64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-websockets-linuxx64-3.1.2-SNAPSHOT.klib",
          "size": 40482,
          "sha512": "e177688aa3467899e5a9e546cac4f7f8b7c15e212217892d1ca7ed43b8ebe11dec4a954dad5f5a9fbe4a49ca33a83c39daf66ec91274759966f62a3be7237db9",
          "sha256": "690cadb8330ebf7c04d07151e6da0e19065583027445e4c7154b47a623adbe53",
          "sha1": "fe92a697da39436afa47f2df20a4d380ae074a6b",
          "md5": "8325c175ba8d51c01dae667be88d176e"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-server-websockets-linuxx64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-server-websockets-linuxx64-3.1.2-SNAPSHOT-sources.jar",
          "size": 9120,
          "sha512": "fda89867e3d1f098f7519cfc056f807621cc201c619579f7406740189966f51ec9a23a5495d6c4de8b0553d44930782333283c891e6cfd34c7ddd0e1579aa071",
          "sha256": "88a71890c75a2b5365b5f08fbcc7502a8ae943110fded3aa235d0e95d1e6ab1d",
          "sha1": "4f61c6ce3e3603614c57b87a583cfdd6972f9784",
          "md5": "293983f099e3d3b88c7c50f0d20f7a70"
        }
      ]
    }
  ]
}
