{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-core/3.1.2-SNAPSHOT/ktor-server-core-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-server-core",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-utils",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-serialization",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-events",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-http-cio",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-websockets",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-core-macosArm64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-core-macosarm64-3.1.2-SNAPSHOT.klib",
          "size": 441389,
          "sha512": "75fc6198e099a0fc8bb33e5862691ce93fbdca9508d9b121f32da3c629b30b9fdd547beaa6ce7c50cc21bcc6961d3f7127ff928088708cf3c1aa9051428ee810",
          "sha256": "459166aabba9f2db85aff6e128a325a23c785369dc2e1ea5c2de26910876491d",
          "sha1": "1abb1c7a96ef137c984e1e1811f0e97d2744410c",
          "md5": "9e0aa07d3d12366be2e723805d379382"
        },
        {
          "name": "ktor-server-core-macosArm64Cinterop-host_commonMain-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-core-macosarm64-3.1.2-SNAPSHOT-cinterop-host_common.klib",
          "size": 6505,
          "sha512": "80c42095782bbc19b5c7d3f0b7a02d08013343e18beb45604dd00ba0db8bb7757d55349f060b4e16f0c11ceb2bab6bbf9375db72180b6cae928fc36bac7bb8c2",
          "sha256": "d5cdace4498b7d1a384335cd84d4bbf01163ca43bf9f6e9fa17ea2ef8cb7896d",
          "sha1": "b880501c7d8652d75d20c4111e362116d12bc810",
          "md5": "5a494ade6c0226aad0c5f963b55fdbad"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-server-core-macosarm64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-server-core-macosarm64-3.1.2-SNAPSHOT-sources.jar",
          "size": 118184,
          "sha512": "3954a0402e48412c976eac690b449da7e00574a9208578aad5e16344875f3989bd04aaf3191481605855b648c08f650e5406998cac79cd3c5354ff194db14ea9",
          "sha256": "c6c2fb9c28a5a23297ea55815de1a6edb2dd38308e5cf3825b2ceb18141c16cc",
          "sha1": "7cf6719011753c1c649b70251351eba85af08300",
          "md5": "38c7f2c8265bbd690f532f905b9d3e56"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-utils",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-serialization",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-events",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-http-cio",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-websockets",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-core-macosarm64-3.1.2-SNAPSHOT-metadata.jar",
          "url": "ktor-server-core-macosarm64-3.1.2-SNAPSHOT-metadata.jar",
          "size": 28145,
          "sha512": "65ea7b83e631bf8ed68cc60119a1d2d265bcd47a5278fc4c9f528cdd7d9283b3f1e46205a899d22335c13e6f04e95518a1ea2dc690fd982e860d7fca074a6b63",
          "sha256": "37ab5e21179c8082315e9172d8edd743ba5ad95d61cc5e7d4ab9faa0f1a59687",
          "sha1": "dc23be8e7a22fa6a7a8d27d27daf6512fe6702e6",
          "md5": "1f5f7a2ecaa498af8e78d6470a03c573"
        }
      ]
    }
  ]
}
