{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-client-curl/3.1.2-SNAPSHOT/ktor-client-curl-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-client-curl",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-http-cio",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-curl-macosX64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-client-curl-macosx64-3.1.2-SNAPSHOT.klib",
          "size": 81810,
          "sha512": "0826e2a20918e1e1f726b088e5607d08889e611050af7645682ce0f95d8bff81bca2b58646f7d6f0b2bc5a1de97d44e9630615bca9929d4f5560fe4f6fe0e033",
          "sha256": "210ed9682d980d1d4c0efd88d786edfcd2088f8ac16a0ae2018b719bf59d97f3",
          "sha1": "f1e07d8f052cd2750c8971e0e9995a0ecee19015",
          "md5": "86d74fd5d226a0b72691f6ea1778b9a6"
        },
        {
          "name": "ktor-client-curl-macosX64Cinterop-libcurlMain-3.1.2-SNAPSHOT.klib",
          "url": "ktor-client-curl-macosx64-3.1.2-SNAPSHOT-cinterop-libcurl.klib",
          "size": 459409,
          "sha512": "f58c87d77a06d87fc175ae4ad40abc4e3a0b75e22098dacad3d07bfaebcd1b95fd2a698120f815e5b4fe469a300809ff9e3bbb3e1cacb499872c2cb8ce89d8bc",
          "sha256": "4c46910735b21d139038d8c79f862e6e307eec6257510d079b8cc6028464dd57",
          "sha1": "7d2b808cc887ba31a9387fa2a28d08cc448fa5d6",
          "md5": "164482881292bc372e93f28795b2adda"
        }
      ]
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-client-curl-macosx64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-client-curl-macosx64-3.1.2-SNAPSHOT-sources.jar",
          "size": 17431,
          "sha512": "6b8c36dde71c7e31362996ab8946c599ed783d504297ef0871ada375e1719e3bcad4366f42424a550a233ed3631c94e705c43b30675500fa9e4e0366f2dd69b3",
          "sha256": "e4a473788e24d20ea17d9164a657140a76c027642b98b464adabf7d2f3417d86",
          "sha1": "ac789b266dd22c087ce792a4ee0e17e827986f93",
          "md5": "fc26ea2b4dab9d6f503ac4bef27b2e64"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-http-cio",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-curl-macosx64-3.1.2-SNAPSHOT-metadata.jar",
          "url": "ktor-client-curl-macosx64-3.1.2-SNAPSHOT-metadata.jar",
          "size": 89839,
          "sha512": "0e3718e1a56242044e00893ffe89910cc50a65754e2be9a4c5bc328b56be5bc89164aadcd34fe23b75b104b2f560abdb479a3c624b1609fb665b7ed9405e0fbc",
          "sha256": "29ad8785f892f9a88fa1024a0c171d6dbef285e60903d453c3e2f7712413fbc3",
          "sha1": "a0fd50fb46897eadc63cbbc0e634481f029beb70",
          "md5": "97e08c936dbef4655635690774c108fc"
        }
      ]
    }
  ]
}
