{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-client-mock/3.1.2-SNAPSHOT/ktor-client-mock-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-client-mock",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-mock-linuxX64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-client-mock-linuxx64-3.1.2-SNAPSHOT.klib",
          "size": 19429,
          "sha512": "4a86f04dbeb8c5f63f7234a6ea5b39c6c7b78bf31040cea5c4a6bc5a24e64526db682caf8388f1df0bc95df88663fd406d58100de9afe62edd4328c622a69c64",
          "sha256": "cf041f577d928b254bbe4e470dcf348d0c7a189102c2c87069f093babf30abc1",
          "sha1": "5587de875213558ad7389d7a7e269c5afeda30c3",
          "md5": "48caa681851bdd8249252744388927fd"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-client-mock-linuxx64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-client-mock-linuxx64-3.1.2-SNAPSHOT-sources.jar",
          "size": 4335,
          "sha512": "659eae04da34cd1c8342ca545ad5ad774492ddaf211eb0814406ac63196e043340a15ae0798af6c5d3e0fa4c0cb29a1aa7a12cd6def3c94a4fa9c3482788f4ad",
          "sha256": "8c47ed0e7a044a368ee139db4d9e372ab295931b8091fcc6027c6124de8eb7ef",
          "sha1": "7fbff87081316babe6b26a885d2f4d5c4ad4f3b0",
          "md5": "92895bd2f661401e157a3abc4d0b3f11"
        }
      ]
    }
  ]
}
