{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-content-negotiation/3.1.2-SNAPSHOT/ktor-server-content-negotiation-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-server-content-negotiation",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-content-negotiation-linuxArm64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-content-negotiation-linuxarm64-3.1.2-SNAPSHOT.klib",
          "size": 31478,
          "sha512": "65dc2ccbea5e333b4d88c8fe197b9f5a0306527700cfe028bf590c58b462d776e6c21dbaeacaccb5aaae2ed32e55781e9db1dc26e72ff13295206fc319070a72",
          "sha256": "6d514805dd21dd936070c710224674a4dbc47ca950ed3caeb200ed6ae56329af",
          "sha1": "73e522f4bc5f7b2e89e31675a179b5199dd1804b",
          "md5": "0e840a05bed328587286657bd31023d9"
        }
      ]
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-server-content-negotiation-linuxarm64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-server-content-negotiation-linuxarm64-3.1.2-SNAPSHOT-sources.jar",
          "size": 8087,
          "sha512": "f0cd7d2dab298c5288286a4c1180b5f69a10d9f39209de8e5bbeecb989d4420f66a298853ea23008bf91d805872acb3f1a13d2988093dbeffd1be375747b5003",
          "sha256": "672e0e24200e29c18949399f84b5c57033587192cda9d2001da2450ad4b0e6de",
          "sha1": "b483aa30f3604ae9909b45dc771ce8b54a6183cb",
          "md5": "c14032a2c75e1fdab4d37e35c1aa672e"
        }
      ]
    }
  ]
}
