{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-network-tls/3.1.2-SNAPSHOT/ktor-network-tls-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-network-tls",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-network",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-utils",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-network-tls-jvm-3.1.2-SNAPSHOT.jar",
          "url": "ktor-network-tls-jvm-3.1.2-SNAPSHOT.jar",
          "size": 197951,
          "sha512": "31d0be36e2c18073a923e4b2ee6b930fed3fd4a1c32613ef2fc806af19a7017d8555030ab4a1d32e9e267f2993ab577956172a81999f0dc669f185c2660ebfb3",
          "sha256": "4b48e225dc62f165ca7700ea3e105cf4b5688b45ffc82d14a96def5ce6ed49d0",
          "sha1": "fcf36f3066778dff9bd58fd1918c747554a5a66e",
          "md5": "3fb70e2403e85e44863d4a1d461c2aff"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-network",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-utils",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-network-tls-jvm-3.1.2-SNAPSHOT.jar",
          "url": "ktor-network-tls-jvm-3.1.2-SNAPSHOT.jar",
          "size": 197951,
          "sha512": "31d0be36e2c18073a923e4b2ee6b930fed3fd4a1c32613ef2fc806af19a7017d8555030ab4a1d32e9e267f2993ab577956172a81999f0dc669f185c2660ebfb3",
          "sha256": "4b48e225dc62f165ca7700ea3e105cf4b5688b45ffc82d14a96def5ce6ed49d0",
          "sha1": "fcf36f3066778dff9bd58fd1918c747554a5a66e",
          "md5": "3fb70e2403e85e44863d4a1d461c2aff"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ktor-network-tls-jvm-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-network-tls-jvm-3.1.2-SNAPSHOT-sources.jar",
          "size": 39186,
          "sha512": "dde4c51a42f75986dc8d60c0c3ead2e9882f1b2324117cd9538fd454a2a58e94e522996f22c75535815c476c78c76168455f9aef8ba0a6e9419835cecd557e96",
          "sha256": "10bd017eeee0f9f616c9a11bc4467565e1ce89273f251b4e247a718afa558de3",
          "sha1": "cbc8b6c39228c4a627a52f42fc018eb10d5f86ad",
          "md5": "f108258220945bad4cb28b336868483a"
        }
      ]
    }
  ]
}
