{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-rpc-utils/0.5.1/kotlinx-rpc-utils-0.5.1.module",
    "group": "com.vickyleu.kotlinx",
    "module": "kotlinx-rpc-utils",
    "version": "0.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-rpc-utils-iosSimulatorArm64Main-0.5.1.klib",
          "url": "kotlinx-rpc-utils-iossimulatorarm64-0.5.1.klib",
          "size": 28536,
          "sha512": "cf905cd26827a1271c3aa5d708eeb121c03a6a8361b2bfecb0b995403130cb701f1dffc1676c3576f7ae52c6ebad8ed292da47d9ad0f1176eca2c57d4ae18a59",
          "sha256": "0b2c32804e09a64c55de9ea5dffa6f3f3b3a88c00727ae8e538fc28e445c122b",
          "sha1": "ca3be686b4dc791c28d4cdd3d116dbed90581604",
          "md5": "8b50bd641345aa4c9cbabed6d4675e30"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-rpc-utils-iossimulatorarm64-0.5.1-sources.jar",
          "url": "kotlinx-rpc-utils-iossimulatorarm64-0.5.1-sources.jar",
          "size": 7752,
          "sha512": "7fad39a6c20adcf4041b2db58f8b8a92638574d5b3686ee4f51863a9150f2c6ce1907c48386424c9542414268ae6ae4c0dc66f31c2dea563e83f03c13446fd5e",
          "sha256": "c5c87127d49690814af31b1b1cb42362cf6348256fd8ebb1719efe892c576072",
          "sha1": "86211be509882f463b68e2a9c41e6e691c3d8998",
          "md5": "50d8d6cbb0502696f86338ced7cc4ac9"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-rpc-utils-iossimulatorarm64-0.5.1-metadata.jar",
          "url": "kotlinx-rpc-utils-iossimulatorarm64-0.5.1-metadata.jar",
          "size": 261,
          "sha512": "7fe85b4e162e64406290dfddf652efe44379073ebcff91fd728b65355bd7bbe5d9a8fd312b8514e6745de6e210cda73745e810bd16b770e988cc5c08944bba71",
          "sha256": "32dc60505f759c5a3fc180df18bc77444c05776f0e2e31603221cf53001d02b3",
          "sha1": "7fedeeec037a12b76cc728cd551860dfea5a4d31",
          "md5": "6d61b6be9b806b804557697f40724694"
        }
      ]
    }
  ]
}
