{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-rpc-krpc-logging/0.5.1/kotlinx-rpc-krpc-logging-0.5.1.module",
    "group": "com.vickyleu.kotlinx",
    "module": "kotlinx-rpc-krpc-logging",
    "version": "0.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-rpc-krpc-logging-wasm-js-0.5.1.klib",
          "url": "kotlinx-rpc-krpc-logging-wasm-js-0.5.1.klib",
          "size": 12034,
          "sha512": "c8ef3118d36c0b32556cf74d29c86cd9849653d5ab95a12d3df9653db0d971d871d26c323ca640ac053a1def191437678fc737b30680b4f71ede430c65c227f7",
          "sha256": "9ab94b0130258e80c8d54ea4c7c9b4cd0b6cbae0b3e8f73d7fb5d12e8df58d0c",
          "sha1": "8c81b5fbd104249506a58516bf87270f6832fa10",
          "md5": "e2dbe6631ced9f700135a861d0572d91"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-browser",
          "version": {
            "requires": "0.3"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.6"
          }
        },
        {
          "group": "com.vickyleu.kotlinx",
          "module": "kotlinx-rpc-utils",
          "version": {
            "requires": "0.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-rpc-krpc-logging-wasm-js-0.5.1.klib",
          "url": "kotlinx-rpc-krpc-logging-wasm-js-0.5.1.klib",
          "size": 12034,
          "sha512": "c8ef3118d36c0b32556cf74d29c86cd9849653d5ab95a12d3df9653db0d971d871d26c323ca640ac053a1def191437678fc737b30680b4f71ede430c65c227f7",
          "sha256": "9ab94b0130258e80c8d54ea4c7c9b4cd0b6cbae0b3e8f73d7fb5d12e8df58d0c",
          "sha1": "8c81b5fbd104249506a58516bf87270f6832fa10",
          "md5": "e2dbe6631ced9f700135a861d0572d91"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "kotlinx-rpc-krpc-logging-wasm-js-0.5.1-sources.jar",
          "url": "kotlinx-rpc-krpc-logging-wasm-js-0.5.1-sources.jar",
          "size": 3141,
          "sha512": "02123f3be3ee56a880ea0742c1ea34d5e0e61f63530f12524c374fcf6f5f083a687f36115fbdac268315f88b26e6132ab5b514b88d71dbf081e7127f8912f6d6",
          "sha256": "8e48b530ee5752910707bf402ff89d304e9cd21d60d6b841a0b29bd4b6413cf0",
          "sha1": "9a949afff48ebd85331320e4b8d5a8da07bb1f66",
          "md5": "1da329d6bc94828d33ab4607a09699a0"
        }
      ]
    }
  ]
}
