{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-default-headers/3.1.2-SNAPSHOT/ktor-server-default-headers-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-server-default-headers",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-default-headers-androidNativeX86Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-default-headers-androidnativex86-3.1.2-SNAPSHOT.klib",
          "size": 10141,
          "sha512": "819f21437e8d3a8e2b0bfce8e83ba179e6e9dfbee277479f6676a7ebf9bca25c5cd2f44ba35e884494c891511cfd3ac26733afabccae12c8fca050aec37f9e06",
          "sha256": "36c205729a5700288b5309e29ffca26c5be3e9829322688e2f547e2e74f1c85f",
          "sha1": "dd7e2a9992c54af8843931c00fe5c7f831737a7e",
          "md5": "e7e183c47f0cec7ee98d3cc06d1ac696"
        }
      ]
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-server-default-headers-androidnativex86-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-server-default-headers-androidnativex86-3.1.2-SNAPSHOT-sources.jar",
          "size": 2812,
          "sha512": "8422caef99b6bef79d3fafb4c92701db0ca43ad43a03e5a92ded4233154a1b60c1e4c493ba5b9ffbe5f85f56961ed0a58d044619758e09ca032168f55a454f3d",
          "sha256": "b3cfc2a852b6a7f401cd817f3183251ca58b056d1c0e6709461d15182a9445fb",
          "sha1": "436b39c7dbb729f24456514c39bd09ec3a7b2403",
          "md5": "0be796bd549efa2bdeb94a525c2b57d2"
        }
      ]
    }
  ]
}
