{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-html/0.12.0/kotlinx-html-0.12.0.module",
    "group": "com.vickyleu.kotlinx",
    "module": "kotlinx-html",
    "version": "0.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-html.klib",
          "url": "kotlinx-html-linuxarm64-0.12.0.klib",
          "size": 474214,
          "sha512": "bca1bfa8668ee73c4ebbdcb9c0b058c4fcb466fcbb41dbc1d407afe354eb2163617641cef53eacbb34a79a54259c686c5d7d569a18e7763f9e1ed5a57c0aeaa8",
          "sha256": "5499c4ca13f4308a64ad53b9dfab4ed2d81be01444add57194e90b2dff442e5d",
          "sha1": "790ba43b29f646820e36fdee566c8d085bb526ea",
          "md5": "634819d99c4460f40f0219b07a19afab"
        }
      ]
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-html-linuxarm64-0.12.0-sources.jar",
          "url": "kotlinx-html-linuxarm64-0.12.0-sources.jar",
          "size": 55168,
          "sha512": "629a6a5b08800f9382a4df5188ea8e6c413cdb5074b7c4e119f83f165c6243e2f28df27546def18e0e9c2f0bf84e96cf262c8db28d753a990797a10201ee1da2",
          "sha256": "f6a09275546d8ad23d08aaee028fb28a990bb1030d039016633ef618e3ec36a2",
          "sha1": "10527b70184b7ebe1807d471eacb550c98e2e362",
          "md5": "8f2db0811ea4f1b7b0a792845dfdd05d"
        }
      ]
    }
  ]
}
