{
  "formatVersion": "1.1",
  "component": {
    "group": "com.vickyleu.kotlinx",
    "module": "kotlinx-rpc-protobuf-plugin",
    "version": "0.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-rpc-protobuf-plugin-0.6.1-all.jar",
          "url": "kotlinx-rpc-protobuf-plugin-0.6.1-all.jar",
          "size": 4615096,
          "sha512": "94c7d796dd6e8751e02467c669d4163c54497b279d2068f698a7be5a0efd54726251e8f33157f654438e18e127301d1830c9e2e6262cf8f230a4ea57ceb4ac2c",
          "sha256": "620d26e03b05bb7d6325a4720b656725e262efaa17c6b7b4b61d991b3eca8700",
          "sha1": "3786249c001a68a7c2c7d9066ee8ff9faed41335",
          "md5": "ee2d6db0bfee6220e5bf8c1a4622dc52"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "4.29.3"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.3.14"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-rpc-protobuf-plugin-0.6.1-all.jar",
          "url": "kotlinx-rpc-protobuf-plugin-0.6.1-all.jar",
          "size": 4615096,
          "sha512": "94c7d796dd6e8751e02467c669d4163c54497b279d2068f698a7be5a0efd54726251e8f33157f654438e18e127301d1830c9e2e6262cf8f230a4ea57ceb4ac2c",
          "sha256": "620d26e03b05bb7d6325a4720b656725e262efaa17c6b7b4b61d991b3eca8700",
          "sha1": "3786249c001a68a7c2c7d9066ee8ff9faed41335",
          "md5": "ee2d6db0bfee6220e5bf8c1a4622dc52"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlinx-rpc-protobuf-plugin-0.6.1-sources.jar",
          "url": "kotlinx-rpc-protobuf-plugin-0.6.1-sources.jar",
          "size": 18488,
          "sha512": "5db53c725983296ed1be57e846e4990e2599b2759fa80fbd8ac7970033f5b95bfa001174325805d8144d69679ce14cac775cfcef74a65cd604dfb8102f03ce52",
          "sha256": "8ad47b04456656af40908cc19064cce0c7ef1697c9de58d33c51358091300282",
          "sha1": "20b8bfdb194decd78a79f156bb3d1bcb8f6db0ad",
          "md5": "2d7f30381d0da78ec835ee7ed0895d16"
        }
      ]
    }
  ]
}
