{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-coroutines-core/1.10.1-SNAPSHOT/kotlinx-coroutines-core-1.10.1-SNAPSHOT.module",
    "group": "com.vickyleu.kotlinx.coroutines",
    "module": "kotlinx-coroutines-core",
    "version": "1.10.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.26.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.23.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-core-macosX64Main-1.10.1-SNAPSHOT.klib",
          "url": "kotlinx-coroutines-core-macosx64-1.10.1-SNAPSHOT.klib",
          "size": 885127,
          "sha512": "679b2f0f8024efc1d750eafd1efdf447bca4c69d006d76adf0ee07fbdab5805ba97c4773248cc17eb86033937f1e49803aec2df4ed6e95b022e67c4efed620a9",
          "sha256": "5cf8ce54c72c9d648a11a74d942d678bf7f49c261b7c67532d022ba88098b64d",
          "sha1": "df6b952ed13410c40273282af31c50d6f274c698",
          "md5": "41db784d41ec0009f418ecc9fe800cc4"
        }
      ]
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-coroutines-core-macosx64-1.10.1-SNAPSHOT-sources.jar",
          "url": "kotlinx-coroutines-core-macosx64-1.10.1-SNAPSHOT-sources.jar",
          "size": 326899,
          "sha512": "9d4892499ed632b3500f8915664100dd1d6a4ba9e4b54d70be3bc03b11e4448a6621bb39b5a807ad5b33fad948d8dedf651d33220b1b73aa9efdbcfe6292a354",
          "sha256": "d15395d2dd17ba38c6bbce79c6f0b596d092e29f220b9aec5e0df85aee4f9afd",
          "sha1": "0a289e9827a7dad4daf501d658ee05922a0479ac",
          "md5": "e2d0cc73ef6f4d7fd7aca63892d36eb1"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.26.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.23.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-core-macosx64-1.10.1-SNAPSHOT-metadata.jar",
          "url": "kotlinx-coroutines-core-macosx64-1.10.1-SNAPSHOT-metadata.jar",
          "size": 3537,
          "sha512": "c73b01b97ae9b6b760cbc1fdc3908a79c1c407d556d09aa1f22b536cce9367d70007a60a1a31237191b944adeaeec96c1683a3a4cf60627e800fedb49b628e4c",
          "sha256": "21f69f6a43455741a687779d48df229699aceef417bd670aeb46a0a7dc9b742d",
          "sha1": "2616738c956bf837439ec103a9f502b9b884cbde",
          "md5": "c5e2f156d548442c527a8bbd31501529"
        }
      ]
    }
  ]
}
