{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-coroutines-core/1.10.1-SNAPSHOT/kotlinx-coroutines-core-1.10.1-SNAPSHOT.module",
    "group": "com.vickyleu.kotlinx.coroutines",
    "module": "kotlinx-coroutines-core",
    "version": "1.10.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.26.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.23.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-core-tvosSimulatorArm64Main-1.10.1-SNAPSHOT.klib",
          "url": "kotlinx-coroutines-core-tvossimulatorarm64-1.10.1-SNAPSHOT.klib",
          "size": 885220,
          "sha512": "7c12b7c9f29665871b3d51dd1c90f05275a729f7b9d1a6bef8de2a85863c810f59025cf3c3182491b1b22b36820d4a4eaadd560dc66c2fd1f2dff4b5f0720851",
          "sha256": "bbe2cc19baba6737a3c1165fbb91e00b35fa01110ec183f6cb44d1cad3bb786e",
          "sha1": "a3106257586ae409602afa818b2862ad3d0408d9",
          "md5": "58313a5551ea68b50f825c3fa45dd38d"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-coroutines-core-tvossimulatorarm64-1.10.1-SNAPSHOT-sources.jar",
          "url": "kotlinx-coroutines-core-tvossimulatorarm64-1.10.1-SNAPSHOT-sources.jar",
          "size": 326899,
          "sha512": "9d4892499ed632b3500f8915664100dd1d6a4ba9e4b54d70be3bc03b11e4448a6621bb39b5a807ad5b33fad948d8dedf651d33220b1b73aa9efdbcfe6292a354",
          "sha256": "d15395d2dd17ba38c6bbce79c6f0b596d092e29f220b9aec5e0df85aee4f9afd",
          "sha1": "0a289e9827a7dad4daf501d658ee05922a0479ac",
          "md5": "e2d0cc73ef6f4d7fd7aca63892d36eb1"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.26.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.23.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-core-tvossimulatorarm64-1.10.1-SNAPSHOT-metadata.jar",
          "url": "kotlinx-coroutines-core-tvossimulatorarm64-1.10.1-SNAPSHOT-metadata.jar",
          "size": 3537,
          "sha512": "3db844356104c81ae02cbe066c356752d8710c9906da8ba2990a0b008acad2f19f78df18162f8367a510c98db9d2dfaa9f58a94bbdd4332b080f4a8a2c529737",
          "sha256": "324a6887ab6b67cf1479c98885ec3a13f93e2962dd132ec6a13393638861d12a",
          "sha1": "09ecd3d35a8872a8483f31d39c3818fb3254ba1e",
          "md5": "d152dc9460cc1173fc282bb8a75e408a"
        }
      ]
    }
  ]
}
