{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-hsts/3.1.2-SNAPSHOT/ktor-server-hsts-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-server-hsts",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-hsts-androidNativeArm64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-hsts-androidnativearm64-3.1.2-SNAPSHOT.klib",
          "size": 13426,
          "sha512": "ed2b1896019ffa328d36736c53256aef8299c1e57084b892209910cfad67b28d5b1854f60ad8a66b8df811af348953ab2e7b9b9243cfd870277710e2f188026f",
          "sha256": "232686c7003594e6cb0ebdf411e0dd3826b0f22385da92db8007ed2f24e99c39",
          "sha1": "fd5aa96bd9e3764c3e13fd1e9364ba115317c85b",
          "md5": "9e99fec1c9d898e4ad275824e280ed4e"
        }
      ]
    },
    {
      "name": "androidNativeArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-server-hsts-androidnativearm64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-server-hsts-androidnativearm64-3.1.2-SNAPSHOT-sources.jar",
          "size": 3323,
          "sha512": "651edba1850a83d467c526b1b8b970f4d08350490283e4de3bcabd1a7eba3d4c096db53f975a433945868e7aaffb963ce4de3b5a2a049e7f0d33ff129f7fd977",
          "sha256": "7c98706e0d2ce08552b15d0326a8df0211e7368f9fa0b42ca76b8a5f96479d09",
          "sha1": "bdbda58ec2947691fa225823995da28d391522dc",
          "md5": "72f5ccd82581b8becd1c3e4a4c705315"
        }
      ]
    }
  ]
}
