{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-data-conversion/3.1.2-SNAPSHOT/ktor-server-data-conversion-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-server-data-conversion",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-data-conversion-androidNativeArm32Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-data-conversion-androidnativearm32-3.1.2-SNAPSHOT.klib",
          "size": 5825,
          "sha512": "9d0b6e7f2df572ece131a3e60dbe16df449c71360d1ce3441dfda07ab5f013c5b1582c27806bfaf4aa9bd1f9aaab80efa85eb9c59aa21c5b091d64670c9001aa",
          "sha256": "a6384b620f122da4c5abd80d70ffe746c139e759cc5129ed9d99b0a7b9c5741d",
          "sha1": "c080dbfa120a206ac8da325c6bf9b635ee332f23",
          "md5": "9c64fc6365e1d5eeb2b0e14a8683c961"
        }
      ]
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-server-data-conversion-androidnativearm32-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-server-data-conversion-androidnativearm32-3.1.2-SNAPSHOT-sources.jar",
          "size": 1782,
          "sha512": "2ff57d536c9be84fccc877003df07119317b8dd33b443d78785c72c4cc2eba967743937f5b062b166a792836747cae6b9f810ff888664b148f2d910404f96cff",
          "sha256": "a6d9710261dd2448519c7fe4dbe020a5c903270d4d1bcd83c5adbf322909e1f8",
          "sha1": "38acec474a03563944b2137996b9cb0634f8df94",
          "md5": "705b84a0b2dcce15e9264010650192ac"
        }
      ]
    }
  ]
}
