{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-caching-headers/3.1.2-SNAPSHOT/ktor-server-caching-headers-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-server-caching-headers",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-caching-headers-tvosArm64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-caching-headers-tvosarm64-3.1.2-SNAPSHOT.klib",
          "size": 15587,
          "sha512": "db517bd23a5df4a11784520da027571169c8990168ff2e9c705d63d2067764cedd950e0a846ae034eef5a6792219254f9347e5e722cb6b15c02d30dd23241bc7",
          "sha256": "334dfd34017eda5d3e432ffaa9bed0b7a19ab262cf48db448c0a6c128f2d8168",
          "sha1": "545762eb859da35599810891309288ef47e47fb1",
          "md5": "bebb4e77d29586d9bc4f07fae6d6f4a9"
        }
      ]
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-server-caching-headers-tvosarm64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-server-caching-headers-tvosarm64-3.1.2-SNAPSHOT-sources.jar",
          "size": 3764,
          "sha512": "58343a5fc9e812f9deb65c82653a1601c3c960ac9435649ff674fa583b5554399be5222884569806c764d597a7689f6164b92fd33f1d2e24d5f8d4bca664475e",
          "sha256": "7e62d7c4439346be094e988839b8dc58b0432f1e8257827dc0e257d536d9982b",
          "sha1": "652163fa0c69e2349eb7e812300555005889109d",
          "md5": "03c222a2c8a458caaaa14bf1046328f9"
        }
      ]
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-caching-headers-tvosarm64-3.1.2-SNAPSHOT-metadata.jar",
          "url": "ktor-server-caching-headers-tvosarm64-3.1.2-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "3878aa0b89a5611357c275dbbf768e41470b30ec994979980283bc5207cad301ba29741960913940892d5366696377bf0105696ac8fd7ad88fc5224adc7e6482",
          "sha256": "f6104cd67d3bb92c5e6c791fb31f305e37e86b3e8ae35d7f54cf6d0a9deae94b",
          "sha1": "c3c8905082209010ce7284d8468b4b4514e93ab1",
          "md5": "e13d09a0c87c325f97a5e5692224fff0"
        }
      ]
    }
  ]
}
