{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-client-json/3.1.2-SNAPSHOT/ktor-client-json-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-client-json",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-json-androidNativeX64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-client-json-androidnativex64-3.1.2-SNAPSHOT.klib",
          "size": 20935,
          "sha512": "08837de4b11a5b3d1bfb19c7370fff0f7c27a05d43db2da47310c11d0c0c31a1dee9b6743947acdb9c531136f1d03e51914f2f9b55f1cefa61999c65743bef2a",
          "sha256": "a380f901c546d0a004f1f40a2a7bb86a16622107d746208c1367d2c4ae6cfc78",
          "sha1": "50eee69015c5d0e258d6337a0a718c2725ece257",
          "md5": "4d6ccc87218c73bc1298c911bd077517"
        }
      ]
    },
    {
      "name": "androidNativeX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-client-json-androidnativex64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-client-json-androidnativex64-3.1.2-SNAPSHOT-sources.jar",
          "size": 6671,
          "sha512": "0949ac750b6561d37b9726f73d195152834b7bb51d427c75f664bd5e7fc17b4f8d2b58ef3de1a1de3ef8afaee3a5136471d846062d7074bbdd8f83b43c198f4c",
          "sha256": "b19ea5224717044ca8b54efee9a4aefd77bed2442761d68c1c54d0ca88a16172",
          "sha1": "6bfe9d319f114e982e3eeaa18451a07131eab82a",
          "md5": "fa340d1d8eb189f8cb81992a75a7c0dc"
        }
      ]
    }
  ]
}
