{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-sse/3.1.2-SNAPSHOT/ktor-server-sse-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-server-sse",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-sse",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-sse-iosSimulatorArm64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-sse-iossimulatorarm64-3.1.2-SNAPSHOT.klib",
          "size": 23381,
          "sha512": "5572d65da2eeb07605ce477ffca0ebcfc0179b1a1f7e40a03bf9ce0dd9cbe6ec4c9e9a3f738ba6aae9ab81eb02e2a3beeffa8e45d59532cfb6c0ee7a4b4a449c",
          "sha256": "8a9852d690213fac63e68bc3b3f7733a800c7d78a95fefa690c47af635d2639b",
          "sha1": "9599ede4efcf41f9349bcf1e918436c7e45a029c",
          "md5": "b7f855dff2a6990e7babef1aaec148e8"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-server-sse-iossimulatorarm64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-server-sse-iossimulatorarm64-3.1.2-SNAPSHOT-sources.jar",
          "size": 6935,
          "sha512": "2c60830cbfd64fdfe911bf6596423bf094ca25deaa77cdd05fd9b32fba0e03bf4e182187b3bc49f7841a94bada60934b9c6a726018b3d4b186da30c21572f8bc",
          "sha256": "513c0f6d91cdb398573389889266a510caee1f0b119540317d64758b2f815e87",
          "sha1": "1da279d6d7eaecc69e64e993585290081a3530b5",
          "md5": "f30f88f85270b7ada2d49798e4f33cac"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-sse",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-sse-iossimulatorarm64-3.1.2-SNAPSHOT-metadata.jar",
          "url": "ktor-server-sse-iossimulatorarm64-3.1.2-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "35d81a07d4522b551b4983182a59e568939b281123821317ae24005db57d35ba7f26fbd16b526e59086a5f25d281e5799ae00f37f1ccc3b6cbb325b845cfac9f",
          "sha256": "2e5514b293a99257a085ef8714ccba874d9c8d00d53d07de6b18697d2873fb4e",
          "sha1": "210cff97c6c2a0c599a0fc2811319ae52769c3c0",
          "md5": "29b623e1a154112860a6ae18d6ffd563"
        }
      ]
    }
  ]
}
