{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-hsts/3.1.2-SNAPSHOT/ktor-server-hsts-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-server-hsts",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-hsts-wasm-js-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-hsts-wasm-js-3.1.2-SNAPSHOT.klib",
          "size": 13021,
          "sha512": "d2b77f7806fdb169909deb132e0656ec939a1dbdc90996092b56f2814b8a347dfed853efe1225b52769676be9d5eaf969c9130870c8168fadc36caac09269dec",
          "sha256": "08b457bb9491397e3e7e256727bb6bc07261d6e339de24a1d0d3dc76b0c3a173",
          "sha1": "0d809a0244307b9ede2df34bfe61cbd10328dcda",
          "md5": "db3a259cef988332e6ab88048f7f21e4"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-browser",
          "version": {
            "requires": "0.3"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-hsts-wasm-js-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-hsts-wasm-js-3.1.2-SNAPSHOT.klib",
          "size": 13021,
          "sha512": "d2b77f7806fdb169909deb132e0656ec939a1dbdc90996092b56f2814b8a347dfed853efe1225b52769676be9d5eaf969c9130870c8168fadc36caac09269dec",
          "sha256": "08b457bb9491397e3e7e256727bb6bc07261d6e339de24a1d0d3dc76b0c3a173",
          "sha1": "0d809a0244307b9ede2df34bfe61cbd10328dcda",
          "md5": "db3a259cef988332e6ab88048f7f21e4"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "ktor-server-hsts-wasm-js-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-server-hsts-wasm-js-3.1.2-SNAPSHOT-sources.jar",
          "size": 3323,
          "sha512": "651edba1850a83d467c526b1b8b970f4d08350490283e4de3bcabd1a7eba3d4c096db53f975a433945868e7aaffb963ce4de3b5a2a049e7f0d33ff129f7fd977",
          "sha256": "7c98706e0d2ce08552b15d0326a8df0211e7368f9fa0b42ca76b8a5f96479d09",
          "sha1": "bdbda58ec2947691fa225823995da28d391522dc",
          "md5": "72f5ccd82581b8becd1c3e4a4c705315"
        }
      ]
    }
  ]
}
