{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-rpc-krpc-ktor-client/0.5.1/kotlinx-rpc-krpc-ktor-client-0.5.1.module",
    "group": "com.vickyleu.kotlinx",
    "module": "kotlinx-rpc-krpc-ktor-client",
    "version": "0.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.vickyleu.kotlinx",
          "module": "kotlinx-rpc-krpc-client",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "com.vickyleu.kotlinx",
          "module": "kotlinx-rpc-krpc-ktor-core",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-websockets",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-rpc-krpc-ktor-client-watchosArm32Main-0.5.1.klib",
          "url": "kotlinx-rpc-krpc-ktor-client-watchosarm32-0.5.1.klib",
          "size": 11941,
          "sha512": "1f43f7df5e0574f282e50c47f4e61f31a55a7a4c57d819ef21884023775f355a77a3c441816c5d0278bc5c9e8dd452ae7f81c2f6ec82f04dc16e6725d7f86028",
          "sha256": "4dba7f3dce7dd664eb8646db000ce41e03b4592e47ea6e8bfd276f16c80d4497",
          "sha1": "74881b41f877901ff825d6f981c3d1e939d56e23",
          "md5": "ce660a9cf26b1f6a5ba9371eb23486fc"
        }
      ]
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-rpc-krpc-ktor-client-watchosarm32-0.5.1-sources.jar",
          "url": "kotlinx-rpc-krpc-ktor-client-watchosarm32-0.5.1-sources.jar",
          "size": 3324,
          "sha512": "2a29469277d9872d798ddc91c27d0f6737621c12a29d3c87c29525951eba56b0b97ba0c6cc894316d4776050b912f1c64d3b32738daa4f74ce1de7449cbc4de4",
          "sha256": "1e15015e92429743b18c7a242a42e3fa38971d9034cf6979d6c5cc199bc6d53d",
          "sha1": "c5269cc3aa65e334361c11a8e28df375f0d1d237",
          "md5": "a246d63fe8d1dc585d2f8585d00ec781"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.vickyleu.kotlinx",
          "module": "kotlinx-rpc-krpc-client",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "com.vickyleu.kotlinx",
          "module": "kotlinx-rpc-krpc-ktor-core",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-websockets",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-rpc-krpc-ktor-client-watchosarm32-0.5.1-metadata.jar",
          "url": "kotlinx-rpc-krpc-ktor-client-watchosarm32-0.5.1-metadata.jar",
          "size": 261,
          "sha512": "85be1c295f615a2ad4a59d77b507efb8c2ff209a6c71decf81b343dbe04d5525886a4c550d1319a59b01b19a1e8220ad6395909f23abb3c2985215b444689fe6",
          "sha256": "197affec993c9881813bd42180cdb4a7da21e6f2efc0b20e7d20c232f3849e3a",
          "sha1": "9f3d26b13c89e12f51cff52085802e897ed6d473",
          "md5": "55fef0533f5e11bc59a189eab494e774"
        }
      ]
    }
  ]
}
