{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-rpc-krpc-ktor-server/0.6.1/kotlinx-rpc-krpc-ktor-server-0.6.1.module",
    "group": "com.vickyleu.kotlinx",
    "module": "kotlinx-rpc-krpc-ktor-server",
    "version": "0.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.vickyleu.kotlinx",
          "module": "kotlinx-rpc-krpc-server",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "com.vickyleu.kotlinx",
          "module": "kotlinx-rpc-krpc-ktor-core",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-websockets",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-rpc-krpc-ktor-server-iosSimulatorArm64Main-0.6.1.klib",
          "url": "kotlinx-rpc-krpc-ktor-server-iossimulatorarm64-0.6.1.klib",
          "size": 16405,
          "sha512": "74bec81285b3d2fdc5b6224777b70b7ef97449be0b30adc2777ee43e68ebdfe7c59abbde764d479a2d018a22fc78aa2fc7cbe97acc17d2b88ab2211b8cc7305d",
          "sha256": "170008fc4d3e26b5e1621f620f764a785e83160fd0042390157439717ba6f45d",
          "sha1": "4fe85836c0120ea4824503f4d1cba82fe74a9a8b",
          "md5": "4c9f63918c80849783ba9fc1f66b2910"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-rpc-krpc-ktor-server-iossimulatorarm64-0.6.1-sources.jar",
          "url": "kotlinx-rpc-krpc-ktor-server-iossimulatorarm64-0.6.1-sources.jar",
          "size": 4130,
          "sha512": "e7335ff86532b2576e9a93bf285145f5710fbf2ff3fa08d76031aa66efe182756e5c4d89984d94b5bb2c04389c774410ef13ee8594bd2f921c60a7d687b953a7",
          "sha256": "e85d3c36e11d60635e12c7f52d22574a505a4cb5616f10436576a6d1470cf915",
          "sha1": "58495b65a3cfed725bb4fc971850d64bf1d08652",
          "md5": "2b910f18cce4f4de1e8c236b06f19270"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.vickyleu.kotlinx",
          "module": "kotlinx-rpc-krpc-server",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "com.vickyleu.kotlinx",
          "module": "kotlinx-rpc-krpc-ktor-core",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-websockets",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-rpc-krpc-ktor-server-iossimulatorarm64-0.6.1-metadata.jar",
          "url": "kotlinx-rpc-krpc-ktor-server-iossimulatorarm64-0.6.1-metadata.jar",
          "size": 261,
          "sha512": "a38024cf1c5a9b91478122598df1dc8e59cdccc529d3fb9d4b68d3b9ede6a6d37bd6f958c7998d60bc2bcf7cf4c4b15e6bba5b6d95458bd4b8e24acc96f1b6dc",
          "sha256": "6df3e8e234ea1ff2b731b912f59721afbb0ce3621616083c67c5a2ac16ffda37",
          "sha1": "72ba5445cfa6a38d98d001ef9732c7ccab04c4ec",
          "md5": "a0a2c27dbbbcc231d9ce1d7299efdc8f"
        }
      ]
    }
  ]
}
