{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-client-logging/3.1.2-SNAPSHOT/ktor-client-logging-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-client-logging",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-logging-js-3.1.2-SNAPSHOT.klib",
          "url": "ktor-client-logging-js-3.1.2-SNAPSHOT.klib",
          "size": 65158,
          "sha512": "289b6fe59ea5160e0605537ed41f6ca2bfdadb7b60cfbe3e80ed18fbaf190cb10733222feb03b8175723b2ee07a5d1578b70a5ce25944fa85f9200619cdcdc44",
          "sha256": "d9526c49053fbf017409fc32ca054353f8dc50910c16b90556314e55d30f6509",
          "sha1": "8d64cc9a4730f52d6934c27eaac9a67901276bd2",
          "md5": "6d8318e1104c8dd9462ddb9cae9b6b4f"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-logging-js-3.1.2-SNAPSHOT.klib",
          "url": "ktor-client-logging-js-3.1.2-SNAPSHOT.klib",
          "size": 65158,
          "sha512": "289b6fe59ea5160e0605537ed41f6ca2bfdadb7b60cfbe3e80ed18fbaf190cb10733222feb03b8175723b2ee07a5d1578b70a5ce25944fa85f9200619cdcdc44",
          "sha256": "d9526c49053fbf017409fc32ca054353f8dc50910c16b90556314e55d30f6509",
          "sha1": "8d64cc9a4730f52d6934c27eaac9a67901276bd2",
          "md5": "6d8318e1104c8dd9462ddb9cae9b6b4f"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "ktor-client-logging-js-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-client-logging-js-3.1.2-SNAPSHOT-sources.jar",
          "size": 13058,
          "sha512": "59c44bb3f0f7f0bdcd0bdd4a7b2546c35c5a1adcc4cd91c3a018e8ae5ed986c4311b16129eb62e0c7e1b3311d175fb0886acdf2e6752e810fe5c02eea913d225",
          "sha256": "76539607866eef50411e4e7f85c975263d19d34e1ac3c25cf6895741944aa37e",
          "sha1": "602b0da986e6259a998a065f0178700a60f0a546",
          "md5": "bf992c1e516d4f700599f4f76171fdd6"
        }
      ]
    }
  ]
}
