{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-logging/7.0.6/kotlin-logging-7.0.6.module",
    "group": "com.vickyleu.oshai",
    "module": "kotlin-logging",
    "version": "7.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-logging.klib",
          "url": "kotlin-logging-androidnativearm32-7.0.6.klib",
          "size": 61061,
          "sha512": "ec6fd4b900486947e63fe276e4817afa25022558ee472dc184502c9241d8e714775d8111d63fb5343c2cc3c4a0031a1533423e38d75797d2225264486622f688",
          "sha256": "d59d4b8eb01652b9065d5593c322622d785c6dcd7e898cf4bcfa9529a1495b53",
          "sha1": "151f98a9ab147ea411a2c83177d806cdef3db538",
          "md5": "5f847b45ac28ea1ae0552a6d19b4ad9e"
        }
      ]
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlin-logging-androidnativearm32-7.0.6-sources.jar",
          "url": "kotlin-logging-androidnativearm32-7.0.6-sources.jar",
          "size": 20201,
          "sha512": "4c7ca5e16cf801d9d315da093d1d9c7a43f5d3c0d68584610baaad205b061b26e145cff26aa717042f411a034c2a749ecdad993c78272520d23b8b94689a3cd9",
          "sha256": "e17789d3323197aace91091e0c2563797ab53750466f6ff50f592b21c75ee0ad",
          "sha1": "7ead86b2f539ec848cd1becb7e095295111d14a6",
          "md5": "a5039892c87f0d38983d3ea938daba09"
        }
      ]
    }
  ]
}
