{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-rpc-krpc-serialization-core/0.6.1/kotlinx-rpc-krpc-serialization-core-0.6.1.module",
    "group": "com.vickyleu.kotlinx",
    "module": "kotlinx-rpc-krpc-serialization-core",
    "version": "0.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "com.vickyleu.kotlinx",
          "module": "kotlinx-rpc-utils",
          "version": {
            "requires": "0.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-rpc-krpc-serialization-core-linuxArm64Main-0.6.1.klib",
          "url": "kotlinx-rpc-krpc-serialization-core-linuxarm64-0.6.1.klib",
          "size": 9062,
          "sha512": "9562906dbdece37018e807f0b1f08ac08252d92e9f75675ec033315687fa2a699751e260a7bbd442e9c6c4e2ec5e100f19b6d55de06f20702f78eb8d51957145",
          "sha256": "7b177aa746ea79101b6a8086a5e8e1d8e3f467d7b21c74375db28144f54888af",
          "sha1": "692cf50be7d9d8a5737a38a000a448df6a8dd805",
          "md5": "1f15bf6b823d791ae0613d64ea821d08"
        }
      ]
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-rpc-krpc-serialization-core-linuxarm64-0.6.1-sources.jar",
          "url": "kotlinx-rpc-krpc-serialization-core-linuxarm64-0.6.1-sources.jar",
          "size": 2900,
          "sha512": "632cf30f421c4f5d16c7e4cfdb7abceadadb2aa6b78f6b9883b21724e62cdcb0f03a5959ba1d3538d2d101bca870066fa5ce211bbe0fcf2a6c0e1b1e453abea9",
          "sha256": "e7aaa7fe1f037413fe15ae7491dd1d2cdd9596b170cf6973c5a2bde1fd269065",
          "sha1": "e3f669e66041adc3c2f9c3ff8133a2a28410ec5d",
          "md5": "b949ed5d91c37e620fb383140fc50e77"
        }
      ]
    }
  ]
}
