{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-client-bom-remover/3.1.2-SNAPSHOT/ktor-client-bom-remover-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-client-bom-remover",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-bom-remover-androidNativeX86Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-client-bom-remover-androidnativex86-3.1.2-SNAPSHOT.klib",
          "size": 10245,
          "sha512": "73acf6ce9746d1cfca676757c698ed5e9871f3fdbde9d0ac9966600670919934e04135822467e8b7e01d84d2d8bb91e0e1aad24a98087154d1cc30f5ef0c60c8",
          "sha256": "539d1fb4be17f70cad7e25564cb77613bcd777fd2edb641403d99e2371e26a39",
          "sha1": "4092eae5d9e3dbf269418c01fc6c8358ea7426fb",
          "md5": "a71016253aac1808693c3389f31a5928"
        }
      ]
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-client-bom-remover-androidnativex86-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-client-bom-remover-androidnativex86-3.1.2-SNAPSHOT-sources.jar",
          "size": 2250,
          "sha512": "601d1b60ba994ecee1d35c9029023c73b7150c6dd9ba4144e00013972be24ae7ab903003720c2b7349b0d3bb98041e819e9c70c6ea5bcd5a18af97106c3f2e53",
          "sha256": "5afb89a510b8d286b3287f61e18b9d473f518cb05d09db82a95894bf9d00866e",
          "sha1": "63bf5f9eb5e0c5fe653543ebe814bf5a8d3f37f6",
          "md5": "ef474c89c65a2d83b9ecbef2a413b7c1"
        }
      ]
    }
  ]
}
