{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-rpc-krpc-ktor-client/0.5.1/kotlinx-rpc-krpc-ktor-client-0.5.1.module",
    "group": "com.vickyleu.kotlinx",
    "module": "kotlinx-rpc-krpc-ktor-client",
    "version": "0.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.vickyleu.kotlinx",
          "module": "kotlinx-rpc-krpc-client",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "com.vickyleu.kotlinx",
          "module": "kotlinx-rpc-krpc-ktor-core",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-websockets",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-rpc-krpc-ktor-client-jvm-0.5.1.jar",
          "url": "kotlinx-rpc-krpc-ktor-client-jvm-0.5.1.jar",
          "size": 10751,
          "sha512": "c50f58beabb63b26f28670f4166dbb5c92994ea18dab66366a8457f46bfeff1dbafd10440c0bfa6387a38d71f1172e37be3b932fc03c0a64f46bd90e108ac600",
          "sha256": "1ef5cc7ec5227d2a3b8dc21cf1d424d0b2f13953096866f5279107871dd5fff5",
          "sha1": "b46d2c5ad0a590890462929a77909119664ba7b5",
          "md5": "b39c2a0388d7929e2dc080ff29291ee6"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.vickyleu.kotlinx",
          "module": "kotlinx-rpc-krpc-client",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "com.vickyleu.kotlinx",
          "module": "kotlinx-rpc-krpc-ktor-core",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-websockets",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-rpc-krpc-ktor-client-jvm-0.5.1.jar",
          "url": "kotlinx-rpc-krpc-ktor-client-jvm-0.5.1.jar",
          "size": 10751,
          "sha512": "c50f58beabb63b26f28670f4166dbb5c92994ea18dab66366a8457f46bfeff1dbafd10440c0bfa6387a38d71f1172e37be3b932fc03c0a64f46bd90e108ac600",
          "sha256": "1ef5cc7ec5227d2a3b8dc21cf1d424d0b2f13953096866f5279107871dd5fff5",
          "sha1": "b46d2c5ad0a590890462929a77909119664ba7b5",
          "md5": "b39c2a0388d7929e2dc080ff29291ee6"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlinx-rpc-krpc-ktor-client-jvm-0.5.1-sources.jar",
          "url": "kotlinx-rpc-krpc-ktor-client-jvm-0.5.1-sources.jar",
          "size": 3324,
          "sha512": "2a29469277d9872d798ddc91c27d0f6737621c12a29d3c87c29525951eba56b0b97ba0c6cc894316d4776050b912f1c64d3b32738daa4f74ce1de7449cbc4de4",
          "sha256": "1e15015e92429743b18c7a242a42e3fa38971d9034cf6979d6c5cc199bc6d53d",
          "sha1": "c5269cc3aa65e334361c11a8e28df375f0d1d237",
          "md5": "a246d63fe8d1dc585d2f8585d00ec781"
        }
      ]
    }
  ]
}
