{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-double-receive/3.1.2-SNAPSHOT/ktor-server-double-receive-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-server-double-receive",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-double-receive-androidNativeX86Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-double-receive-androidnativex86-3.1.2-SNAPSHOT.klib",
          "size": 23208,
          "sha512": "4a39f1c0a40269c8eea907657d145720b166e1887f70a91e1fde60044bd26bc54af648ab6f8280a15f635416090684f1f119e45aa44178bb80198cc61e63b34e",
          "sha256": "a06a87944082d0f48312015c1620b3d6cde0cbd071e867713bcbed172283ab95",
          "sha1": "263efbe6648db9b050c87f4e18e6fa2673695f36",
          "md5": "fa5164bff8d7ef571d8229dc11f5ffa0"
        }
      ]
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-server-double-receive-androidnativex86-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-server-double-receive-androidnativex86-3.1.2-SNAPSHOT-sources.jar",
          "size": 7243,
          "sha512": "f4ab371064a5ddbe99c957d85ce93ab1b8b9af2b7782913846e0ee540919ae0fa2eb317b7abb23c258f07b9b9c462d2dc110f15d9f0854a6989b0750444de85b",
          "sha256": "d31cf7c6a6b0ff00b18cfb9f1cd622ee70e64be0c505d1141ebcc61115d6936c",
          "sha1": "45f922896fdd1a97360dbead8657de50b0f2aba0",
          "md5": "90d091b4a2b5cfbb9b25db2082360d5e"
        }
      ]
    }
  ]
}
