{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-html-builder/3.1.2-SNAPSHOT/ktor-server-html-builder-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-server-html-builder",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-html-builder-js-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-html-builder-js-3.1.2-SNAPSHOT.klib",
          "size": 15777,
          "sha512": "bc30b861ceb4eae20d607166748c963b178d2c0affc0d96d90ca068380390921f4a37d37e98deedbf02e2f04c9f916f02781a150d34c783b7669287f19a7a7fc",
          "sha256": "7ad4a32a29384a32e40f24249a77b75ac028ac95bcd610d4ce91d1bc26a0952b",
          "sha1": "1c232a63119d2cd179db67901de9902b268d51da",
          "md5": "d0aee5da40821e2fbbbe7be5ae925cbd"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-html-builder-js-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-html-builder-js-3.1.2-SNAPSHOT.klib",
          "size": 15777,
          "sha512": "bc30b861ceb4eae20d607166748c963b178d2c0affc0d96d90ca068380390921f4a37d37e98deedbf02e2f04c9f916f02781a150d34c783b7669287f19a7a7fc",
          "sha256": "7ad4a32a29384a32e40f24249a77b75ac028ac95bcd610d4ce91d1bc26a0952b",
          "sha1": "1c232a63119d2cd179db67901de9902b268d51da",
          "md5": "d0aee5da40821e2fbbbe7be5ae925cbd"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "ktor-server-html-builder-js-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-server-html-builder-js-3.1.2-SNAPSHOT-sources.jar",
          "size": 3624,
          "sha512": "ae49215733d475fb2907f74f88eb3a35d19aa7c1d551ead30ccd2d249fe7c7f6202b56f068d0c446585d364c73dc6a5d4a3f40c3f6db5b4a8aacb7e68e620324",
          "sha256": "a99b379ad0a12c0b88263bed2344f4912bafc8b2a1fad50426b7af85dbd6a831",
          "sha1": "ba1b0434aaade1511092dd908b61086894bdf31e",
          "md5": "a33f6166580925e7c3c33680a951369b"
        }
      ]
    }
  ]
}
