{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-rpc-utils/0.5.1/kotlinx-rpc-utils-0.5.1.module",
    "group": "com.vickyleu.kotlinx",
    "module": "kotlinx-rpc-utils",
    "version": "0.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-rpc-utils-js-0.5.1.klib",
          "url": "kotlinx-rpc-utils-js-0.5.1.klib",
          "size": 28208,
          "sha512": "dc434cf148b1c82ed9788327ceaeb445a1f800a00bae13ffaced194d4b38a279338d185d88e2e4a0ce073b6f8f717e42bcd045220a0519e2ce023d63831b91cc",
          "sha256": "56a65c0a6474ac48e62c7294ade29097711662171662b545b0d9dd2d0b5db0ee",
          "sha1": "483df8671b78d0298af59ed472896c9aff3eb08e",
          "md5": "c36c470efba14b7f3267943bd9644da7"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-rpc-utils-js-0.5.1.klib",
          "url": "kotlinx-rpc-utils-js-0.5.1.klib",
          "size": 28208,
          "sha512": "dc434cf148b1c82ed9788327ceaeb445a1f800a00bae13ffaced194d4b38a279338d185d88e2e4a0ce073b6f8f717e42bcd045220a0519e2ce023d63831b91cc",
          "sha256": "56a65c0a6474ac48e62c7294ade29097711662171662b545b0d9dd2d0b5db0ee",
          "sha1": "483df8671b78d0298af59ed472896c9aff3eb08e",
          "md5": "c36c470efba14b7f3267943bd9644da7"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "kotlinx-rpc-utils-js-0.5.1-sources.jar",
          "url": "kotlinx-rpc-utils-js-0.5.1-sources.jar",
          "size": 7688,
          "sha512": "df46a5fa35cb7243cd2fcb631d0bc1428c8cdc964c28b28324aeaf6350cd7c79df4c3aca1479021dce49facf4a2d560425bcc0e21889bbaeef2143b7fa2cfe34",
          "sha256": "2bd99958f1dcd940583d1dcd6673484cc1859cfb8fae86baf27dc54305ae9ad3",
          "sha1": "7152de9dfeeba39c23542539752e0d7c8b8ab39d",
          "md5": "95953016ba110bfe76b83fcaa8224bc8"
        }
      ]
    }
  ]
}
