{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-client-logging/3.1.2-SNAPSHOT/ktor-client-logging-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-client-logging",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "linuxArm32HfpApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm32_hfp",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-logging-linuxArm32HfpMain-3.1.2-SNAPSHOT.klib",
          "url": "ktor-client-logging-linuxarm32hfp-3.1.2-SNAPSHOT.klib",
          "size": 65413,
          "sha512": "429feada783fccb278f9e9d3d36c19767c6ef80077b72af5175ceb9f438001b0ff6cae05f7d3580fed636f152eec20c16588caf51efb13fc8208efd074a8341b",
          "sha256": "2ea44578a2da0108da66b30b39597e6263aed88fb9d1ea75eb7ca6897185d148",
          "sha1": "c03d0cdc7fa588dd08738cea12686b2b492e29ae",
          "md5": "f10afbcbc79f2c2824b49c07d03faaa3"
        }
      ]
    },
    {
      "name": "linuxArm32HfpSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm32_hfp",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-client-logging-linuxarm32hfp-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-client-logging-linuxarm32hfp-3.1.2-SNAPSHOT-sources.jar",
          "size": 12884,
          "sha512": "d6c655e54a0140f79a081c3894fbbed45bb11b789e253bb89da518460ab7bc7a24d7fefe2f09f78e638f9ecab50faf3920b5db7ca2e4ef77614a05ea54dbdb1e",
          "sha256": "c1b5e42a0f62aba40eb6e1b7be3b14b3b8e7a1faed66b70809d20ccf126dab5f",
          "sha1": "7665416d5f350b1f050645318d6d500c49c0771f",
          "md5": "58abd29cbd75848178782c0133745b8c"
        }
      ]
    }
  ]
}
