{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-logging/7.0.6/kotlin-logging-7.0.6.module",
    "group": "com.vickyleu.oshai",
    "module": "kotlin-logging",
    "version": "7.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-logging.klib",
          "url": "kotlin-logging-iosx64-7.0.6.klib",
          "size": 53048,
          "sha512": "1af656b748d287fdbde675fbc33a22d9d109d1c4ab3ae4d59f0edb61bcae000ddd17559dfd58b3a733f8355f33c862b1be1a099d049673f76a8793895827c92c",
          "sha256": "8dc0d6b413cc88b3de0fcbc0a106f81ab6b5a48a67bfe67f1d326c715083ca0f",
          "sha1": "68a47a62006d09303e2c6b111c645600a96d83d2",
          "md5": "296f87d2c1336f975343a5392e7fd688"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlin-logging-iosx64-7.0.6-sources.jar",
          "url": "kotlin-logging-iosx64-7.0.6-sources.jar",
          "size": 16496,
          "sha512": "bd1dab8709b1a2d3cc798bf285bf936216e5ea5759f80e89e8af56bcf76e52d30352deaf335e0dc0fe8bb230482e02b022c7c872377418038668a3f372015996",
          "sha256": "4e273ad46eff6f1878a64f6b6ff98477709223dfecaa6d63fd3019fbb4da6162",
          "sha1": "2bfe758ad68d35ee3131001cd5dff984e52c890b",
          "md5": "50ce16cbbf7a625e8b862c29d87b3b79"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-logging-iosx64-7.0.6-metadata.jar",
          "url": "kotlin-logging-iosx64-7.0.6-metadata.jar",
          "size": 9248,
          "sha512": "f9e66c80cd99f494606d2db2a520d163182e9f00fe03340060dee5910c6acb4e6adf5ddf57d5a58eb9d4745f77836729c445a2aca6611660198fb101822247dd",
          "sha256": "29406b21716131623c743a3c0a68734dc04a36e8f58e90e983e688665f687cf5",
          "sha1": "de29f250d320ec58a5c1a5b64f197f0121bee850",
          "md5": "9f89d38512ff3c2299a685e7b2039035"
        }
      ]
    }
  ]
}
