{
  "formatVersion": "1.1",
  "component": {
    "group": "com.vickyleu.ktor",
    "module": "ktor-resources",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-utils",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-resources-metadata-3.1.2-SNAPSHOT.jar",
          "url": "ktor-resources-3.1.2-SNAPSHOT.jar",
          "size": 7191,
          "sha512": "cd5a6e37588cb58441e54452699abdef3c77216f6b76d9a45d23f81659c481568b949e0943e3c4ed120e329e0318af1460e48bc3c73ca8549b662e1364bd4865",
          "sha256": "f28314263e999138eaa11abed8b93b94ccc9c0283187d862a71393e8790ec21f",
          "sha1": "4fa29abb6c28cad24b8fbc38622e1c7849ec44c0",
          "md5": "642f73aa2556a2a1d2e3c4886be0a996"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "ktor-resources-kotlin-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-resources-3.1.2-SNAPSHOT-sources.jar",
          "size": 7352,
          "sha512": "67c11afcdce02a947eccb437cc0c144535506e38924f7f4c52a03ddadfebab135c3e8e662d0f9541136fa7b3e5a458f709c83012d79e6b78bc63776b4d0e0656",
          "sha256": "836b34e90ae980c60d258f5f02ddcb85d495190632ca4efb85a4e3c62f3e7aa4",
          "sha1": "d57c8e6c873e41e78cc0ba50344e50cb68743c5f",
          "md5": "bbcde504ca4d38d95a268ddbc41af6ef"
        }
      ]
    },
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-resources-androidnativearm32/3.1.2-SNAPSHOT/ktor-resources-androidnativearm32-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-resources-androidnativearm32",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-resources-androidnativearm32/3.1.2-SNAPSHOT/ktor-resources-androidnativearm32-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-resources-androidnativearm32",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-resources-androidnativearm64/3.1.2-SNAPSHOT/ktor-resources-androidnativearm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-resources-androidnativearm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "androidNativeArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-resources-androidnativearm64/3.1.2-SNAPSHOT/ktor-resources-androidnativearm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-resources-androidnativearm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-resources-androidnativex64/3.1.2-SNAPSHOT/ktor-resources-androidnativex64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-resources-androidnativex64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "androidNativeX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-resources-androidnativex64/3.1.2-SNAPSHOT/ktor-resources-androidnativex64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-resources-androidnativex64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-resources-androidnativex86/3.1.2-SNAPSHOT/ktor-resources-androidnativex86-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-resources-androidnativex86",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-resources-androidnativex86/3.1.2-SNAPSHOT/ktor-resources-androidnativex86-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-resources-androidnativex86",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-resources-iosarm64/3.1.2-SNAPSHOT/ktor-resources-iosarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-resources-iosarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-resources-iosarm64/3.1.2-SNAPSHOT/ktor-resources-iosarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-resources-iosarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-resources-iosarm64/3.1.2-SNAPSHOT/ktor-resources-iosarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-resources-iosarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-resources-iossimulatorarm64/3.1.2-SNAPSHOT/ktor-resources-iossimulatorarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-resources-iossimulatorarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-resources-iossimulatorarm64/3.1.2-SNAPSHOT/ktor-resources-iossimulatorarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-resources-iossimulatorarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-resources-iossimulatorarm64/3.1.2-SNAPSHOT/ktor-resources-iossimulatorarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-resources-iossimulatorarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-resources-iosx64/3.1.2-SNAPSHOT/ktor-resources-iosx64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-resources-iosx64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-resources-iosx64/3.1.2-SNAPSHOT/ktor-resources-iosx64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-resources-iosx64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-resources-iosx64/3.1.2-SNAPSHOT/ktor-resources-iosx64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-resources-iosx64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../ktor-resources-js/3.1.2-SNAPSHOT/ktor-resources-js-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-resources-js",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../ktor-resources-js/3.1.2-SNAPSHOT/ktor-resources-js-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-resources-js",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../ktor-resources-js/3.1.2-SNAPSHOT/ktor-resources-js-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-resources-js",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktor-resources-jvm/3.1.2-SNAPSHOT/ktor-resources-jvm-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-resources-jvm",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktor-resources-jvm/3.1.2-SNAPSHOT/ktor-resources-jvm-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-resources-jvm",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktor-resources-jvm/3.1.2-SNAPSHOT/ktor-resources-jvm-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-resources-jvm",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "linuxArm32HfpApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm32_hfp",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-resources-linuxarm32hfp/3.1.2-SNAPSHOT/ktor-resources-linuxarm32hfp-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-resources-linuxarm32hfp",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "linuxArm32HfpSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm32_hfp",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-resources-linuxarm32hfp/3.1.2-SNAPSHOT/ktor-resources-linuxarm32hfp-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-resources-linuxarm32hfp",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-resources-linuxarm64/3.1.2-SNAPSHOT/ktor-resources-linuxarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-resources-linuxarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-resources-linuxarm64/3.1.2-SNAPSHOT/ktor-resources-linuxarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-resources-linuxarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-resources-linuxx64/3.1.2-SNAPSHOT/ktor-resources-linuxx64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-resources-linuxx64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-resources-linuxx64/3.1.2-SNAPSHOT/ktor-resources-linuxx64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-resources-linuxx64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-resources-macosarm64/3.1.2-SNAPSHOT/ktor-resources-macosarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-resources-macosarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-resources-macosarm64/3.1.2-SNAPSHOT/ktor-resources-macosarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-resources-macosarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-resources-macosarm64/3.1.2-SNAPSHOT/ktor-resources-macosarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-resources-macosarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-resources-macosx64/3.1.2-SNAPSHOT/ktor-resources-macosx64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-resources-macosx64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-resources-macosx64/3.1.2-SNAPSHOT/ktor-resources-macosx64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-resources-macosx64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-resources-macosx64/3.1.2-SNAPSHOT/ktor-resources-macosx64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-resources-macosx64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-resources-mingwx64/3.1.2-SNAPSHOT/ktor-resources-mingwx64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-resources-mingwx64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-resources-mingwx64/3.1.2-SNAPSHOT/ktor-resources-mingwx64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-resources-mingwx64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-resources-tvosarm64/3.1.2-SNAPSHOT/ktor-resources-tvosarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-resources-tvosarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-resources-tvosarm64/3.1.2-SNAPSHOT/ktor-resources-tvosarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-resources-tvosarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-resources-tvosarm64/3.1.2-SNAPSHOT/ktor-resources-tvosarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-resources-tvosarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-resources-tvossimulatorarm64/3.1.2-SNAPSHOT/ktor-resources-tvossimulatorarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-resources-tvossimulatorarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-resources-tvossimulatorarm64/3.1.2-SNAPSHOT/ktor-resources-tvossimulatorarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-resources-tvossimulatorarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-resources-tvossimulatorarm64/3.1.2-SNAPSHOT/ktor-resources-tvossimulatorarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-resources-tvossimulatorarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-resources-tvosx64/3.1.2-SNAPSHOT/ktor-resources-tvosx64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-resources-tvosx64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-resources-tvosx64/3.1.2-SNAPSHOT/ktor-resources-tvosx64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-resources-tvosx64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-resources-tvosx64/3.1.2-SNAPSHOT/ktor-resources-tvosx64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-resources-tvosx64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../ktor-resources-wasm-js/3.1.2-SNAPSHOT/ktor-resources-wasm-js-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-resources-wasm-js",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../ktor-resources-wasm-js/3.1.2-SNAPSHOT/ktor-resources-wasm-js-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-resources-wasm-js",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../ktor-resources-wasm-js/3.1.2-SNAPSHOT/ktor-resources-wasm-js-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-resources-wasm-js",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-resources-watchosarm32/3.1.2-SNAPSHOT/ktor-resources-watchosarm32-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-resources-watchosarm32",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-resources-watchosarm32/3.1.2-SNAPSHOT/ktor-resources-watchosarm32-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-resources-watchosarm32",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-resources-watchosarm32/3.1.2-SNAPSHOT/ktor-resources-watchosarm32-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-resources-watchosarm32",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-resources-watchosarm64/3.1.2-SNAPSHOT/ktor-resources-watchosarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-resources-watchosarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-resources-watchosarm64/3.1.2-SNAPSHOT/ktor-resources-watchosarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-resources-watchosarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-resources-watchosarm64/3.1.2-SNAPSHOT/ktor-resources-watchosarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-resources-watchosarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "watchosDeviceArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-resources-watchosdevicearm64/3.1.2-SNAPSHOT/ktor-resources-watchosdevicearm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-resources-watchosdevicearm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "watchosDeviceArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-resources-watchosdevicearm64/3.1.2-SNAPSHOT/ktor-resources-watchosdevicearm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-resources-watchosdevicearm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "watchosDeviceArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-resources-watchosdevicearm64/3.1.2-SNAPSHOT/ktor-resources-watchosdevicearm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-resources-watchosdevicearm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-resources-watchossimulatorarm64/3.1.2-SNAPSHOT/ktor-resources-watchossimulatorarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-resources-watchossimulatorarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-resources-watchossimulatorarm64/3.1.2-SNAPSHOT/ktor-resources-watchossimulatorarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-resources-watchossimulatorarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-resources-watchossimulatorarm64/3.1.2-SNAPSHOT/ktor-resources-watchossimulatorarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-resources-watchossimulatorarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-resources-watchosx64/3.1.2-SNAPSHOT/ktor-resources-watchosx64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-resources-watchosx64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-resources-watchosx64/3.1.2-SNAPSHOT/ktor-resources-watchosx64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-resources-watchosx64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-resources-watchosx64/3.1.2-SNAPSHOT/ktor-resources-watchosx64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-resources-watchosx64",
        "version": "3.1.2-SNAPSHOT"
      }
    }
  ]
}
