{
  "formatVersion": "1.1",
  "component": {
    "group": "com.vickyleu.ktor",
    "module": "ktor-server-host-common",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-host-common-metadata-3.1.2-SNAPSHOT.jar",
          "url": "ktor-server-host-common-3.1.2-SNAPSHOT.jar",
          "size": 2741,
          "sha512": "a8fcd54e10c1b50eeda714396f52d123e953e9e2c74dfb1f70945bf639ffa8a0a7e860a2d09a85bacf74795f0d65582d879125ffbd6c5033793bd0be6144c50a",
          "sha256": "8c383e7055a05802ec80f48e265827ce0e05676b549d5a5be322ed789f7bd406",
          "sha1": "958eca8c8b151cebd4ee293bda32570b2ff4bb75",
          "md5": "70c76ef012b9cc00c4075e3824d2e8b2"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "ktor-server-host-common-kotlin-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-server-host-common-3.1.2-SNAPSHOT-sources.jar",
          "size": 621,
          "sha512": "f04f945d6a7d30a53537aa03c5b9ff5f72e60e4150cc04bec3114161649c0177f6ef2d801ca541f66ae5e2a12a40c6f5560f6c166f14e70f3731a9b77361aced",
          "sha256": "8f1b77aa660fed1302454fd2a303ab07ab29a5d52029c98850cedff554c454f0",
          "sha1": "ee19f777cd0f857f7e5bccd5eacb04c7496d9a13",
          "md5": "5b14dfc1ec7145751b60a8479edee37d"
        }
      ]
    },
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-host-common-androidnativearm32/3.1.2-SNAPSHOT/ktor-server-host-common-androidnativearm32-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-host-common-androidnativearm32",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-host-common-androidnativearm32/3.1.2-SNAPSHOT/ktor-server-host-common-androidnativearm32-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-host-common-androidnativearm32",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-host-common-androidnativearm64/3.1.2-SNAPSHOT/ktor-server-host-common-androidnativearm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-host-common-androidnativearm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "androidNativeArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-host-common-androidnativearm64/3.1.2-SNAPSHOT/ktor-server-host-common-androidnativearm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-host-common-androidnativearm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-host-common-androidnativex64/3.1.2-SNAPSHOT/ktor-server-host-common-androidnativex64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-host-common-androidnativex64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "androidNativeX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-host-common-androidnativex64/3.1.2-SNAPSHOT/ktor-server-host-common-androidnativex64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-host-common-androidnativex64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-host-common-androidnativex86/3.1.2-SNAPSHOT/ktor-server-host-common-androidnativex86-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-host-common-androidnativex86",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-host-common-androidnativex86/3.1.2-SNAPSHOT/ktor-server-host-common-androidnativex86-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-host-common-androidnativex86",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-host-common-iosarm64/3.1.2-SNAPSHOT/ktor-server-host-common-iosarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-host-common-iosarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-host-common-iosarm64/3.1.2-SNAPSHOT/ktor-server-host-common-iosarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-host-common-iosarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-host-common-iosarm64/3.1.2-SNAPSHOT/ktor-server-host-common-iosarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-host-common-iosarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-host-common-iossimulatorarm64/3.1.2-SNAPSHOT/ktor-server-host-common-iossimulatorarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-host-common-iossimulatorarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-host-common-iossimulatorarm64/3.1.2-SNAPSHOT/ktor-server-host-common-iossimulatorarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-host-common-iossimulatorarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-host-common-iossimulatorarm64/3.1.2-SNAPSHOT/ktor-server-host-common-iossimulatorarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-host-common-iossimulatorarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-host-common-iosx64/3.1.2-SNAPSHOT/ktor-server-host-common-iosx64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-host-common-iosx64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-host-common-iosx64/3.1.2-SNAPSHOT/ktor-server-host-common-iosx64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-host-common-iosx64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-host-common-iosx64/3.1.2-SNAPSHOT/ktor-server-host-common-iosx64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-host-common-iosx64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../ktor-server-host-common-js/3.1.2-SNAPSHOT/ktor-server-host-common-js-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-host-common-js",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../ktor-server-host-common-js/3.1.2-SNAPSHOT/ktor-server-host-common-js-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-host-common-js",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../ktor-server-host-common-js/3.1.2-SNAPSHOT/ktor-server-host-common-js-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-host-common-js",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktor-server-host-common-jvm/3.1.2-SNAPSHOT/ktor-server-host-common-jvm-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-host-common-jvm",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktor-server-host-common-jvm/3.1.2-SNAPSHOT/ktor-server-host-common-jvm-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-host-common-jvm",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktor-server-host-common-jvm/3.1.2-SNAPSHOT/ktor-server-host-common-jvm-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-host-common-jvm",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "linuxArm32HfpApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm32_hfp",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-host-common-linuxarm32hfp/3.1.2-SNAPSHOT/ktor-server-host-common-linuxarm32hfp-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-host-common-linuxarm32hfp",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "linuxArm32HfpSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm32_hfp",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-host-common-linuxarm32hfp/3.1.2-SNAPSHOT/ktor-server-host-common-linuxarm32hfp-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-host-common-linuxarm32hfp",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-host-common-linuxarm64/3.1.2-SNAPSHOT/ktor-server-host-common-linuxarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-host-common-linuxarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-host-common-linuxarm64/3.1.2-SNAPSHOT/ktor-server-host-common-linuxarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-host-common-linuxarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-host-common-linuxx64/3.1.2-SNAPSHOT/ktor-server-host-common-linuxx64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-host-common-linuxx64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-host-common-linuxx64/3.1.2-SNAPSHOT/ktor-server-host-common-linuxx64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-host-common-linuxx64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-host-common-macosarm64/3.1.2-SNAPSHOT/ktor-server-host-common-macosarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-host-common-macosarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-host-common-macosarm64/3.1.2-SNAPSHOT/ktor-server-host-common-macosarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-host-common-macosarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-host-common-macosarm64/3.1.2-SNAPSHOT/ktor-server-host-common-macosarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-host-common-macosarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-host-common-macosx64/3.1.2-SNAPSHOT/ktor-server-host-common-macosx64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-host-common-macosx64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-host-common-macosx64/3.1.2-SNAPSHOT/ktor-server-host-common-macosx64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-host-common-macosx64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-host-common-macosx64/3.1.2-SNAPSHOT/ktor-server-host-common-macosx64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-host-common-macosx64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-host-common-mingwx64/3.1.2-SNAPSHOT/ktor-server-host-common-mingwx64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-host-common-mingwx64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-host-common-mingwx64/3.1.2-SNAPSHOT/ktor-server-host-common-mingwx64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-host-common-mingwx64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-host-common-tvosarm64/3.1.2-SNAPSHOT/ktor-server-host-common-tvosarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-host-common-tvosarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-host-common-tvosarm64/3.1.2-SNAPSHOT/ktor-server-host-common-tvosarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-host-common-tvosarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-host-common-tvosarm64/3.1.2-SNAPSHOT/ktor-server-host-common-tvosarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-host-common-tvosarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-host-common-tvossimulatorarm64/3.1.2-SNAPSHOT/ktor-server-host-common-tvossimulatorarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-host-common-tvossimulatorarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-host-common-tvossimulatorarm64/3.1.2-SNAPSHOT/ktor-server-host-common-tvossimulatorarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-host-common-tvossimulatorarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-host-common-tvossimulatorarm64/3.1.2-SNAPSHOT/ktor-server-host-common-tvossimulatorarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-host-common-tvossimulatorarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-host-common-tvosx64/3.1.2-SNAPSHOT/ktor-server-host-common-tvosx64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-host-common-tvosx64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-host-common-tvosx64/3.1.2-SNAPSHOT/ktor-server-host-common-tvosx64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-host-common-tvosx64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-host-common-tvosx64/3.1.2-SNAPSHOT/ktor-server-host-common-tvosx64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-host-common-tvosx64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../ktor-server-host-common-wasm-js/3.1.2-SNAPSHOT/ktor-server-host-common-wasm-js-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-host-common-wasm-js",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../ktor-server-host-common-wasm-js/3.1.2-SNAPSHOT/ktor-server-host-common-wasm-js-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-host-common-wasm-js",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../ktor-server-host-common-wasm-js/3.1.2-SNAPSHOT/ktor-server-host-common-wasm-js-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-host-common-wasm-js",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-host-common-watchosarm32/3.1.2-SNAPSHOT/ktor-server-host-common-watchosarm32-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-host-common-watchosarm32",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-host-common-watchosarm32/3.1.2-SNAPSHOT/ktor-server-host-common-watchosarm32-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-host-common-watchosarm32",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-host-common-watchosarm32/3.1.2-SNAPSHOT/ktor-server-host-common-watchosarm32-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-host-common-watchosarm32",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-host-common-watchosarm64/3.1.2-SNAPSHOT/ktor-server-host-common-watchosarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-host-common-watchosarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-host-common-watchosarm64/3.1.2-SNAPSHOT/ktor-server-host-common-watchosarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-host-common-watchosarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-host-common-watchosarm64/3.1.2-SNAPSHOT/ktor-server-host-common-watchosarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-host-common-watchosarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "watchosDeviceArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-host-common-watchosdevicearm64/3.1.2-SNAPSHOT/ktor-server-host-common-watchosdevicearm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-host-common-watchosdevicearm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "watchosDeviceArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-host-common-watchosdevicearm64/3.1.2-SNAPSHOT/ktor-server-host-common-watchosdevicearm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-host-common-watchosdevicearm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "watchosDeviceArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-host-common-watchosdevicearm64/3.1.2-SNAPSHOT/ktor-server-host-common-watchosdevicearm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-host-common-watchosdevicearm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-host-common-watchossimulatorarm64/3.1.2-SNAPSHOT/ktor-server-host-common-watchossimulatorarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-host-common-watchossimulatorarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-host-common-watchossimulatorarm64/3.1.2-SNAPSHOT/ktor-server-host-common-watchossimulatorarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-host-common-watchossimulatorarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-host-common-watchossimulatorarm64/3.1.2-SNAPSHOT/ktor-server-host-common-watchossimulatorarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-host-common-watchossimulatorarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-host-common-watchosx64/3.1.2-SNAPSHOT/ktor-server-host-common-watchosx64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-host-common-watchosx64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-host-common-watchosx64/3.1.2-SNAPSHOT/ktor-server-host-common-watchosx64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-host-common-watchosx64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-host-common-watchosx64/3.1.2-SNAPSHOT/ktor-server-host-common-watchosx64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-host-common-watchosx64",
        "version": "3.1.2-SNAPSHOT"
      }
    }
  ]
}
