{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-rpc-krpc-logging/0.5.1/kotlinx-rpc-krpc-logging-0.5.1.module",
    "group": "com.vickyleu.kotlinx",
    "module": "kotlinx-rpc-krpc-logging",
    "version": "0.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.6"
          }
        },
        {
          "group": "com.vickyleu.kotlinx",
          "module": "kotlinx-rpc-utils",
          "version": {
            "requires": "0.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-rpc-krpc-logging-macosArm64Main-0.5.1.klib",
          "url": "kotlinx-rpc-krpc-logging-macosarm64-0.5.1.klib",
          "size": 12401,
          "sha512": "f0f4f641122d23108aeca26a21a899ba3f80883088335e38200e6943193129a042f29642cb5fe1910697e462a0a4842b0927d609be2565aec509d90021676698",
          "sha256": "a08ba3ffd49910afd948170f7c85a0118065747adb42bc986e9b0bccb1b088fd",
          "sha1": "4f541cafa4c4dd2b20182b16f96cb61546f4a043",
          "md5": "ebd19eba9bf878314c2ea7c90c06412b"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-rpc-krpc-logging-macosarm64-0.5.1-sources.jar",
          "url": "kotlinx-rpc-krpc-logging-macosarm64-0.5.1-sources.jar",
          "size": 3141,
          "sha512": "02123f3be3ee56a880ea0742c1ea34d5e0e61f63530f12524c374fcf6f5f083a687f36115fbdac268315f88b26e6132ab5b514b88d71dbf081e7127f8912f6d6",
          "sha256": "8e48b530ee5752910707bf402ff89d304e9cd21d60d6b841a0b29bd4b6413cf0",
          "sha1": "9a949afff48ebd85331320e4b8d5a8da07bb1f66",
          "md5": "1da329d6bc94828d33ab4607a09699a0"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.6"
          }
        },
        {
          "group": "com.vickyleu.kotlinx",
          "module": "kotlinx-rpc-utils",
          "version": {
            "requires": "0.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-rpc-krpc-logging-macosarm64-0.5.1-metadata.jar",
          "url": "kotlinx-rpc-krpc-logging-macosarm64-0.5.1-metadata.jar",
          "size": 261,
          "sha512": "4e4c5f4b8acb0ada76c2c5e684218e5c8508a79942fd676615b6714a7b1b926668c047fad2b2e8090bc9d2176d32c66e8d2ed8a0e0daae18f8e5f59978e433e3",
          "sha256": "78f2ab3df68f7bed63906394a1c4c563cd7b7274bfe1ba1991ae4eb8565b6524",
          "sha1": "221529aebaa1a22ae9a75b481bd78fe18d402368",
          "md5": "1da75dbe527756cc868af023efab71ea"
        }
      ]
    }
  ]
}
