{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-serialization-kotlinx-json/3.1.2-SNAPSHOT/ktor-serialization-kotlinx-json-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-serialization-kotlinx-json",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-serialization-kotlinx",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json-io",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-serialization-kotlinx-json-js-3.1.2-SNAPSHOT.klib",
          "url": "ktor-serialization-kotlinx-json-js-3.1.2-SNAPSHOT.klib",
          "size": 17423,
          "sha512": "cf27c8054503215351192064f4ab6802629f14db5e796286c1657d51da10cabba0bc80ece9dca4b292d4b8b48d3165202d0edd09d697546ccd2f2dafc749e731",
          "sha256": "8f8a06c0abe71dd31465a29f1d0602f6483892a4cb150c8e86a9e7bf2d984610",
          "sha1": "b4df793719cb1f821a196dc3e81e0f36d6e5f5ca",
          "md5": "e1c6823f8e1199dea679f5f289de65f7"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-serialization-kotlinx",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json-io",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-serialization-kotlinx-json-js-3.1.2-SNAPSHOT.klib",
          "url": "ktor-serialization-kotlinx-json-js-3.1.2-SNAPSHOT.klib",
          "size": 17423,
          "sha512": "cf27c8054503215351192064f4ab6802629f14db5e796286c1657d51da10cabba0bc80ece9dca4b292d4b8b48d3165202d0edd09d697546ccd2f2dafc749e731",
          "sha256": "8f8a06c0abe71dd31465a29f1d0602f6483892a4cb150c8e86a9e7bf2d984610",
          "sha1": "b4df793719cb1f821a196dc3e81e0f36d6e5f5ca",
          "md5": "e1c6823f8e1199dea679f5f289de65f7"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "ktor-serialization-kotlinx-json-js-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-serialization-kotlinx-json-js-3.1.2-SNAPSHOT-sources.jar",
          "size": 5971,
          "sha512": "9e34b10fb0fb485c23444fa2e269b9b30f412fb69f77e651e31d7f84b608d80ff79e7ab30669a0ea13f988b87c6ccc221ac13bc9cc4c6ff3967677ebb57373de",
          "sha256": "8cff8bbae735ec9ff9b793fe2f4b31897b76d5609fd3967f35ed6dcafe848c58",
          "sha1": "1c1febe9d4ef3ccfb8a19c9a3a0322905184cf9e",
          "md5": "7b202301caf74e10390b14a8c98cf7cb"
        }
      ]
    }
  ]
}
