{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-sessions/3.1.2-SNAPSHOT/ktor-server-sessions-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-server-sessions",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-sessions-tvosX64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-sessions-tvosx64-3.1.2-SNAPSHOT.klib",
          "size": 111454,
          "sha512": "c4ab87a6062c4db105b6c2a8911887b12d7dbf50ac5f5a693a6c0100653929b872265cbfb62d99f5bab0f7a3f8d0a1d6815199dae0ad9d6082cbb17e2ae010f8",
          "sha256": "1e102a10104cd33eac0009fa93bab53c65135591c2f77ad7f9de3c727d656990",
          "sha1": "2357c14ec2081eea102e3a0d67033ae59c178375",
          "md5": "010cb75ba92d75b71821404ad57a0491"
        }
      ]
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-server-sessions-tvosx64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-server-sessions-tvosx64-3.1.2-SNAPSHOT-sources.jar",
          "size": 31745,
          "sha512": "f0a4238abe0b783ccdf0a08c52cfeb51c0ba3d4b63d14de7dc6d33547deeac8f57ac8d1b562f92cba6ff43ef0d87945e1beb779b1231dd90bd70e5b1dd1159b6",
          "sha256": "71cb3dad0879dad51ba8ed0dc330d1561d0a998a7377f6eea767c7c197bbb49a",
          "sha1": "ce297cc940281d294abede6ed7437829ddf83b59",
          "md5": "798da78b8d7098cee70dab8cb8b43c56"
        }
      ]
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-sessions-tvosx64-3.1.2-SNAPSHOT-metadata.jar",
          "url": "ktor-server-sessions-tvosx64-3.1.2-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "3157f1ae9a5d2e035a12613cf298ae3f780f79cc4661cfb2730d949d9009e1626fdf2133abbdedcf499a781de831b3dac8a43012c3f64f291e9008d44290cb64",
          "sha256": "cf26e268c63640658d6049a3ecc69b776049510e9c5011d5328687506809356e",
          "sha1": "ba8ebf472be1a847798050df9866d03a9d91238c",
          "md5": "da66f7fbf39936ced790cf225cc283d2"
        }
      ]
    }
  ]
}
