{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-client-serialization/3.1.2-SNAPSHOT/ktor-client-serialization-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-client-serialization",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-json",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-serialization-watchosSimulatorArm64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-client-serialization-watchossimulatorarm64-3.1.2-SNAPSHOT.klib",
          "size": 14383,
          "sha512": "b05eb0b51a7534a6cde1a03b6287fbac8eff7bf037db5f8ecd66169057e98088cfdc3a11f99799e08c32bde6ef1816a53bb6fed229828d6cf96db168674a0706",
          "sha256": "2e68347c5756a37329827a99da3815cb74139a33b78e9dd4d74dcfc74ca829a3",
          "sha1": "f0dff6779034e0b4dcba16fac93dcfdfb47b7d7c",
          "md5": "6cabe905ea7bd31335a576226110ff30"
        }
      ]
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-client-serialization-watchossimulatorarm64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-client-serialization-watchossimulatorarm64-3.1.2-SNAPSHOT-sources.jar",
          "size": 3394,
          "sha512": "eea49ae1a94a5d00db16695a67180ed24f798e17c2c81504c3e2dcd90db917049269f10755edd6def16aa2e5aed2522d8217075c379d1aeeb680a037487e04f5",
          "sha256": "9f9285d261c3855649a0c4514451321a043edcafa3489c64e61ee0f2388f63d3",
          "sha1": "216426f0558308f7c9c460f10e29ee50bb4feca8",
          "md5": "a739bed8bcf9bb4951030df82e403d35"
        }
      ]
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-json",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-serialization-watchossimulatorarm64-3.1.2-SNAPSHOT-metadata.jar",
          "url": "ktor-client-serialization-watchossimulatorarm64-3.1.2-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "8c74905187b8c0c0c04ebfb512f4df5b2302e07eb1a7bd92882253feafaeed0886de2accbd3969487416c2767c924310d7a303906c342e763cf3b0eccac37b02",
          "sha256": "bf90c797d6e529306fae63afcb4d1c2b907afe1a134c0f026837b061ab423a06",
          "sha1": "819e0733093939c9f4362f312e4fdf44ebdb97ec",
          "md5": "c1398f5b5dba4020bad110e7ba713dab"
        }
      ]
    }
  ]
}
