{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-websockets/3.1.2-SNAPSHOT/ktor-websockets-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-websockets",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-utils",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-websockets-wasm-js-3.1.2-SNAPSHOT.klib",
          "url": "ktor-websockets-wasm-js-3.1.2-SNAPSHOT.klib",
          "size": 80676,
          "sha512": "8a40c1ba99e9550bb5fe307fcb9363c1caf28258e9acb7d7a2227d1c2d14cdeb89159e645b09b3245fbbd53f28b3fe2edbb40cab044d24fc4de2c1429e99407d",
          "sha256": "d33417b776666efb977c5e7728d2da912b460b613e0d5a1593743e39163b2e59",
          "sha1": "f63be27f808ba06686f17c151d08ace6a2ab7cbc",
          "md5": "7e40bdbb611451f2d624e09200747c8d"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-utils",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-browser",
          "version": {
            "requires": "0.3"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-websockets-wasm-js-3.1.2-SNAPSHOT.klib",
          "url": "ktor-websockets-wasm-js-3.1.2-SNAPSHOT.klib",
          "size": 80676,
          "sha512": "8a40c1ba99e9550bb5fe307fcb9363c1caf28258e9acb7d7a2227d1c2d14cdeb89159e645b09b3245fbbd53f28b3fe2edbb40cab044d24fc4de2c1429e99407d",
          "sha256": "d33417b776666efb977c5e7728d2da912b460b613e0d5a1593743e39163b2e59",
          "sha1": "f63be27f808ba06686f17c151d08ace6a2ab7cbc",
          "md5": "7e40bdbb611451f2d624e09200747c8d"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "ktor-websockets-wasm-js-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-websockets-wasm-js-3.1.2-SNAPSHOT-sources.jar",
          "size": 22640,
          "sha512": "324cdf2c01ade21772ddf7282d9a9e46bcf18916e53607fa6206a684c99cc3d01a06bfb1218f3d35cdfbee59dee09031247ed358fa085215659c527005802c8f",
          "sha256": "680428ce34cd73aca55a9ffe2893234505d6563059f8a242728961fb2570ec02",
          "sha1": "3b2376463e2af31f3faeb830ac04bf3fb1266054",
          "md5": "5314473950d22b5e989214ffaad5dd5b"
        }
      ]
    }
  ]
}
