{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-http-cio/3.1.2-SNAPSHOT/ktor-http-cio-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-http-cio",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-io",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-http-cio-androidNativeArm32Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-http-cio-androidnativearm32-3.1.2-SNAPSHOT.klib",
          "size": 131202,
          "sha512": "550dc7ddb7807112c690dd324cea288cb07aebe9398b5289d58847ede1319221d2eabe507dea4f951ba8389a86ea8afab66d9868968eab577cb97e5e7acc5d8d",
          "sha256": "5143c5d96a08233f3e9e6e1e9662f4ed8bc5fc72ba8f75f26ed019a48c58ffa0",
          "sha1": "94b22fd1d1ffa8033b3171a1acf503239b8995ca",
          "md5": "1a14ae46a1b3066c614cec7cb5a20f8d"
        }
      ]
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-http-cio-androidnativearm32-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-http-cio-androidnativearm32-3.1.2-SNAPSHOT-sources.jar",
          "size": 28012,
          "sha512": "eeb1e5f41eaea9d570e2adf80131ce15fdb6ff7b485161e918b5307ddecf61639d983d5085b81afc80570d615410c340633ddf326be4ccf6895cf5949f9037d4",
          "sha256": "354c235d3b5e2c1b658a98372fa714e879f1cc6a7b68ff5e0ad0dbdb8f27a2b9",
          "sha1": "5e1f9da60d6952c974b3958af3c6761c307d2761",
          "md5": "92216b961edd779fabbaea1a5ad7a1a6"
        }
      ]
    }
  ]
}
