{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-coroutines-core/1.10.1-SNAPSHOT/kotlinx-coroutines-core-1.10.1-SNAPSHOT.module",
    "group": "com.vickyleu.kotlinx.coroutines",
    "module": "kotlinx-coroutines-core",
    "version": "1.10.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.26.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.23.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-core-tvosArm64Main-1.10.1-SNAPSHOT.klib",
          "url": "kotlinx-coroutines-core-tvosarm64-1.10.1-SNAPSHOT.klib",
          "size": 885135,
          "sha512": "25ff205f14f538e5a0f8dbea6887117fde20cda01e4dd11efea412db60717a4726d7c2cdd043e3ef549a559778273ab87d9ee7e85683dd881e964c80f94be99a",
          "sha256": "f2ea4bc60eb57e80491d878e7eaf8e3d3fe96b05c1683f5cd6ca7de5cdc2b592",
          "sha1": "484f88258e389c704a1ecadb4d80ace26582153f",
          "md5": "18e6158de6681050326fce47eb7e4265"
        }
      ]
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-coroutines-core-tvosarm64-1.10.1-SNAPSHOT-sources.jar",
          "url": "kotlinx-coroutines-core-tvosarm64-1.10.1-SNAPSHOT-sources.jar",
          "size": 326899,
          "sha512": "9d4892499ed632b3500f8915664100dd1d6a4ba9e4b54d70be3bc03b11e4448a6621bb39b5a807ad5b33fad948d8dedf651d33220b1b73aa9efdbcfe6292a354",
          "sha256": "d15395d2dd17ba38c6bbce79c6f0b596d092e29f220b9aec5e0df85aee4f9afd",
          "sha1": "0a289e9827a7dad4daf501d658ee05922a0479ac",
          "md5": "e2d0cc73ef6f4d7fd7aca63892d36eb1"
        }
      ]
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.26.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.23.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-core-tvosarm64-1.10.1-SNAPSHOT-metadata.jar",
          "url": "kotlinx-coroutines-core-tvosarm64-1.10.1-SNAPSHOT-metadata.jar",
          "size": 3537,
          "sha512": "e2a66e4a0c2dd1fc409252a5967d2f8b6ea9955fd4fc5a3e3e78beab5fae6384120423884a2bd3736d951435f357b5439771e3d3d9df6777c4fbcab0d1100c85",
          "sha256": "eb8646df16973f13daeb8c3744f37d5297b760c2734a83c3b35191617e896acd",
          "sha1": "952dc5772196c3d86ead3553bcf9449b83f26d8b",
          "md5": "7e017d804c67ceaf71ca463538e9bf8c"
        }
      ]
    }
  ]
}
