{
  "formatVersion": "1.1",
  "component": {
    "group": "com.vickyleu.kotlinx",
    "module": "kotlinx-rpc-protobuf-plugin",
    "version": "0.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-rpc-protobuf-plugin-0.5.1-all.jar",
          "url": "kotlinx-rpc-protobuf-plugin-0.5.1-all.jar",
          "size": 4580571,
          "sha512": "33d3db0c36ce4a0136ef9fd994bcb744039c34437495abc07451eeb74fbd9e9d2ca670c2ff9aa49e76c297ac1d834acf70bf8085cf0d7a935e72a411b859803a",
          "sha256": "b064cd4ba62bcea39e020d9a592d6fa2698234e45d8986ed0253db66f5b3e632",
          "sha1": "b3a598980e4eba2c97ddccdd6e1f7286f1544939",
          "md5": "4f88c88ba0d8cceb21c432771f664272"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "4.29.3"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.3.14"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-rpc-protobuf-plugin-0.5.1-all.jar",
          "url": "kotlinx-rpc-protobuf-plugin-0.5.1-all.jar",
          "size": 4580571,
          "sha512": "33d3db0c36ce4a0136ef9fd994bcb744039c34437495abc07451eeb74fbd9e9d2ca670c2ff9aa49e76c297ac1d834acf70bf8085cf0d7a935e72a411b859803a",
          "sha256": "b064cd4ba62bcea39e020d9a592d6fa2698234e45d8986ed0253db66f5b3e632",
          "sha1": "b3a598980e4eba2c97ddccdd6e1f7286f1544939",
          "md5": "4f88c88ba0d8cceb21c432771f664272"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlinx-rpc-protobuf-plugin-0.5.1-sources.jar",
          "url": "kotlinx-rpc-protobuf-plugin-0.5.1-sources.jar",
          "size": 18443,
          "sha512": "b87069de930bf46136e80ad14e3b8eb81f7bfb5f024486944cebc84fe3a63f867b99f132ecd7b2985339a60e3d65c675ea1360dd8c09cfa8461c2c45102a9b84",
          "sha256": "46899b5d5db3abaf635db94f5fc71d38ef647c351836f47021e1d3e87fc3cab0",
          "sha1": "8cd233b7683d110461b62e17e871d64ceaac0fab",
          "md5": "bc3349b28a7186fd77c3a82ea4d5c1cc"
        }
      ]
    }
  ]
}
