{
  "formatVersion": "1.1",
  "component": {
    "url": "../../pbandk-runtime/0.16.1-SNAPSHOT/pbandk-runtime-0.16.1-SNAPSHOT.module",
    "group": "com.vickyleu.pbandk",
    "module": "pbandk-runtime",
    "version": "0.16.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.2"
          }
        }
      ],
      "files": [
        {
          "name": "pbandk-runtime.klib",
          "url": "pbandk-runtime-watchosarm32-0.16.1-SNAPSHOT.klib",
          "size": 678477,
          "sha512": "555963f54e249db3a3142715a6fad2a9712c52bacb6228e31aa1984ea52566735f4830af017aab391a99e9c8f5dfb0625cf8601660c69f6e520db6529e35d882",
          "sha256": "813006ebe9aff21ea1be33b64d27c7a95a4bbf1edc2126c8d9588e788495c74c",
          "sha1": "3dd63ef3effa652778304ae980ca9ff909338fe2",
          "md5": "d6c86059e493599bc70e2d125cc7d0d3"
        }
      ]
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "pbandk-runtime-watchosarm32-0.16.1-SNAPSHOT-sources.jar",
          "url": "pbandk-runtime-watchosarm32-0.16.1-SNAPSHOT-sources.jar",
          "size": 89500,
          "sha512": "036c717c886c7f2c66b568ad3f05a1cb159fa5c07ee64235fbe6c226562682e11c912094acbd57cc82fa03b81919ca35c59763c042e88d3d5c74138950020ff7",
          "sha256": "51e2b29d585dbda1123cca39bc5e65c2495759858466323d67a5c02fd1fb998b",
          "sha1": "4d74b3fac1961c3b7cf671023c4d8af87873ec17",
          "md5": "e33355a59f03ba7232f002d0d24d31e2"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.2"
          }
        }
      ],
      "files": [
        {
          "name": "pbandk-runtime-watchosarm32-0.16.1-SNAPSHOT-metadata.jar",
          "url": "pbandk-runtime-watchosarm32-0.16.1-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "ca440462aa1af49b7de0526cbd4ea8bd6898163269363313850614ccdb6d56d70f41777ebd850dbe53332d4005b23755a8e45f0caa2dd46b099d4671d9f4aec7",
          "sha256": "b6985a03b411d244afdc27f5b66d5c61df4e89b9287fc524c9228a8efcbb74dd",
          "sha1": "3739b2b82f2cd9bbd42d8e3805592c935ff17cf7",
          "md5": "8f7933626e8474f0f154f9e7b6f79f4e"
        }
      ]
    }
  ]
}
