{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-utils/3.1.2-SNAPSHOT/ktor-utils-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-utils",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-io",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-utils-androidNativeArm64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-utils-androidnativearm64-3.1.2-SNAPSHOT.klib",
          "size": 302991,
          "sha512": "b537022be09dbfc9292238bf7e9cb31e496772fffd85f9c1af880ffc12df1eb7e14ab7b1bf4ddf68fc547699f849581c808e26481ff08041434f0f0fccb0f2cd",
          "sha256": "8d5de123686cce11f3db9bd1de7daf8e8607e0628bfa1b1ca99217f5aa192455",
          "sha1": "753013252b892b7c74a737e8e3b48f21144da928",
          "md5": "f28f7a8b45272b94ccb7ad17a1fd8e81"
        },
        {
          "name": "ktor-utils-androidNativeArm64Cinterop-threadUtilsMain-3.1.2-SNAPSHOT.klib",
          "url": "ktor-utils-androidnativearm64-3.1.2-SNAPSHOT-cinterop-threadUtils.klib",
          "size": 3624,
          "sha512": "e90a3e78019ad539de137673b1f4809caafcffa343e6ec98bf5eb0c07dddb89a22d7a2da4ee29958bab2fb1213183b76942b9dd7236b668136694b8ac8a442fa",
          "sha256": "0240245568c2b540537c057b7a4fa0c3e795ce66f4bf9842b96aea492ba19ce0",
          "sha1": "7ab79ffe1ebe035ca811b0d0b9d2d026a3fff4f6",
          "md5": "d8fc2be230c2deff391267adb62086f9"
        }
      ]
    },
    {
      "name": "androidNativeArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-utils-androidnativearm64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-utils-androidnativearm64-3.1.2-SNAPSHOT-sources.jar",
          "size": 79218,
          "sha512": "f3f6ef880e26439eeaacc8ef12eca1e4e1a9890f95b6de0bab6e929d1cb0d5934effd23fcfc0a709c0a8ad46f1841968167ed83107c81b77d1e71a261593b8c2",
          "sha256": "8e37de852133c8e41b7e02c6d233d4944819372434221175e06ebba97880bcd6",
          "sha1": "dabd10b3fea69addafe3174d2849b43f7d4f32fd",
          "md5": "1e00290f4817176c8ab39e5f08f39564"
        }
      ]
    }
  ]
}
