{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-sessions/3.1.2-SNAPSHOT/ktor-server-sessions-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-server-sessions",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-sessions-wasm-js-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-sessions-wasm-js-3.1.2-SNAPSHOT.klib",
          "size": 104541,
          "sha512": "8b8a85ead5975759275842f0fce2b7f6e8c364c2ffb38b0cda385b85b8251925983343c80cb070578b577082bb14261dad93b218f3ef9de34d9c0b4911420824",
          "sha256": "57bc532a89b0195c459b08fc6b4835e7ae69312905e4b584c7d6dd66f9177b63",
          "sha1": "770bab298b9bdd7ec068a8c75b63f18d5378a8d7",
          "md5": "4f88bee9a33d7036d2db30b9cb77790f"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-browser",
          "version": {
            "requires": "0.3"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-sessions-wasm-js-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-sessions-wasm-js-3.1.2-SNAPSHOT.klib",
          "size": 104541,
          "sha512": "8b8a85ead5975759275842f0fce2b7f6e8c364c2ffb38b0cda385b85b8251925983343c80cb070578b577082bb14261dad93b218f3ef9de34d9c0b4911420824",
          "sha256": "57bc532a89b0195c459b08fc6b4835e7ae69312905e4b584c7d6dd66f9177b63",
          "sha1": "770bab298b9bdd7ec068a8c75b63f18d5378a8d7",
          "md5": "4f88bee9a33d7036d2db30b9cb77790f"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "ktor-server-sessions-wasm-js-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-server-sessions-wasm-js-3.1.2-SNAPSHOT-sources.jar",
          "size": 29484,
          "sha512": "50bb2e099de3dc2f73be86e573eb15458fc8427b5d2d6235995ab2352c9bd87ee4f614ae83ebdc7dfa085a966363597eb008ab93d43eb4aec1cbc77606e035cb",
          "sha256": "5fb8062e4ea2cbcb76da7e09bc34f81cdd1af7cb1cb69b7e7861c89b6faaeb2d",
          "sha1": "96b88b8151bae65bb4b47710e7ce3102a200bcfa",
          "md5": "89a35c52d00577046e6cac24fe9c7d05"
        }
      ]
    }
  ]
}
