{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-coroutines-core/1.10.1-SNAPSHOT/kotlinx-coroutines-core-1.10.1-SNAPSHOT.module",
    "group": "com.vickyleu.kotlinx.coroutines",
    "module": "kotlinx-coroutines-core",
    "version": "1.10.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.26.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.23.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-core-androidNativeArm64Main-1.10.1-SNAPSHOT.klib",
          "url": "kotlinx-coroutines-core-androidnativearm64-1.10.1-SNAPSHOT.klib",
          "size": 880566,
          "sha512": "8286e373df99fb0c7e641f2425771ca0d76b016898094fd7426d6f27bfab1da41659042f375ca5bbad90ccbbe517dd89346ea639c84f223976a4568bca4352c5",
          "sha256": "946e372e36dbd5e38202768b5768099d0158cdf79d95fbae7b1bd0b09c5886e7",
          "sha1": "52dfbf0f23d744b062c07cb1bf91f0047414b0f3",
          "md5": "00879ee8260bbd5b0acad2443198337b"
        }
      ]
    },
    {
      "name": "androidNativeArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-coroutines-core-androidnativearm64-1.10.1-SNAPSHOT-sources.jar",
          "url": "kotlinx-coroutines-core-androidnativearm64-1.10.1-SNAPSHOT-sources.jar",
          "size": 326322,
          "sha512": "3baa45410e34e627d94ce48b2ac83d746dc218c15ac61ad9248e2ecbbbd8100f3d2d669ac9b4e08c886cb43cbcf60dc511da381318912d8646cd02b71f0f8eca",
          "sha256": "2e41aae66473253a7e059fc459fc565cca6cb1364e556b844b2118489f6d498b",
          "sha1": "e6a5ebd30625c67b9e9f2f83e0adac8e09ae994d",
          "md5": "8fde3447dbcd242e15d842cd47ddf9df"
        }
      ]
    }
  ]
}
