{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-client-android/3.1.2-SNAPSHOT/ktor-client-android-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-client-android",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-android-jvm-3.1.2-SNAPSHOT.jar",
          "url": "ktor-client-android-jvm-3.1.2-SNAPSHOT.jar",
          "size": 24022,
          "sha512": "72240779b901127f035f954344ccffca6e4f27949e7328ec5597dbdc64a3fcc1fc366a35edbe583eee8929a2dd6f01ecf9ea10660e7bc0ddfb807101c26dc6b1",
          "sha256": "f6cabcc414b8f0ae3e1ffb6c581e6925a1b26d49c19babdf237ab7e91380f810",
          "sha1": "5fee3e36b3bab12e09daa65cd10366ff1c7cc49a",
          "md5": "db2a18a8d084f814062262190796640f"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-android-jvm-3.1.2-SNAPSHOT.jar",
          "url": "ktor-client-android-jvm-3.1.2-SNAPSHOT.jar",
          "size": 24022,
          "sha512": "72240779b901127f035f954344ccffca6e4f27949e7328ec5597dbdc64a3fcc1fc366a35edbe583eee8929a2dd6f01ecf9ea10660e7bc0ddfb807101c26dc6b1",
          "sha256": "f6cabcc414b8f0ae3e1ffb6c581e6925a1b26d49c19babdf237ab7e91380f810",
          "sha1": "5fee3e36b3bab12e09daa65cd10366ff1c7cc49a",
          "md5": "db2a18a8d084f814062262190796640f"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ktor-client-android-jvm-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-client-android-jvm-3.1.2-SNAPSHOT-sources.jar",
          "size": 5904,
          "sha512": "001fda1f24c62659d533c95235215078c6046109ebeacae34a4791409e38f453adfa92cf98baf91f146bac20bda4d9f648431bb36e987b31f59dd2daaee8dd23",
          "sha256": "5f70d08f3a99b6d7bfc8ba3e8682fc3ecd778d83460aa9a546e5bccb9e19f24d",
          "sha1": "f981de8c4a28c9c4206fb97fb6b969e8b5c41a30",
          "md5": "50a998b1a97ad40edc58f88dde9b2746"
        }
      ]
    }
  ]
}
