{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-status-pages/3.1.2-SNAPSHOT/ktor-server-status-pages-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-server-status-pages",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-status-pages-macosX64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-status-pages-macosx64-3.1.2-SNAPSHOT.klib",
          "size": 18049,
          "sha512": "0817329e1fddad41cdc6476d53e158bfc6af8afdeebc1e8776bd92486b6397ec826febf432f31a21ef10085c0d175df5b89a100fb9f5f3971bf9a5cd7425931b",
          "sha256": "fe3883e06a6f5c924335986891071e0631e8d16395436c80dea24179eda7a1fc",
          "sha1": "d1d67f656c49f599ce9c1ffa84806830136712f4",
          "md5": "78e097d12914cefa5b5677dc545ee490"
        }
      ]
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-server-status-pages-macosx64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-server-status-pages-macosx64-3.1.2-SNAPSHOT-sources.jar",
          "size": 4758,
          "sha512": "6b1a6e1606534e11002bc47a2d5ed94b186a4e02a2f868ff3c3687b7bba676b323c77d45847a5acdc9a27433e4546f781db9ad4f09eb431a48370d31e1d3a03d",
          "sha256": "ba3d5d42cdc12b18d9c449179b9ed4c0ef3d0b020ac641fe0eae9742a84dce08",
          "sha1": "e314d526d0e34a6fef84635936faec5915fa9554",
          "md5": "f58150dbe90df72f4f2741c8447d9c34"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-status-pages-macosx64-3.1.2-SNAPSHOT-metadata.jar",
          "url": "ktor-server-status-pages-macosx64-3.1.2-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "6a9d004b7b1dbe705338ab536e104e89b0c862c50f44e0cab2ff6041e46cba33ef3f92575c5bf0fdc4942568bd734a128b7fb9d6562f654c6ec08838fcdaa4b2",
          "sha256": "8e5a91cf6a6a8c101028b864ce58545222eac0d8f09cefd157a43eff5ebfff8b",
          "sha1": "3c8053787b0e3743f462f67f349fa71610295352",
          "md5": "48cc397b0448d1e872e818ca2efd11f8"
        }
      ]
    }
  ]
}
