{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-client-darwin-legacy/3.1.2-SNAPSHOT/ktor-client-darwin-legacy-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-client-darwin-legacy",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-darwin-legacy-macosArm64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-client-darwin-legacy-macosarm64-3.1.2-SNAPSHOT.klib",
          "size": 86481,
          "sha512": "45ec9050a9518a2e559fb5a38b8a39a7068bb64379e3149f4932dcd4728c39cd39a2b29ef001fb2054fc47fb66060fd9002efe9aed58d25eb316ec50b6dce230",
          "sha256": "2499ac266970aac8b16b966b8a1952da7d6ce2f704ee15c6a9be9d81691782f3",
          "sha1": "b2a8cf3fcda806188be9da9c7b5f4611e96c398b",
          "md5": "813a8e0d99a7d69ed7e4f070bd3e7f5e"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-client-darwin-legacy-macosarm64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-client-darwin-legacy-macosarm64-3.1.2-SNAPSHOT-sources.jar",
          "size": 21583,
          "sha512": "a33bbccb06359ff2ebf521080a76ab2ecd34b301d3419dcf3303ee974c1bfd8912f94aab0c39371e71b5244551388f24827ba3b6d87b3ba0b741f6a07b8df568",
          "sha256": "9b2a6888d14345b7aa8db1e9ad5dfcdbe7bc2cd4e336ad58326be1b96e6992ca",
          "sha1": "79ab0165fe95797a7dd475ad4088641925592970",
          "md5": "c6d8bf2a23b2f17b231fd52f412a3022"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-darwin-legacy-macosarm64-3.1.2-SNAPSHOT-metadata.jar",
          "url": "ktor-client-darwin-legacy-macosarm64-3.1.2-SNAPSHOT-metadata.jar",
          "size": 15252,
          "sha512": "c10e11d883ac04b28197ed98ebc5226a8cadaf6ddbda19cca048c6a19814a20f69ae4268d218bff99ba241b5e3df0bba494db709e41a9b7c2f1cc3ed2c3cd615",
          "sha256": "122336f972e374da7c2b6cc6075df5e155951ca7905b814248956ca372d66450",
          "sha1": "631d31be7accf2c1145021a84458d8fd0ad82701",
          "md5": "4e6c1c1479d8143534e3355d07cf7e76"
        }
      ]
    }
  ]
}
