{
  "formatVersion": "1.1",
  "component": {
    "group": "com.vickyleu.ktor",
    "module": "ktor-http-cio",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-io",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-http-cio-metadata-3.1.2-SNAPSHOT.jar",
          "url": "ktor-http-cio-3.1.2-SNAPSHOT.jar",
          "size": 21173,
          "sha512": "3273b63709b90c1ba2830fb0319f754df5c6c36a8bd55408a55b9a419b505a7e1ea142e13e9f90126ae7a8b5ca2eeec1e22d54410d79cd34c97249e5b2555e67",
          "sha256": "eb4d8bcecb206ff2c1ce5a1f67833a7cec6c265fa26d3f76111abfef0351678f",
          "sha1": "7c22c4422256b407a75f14d6a06e9034e7c8900c",
          "md5": "f1a515d1ddf7ca9dd15fdc6e51351b0c"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "ktor-http-cio-kotlin-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-http-cio-3.1.2-SNAPSHOT-sources.jar",
          "size": 30572,
          "sha512": "5ce112ea42b05599900d095bc812ae8e7fb274b4babfa8831dce5c9d82f314a9557be0ba9d911087d330c6e56dc003eed9367a8d62aa29c3dcafffedde3542ef",
          "sha256": "749a665973adbf1128d1f03b9af50954a38b66bf333f9e1ab473b8c65103d22b",
          "sha1": "1ed304054349ead1f0f6737dc821f4da49f80f8d",
          "md5": "df016d185a9c3c70d1f9578e3b55d921"
        }
      ]
    },
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-androidnativearm32/3.1.2-SNAPSHOT/ktor-http-cio-androidnativearm32-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-http-cio-androidnativearm32",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-androidnativearm32/3.1.2-SNAPSHOT/ktor-http-cio-androidnativearm32-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-http-cio-androidnativearm32",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-androidnativearm64/3.1.2-SNAPSHOT/ktor-http-cio-androidnativearm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-http-cio-androidnativearm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "androidNativeArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-androidnativearm64/3.1.2-SNAPSHOT/ktor-http-cio-androidnativearm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-http-cio-androidnativearm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-androidnativex64/3.1.2-SNAPSHOT/ktor-http-cio-androidnativex64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-http-cio-androidnativex64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "androidNativeX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-androidnativex64/3.1.2-SNAPSHOT/ktor-http-cio-androidnativex64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-http-cio-androidnativex64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-androidnativex86/3.1.2-SNAPSHOT/ktor-http-cio-androidnativex86-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-http-cio-androidnativex86",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-androidnativex86/3.1.2-SNAPSHOT/ktor-http-cio-androidnativex86-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-http-cio-androidnativex86",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-iosarm64/3.1.2-SNAPSHOT/ktor-http-cio-iosarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-http-cio-iosarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-iosarm64/3.1.2-SNAPSHOT/ktor-http-cio-iosarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-http-cio-iosarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-iosarm64/3.1.2-SNAPSHOT/ktor-http-cio-iosarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-http-cio-iosarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-iossimulatorarm64/3.1.2-SNAPSHOT/ktor-http-cio-iossimulatorarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-http-cio-iossimulatorarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-iossimulatorarm64/3.1.2-SNAPSHOT/ktor-http-cio-iossimulatorarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-http-cio-iossimulatorarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-iossimulatorarm64/3.1.2-SNAPSHOT/ktor-http-cio-iossimulatorarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-http-cio-iossimulatorarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-iosx64/3.1.2-SNAPSHOT/ktor-http-cio-iosx64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-http-cio-iosx64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-iosx64/3.1.2-SNAPSHOT/ktor-http-cio-iosx64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-http-cio-iosx64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-iosx64/3.1.2-SNAPSHOT/ktor-http-cio-iosx64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-http-cio-iosx64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../ktor-http-cio-js/3.1.2-SNAPSHOT/ktor-http-cio-js-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-http-cio-js",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../ktor-http-cio-js/3.1.2-SNAPSHOT/ktor-http-cio-js-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-http-cio-js",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../ktor-http-cio-js/3.1.2-SNAPSHOT/ktor-http-cio-js-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-http-cio-js",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktor-http-cio-jvm/3.1.2-SNAPSHOT/ktor-http-cio-jvm-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-http-cio-jvm",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktor-http-cio-jvm/3.1.2-SNAPSHOT/ktor-http-cio-jvm-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-http-cio-jvm",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktor-http-cio-jvm/3.1.2-SNAPSHOT/ktor-http-cio-jvm-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-http-cio-jvm",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "linuxArm32HfpApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm32_hfp",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-linuxarm32hfp/3.1.2-SNAPSHOT/ktor-http-cio-linuxarm32hfp-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-http-cio-linuxarm32hfp",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "linuxArm32HfpSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm32_hfp",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-linuxarm32hfp/3.1.2-SNAPSHOT/ktor-http-cio-linuxarm32hfp-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-http-cio-linuxarm32hfp",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-linuxarm64/3.1.2-SNAPSHOT/ktor-http-cio-linuxarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-http-cio-linuxarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-linuxarm64/3.1.2-SNAPSHOT/ktor-http-cio-linuxarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-http-cio-linuxarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-linuxx64/3.1.2-SNAPSHOT/ktor-http-cio-linuxx64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-http-cio-linuxx64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-linuxx64/3.1.2-SNAPSHOT/ktor-http-cio-linuxx64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-http-cio-linuxx64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-macosarm64/3.1.2-SNAPSHOT/ktor-http-cio-macosarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-http-cio-macosarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-macosarm64/3.1.2-SNAPSHOT/ktor-http-cio-macosarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-http-cio-macosarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-macosarm64/3.1.2-SNAPSHOT/ktor-http-cio-macosarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-http-cio-macosarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-macosx64/3.1.2-SNAPSHOT/ktor-http-cio-macosx64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-http-cio-macosx64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-macosx64/3.1.2-SNAPSHOT/ktor-http-cio-macosx64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-http-cio-macosx64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-macosx64/3.1.2-SNAPSHOT/ktor-http-cio-macosx64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-http-cio-macosx64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-mingwx64/3.1.2-SNAPSHOT/ktor-http-cio-mingwx64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-http-cio-mingwx64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-mingwx64/3.1.2-SNAPSHOT/ktor-http-cio-mingwx64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-http-cio-mingwx64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-tvosarm64/3.1.2-SNAPSHOT/ktor-http-cio-tvosarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-http-cio-tvosarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-tvosarm64/3.1.2-SNAPSHOT/ktor-http-cio-tvosarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-http-cio-tvosarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-tvosarm64/3.1.2-SNAPSHOT/ktor-http-cio-tvosarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-http-cio-tvosarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-tvossimulatorarm64/3.1.2-SNAPSHOT/ktor-http-cio-tvossimulatorarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-http-cio-tvossimulatorarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-tvossimulatorarm64/3.1.2-SNAPSHOT/ktor-http-cio-tvossimulatorarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-http-cio-tvossimulatorarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-tvossimulatorarm64/3.1.2-SNAPSHOT/ktor-http-cio-tvossimulatorarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-http-cio-tvossimulatorarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-tvosx64/3.1.2-SNAPSHOT/ktor-http-cio-tvosx64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-http-cio-tvosx64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-tvosx64/3.1.2-SNAPSHOT/ktor-http-cio-tvosx64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-http-cio-tvosx64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-tvosx64/3.1.2-SNAPSHOT/ktor-http-cio-tvosx64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-http-cio-tvosx64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../ktor-http-cio-wasm-js/3.1.2-SNAPSHOT/ktor-http-cio-wasm-js-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-http-cio-wasm-js",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../ktor-http-cio-wasm-js/3.1.2-SNAPSHOT/ktor-http-cio-wasm-js-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-http-cio-wasm-js",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../ktor-http-cio-wasm-js/3.1.2-SNAPSHOT/ktor-http-cio-wasm-js-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-http-cio-wasm-js",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-watchosarm32/3.1.2-SNAPSHOT/ktor-http-cio-watchosarm32-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-http-cio-watchosarm32",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-watchosarm32/3.1.2-SNAPSHOT/ktor-http-cio-watchosarm32-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-http-cio-watchosarm32",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-watchosarm32/3.1.2-SNAPSHOT/ktor-http-cio-watchosarm32-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-http-cio-watchosarm32",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-watchosarm64/3.1.2-SNAPSHOT/ktor-http-cio-watchosarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-http-cio-watchosarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-watchosarm64/3.1.2-SNAPSHOT/ktor-http-cio-watchosarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-http-cio-watchosarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-watchosarm64/3.1.2-SNAPSHOT/ktor-http-cio-watchosarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-http-cio-watchosarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "watchosDeviceArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-watchosdevicearm64/3.1.2-SNAPSHOT/ktor-http-cio-watchosdevicearm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-http-cio-watchosdevicearm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "watchosDeviceArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-watchosdevicearm64/3.1.2-SNAPSHOT/ktor-http-cio-watchosdevicearm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-http-cio-watchosdevicearm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "watchosDeviceArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-watchosdevicearm64/3.1.2-SNAPSHOT/ktor-http-cio-watchosdevicearm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-http-cio-watchosdevicearm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-watchossimulatorarm64/3.1.2-SNAPSHOT/ktor-http-cio-watchossimulatorarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-http-cio-watchossimulatorarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-watchossimulatorarm64/3.1.2-SNAPSHOT/ktor-http-cio-watchossimulatorarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-http-cio-watchossimulatorarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-watchossimulatorarm64/3.1.2-SNAPSHOT/ktor-http-cio-watchossimulatorarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-http-cio-watchossimulatorarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-watchosx64/3.1.2-SNAPSHOT/ktor-http-cio-watchosx64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-http-cio-watchosx64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-watchosx64/3.1.2-SNAPSHOT/ktor-http-cio-watchosx64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-http-cio-watchosx64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-watchosx64/3.1.2-SNAPSHOT/ktor-http-cio-watchosx64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-http-cio-watchosx64",
        "version": "3.1.2-SNAPSHOT"
      }
    }
  ]
}
