{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-call-id/3.1.2-SNAPSHOT/ktor-server-call-id-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-server-call-id",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-call-id",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-call-id-androidNativeArm64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-call-id-androidnativearm64-3.1.2-SNAPSHOT.klib",
          "size": 18683,
          "sha512": "a8e9830f079fd65d687affe1551a9a9d595503c7e2165da56dca14bd938ec3518303ba7dca076fb2da9fad2c742542fce668c856c4a465319b8ec4af00ebdfeb",
          "sha256": "70f0bf24f91a3f8b03991881757a84ea2ad008afe4474101dbb21ec7f101428e",
          "sha1": "b8ea48692a2c4338218d4c89ee1f01b59b8866b7",
          "md5": "64f6e36e3082bb81e372995650ba5efb"
        }
      ]
    },
    {
      "name": "androidNativeArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-server-call-id-androidnativearm64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-server-call-id-androidnativearm64-3.1.2-SNAPSHOT-sources.jar",
          "size": 4479,
          "sha512": "a4324e60c773617e0c4534077cf0af86e3eba25a65638ddffd6cf9c7cceecba4302702a1d6aaee30f71033920c22bc54ec16e39b4c50e33ba40179f3cf71d5fc",
          "sha256": "9b1252ffa010418087fbff88dd1845345773f7fafbafef83f44a80df6ec98d1e",
          "sha1": "060756a9ed48db76942b9d69afa21c8e563a62f5",
          "md5": "5bf555c140d0f68a79d8f10f4b48a167"
        }
      ]
    }
  ]
}
