{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-rpc-krpc-test/0.5.1/kotlinx-rpc-krpc-test-0.5.1.module",
    "group": "com.vickyleu.kotlinx",
    "module": "kotlinx-rpc-krpc-test",
    "version": "0.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-rpc-krpc-test-tvosSimulatorArm64Main-0.5.1.klib",
          "url": "kotlinx-rpc-krpc-test-tvossimulatorarm64-0.5.1.klib",
          "size": 3566,
          "sha512": "0dee3b325d6354d298e6a51aa2a169c364b0bcebe61227a6d6de28430b3efcb8b7a49cb9eb7e9c6016558fbea6731cc67ebb9b863407e8f104e90c0298502975",
          "sha256": "39fcf68c727d959bf8711e39a2ef862d7a623bff46777dc4bb7e84844f2b2b2d",
          "sha1": "5b2c162d0719eb504512315c042c664d771af1f8",
          "md5": "913bff0cfcce7b5cfeb8901a94d721c4"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-rpc-krpc-test-tvossimulatorarm64-0.5.1-sources.jar",
          "url": "kotlinx-rpc-krpc-test-tvossimulatorarm64-0.5.1-sources.jar",
          "size": 644,
          "sha512": "16b83ce79591b095adf720df482abb2e14da3f3fd40a3c1a46ba59becf28f1d094aaf1ff99fc772f864e59e8b105e930693159fd80ae6d94f9eb24806a9ce020",
          "sha256": "b3145b4e01e1f3412d297a56c86209350d08be1ba36a31a6126e98de2a006f25",
          "sha1": "4c87a2cd579bf018fe4db89f467db3a78d0bbf97",
          "md5": "fcbb59b898de6c68f8351d4bebbb2bfd"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-rpc-krpc-test-tvossimulatorarm64-0.5.1-metadata.jar",
          "url": "kotlinx-rpc-krpc-test-tvossimulatorarm64-0.5.1-metadata.jar",
          "size": 261,
          "sha512": "06b5012e407d775cef55acf7d9460d5f801ac4fdf6fede0ee4519e534004560f2e0fe2a21eeb0bff082316176e45cac71160a7571ffb8c283eb3b1b98d5868db",
          "sha256": "825b64815284615e08eb4a6612dcf369aad0f6e962521a58975b09242b9f1674",
          "sha1": "c53255a63b90fa0ee89fe6e44ce89e817faaa7af",
          "md5": "cea5446d23667a4af03b805efbfba2cb"
        }
      ]
    }
  ]
}
