{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-sessions/3.1.2-SNAPSHOT/ktor-server-sessions-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-server-sessions",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-sessions-androidNativeArm32Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-sessions-androidnativearm32-3.1.2-SNAPSHOT.klib",
          "size": 111496,
          "sha512": "01ff268879f2579cd784151c7f2fa73e5adbbca982bb7d3f81c12314afc75b5c2158e9e0f9d637a3d26a44e49867fb7feea7f04684cfbd7829ac408252026323",
          "sha256": "a446f789e472512f1e29a09a690b765fdfa662392e932ad8362f26ed5d1b4f34",
          "sha1": "8c8c205cafe5aa1ab6bb154871208941a0b7f5a8",
          "md5": "cef439d01c97436422796b438323f1aa"
        }
      ]
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-server-sessions-androidnativearm32-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-server-sessions-androidnativearm32-3.1.2-SNAPSHOT-sources.jar",
          "size": 31745,
          "sha512": "f0a4238abe0b783ccdf0a08c52cfeb51c0ba3d4b63d14de7dc6d33547deeac8f57ac8d1b562f92cba6ff43ef0d87945e1beb779b1231dd90bd70e5b1dd1159b6",
          "sha256": "71cb3dad0879dad51ba8ed0dc330d1561d0a998a7377f6eea767c7c197bbb49a",
          "sha1": "ce297cc940281d294abede6ed7437829ddf83b59",
          "md5": "798da78b8d7098cee70dab8cb8b43c56"
        }
      ]
    }
  ]
}
