{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-core/3.1.2-SNAPSHOT/ktor-server-core-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-server-core",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-utils",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-serialization",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-events",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-http-cio",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-websockets",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-core-tvosX64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-core-tvosx64-3.1.2-SNAPSHOT.klib",
          "size": 441363,
          "sha512": "80d9ceaa8ff33ff7d1721de16042b81d080360f81e89c32d0a27b441484a8b3ecc2efc948417e27a9886abc5d35411c2f65686c68cdaf879ad4be24a55f7964a",
          "sha256": "9ffd4c0e6323fd7dcd3007d989fdd3d67715fc9081455260b8a942d187f236ef",
          "sha1": "c20df6c3ad77166c58913073928855513c7062ae",
          "md5": "311c2c4c88208b7ff120ae8042ac6ad4"
        },
        {
          "name": "ktor-server-core-tvosX64Cinterop-host_commonMain-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-core-tvosx64-3.1.2-SNAPSHOT-cinterop-host_common.klib",
          "size": 6377,
          "sha512": "d8e6ad6d8c707bdd32f1b82088aaa56ecb90092c6d18c8c145d87713c77aba6809e845cebd8477c7cf639a12d452eff5a53b617e8b296882ac209b8126207c2e",
          "sha256": "d88717c3c984a15fc512c465ce072b7ba82d1c01e5fb6f622080e1e443f3c54e",
          "sha1": "9ec9d7fd03137365a957ff9d15ab18e64ce39ed1",
          "md5": "777bf0f434b4af4658f20983c7cdb1e4"
        }
      ]
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-server-core-tvosx64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-server-core-tvosx64-3.1.2-SNAPSHOT-sources.jar",
          "size": 118184,
          "sha512": "3954a0402e48412c976eac690b449da7e00574a9208578aad5e16344875f3989bd04aaf3191481605855b648c08f650e5406998cac79cd3c5354ff194db14ea9",
          "sha256": "c6c2fb9c28a5a23297ea55815de1a6edb2dd38308e5cf3825b2ceb18141c16cc",
          "sha1": "7cf6719011753c1c649b70251351eba85af08300",
          "md5": "38c7f2c8265bbd690f532f905b9d3e56"
        }
      ]
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-utils",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-serialization",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-events",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-http-cio",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-websockets",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-core-tvosx64-3.1.2-SNAPSHOT-metadata.jar",
          "url": "ktor-server-core-tvosx64-3.1.2-SNAPSHOT-metadata.jar",
          "size": 28145,
          "sha512": "65ea7b83e631bf8ed68cc60119a1d2d265bcd47a5278fc4c9f528cdd7d9283b3f1e46205a899d22335c13e6f04e95518a1ea2dc690fd982e860d7fca074a6b63",
          "sha256": "37ab5e21179c8082315e9172d8edd743ba5ad95d61cc5e7d4ab9faa0f1a59687",
          "sha1": "dc23be8e7a22fa6a7a8d27d27daf6512fe6702e6",
          "md5": "1f5f7a2ecaa498af8e78d6470a03c573"
        }
      ]
    }
  ]
}
