{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-websockets/3.1.2-SNAPSHOT/ktor-websockets-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-websockets",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-utils",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-websockets-macosX64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-websockets-macosx64-3.1.2-SNAPSHOT.klib",
          "size": 80815,
          "sha512": "bfbbfc7f7d7392bea8748e46835c706bdc9c8319d7922c78344cddeb25a86ce754a538a2157d18108f16120928a7870df17c05b0845b9d1fdd4be03a55261053",
          "sha256": "ea83e7706e430465781f0ca7ca2384611ed6b768ef1ee93b9b8f76a44ae9bb65",
          "sha1": "26f1d7690ee1856c99aab9bd90217a36e1373a36",
          "md5": "71ca9b1ddbd4b370f2620b65401f2183"
        }
      ]
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-websockets-macosx64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-websockets-macosx64-3.1.2-SNAPSHOT-sources.jar",
          "size": 22517,
          "sha512": "17310a80b992d7521157b511cabede739e63351cf15409a1fe7eab1785aa952834b310d222e546f1df73b6a53fa9a833cb0dfe3a1bf21d7635e85bc3a41c3158",
          "sha256": "1fb0a916b326441833905a3001d9f9ead5cf786aa47fc93ee327da0c046885c4",
          "sha1": "4377deafb26380e886431d1851d2af0c581e57f7",
          "md5": "19f80aad00d806e3fa2f41d27d66c47d"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-utils",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-websockets-macosx64-3.1.2-SNAPSHOT-metadata.jar",
          "url": "ktor-websockets-macosx64-3.1.2-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "5b85765e6ee3a23778898d5712566fafcda6d22a5eb9f181eec253f256e8e3fe76c87a209740819162e2b37a61c93903ac9b479f652d36c98851b83e49aa538b",
          "sha256": "6d06b170aece039ae981526e8a71d29d142f8e6ea0fdbc7cf1a750d75572f1fa",
          "sha1": "2a53028891934c4783e499f72d50fe26f5408fa3",
          "md5": "c2f5f6b9533b7e2be38421ee4c48d6ce"
        }
      ]
    }
  ]
}
