{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-coroutines-test/1.10.1-SNAPSHOT/kotlinx-coroutines-test-1.10.1-SNAPSHOT.module",
    "group": "com.vickyleu.kotlinx.coroutines",
    "module": "kotlinx-coroutines-test",
    "version": "1.10.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "watchosDeviceArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.26.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.23.1"
          }
        },
        {
          "group": "com.vickyleu.kotlinx.coroutines",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-test-watchosDeviceArm64Main-1.10.1-SNAPSHOT.klib",
          "url": "kotlinx-coroutines-test-watchosdevicearm64-1.10.1-SNAPSHOT.klib",
          "size": 78423,
          "sha512": "2d9d98471a533ef07fd7e59e15a0d279e54fdb90d4a188a4cf4432dcf2a9e7ab0d2413339381bd3b63fb59a0c25564a9442c214b21a5c7d74b9c8f1f8d64917b",
          "sha256": "5a7570d4c060d7da42e62efc112fb17ea91df71bbc4e02db7ce48872d4e26a40",
          "sha1": "f297224c06a5c69b5aa524e1e5da9ca9246e8397",
          "md5": "0432cbdee6f4577cc3088e21a60c8949"
        }
      ]
    },
    {
      "name": "watchosDeviceArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-coroutines-test-watchosdevicearm64-1.10.1-SNAPSHOT-sources.jar",
          "url": "kotlinx-coroutines-test-watchosdevicearm64-1.10.1-SNAPSHOT-sources.jar",
          "size": 25551,
          "sha512": "0b86541175c8bc10d764f2f4d295f4f92ca688ea46140a7bfc2df9b0118c70ca873915cd172b1b22aef84f5be8aa7b3c5595a554925a0ecfc6bfaf11347ccb9d",
          "sha256": "1bd49665fd31fc15b841b13b70fca8820afb4f90c87043904e879dc1a80a3b0d",
          "sha1": "70fde0188fb0a9d5d20929d348a22714d8389e19",
          "md5": "afe9605896140cd48b74065440ca89fd"
        }
      ]
    },
    {
      "name": "watchosDeviceArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.26.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.23.1"
          }
        },
        {
          "group": "com.vickyleu.kotlinx.coroutines",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-test-watchosdevicearm64-1.10.1-SNAPSHOT-metadata.jar",
          "url": "kotlinx-coroutines-test-watchosdevicearm64-1.10.1-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "c81b22c5f563f4944a2e69afe0899cfda028db75f1e02061a762688f9837e9e18adb876c66d60bbc7b0199214c92671a377e51717fcb13b1c723a0d65eb4b1a8",
          "sha256": "0f980417300abc01414a25564d914571c1ce47cedbf4fc2e3d45be0964081e19",
          "sha1": "d64de10296b7d8b8e43f9c68b4cc49ae9545a513",
          "md5": "8bc3d92b2251a9d027449b157ceeb0d0"
        }
      ]
    }
  ]
}
