{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-auto-head-response/3.1.2-SNAPSHOT/ktor-server-auto-head-response-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-server-auto-head-response",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-auto-head-response-tvosSimulatorArm64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-auto-head-response-tvossimulatorarm64-3.1.2-SNAPSHOT.klib",
          "size": 8654,
          "sha512": "a67d67482ca2e6e2aea5b97fa0338bafbe27261fb610b2a31a2c8fb917851b40357ba5a18d284cb2e8d7aa2772a0a328536d22e7498912a1b114ffcf13b1d595",
          "sha256": "025b9a96baec23c1aec74cbabde99a49aa4cd067f015dae6ea7070b26791b9b1",
          "sha1": "df343f71c89b40ae5a7b6b59eba84ab6a153fc41",
          "md5": "a72d40cce7efc78144970ff691bd3f6d"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-server-auto-head-response-tvossimulatorarm64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-server-auto-head-response-tvossimulatorarm64-3.1.2-SNAPSHOT-sources.jar",
          "size": 2047,
          "sha512": "07995b089bf9365a232699cc86359f9068cb1265816943f421ad2eb37dd2e2bace2519bf7b0913c69ba4363bc14474b732552f7c93626c550802579b1967b530",
          "sha256": "561ccd5f736e5397a51c1d076cac900331d69176e5fab54db4f1cb45747fce3c",
          "sha1": "10284cbff643086f949494e7698256b3e1f6569a",
          "md5": "ccb90f8a40d6e4e990fdf7aab05a9894"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-auto-head-response-tvossimulatorarm64-3.1.2-SNAPSHOT-metadata.jar",
          "url": "ktor-server-auto-head-response-tvossimulatorarm64-3.1.2-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "3878aa0b89a5611357c275dbbf768e41470b30ec994979980283bc5207cad301ba29741960913940892d5366696377bf0105696ac8fd7ad88fc5224adc7e6482",
          "sha256": "f6104cd67d3bb92c5e6c791fb31f305e37e86b3e8ae35d7f54cf6d0a9deae94b",
          "sha1": "c3c8905082209010ce7284d8468b4b4514e93ab1",
          "md5": "e13d09a0c87c325f97a5e5692224fff0"
        }
      ]
    }
  ]
}
