{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-host-common/3.1.2-SNAPSHOT/ktor-server-host-common-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-server-host-common",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-host-common-linuxX64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-host-common-linuxx64-3.1.2-SNAPSHOT.klib",
          "size": 3433,
          "sha512": "ffc9587ad8b3f7eaa9fd2fb7fc4bce7c1cc957695fabf8725215ab348f379a8bc8b45b63296ca66310857f7d1882d0795de2f2f07579e41190fbd4bd48cdcf45",
          "sha256": "f881b2d4bad4dacd13e9d8e38a8398d89d693fb512e0001414b9427b6535d1d5",
          "sha1": "fe2a2f47316c1dbc1492f57a02445a8b5805eaf2",
          "md5": "0eff8aadee4d32ddd97f5fc75b19ebbb"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-server-host-common-linuxx64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-server-host-common-linuxx64-3.1.2-SNAPSHOT-sources.jar",
          "size": 621,
          "sha512": "f04f945d6a7d30a53537aa03c5b9ff5f72e60e4150cc04bec3114161649c0177f6ef2d801ca541f66ae5e2a12a40c6f5560f6c166f14e70f3731a9b77361aced",
          "sha256": "8f1b77aa660fed1302454fd2a303ab07ab29a5d52029c98850cedff554c454f0",
          "sha1": "ee19f777cd0f857f7e5bccd5eacb04c7496d9a13",
          "md5": "5b14dfc1ec7145751b60a8479edee37d"
        }
      ]
    }
  ]
}
