{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-conditional-headers/3.1.2-SNAPSHOT/ktor-server-conditional-headers-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-server-conditional-headers",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-conditional-headers-jvm-3.1.2-SNAPSHOT.jar",
          "url": "ktor-server-conditional-headers-jvm-3.1.2-SNAPSHOT.jar",
          "size": 16439,
          "sha512": "802145b1f2b913fc1753e7cd749dd542c45f3a21db93f9107fe2b0e23b8417ae0cb96398bb7528d890a090e927166d440a9fce7386b8d9be604ea1dd3fe2243b",
          "sha256": "0aa5d33d2efedd73efa3f3d00d524e705aea1fda768fc217f9b1e295621c74f7",
          "sha1": "cbb84cb701b7c64c00096d055c1368f00959be66",
          "md5": "170741a3ef650987e3f0f8ad3949ca54"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-conditional-headers-jvm-3.1.2-SNAPSHOT.jar",
          "url": "ktor-server-conditional-headers-jvm-3.1.2-SNAPSHOT.jar",
          "size": 16439,
          "sha512": "802145b1f2b913fc1753e7cd749dd542c45f3a21db93f9107fe2b0e23b8417ae0cb96398bb7528d890a090e927166d440a9fce7386b8d9be604ea1dd3fe2243b",
          "sha256": "0aa5d33d2efedd73efa3f3d00d524e705aea1fda768fc217f9b1e295621c74f7",
          "sha1": "cbb84cb701b7c64c00096d055c1368f00959be66",
          "md5": "170741a3ef650987e3f0f8ad3949ca54"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ktor-server-conditional-headers-jvm-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-server-conditional-headers-jvm-3.1.2-SNAPSHOT-sources.jar",
          "size": 3012,
          "sha512": "1bc25c28c688d815af04b2a904e0bc529973a4598817dbfc08fa4330286c748d06e169f96998aeda2da5530482d32ec563617c0d869a8d689cb73fd14894526a",
          "sha256": "df404c6f6c0e957120cf20a9aa04255d56a95e7e655dc6f3dac2263c034532ef",
          "sha1": "5a68ff5619ddc990a456b3ae260e49876e042af0",
          "md5": "f73366c4698e40cb75a23709ff53b932"
        }
      ]
    }
  ]
}
