{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-auto-head-response/3.1.2-SNAPSHOT/ktor-server-auto-head-response-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-server-auto-head-response",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-auto-head-response-watchosArm64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-auto-head-response-watchosarm64-3.1.2-SNAPSHOT.klib",
          "size": 8594,
          "sha512": "ed6bcc3cda60c2b631e774bd10eb75f065641ba1ffc01d964f307ddb121bdc5961c03b227a0a973df93869f8fcaa10e12c217d4fcb983af43cb1797255e24818",
          "sha256": "8ea02f7a3112e5d2867db7f7fa1eda76c2f9dc6a96d112c42956954ef20efd70",
          "sha1": "07e1dd891ac159f0dee2c173462d54cac3dc0e05",
          "md5": "c58b95aebacdfc464e6aed9ae5c32752"
        }
      ]
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-server-auto-head-response-watchosarm64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-server-auto-head-response-watchosarm64-3.1.2-SNAPSHOT-sources.jar",
          "size": 2047,
          "sha512": "07995b089bf9365a232699cc86359f9068cb1265816943f421ad2eb37dd2e2bace2519bf7b0913c69ba4363bc14474b732552f7c93626c550802579b1967b530",
          "sha256": "561ccd5f736e5397a51c1d076cac900331d69176e5fab54db4f1cb45747fce3c",
          "sha1": "10284cbff643086f949494e7698256b3e1f6569a",
          "md5": "ccb90f8a40d6e4e990fdf7aab05a9894"
        }
      ]
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-auto-head-response-watchosarm64-3.1.2-SNAPSHOT-metadata.jar",
          "url": "ktor-server-auto-head-response-watchosarm64-3.1.2-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "3878aa0b89a5611357c275dbbf768e41470b30ec994979980283bc5207cad301ba29741960913940892d5366696377bf0105696ac8fd7ad88fc5224adc7e6482",
          "sha256": "f6104cd67d3bb92c5e6c791fb31f305e37e86b3e8ae35d7f54cf6d0a9deae94b",
          "sha1": "c3c8905082209010ce7284d8468b4b4514e93ab1",
          "md5": "e13d09a0c87c325f97a5e5692224fff0"
        }
      ]
    }
  ]
}
