{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-rpc-krpc-logging/0.5.1/kotlinx-rpc-krpc-logging-0.5.1.module",
    "group": "com.vickyleu.kotlinx",
    "module": "kotlinx-rpc-krpc-logging",
    "version": "0.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.6"
          }
        },
        {
          "group": "com.vickyleu.kotlinx",
          "module": "kotlinx-rpc-utils",
          "version": {
            "requires": "0.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-rpc-krpc-logging-mingwX64Main-0.5.1.klib",
          "url": "kotlinx-rpc-krpc-logging-mingwx64-0.5.1.klib",
          "size": 12385,
          "sha512": "9447170bd0e57719ff0c9ae28ce82653e5a49f69e34c5651c579f2c1ed29474832af3a39f20429bf6bcd4c0cd3e2c5c3f0f39b443cc4aae24d777b0d78c838fe",
          "sha256": "f1145eec3eb98f5aee93963ba22b8bc10fc7c7d4c839ad0ad089e7bfc1353d2b",
          "sha1": "e384b5d1b8bca6dc7cf736eeff579bc145a6e9fb",
          "md5": "abc59ac27c3aec36bb2ca80c38946747"
        }
      ]
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-rpc-krpc-logging-mingwx64-0.5.1-sources.jar",
          "url": "kotlinx-rpc-krpc-logging-mingwx64-0.5.1-sources.jar",
          "size": 3141,
          "sha512": "02123f3be3ee56a880ea0742c1ea34d5e0e61f63530f12524c374fcf6f5f083a687f36115fbdac268315f88b26e6132ab5b514b88d71dbf081e7127f8912f6d6",
          "sha256": "8e48b530ee5752910707bf402ff89d304e9cd21d60d6b841a0b29bd4b6413cf0",
          "sha1": "9a949afff48ebd85331320e4b8d5a8da07bb1f66",
          "md5": "1da329d6bc94828d33ab4607a09699a0"
        }
      ]
    }
  ]
}
