{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-body-limit/3.1.2-SNAPSHOT/ktor-server-body-limit-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-server-body-limit",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-body-limit-iosArm64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-body-limit-iosarm64-3.1.2-SNAPSHOT.klib",
          "size": 10571,
          "sha512": "67052e61edce35a11f4085ecc745bebd18b2388443ee5c84b6a0b7b5f7425d55d925880b5e6e2baba5834275384915180bc8fe5b518d8eb0546fce7b39663a2b",
          "sha256": "0547f40cc11ce07e7aac045da597df136231d4421f94aaa6f4d8eb8ef4f53938",
          "sha1": "ea299e7787484ae71394441f0f34b7791da325a8",
          "md5": "2b2496dc2a18afe801e1c8df756ad75f"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-server-body-limit-iosarm64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-server-body-limit-iosarm64-3.1.2-SNAPSHOT-sources.jar",
          "size": 2302,
          "sha512": "1fe49fe1e96d0841045bb151fc8490f761c5c575cb7acad2a5bf076e41e418f7029490236ef35f81dfa0d15187fccb77f80a894aea42ea16b8ed7171b9b2f7a3",
          "sha256": "826cb7e25738122cd5bbc4a6b31bcaea147fd77d806e27211858dc6bc1bc3158",
          "sha1": "407d1eb0bf5b46fac46965247f4f147c5d6ec0fb",
          "md5": "84968e6e84e9497c4ef4155c8e3b5e68"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-body-limit-iosarm64-3.1.2-SNAPSHOT-metadata.jar",
          "url": "ktor-server-body-limit-iosarm64-3.1.2-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "eb354f2eb31be27b62c68ec9339b83b30c78bef491f412ba8be2f8a1b0bae83d785d8f231093ef3d1b4088b0d8567dc73899ec1da229b53591973f64726be98c",
          "sha256": "a2f84c94044c7ccdd7e6497e315569ae9a3433a3754e2326aaeb6c7963a30ad0",
          "sha1": "c1c64e8306b7124cb6a453ded048925805bae25c",
          "md5": "b92ada68892d8ba1644f1b1f06c9a248"
        }
      ]
    }
  ]
}
