{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-auto-head-response/3.1.2-SNAPSHOT/ktor-server-auto-head-response-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-server-auto-head-response",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-auto-head-response-androidNativeX86Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-auto-head-response-androidnativex86-3.1.2-SNAPSHOT.klib",
          "size": 8577,
          "sha512": "88171f497512f9d6c4836f41aee782db0e5b4709b72dc4a17fd89e0369edf757760cf2e7ef066b1a3406f85769cd011d844d70943aa8d7e89655c67fa00d85c8",
          "sha256": "3413d9b449d8a300b23008841b4cea5893894e8ef89f396c5201c343bcba9e2a",
          "sha1": "a202e95e1da9d576cf6a9fc06f3591c79b4c6b7f",
          "md5": "3dd7350962ab567546d7299488e8bb73"
        }
      ]
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-server-auto-head-response-androidnativex86-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-server-auto-head-response-androidnativex86-3.1.2-SNAPSHOT-sources.jar",
          "size": 2047,
          "sha512": "07995b089bf9365a232699cc86359f9068cb1265816943f421ad2eb37dd2e2bace2519bf7b0913c69ba4363bc14474b732552f7c93626c550802579b1967b530",
          "sha256": "561ccd5f736e5397a51c1d076cac900331d69176e5fab54db4f1cb45747fce3c",
          "sha1": "10284cbff643086f949494e7698256b3e1f6569a",
          "md5": "ccb90f8a40d6e4e990fdf7aab05a9894"
        }
      ]
    }
  ]
}
