{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-client-content-negotiation/3.1.2-SNAPSHOT/ktor-client-content-negotiation-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-client-content-negotiation",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-serialization",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-content-negotiation-wasm-js-3.1.2-SNAPSHOT.klib",
          "url": "ktor-client-content-negotiation-wasm-js-3.1.2-SNAPSHOT.klib",
          "size": 22486,
          "sha512": "10c9d6bd0707d285487d5e4a7a82587f99a672fa6813f3ef23e0666fe1fd0ccfa024ae44e8571cb7d7f74db43c0049969051090818cc51b8db20eaff49f36452",
          "sha256": "2e4ab58261769248e6c9768c4c403e24c1f41ca64e2e6163679cc0f331e8e4c0",
          "sha1": "6c5cc58efa454283f57765b93091ccc80888cd85",
          "md5": "b87404eed2a721f6371a656b9b4269b8"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-serialization",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-browser",
          "version": {
            "requires": "0.3"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-content-negotiation-wasm-js-3.1.2-SNAPSHOT.klib",
          "url": "ktor-client-content-negotiation-wasm-js-3.1.2-SNAPSHOT.klib",
          "size": 22486,
          "sha512": "10c9d6bd0707d285487d5e4a7a82587f99a672fa6813f3ef23e0666fe1fd0ccfa024ae44e8571cb7d7f74db43c0049969051090818cc51b8db20eaff49f36452",
          "sha256": "2e4ab58261769248e6c9768c4c403e24c1f41ca64e2e6163679cc0f331e8e4c0",
          "sha1": "6c5cc58efa454283f57765b93091ccc80888cd85",
          "md5": "b87404eed2a721f6371a656b9b4269b8"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "ktor-client-content-negotiation-wasm-js-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-client-content-negotiation-wasm-js-3.1.2-SNAPSHOT-sources.jar",
          "size": 5599,
          "sha512": "80866f50727a5867002741697e3d72292ffbafaadcdfb64d14baf2fb226b8690fe46a9d65f6b7111ac1b553629b1755a94eed8898cdcaa05952c1409bfa2caba",
          "sha256": "1f095f5a9ab293dd38a10b5d76b97509c65c8a0b2cbcf7f5e0fd315919134c8c",
          "sha1": "4690a5c6f563475c51f568d04188e8c29e19587a",
          "md5": "3c4c023f83b28fb6f4b276d602e78c6a"
        }
      ]
    }
  ]
}
