{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-rpc-krpc-ktor-core/0.5.1/kotlinx-rpc-krpc-ktor-core-0.5.1.module",
    "group": "com.vickyleu.kotlinx",
    "module": "kotlinx-rpc-krpc-ktor-core",
    "version": "0.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.vickyleu.kotlinx",
          "module": "kotlinx-rpc-krpc-core",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-websockets",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-rpc-krpc-ktor-core-linuxArm64Main-0.5.1.klib",
          "url": "kotlinx-rpc-krpc-ktor-core-linuxarm64-0.5.1.klib",
          "size": 6314,
          "sha512": "4396b0c50ac9c99ce32493d8f272b6db64adda62d682eed4a4c1a0b71336fb12f84d579a52fd0376a29831f7d18234ccd24b48930f5e862e08ad559b3a77a91f",
          "sha256": "029959551d4801969fede3e6e87fe423de0520337aa6d446c44ecbea2518601f",
          "sha1": "47a241bd8e325f0a0718391dd1fe8424ee4c7e0e",
          "md5": "4dfe2e3d80ddcc3ad364097f28ae35ab"
        }
      ]
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-rpc-krpc-ktor-core-linuxarm64-0.5.1-sources.jar",
          "url": "kotlinx-rpc-krpc-ktor-core-linuxarm64-0.5.1-sources.jar",
          "size": 1686,
          "sha512": "44a6419ceeecc94824e017b415f80765af8cc82ace7dbba25d407260aa1f6546e5dd8a9e15c6c2b27edc556796806416ca68703a672c6e50506675500e897dd9",
          "sha256": "aa04308edf1ce343ee7e2a5cb3d1ea2beb1ab591731d87a71e47c7b54722b900",
          "sha1": "dc97cf7530cf4d5450e912d6cf9e0d58199ee9bc",
          "md5": "6d8d30484c72ad16bc70dcdb8c6a7a16"
        }
      ]
    }
  ]
}
