{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-http-redirect/3.1.2-SNAPSHOT/ktor-server-http-redirect-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-server-http-redirect",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-http-redirect-mingwX64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-http-redirect-mingwx64-3.1.2-SNAPSHOT.klib",
          "size": 9164,
          "sha512": "ab6d160be49fa3b08c592fc326548c51b70585a9cb143b5a9f78c92a1e9cd828f068c7095bf28425122990c68cd257b892b9636e30ac9f71efa980862c91cc3e",
          "sha256": "2b6cbe122f2d18c51d0a8c8725ad688a5b9142e14d46abe735b35a8e0704d189",
          "sha1": "b0801a258911cca9b07c42696b8d7096adbb42b1",
          "md5": "1cc2c3d05dd00083e43ccd2f68994ee5"
        }
      ]
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-server-http-redirect-mingwx64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-server-http-redirect-mingwx64-3.1.2-SNAPSHOT-sources.jar",
          "size": 2310,
          "sha512": "061b03df84e56c8c04b20feb0be9c45fdc5d1a5b274b7739f30b05a73cc4f902ea92b7231c63472efe772bb92295544179947c96f5fb1e587ac8e5547dc5639c",
          "sha256": "0c00540fd6da40f611568a886aa44b9e2655bb66696f76f203cca10f9e3afd6a",
          "sha1": "ff99ba0cf98cd46e5bf40848715540cf941163a1",
          "md5": "bd681ac1a10519c780f969859d2d528a"
        }
      ]
    }
  ]
}
