{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-client-content-negotiation/3.1.2-SNAPSHOT/ktor-client-content-negotiation-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-client-content-negotiation",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-serialization",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-content-negotiation-watchosSimulatorArm64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-client-content-negotiation-watchossimulatorarm64-3.1.2-SNAPSHOT.klib",
          "size": 22930,
          "sha512": "65fb168c3d60cbbfbec841175d6fb006af02412ad6e8f4aa8082ae80605866e34fe648cf8df19e7616bba6114c9c28440fa12f2f8c1d94f343499d1813596278",
          "sha256": "0dba953fafea80d77b93cd4945d7d709a274ee0b0164ee617754b3d6177662ee",
          "sha1": "f37fd709c4f2a92ebae5f63f4a8647b66b293927",
          "md5": "9ec2aa18676d69f3a56bb5f1e14f71f4"
        }
      ]
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-client-content-negotiation-watchossimulatorarm64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-client-content-negotiation-watchossimulatorarm64-3.1.2-SNAPSHOT-sources.jar",
          "size": 5541,
          "sha512": "166ecb1486c61188e275e5e7a33d3bcf6f43e048bccafc145e8c9e0a819750065e4ab45cbbee056bdb12ec14cf2c91429becc261925c46a7692df450752c4fa2",
          "sha256": "5787bc15d42038cad551b274b6c88b9672470c408e27db6a035ae1d42e3fdc7f",
          "sha1": "f3c1785f9e9a969fdcb56943e51f8aa05e33aa3b",
          "md5": "d2d8489404addc6f624e366a8b77ef34"
        }
      ]
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-serialization",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-content-negotiation-watchossimulatorarm64-3.1.2-SNAPSHOT-metadata.jar",
          "url": "ktor-client-content-negotiation-watchossimulatorarm64-3.1.2-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "4c710234a0196ea39189a64d4f05422a7336ae7f06805d988342d30377055e30e07e32b32529a6fb8c734a659a5ffd7e53127111ec534c1ba80aa6afe1f74f34",
          "sha256": "0ad91c530838a55c584e58976bd52a402785e0ce8977dc12f32695eb54552d07",
          "sha1": "34cd439ac540b083599e7bb25103e5c1c1465c21",
          "md5": "e092a194a260d22905bb88b17e8eeadd"
        }
      ]
    }
  ]
}
