{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-client-auth/3.1.2-SNAPSHOT/ktor-client-auth-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-client-auth",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-auth-iosSimulatorArm64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-client-auth-iossimulatorarm64-3.1.2-SNAPSHOT.klib",
          "size": 53581,
          "sha512": "73bd894662f0c70e39b50150ea31ab2227750be83b1d8453517a9104c6c93ae770c4dff0170cae08db614fbd9badef56045214a97d522e89e160079295eb5866",
          "sha256": "9686f9338d16a7ccd14c03db9d9970359cd6d1d69c5881b9166514af19810a22",
          "sha1": "0002fa6821be18a00537cb0a0f4d825da6dee19f",
          "md5": "85778f70609210f5bb270458c2c6605f"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-client-auth-iossimulatorarm64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-client-auth-iossimulatorarm64-3.1.2-SNAPSHOT-sources.jar",
          "size": 12670,
          "sha512": "565278687b8b7d6d0f81174a538e3e36bec2abc6aae7e78283d0afc83759396844cf5d8c19c815bc0e43b87aa0523a92c06107eb6d310400f13ab25534298066",
          "sha256": "d547799a79c9a25bae79fa8ac8322a7eb5a6f44867f2be7a925bf9d4a894f922",
          "sha1": "7425b17152bc668e37ee3e15c572de3d4d5ac339",
          "md5": "b6d07b98246acd355ac78681c561888d"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-auth-iossimulatorarm64-3.1.2-SNAPSHOT-metadata.jar",
          "url": "ktor-client-auth-iossimulatorarm64-3.1.2-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "87b1856a6452d32f290b3848d68bd3c0b4b6561863f50d8ae002a63bd20a4ff0673dd69f26ef3287bd4541bb2c55c8923952d6720ac611064d90757113eae59c",
          "sha256": "184bd2e4969dd491676282b8e47950929a89009a1750617b1921a658651340f4",
          "sha1": "cabf4aa5483fc94d57894b5e9c106fba56d4bb71",
          "md5": "2f3065cb04657d7b9b489fd83c8b4ed6"
        }
      ]
    }
  ]
}
