{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-http/3.1.2-SNAPSHOT/ktor-http-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-http",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-utils",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-http-tvosArm64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-http-tvosarm64-3.1.2-SNAPSHOT.klib",
          "size": 397926,
          "sha512": "b74d1dba89afe0a1429aa3000d7086102c5092056434f29c3391d35e0805ce37ee4a1d604170d9f77a966bc0e2369a01a77395ddca43d0eb4266e127b50b415b",
          "sha256": "b0380106a075958b6e8764d5815fdfe22fd762533bf0d2d64bf05059cdd623a4",
          "sha1": "6fd04470864dc9b63b8139f9cd79e591dd16990b",
          "md5": "478704ce7f2a8a4e5acc502f315503b6"
        }
      ]
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-http-tvosarm64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-http-tvosarm64-3.1.2-SNAPSHOT-sources.jar",
          "size": 88187,
          "sha512": "c643a94f0720cb2d499b38e0c384e929d976b7becbbbe771ebc65852b59bba4c1268c32e52ac06dce1eed64c0b11297170b856619f0df326e698fac5b3a84566",
          "sha256": "3a2ccc35b4cae3370861cf34f506dd2c85af1e4cbd34ff563f1b19efd9f82c36",
          "sha1": "fd340df2b5c3ee4286a2cb8f1860b35a54ebf331",
          "md5": "3ba0cbcd501b20e35666ce00cdb915ea"
        }
      ]
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-utils",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-http-tvosarm64-3.1.2-SNAPSHOT-metadata.jar",
          "url": "ktor-http-tvosarm64-3.1.2-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "f3e3eee2260365f04100baeb3c7790a17ecbaa1f7dad654bcb735bacdf8316b68e029bd532bd477f3335ca5a493b28e8201b6b60a68191ed30356c16a0bbcfa9",
          "sha256": "70ef90b968a1b7d359a4db20bd39139226728c2a518709add4d1bcd5ab37999b",
          "sha1": "2dbcdec6cd01ecaf095b6c1e8820dfdd5ef6acbb",
          "md5": "cf74eec3888e80f91e3303409e4c2122"
        }
      ]
    }
  ]
}
