{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-rpc-krpc-serialization-json/0.5.1/kotlinx-rpc-krpc-serialization-json-0.5.1.module",
    "group": "com.vickyleu.kotlinx",
    "module": "kotlinx-rpc-krpc-serialization-json",
    "version": "0.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.vickyleu.kotlinx",
          "module": "kotlinx-rpc-krpc-serialization-core",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-rpc-krpc-serialization-json-linuxArm64Main-0.5.1.klib",
          "url": "kotlinx-rpc-krpc-serialization-json-linuxarm64-0.5.1.klib",
          "size": 5834,
          "sha512": "42dc65ee46e64beb268ba6b03f00ca454a3d0913bfdf77179f31eaf59eded01da2dba1f164fa06f9dbb0908ad4fa98cdf2f3ead4cfc7e22f59bf1bd5de555459",
          "sha256": "56d46cbd24666a64c4ad2d0baa0f6ab2fb3b8b74458a52379f7c096bb94af2c9",
          "sha1": "7cebcf72d154174adba6413a18eb3d00636ae341",
          "md5": "78abdc3d2221a19894d477b077416686"
        }
      ]
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-rpc-krpc-serialization-json-linuxarm64-0.5.1-sources.jar",
          "url": "kotlinx-rpc-krpc-serialization-json-linuxarm64-0.5.1-sources.jar",
          "size": 1798,
          "sha512": "2086cb1b4aa13165230f4850920c3783e81ec5b7d6d05eebec712926fceae449d210fd1dd28c6f59389ca75cf2e5a0fa7bb39ed0a41349f4891530b2b0d1dccb",
          "sha256": "3b20394fe01bd912868a137d96fe034c69bfc12f367bd9bacfc3347bb79f65b7",
          "sha1": "83fe9f452dc22cdb84ef05410f92df7278351cea",
          "md5": "a5805796c60dcf233c8fd6b4187ac2a3"
        }
      ]
    }
  ]
}
