{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-forwarded-header/3.1.2-SNAPSHOT/ktor-server-forwarded-header-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-server-forwarded-header",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "linuxArm32HfpApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm32_hfp",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-forwarded-header-linuxArm32HfpMain-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-forwarded-header-linuxarm32hfp-3.1.2-SNAPSHOT.klib",
          "size": 32627,
          "sha512": "351916cb9a1ae20d72cc06a72a4a81826ffb410f8a4cf76cc7be5dac636d791fd93287195dd14eae761f0f601e3e499203c144346272b832cb08dabd4a32c01d",
          "sha256": "714594e939b770ff80c8372ff74b90dac252751bc10f6ee922985e701bf13be7",
          "sha1": "50398235f45f6e7d338078abda3844a29b2e568b",
          "md5": "eaaaa5eada5fbc89fcebe58c2258eee7"
        }
      ]
    },
    {
      "name": "linuxArm32HfpSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm32_hfp",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-server-forwarded-header-linuxarm32hfp-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-server-forwarded-header-linuxarm32hfp-3.1.2-SNAPSHOT-sources.jar",
          "size": 6006,
          "sha512": "6389ee2f9b2451d2bc4010a57b55da9b4141d7c05942af4bf7f6d313b56656bb65b4f697bb27f625adc227ab662a3fb2de63b81b699d18ddc669c3d9e4746f4c",
          "sha256": "f77620772e68ab778496a721b74f72b18a49af31d4a2d70fef4a01905e7a843e",
          "sha1": "107437c6c54d22d520d41c370ab1f9ff9a90c18f",
          "md5": "4087cdfda73964219e7183cfeb3a0f2e"
        }
      ]
    }
  ]
}
