{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-client-curl/3.1.2-SNAPSHOT/ktor-client-curl-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-client-curl",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-http-cio",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-curl-linuxX64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-client-curl-linuxx64-3.1.2-SNAPSHOT.klib",
          "size": 81821,
          "sha512": "51438637f9a3476cc7c0e34c63668ef59f2e5b10a34af73e499fbfd0e53f393ddc1a35e845c70720bcc5b846578c5d575d8b4c2503948d4021baaef3603b72d8",
          "sha256": "4873de41da8491db4366cae13295e58f377aba95111aa1a3db861e3cf7437723",
          "sha1": "3e4d0a8948e0976d444bda0b91b5a78f53b27f52",
          "md5": "735bbf31800f4aa4adb34225edc0d8ee"
        },
        {
          "name": "ktor-client-curl-linuxX64Cinterop-libcurlMain-3.1.2-SNAPSHOT.klib",
          "url": "ktor-client-curl-linuxx64-3.1.2-SNAPSHOT-cinterop-libcurl.klib",
          "size": 3997602,
          "sha512": "0cb579f9d9c6f5068a86159a1ca512cc541125786a53680b7f538676df3b8999f80e81c4c9e7bd089f0e771a8cc887e194db6f83ed325b38a0c96ceda89245d5",
          "sha256": "1eebba226a7095070db3508cf774a2c9000e91d0b1c27a272999364fae4861c7",
          "sha1": "2a69b8e42670433f27054d2c72b02c4d9168cd64",
          "md5": "5737a1e56faafc37cd72697f92ad009b"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-client-curl-linuxx64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-client-curl-linuxx64-3.1.2-SNAPSHOT-sources.jar",
          "size": 17431,
          "sha512": "6b8c36dde71c7e31362996ab8946c599ed783d504297ef0871ada375e1719e3bcad4366f42424a550a233ed3631c94e705c43b30675500fa9e4e0366f2dd69b3",
          "sha256": "e4a473788e24d20ea17d9164a657140a76c027642b98b464adabf7d2f3417d86",
          "sha1": "ac789b266dd22c087ce792a4ee0e17e827986f93",
          "md5": "fc26ea2b4dab9d6f503ac4bef27b2e64"
        }
      ]
    }
  ]
}
