{
  "formatVersion": "1.1",
  "component": {
    "url": "../../pbandk-runtime/0.16.1-SNAPSHOT/pbandk-runtime-0.16.1-SNAPSHOT.module",
    "group": "com.vickyleu.pbandk",
    "module": "pbandk-runtime",
    "version": "0.16.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.2"
          }
        }
      ],
      "files": [
        {
          "name": "pbandk-runtime.klib",
          "url": "pbandk-runtime-watchossimulatorarm64-0.16.1-SNAPSHOT.klib",
          "size": 678597,
          "sha512": "d0393aa7d31f38bf303b176f4b5e056abd543d133d0b0baca2c4def1c1533e714f790c013ad07ca2d324ee0b86712c0a75cdc82f6c9b020aefb74094801ff7d0",
          "sha256": "53af9904fdf72ef7522d31e73fbae9072ac99e8143c544cbf624f4669fe018ca",
          "sha1": "dfeb1be7a875316615bde562d2dbf542438d130d",
          "md5": "19322be4bff3c0c5089f8b5be5ea9163"
        }
      ]
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "pbandk-runtime-watchossimulatorarm64-0.16.1-SNAPSHOT-sources.jar",
          "url": "pbandk-runtime-watchossimulatorarm64-0.16.1-SNAPSHOT-sources.jar",
          "size": 89500,
          "sha512": "036c717c886c7f2c66b568ad3f05a1cb159fa5c07ee64235fbe6c226562682e11c912094acbd57cc82fa03b81919ca35c59763c042e88d3d5c74138950020ff7",
          "sha256": "51e2b29d585dbda1123cca39bc5e65c2495759858466323d67a5c02fd1fb998b",
          "sha1": "4d74b3fac1961c3b7cf671023c4d8af87873ec17",
          "md5": "e33355a59f03ba7232f002d0d24d31e2"
        }
      ]
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.2"
          }
        }
      ],
      "files": [
        {
          "name": "pbandk-runtime-watchossimulatorarm64-0.16.1-SNAPSHOT-metadata.jar",
          "url": "pbandk-runtime-watchossimulatorarm64-0.16.1-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "e692b58b2ea444b34ff6f21879312a217d33ce88ed0642006db73ae4c090cb6cd64644b5308b40765d9536c6c822cf5028a86460ecd6fd13da9778767a60fa4b",
          "sha256": "9f1e18a2a9d9e412a0463a3d9d9f80cd55517c2e6b89036a9b24cbe8b74d3992",
          "sha1": "d3e8242562a467bd3b28d3e661202d6d24407bcd",
          "md5": "64222233341cbf36d6254fbb97240008"
        }
      ]
    }
  ]
}
