{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-utils/3.1.2-SNAPSHOT/ktor-utils-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-utils",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-io",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-utils-macosX64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-utils-macosx64-3.1.2-SNAPSHOT.klib",
          "size": 303851,
          "sha512": "5e4d6783f56fb2f2dd1f67ada882ed3f76e207a7a4140bfa298baebb9503755eb3e76053b046fa01459880b0d815e7c3fb280d988e1a8fa109473457f92fab56",
          "sha256": "6e0b213985b2d941ed6d51f15606ed6b081e7dd76bd9f8fc94c71ed92660689f",
          "sha1": "91b8354dc34809dd1bfca842c420b09ae09f6e48",
          "md5": "225ff842eee763b8bdaad5586f6bd196"
        },
        {
          "name": "ktor-utils-macosX64Cinterop-threadUtilsMain-3.1.2-SNAPSHOT.klib",
          "url": "ktor-utils-macosx64-3.1.2-SNAPSHOT-cinterop-threadUtils.klib",
          "size": 6759,
          "sha512": "5cebf46736dbf99965b5069be0adc130f763454b4b99b7b1357cd37d7e2e9f4305f659282d63982ab7b1d7f5fec061765a463358d220f60b8a13a6915c782c55",
          "sha256": "38eee053cf6869ca7d31f528f8c4e821e089f23ec1beb0beed2838ddd08f5401",
          "sha1": "d9ddadad6a785f0d5fa8b6842f6f2ab5886c6546",
          "md5": "7dcd3271187ce3f1d3e4c960f23217d1"
        }
      ]
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-utils-macosx64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-utils-macosx64-3.1.2-SNAPSHOT-sources.jar",
          "size": 79276,
          "sha512": "2577dd5624fef52f225bf2bbe72ca11ddb97901eced70d30a79567709158928483bd490a0ca5e90b9b14c98f413a061dbbcddf30222a1c2e9a92ec382f414bc2",
          "sha256": "d70693069dceeac71482dc21a956fff610ae652a609cc4e195fc0059ce882aac",
          "sha1": "bd61f9bf0c441895db38ae51c3e9f4b6dcafc5d5",
          "md5": "614485d73f17d9599e31b5ed5be3c445"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-io",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-utils-macosx64-3.1.2-SNAPSHOT-metadata.jar",
          "url": "ktor-utils-macosx64-3.1.2-SNAPSHOT-metadata.jar",
          "size": 17505,
          "sha512": "bcc9e2805de9043de437b62f7aad683a7bd2ad393961dde86f6667ff50bf286d7c1f776d1e328a8f6eb2fe03accd891b801085bbd657736cd1e3a2faee256a70",
          "sha256": "46bcfe6a93a21e1221129ce9d9ac4176790a4a629edae97f0f58bfedfee38a5c",
          "sha1": "1a79ec8309fb531e6340dafd632f73f99baef452",
          "md5": "86d3a198ef6f83c19afdad186a2cf0b9"
        }
      ]
    }
  ]
}
