{
  "formatVersion": "1.1",
  "component": {
    "url": "../../annotation/9999.0.0-SNAPSHOT/annotation-9999.0.0-SNAPSHOT.module",
    "group": "com.vickyleu.annotation",
    "module": "annotation",
    "version": "9999.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotation-tvosArm64Main-9999.0.0-SNAPSHOT.klib",
          "url": "annotation-tvosarm64-9999.0.0-SNAPSHOT.klib",
          "size": 27533,
          "sha512": "bb4d2f74cdba0fa348bfdcf4e4a189bd33469d31e6d3cb49980512ce94eca55204fba1ca77986ff7f2f42736a2ef0381b71604317478140644678f30a6b9cf3d",
          "sha256": "0ab37f61ee388262544056fc4a3149ceddc1ea8dbd199e37acf7a97fc276364b",
          "sha1": "cbec8e19b74ac64c4c43601f55433deb6e03b310",
          "md5": "0d6ea8181db87025628e630d2137605c"
        }
      ]
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "annotation-tvosarm64-9999.0.0-SNAPSHOT-sources.jar",
          "url": "annotation-tvosarm64-9999.0.0-SNAPSHOT-sources.jar",
          "size": 25046,
          "sha512": "25798f3568df31f81eb0bcfe18a3fa8a0af36e38200f0a8b5887c8c3daf38e7202c107e404930ec54065d2cd021ef1a2a43f26a88094e56af7d365435611ed95",
          "sha256": "768b81005ebd26d9441a064ef52c02dc98df7490585701af8d81e8e15828510f",
          "sha1": "8f7d0a0ea94eac1d3a340eb0cb69887af6b6f2f0",
          "md5": "6d417dcec41447c8575ccb2a429ba141"
        }
      ]
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotation-tvosarm64-9999.0.0-SNAPSHOT-metadata.jar",
          "url": "annotation-tvosarm64-9999.0.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}