{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-network-tls/3.1.2-SNAPSHOT/ktor-network-tls-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-network-tls",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-network",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-utils",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-network-tls-wasm-js-3.1.2-SNAPSHOT.klib",
          "url": "ktor-network-tls-wasm-js-3.1.2-SNAPSHOT.klib",
          "size": 46000,
          "sha512": "566f4300468feb8d19bbc4b8f275d4d2dadaef83d7d88bf5371cf0a2ea4123bea85fd4e9264cd789e6adfd86829e77276acf994a61aafcbd696b1ffc34a9495d",
          "sha256": "5d6940d9aba2dcdf1fc8aa0707a2c619fecf848a9577d28ee6cc321d581fd0d4",
          "sha1": "c7469c3437fb832dcabc39c9c4fbb505059f9834",
          "md5": "13f5a4622422810d8239b5626c7bd9fc"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-network",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-utils",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-browser",
          "version": {
            "requires": "0.3"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-network-tls-wasm-js-3.1.2-SNAPSHOT.klib",
          "url": "ktor-network-tls-wasm-js-3.1.2-SNAPSHOT.klib",
          "size": 46000,
          "sha512": "566f4300468feb8d19bbc4b8f275d4d2dadaef83d7d88bf5371cf0a2ea4123bea85fd4e9264cd789e6adfd86829e77276acf994a61aafcbd696b1ffc34a9495d",
          "sha256": "5d6940d9aba2dcdf1fc8aa0707a2c619fecf848a9577d28ee6cc321d581fd0d4",
          "sha1": "c7469c3437fb832dcabc39c9c4fbb505059f9834",
          "md5": "13f5a4622422810d8239b5626c7bd9fc"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "ktor-network-tls-wasm-js-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-network-tls-wasm-js-3.1.2-SNAPSHOT-sources.jar",
          "size": 13552,
          "sha512": "917205a2fb65e4de8cf6a75fbf438cd5700dbb2e48099e5a62d75121bc985f3e65bf3af85e28a38271ee231a1156093a3a0998dba8efc970a517135387e4dbab",
          "sha256": "43c4dc620036ac0df7fb0563923be9fc291471c088177ff8c2e7219cc5be1b4e",
          "sha1": "0b8666c79682beb0a373d2030193644572443103",
          "md5": "c6d0b5a209c344e6773339d661186592"
        }
      ]
    }
  ]
}
