{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-events/3.1.2-SNAPSHOT/ktor-events-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-events",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-utils",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-events-wasm-js-3.1.2-SNAPSHOT.klib",
          "url": "ktor-events-wasm-js-3.1.2-SNAPSHOT.klib",
          "size": 8503,
          "sha512": "1c9b53d994c5f43c034e167dc3a0bba71dfa6ec325e182037513de5f7c7038833410f6200a640a65e5edd04317a6bb2aab6c89b052d47bad3ab107de6f43892a",
          "sha256": "9b9fee8f0cc335b87ccbed527187943316785d6074a502e4e7b77678624eaecd",
          "sha1": "0a36fa3eb9985a5505f9a4ec597022792652ecaa",
          "md5": "d2932eabe1f0e67073d44232de98b3e5"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-utils",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-browser",
          "version": {
            "requires": "0.3"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-events-wasm-js-3.1.2-SNAPSHOT.klib",
          "url": "ktor-events-wasm-js-3.1.2-SNAPSHOT.klib",
          "size": 8503,
          "sha512": "1c9b53d994c5f43c034e167dc3a0bba71dfa6ec325e182037513de5f7c7038833410f6200a640a65e5edd04317a6bb2aab6c89b052d47bad3ab107de6f43892a",
          "sha256": "9b9fee8f0cc335b87ccbed527187943316785d6074a502e4e7b77678624eaecd",
          "sha1": "0a36fa3eb9985a5505f9a4ec597022792652ecaa",
          "md5": "d2932eabe1f0e67073d44232de98b3e5"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "ktor-events-wasm-js-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-events-wasm-js-3.1.2-SNAPSHOT-sources.jar",
          "size": 2148,
          "sha512": "7daa847643accbec0d0ff76b1e315cbc1ba8ec279cf92e877b3f1861bc404fb80a8d13e760e1ab8147140475b64fb2be0713189f306fa92873ac9263fea93226",
          "sha256": "25a4d89461d074f84b3f77d8bfe875832adfe744c83aee283f4586f37acdffc3",
          "sha1": "40750b1d65bf1bb0e2740bc83fc54f83b5333808",
          "md5": "97598efdaf9dcc0f013164ec1cce5b35"
        }
      ]
    }
  ]
}
