{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-sse/3.1.2-SNAPSHOT/ktor-sse-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-sse",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-utils",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-sse-androidNativeArm32Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-sse-androidnativearm32-3.1.2-SNAPSHOT.klib",
          "size": 12217,
          "sha512": "628066817166d48ae77d2daf6ec569c9ff802926e9620fca7be6336c1555fe9b8f9715ba7019a021aa4e5bd41d5cd0a3962df4569847b05ca77a7962da2ddeda",
          "sha256": "6aa4bc914211d05f25ce1df3f788673f911179f2856d7d86a191ff10eb018ba6",
          "sha1": "40c7794c218a280cde6050fb07262d586f9d7989",
          "md5": "948e8a7ca71e413b6256ab7dd746d9ab"
        }
      ]
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-sse-androidnativearm32-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-sse-androidnativearm32-3.1.2-SNAPSHOT-sources.jar",
          "size": 1802,
          "sha512": "41429733cbafadd03cbb1831acf3e488832be89324942330849c333c39b46801d273bd1cc324d90db2cdc5ab1e3ab7acfe37552d2c3d6bcf4d60d07eddd7dc1a",
          "sha256": "c68c47d49e1faab58785b6646363a0c634e641c866c7030edc3f44be4c85ec9c",
          "sha1": "ceaf6f378fa7c0005625aff6a95e975bcea932e5",
          "md5": "0d6f9b4c42ca260589a9cc8387193271"
        }
      ]
    }
  ]
}
