{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-jetty/3.1.2-SNAPSHOT/ktor-server-jetty-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-server-jetty",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-servlet",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.eclipse.jetty",
          "module": "jetty-server",
          "version": {
            "requires": "9.4.57.v20241219"
          }
        },
        {
          "group": "org.eclipse.jetty",
          "module": "jetty-servlets",
          "version": {
            "requires": "9.4.57.v20241219"
          }
        },
        {
          "group": "org.eclipse.jetty",
          "module": "jetty-alpn-server",
          "version": {
            "requires": "9.4.57.v20241219"
          }
        },
        {
          "group": "org.eclipse.jetty",
          "module": "jetty-alpn-java-server",
          "version": {
            "requires": "9.4.57.v20241219"
          }
        },
        {
          "group": "org.eclipse.jetty",
          "module": "jetty-alpn-openjdk8-server",
          "version": {
            "requires": "9.4.57.v20241219"
          }
        },
        {
          "group": "org.eclipse.jetty.http2",
          "module": "http2-server",
          "version": {
            "requires": "9.4.57.v20241219"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-jetty-jvm-3.1.2-SNAPSHOT.jar",
          "url": "ktor-server-jetty-jvm-3.1.2-SNAPSHOT.jar",
          "size": 54355,
          "sha512": "0e710e6f079fa6d5a444da1250da63588d6206a58b0447e57b92ad34d66e6340dc2f93250ab83417e6635b163d88766b4088a28fc9e0b48284f1782400f11b51",
          "sha256": "f05a161afd54e003230e23e472cd7b876da8784a394e45a70babda42144ca3ad",
          "sha1": "90a5e360fd0f3f934007887fc5aa413142b3ee82",
          "md5": "ac3c49e0d4b099e6444611c7bdc94707"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-servlet",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.eclipse.jetty",
          "module": "jetty-server",
          "version": {
            "requires": "9.4.57.v20241219"
          }
        },
        {
          "group": "org.eclipse.jetty",
          "module": "jetty-servlets",
          "version": {
            "requires": "9.4.57.v20241219"
          }
        },
        {
          "group": "org.eclipse.jetty",
          "module": "jetty-alpn-server",
          "version": {
            "requires": "9.4.57.v20241219"
          }
        },
        {
          "group": "org.eclipse.jetty",
          "module": "jetty-alpn-java-server",
          "version": {
            "requires": "9.4.57.v20241219"
          }
        },
        {
          "group": "org.eclipse.jetty",
          "module": "jetty-alpn-openjdk8-server",
          "version": {
            "requires": "9.4.57.v20241219"
          }
        },
        {
          "group": "org.eclipse.jetty.http2",
          "module": "http2-server",
          "version": {
            "requires": "9.4.57.v20241219"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-jetty-jvm-3.1.2-SNAPSHOT.jar",
          "url": "ktor-server-jetty-jvm-3.1.2-SNAPSHOT.jar",
          "size": 54355,
          "sha512": "0e710e6f079fa6d5a444da1250da63588d6206a58b0447e57b92ad34d66e6340dc2f93250ab83417e6635b163d88766b4088a28fc9e0b48284f1782400f11b51",
          "sha256": "f05a161afd54e003230e23e472cd7b876da8784a394e45a70babda42144ca3ad",
          "sha1": "90a5e360fd0f3f934007887fc5aa413142b3ee82",
          "md5": "ac3c49e0d4b099e6444611c7bdc94707"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ktor-server-jetty-jvm-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-server-jetty-jvm-3.1.2-SNAPSHOT-sources.jar",
          "size": 11806,
          "sha512": "24bb1588614e565199618d68c0d00240e01bb2984d78e00d94ffe45ca6cfb7e4e137fd4c69123214585f8c3c058aba57c765a5d689449a538ecf87680face513",
          "sha256": "badcf2f7c53e8184e540104592c829cc2020d2efd15a3618c4da43107699ee0a",
          "sha1": "2538af7cfb7eda2f3deb303044a07f7a96369f05",
          "md5": "3d4225915f28f52bb8b1bc577b235620"
        }
      ]
    }
  ]
}
