{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-rpc-utils/0.5.1/kotlinx-rpc-utils-0.5.1.module",
    "group": "com.vickyleu.kotlinx",
    "module": "kotlinx-rpc-utils",
    "version": "0.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-rpc-utils-linuxX64Main-0.5.1.klib",
          "url": "kotlinx-rpc-utils-linuxx64-0.5.1.klib",
          "size": 28461,
          "sha512": "cbbd147540bc5faf8d6254b855daaa410ab3b3c3db282f86cde1608004511cc6efae4c3f81a4a88af1b8bc3f645bb3996c19fde30688aa1823d999c5afb884f9",
          "sha256": "2e10ec758503404ee6f3076798dc67aa984c1ade992d391a9261c47e8aeab8d4",
          "sha1": "2ff7b58ee694ea4a5f98f65a93bb315f2cc63203",
          "md5": "3e249b8503e7563ce5494e68f6f0172b"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-rpc-utils-linuxx64-0.5.1-sources.jar",
          "url": "kotlinx-rpc-utils-linuxx64-0.5.1-sources.jar",
          "size": 7752,
          "sha512": "7fad39a6c20adcf4041b2db58f8b8a92638574d5b3686ee4f51863a9150f2c6ce1907c48386424c9542414268ae6ae4c0dc66f31c2dea563e83f03c13446fd5e",
          "sha256": "c5c87127d49690814af31b1b1cb42362cf6348256fd8ebb1719efe892c576072",
          "sha1": "86211be509882f463b68e2a9c41e6e691c3d8998",
          "md5": "50d8d6cbb0502696f86338ced7cc4ac9"
        }
      ]
    }
  ]
}
