{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-serialization-kotlinx/3.1.2-SNAPSHOT/ktor-serialization-kotlinx-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-serialization-kotlinx",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-serialization",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-serialization-kotlinx-androidNativeX86Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-serialization-kotlinx-androidnativex86-3.1.2-SNAPSHOT.klib",
          "size": 24287,
          "sha512": "a6cfeda46dd84dff2745b06799bd17bd9b356d637196cbca0bd2a223ce9f2b3d329877db1b53070c309e7ea6e3064e600bb887a6e6cb4df6fe10d7c3669e7a2f",
          "sha256": "7c3ad06a9c3ef770861e70cb86bb9bb6e6bb36a93c2edf546b6d701724c6f589",
          "sha1": "d4cc64384b387173337566ffcccfc4902db0efb4",
          "md5": "dfc16283b3d9a0605a3f7e647d1ea260"
        }
      ]
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-serialization-kotlinx-androidnativex86-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-serialization-kotlinx-androidnativex86-3.1.2-SNAPSHOT-sources.jar",
          "size": 6796,
          "sha512": "da0898e6d6250bc2b13fa90ae6dfd3e9ddf3cdb9b0b929dc7e5cd6740a829cc9ab91a4305e59c79d6d2f1171b9610478692a6252934c00ce9618b0ceef106a23",
          "sha256": "154373a2e865760e6ba4622dfc2acce2ff82943d1cdcc8de19d325cf90645335",
          "sha1": "44d6b1f0bcf4e302f36afcf9117332b3fb2cb295",
          "md5": "a365b7b81d888d4a0e5eaec42fd103fd"
        }
      ]
    }
  ]
}
