{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-websocket-serialization/3.1.2-SNAPSHOT/ktor-websocket-serialization-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-websocket-serialization",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-serialization",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-websocket-serialization-js-3.1.2-SNAPSHOT.klib",
          "url": "ktor-websocket-serialization-js-3.1.2-SNAPSHOT.klib",
          "size": 6999,
          "sha512": "f42ecf16e2c41a38a85cb811820f3bfa0d079232ea06333c7022baf3762fc866de709ee07d94b72d12ca173a85f1b3f7e74046a669b1ef7b7e0852866c5ef6ca",
          "sha256": "7f2fa0936237186e83295b75c542a00b3561083cdfc0549bf50b6dc78cb2a67e",
          "sha1": "98ecc94139aba8ed6faff7700c5ac080f68d4f46",
          "md5": "a5a5e609f199eb0d31d2abe38c4b2459"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-serialization",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-websocket-serialization-js-3.1.2-SNAPSHOT.klib",
          "url": "ktor-websocket-serialization-js-3.1.2-SNAPSHOT.klib",
          "size": 6999,
          "sha512": "f42ecf16e2c41a38a85cb811820f3bfa0d079232ea06333c7022baf3762fc866de709ee07d94b72d12ca173a85f1b3f7e74046a669b1ef7b7e0852866c5ef6ca",
          "sha256": "7f2fa0936237186e83295b75c542a00b3561083cdfc0549bf50b6dc78cb2a67e",
          "sha1": "98ecc94139aba8ed6faff7700c5ac080f68d4f46",
          "md5": "a5a5e609f199eb0d31d2abe38c4b2459"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "ktor-websocket-serialization-js-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-websocket-serialization-js-3.1.2-SNAPSHOT-sources.jar",
          "size": 2326,
          "sha512": "e7fe8c5d0f1bab74755507fcfc8214bec60935736c0dc1ad54f1076115ca58f63d40702f38503b3b2a3b9d8d02ba55b91d62f5d4e326b9bcb5c454859258e3f8",
          "sha256": "e186e6ac4d88ce296ef51d91684444ca0002b4b7761a8dcd2fe55ef1dc8a7b75",
          "sha1": "4a023f031c84e174cfcb56892d01b37de32011e9",
          "md5": "0dca7e417fd69fd93f87b73d37846741"
        }
      ]
    }
  ]
}
