{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-rpc-krpc-logging/0.5.1/kotlinx-rpc-krpc-logging-0.5.1.module",
    "group": "com.vickyleu.kotlinx",
    "module": "kotlinx-rpc-krpc-logging",
    "version": "0.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.6"
          }
        },
        {
          "group": "com.vickyleu.kotlinx",
          "module": "kotlinx-rpc-utils",
          "version": {
            "requires": "0.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-rpc-krpc-logging-tvosSimulatorArm64Main-0.5.1.klib",
          "url": "kotlinx-rpc-krpc-logging-tvossimulatorarm64-0.5.1.klib",
          "size": 12479,
          "sha512": "10d97dee7bdc2de0e249f8322ad3739de0e3047d2bc4468b2952d79beef2cac22f09071ea7b6c5efa21678f8d286796563e3db522f6f6ac7b5cf03b244fe416a",
          "sha256": "53cb22728eb437ce7b12c923c03588e4634bb8700c930ac38967c7b3a8546616",
          "sha1": "538bc2bf2bf6bbd1bdd08ae7917a8c2bc6ce21a6",
          "md5": "ebf986c09590d6bd9563565d7f97f23b"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-rpc-krpc-logging-tvossimulatorarm64-0.5.1-sources.jar",
          "url": "kotlinx-rpc-krpc-logging-tvossimulatorarm64-0.5.1-sources.jar",
          "size": 3141,
          "sha512": "02123f3be3ee56a880ea0742c1ea34d5e0e61f63530f12524c374fcf6f5f083a687f36115fbdac268315f88b26e6132ab5b514b88d71dbf081e7127f8912f6d6",
          "sha256": "8e48b530ee5752910707bf402ff89d304e9cd21d60d6b841a0b29bd4b6413cf0",
          "sha1": "9a949afff48ebd85331320e4b8d5a8da07bb1f66",
          "md5": "1da329d6bc94828d33ab4607a09699a0"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.6"
          }
        },
        {
          "group": "com.vickyleu.kotlinx",
          "module": "kotlinx-rpc-utils",
          "version": {
            "requires": "0.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-rpc-krpc-logging-tvossimulatorarm64-0.5.1-metadata.jar",
          "url": "kotlinx-rpc-krpc-logging-tvossimulatorarm64-0.5.1-metadata.jar",
          "size": 261,
          "sha512": "3b23796b59ce12e95390c8cb4ca3ded5f6f12640c292622d524e63d1400a0e733128aa7645922891e7b136368b35d6a7b87979007441a1cac56706a41c0883a6",
          "sha256": "afef69f1548692c3a90eab11bf76d1bfedbf1aca138f25fc08ec97bf02e4f9ad",
          "sha1": "70bd359baf45ae6db8a3c70761989547bf5a4992",
          "md5": "db0fdbb13d52ffd9f3edb48615ed2a9d"
        }
      ]
    }
  ]
}
