{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-call-id/3.1.2-SNAPSHOT/ktor-call-id-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-call-id",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-call-id-androidNativeX86Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-call-id-androidnativex86-3.1.2-SNAPSHOT.klib",
          "size": 5484,
          "sha512": "301fb44ec553ce39aee0b9dd1d894e95e7660a7969e74e4ea31786389be6a176afaa4313cfd5c74c15d900056cc90fdc087641902e26c2e38a7adaa9b1df32c0",
          "sha256": "5e4ffe55ac585572a22038b59eb1f19884cf3180adf37f970aad6a38d293652c",
          "sha1": "5c864a48b022761454bf4ff61603a3e761144c8a",
          "md5": "a250bed4324354471ac421bb2e9e0643"
        }
      ]
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-call-id-androidnativex86-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-call-id-androidnativex86-3.1.2-SNAPSHOT-sources.jar",
          "size": 1414,
          "sha512": "65d139b76c81b7698762646c6d7b77f9abdf4d40135f376dc6ef454332adcfdd4e73b4f78f2bb47b496d6091ce0b986ff7b8666900f499350756c86a60627a6f",
          "sha256": "0271d192d924e609c6b5e25de6deba80e6384ed0f4bf8cd2a33b26cd3d52e9dd",
          "sha1": "ff8d4cf17a592129db6fad5ae7e8a64712b75d35",
          "md5": "bc3a005c746c04911cd0981ded54df9e"
        }
      ]
    }
  ]
}
