{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-rpc-core/0.6.1/kotlinx-rpc-core-0.6.1.module",
    "group": "com.vickyleu.kotlinx",
    "module": "kotlinx-rpc-core",
    "version": "0.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "com.vickyleu.kotlinx",
          "module": "kotlinx-rpc-utils",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-rpc-core-macosX64Main-0.6.1.klib",
          "url": "kotlinx-rpc-core-macosx64-0.6.1.klib",
          "size": 45258,
          "sha512": "d073a98b45802a02bf12dc095f293abc10adf30712c4790203c4300fe8d4401eb30f70464c621598b3603b17e3269f6099e0acbf79a12616703b436489a1983f",
          "sha256": "f4a94db7c43882d71fe704fe40bb9611ed256f062b31eff04fda449e9adc5b87",
          "sha1": "fa3668164c8981787f42f1f22edaf487bfd170f2",
          "md5": "be5adfbc324f99e193ea04a33d41272d"
        }
      ]
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-rpc-core-macosx64-0.6.1-sources.jar",
          "url": "kotlinx-rpc-core-macosx64-0.6.1-sources.jar",
          "size": 17643,
          "sha512": "d5079406f665df410bfe7dfc4d7c5e8f924a285aa8520fede845b7b98244eb441141be1d882ce120d3b6d2cda5bb1f80a6ba4e3cc766ec0b667b5db14b64ff70",
          "sha256": "30dc0fa83f09c7e8f6e25637144e8e9797cd3f03a3c66d37c25550d2200aee15",
          "sha1": "32507c5a36ee55fed957f3dec52c885017a05f11",
          "md5": "4338e230a12fbeaa91826bd5d229e5aa"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "com.vickyleu.kotlinx",
          "module": "kotlinx-rpc-utils",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-rpc-core-macosx64-0.6.1-metadata.jar",
          "url": "kotlinx-rpc-core-macosx64-0.6.1-metadata.jar",
          "size": 261,
          "sha512": "9897697b382eebc5929fcf23e57e6e73100d277a667f317897ac7f08f6fc7a2a62baf3ee907fcb102de6c41cb7a54a5f1b55cc8d6a93a285dcb3a8920692f56b",
          "sha256": "98abb00352fac6b586c2f6db762517bf5c8736649729466ef898de2cb7050bdb",
          "sha1": "e855e039a0ddd0ebbb1cd2bbdec7b9507ae9b491",
          "md5": "08fd388a37f771da1c8dddbb77889917"
        }
      ]
    }
  ]
}
