{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-client-encoding/3.1.2-SNAPSHOT/ktor-client-encoding-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-client-encoding",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-encoding-androidNativeX86Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-client-encoding-androidnativex86-3.1.2-SNAPSHOT.klib",
          "size": 22803,
          "sha512": "c5e220632ff820eb8874c96e691292a5ff2f52f3e06562f5851e8e7dbbc3bcd031410144788f8de2965d6da3dbe172eb345b954df72eb2a2e9a6e83d794f8e25",
          "sha256": "76feb8a325952426e71d671387fa9cfeafe6307d42aeabea6a52688fb08ce3cc",
          "sha1": "82717babc89be1d7fb42ab798baf84f29474c8b4",
          "md5": "d3df7f67890a3897b376044d2ec712f0"
        }
      ]
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-client-encoding-androidnativex86-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-client-encoding-androidnativex86-3.1.2-SNAPSHOT-sources.jar",
          "size": 3218,
          "sha512": "7485eb61a1380e1be058b38bf5f7cd4c225d67f57dc2883cd701b61404ebad36414d8f1089bd641680c2b0f8e5a3156676e90cbc416f2b4a4bb76acf52100a47",
          "sha256": "ce606b2cdc86a8287c01e12dff5a721fe8a37f2bd41ab69926fe1b5b5f4b252e",
          "sha1": "80c2638ddc263fb7183f816fa964a5a798a82d8f",
          "md5": "cf21e5d120a76f6aacb7059c0245091d"
        }
      ]
    }
  ]
}
