{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-double-receive/3.1.2-SNAPSHOT/ktor-server-double-receive-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-server-double-receive",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "linuxArm32HfpApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm32_hfp",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-double-receive-linuxArm32HfpMain-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-double-receive-linuxarm32hfp-3.1.2-SNAPSHOT.klib",
          "size": 23242,
          "sha512": "773b86b2ccffc906db8d41ec7e86be9bc7106f40f9d23915996bb0ea0fe1dd7b8b5d67a772c4197dfe4a50f1b02fcebf4b55a3d074a2d8ed1eff290c064b4bf6",
          "sha256": "07bc796b0a95f11b822a333978592eb8671259e1d2e22aa77fe1392629f31189",
          "sha1": "88730be16eb808f6f726923dc3fffca632868508",
          "md5": "b1188a75a4ec2e70af1a3d2e68d3395d"
        }
      ]
    },
    {
      "name": "linuxArm32HfpSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm32_hfp",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-server-double-receive-linuxarm32hfp-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-server-double-receive-linuxarm32hfp-3.1.2-SNAPSHOT-sources.jar",
          "size": 7243,
          "sha512": "f4ab371064a5ddbe99c957d85ce93ab1b8b9af2b7782913846e0ee540919ae0fa2eb317b7abb23c258f07b9b9c462d2dc110f15d9f0854a6989b0750444de85b",
          "sha256": "d31cf7c6a6b0ff00b18cfb9f1cd622ee70e64be0c505d1141ebcc61115d6936c",
          "sha1": "45f922896fdd1a97360dbead8657de50b0f2aba0",
          "md5": "90d091b4a2b5cfbb9b25db2082360d5e"
        }
      ]
    }
  ]
}
