{
  "formatVersion": "1.1",
  "component": {
    "url": "../../pbandk-runtime/0.16.1-SNAPSHOT/pbandk-runtime-0.16.1-SNAPSHOT.module",
    "group": "com.vickyleu.pbandk",
    "module": "pbandk-runtime",
    "version": "0.16.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.2"
          }
        }
      ],
      "files": [
        {
          "name": "pbandk-runtime.klib",
          "url": "pbandk-runtime-watchosarm64-0.16.1-SNAPSHOT.klib",
          "size": 678477,
          "sha512": "f11ea6616994620bc5d3180cc5479be7fa1dd37089ff932c1d97975a6c1cdc582681fcfd9afb18080a00a245a93551f04aefa2b6731fd2ed556adeabd7370b53",
          "sha256": "61291e037085af394ece1c03ce943fe15f02b07545383a7984d2c418e6b70c15",
          "sha1": "e34167776d3e07e1d7d8dcdf95a72bc1eb8d2745",
          "md5": "e12f69b61938cc005858b533d47d646a"
        }
      ]
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "pbandk-runtime-watchosarm64-0.16.1-SNAPSHOT-sources.jar",
          "url": "pbandk-runtime-watchosarm64-0.16.1-SNAPSHOT-sources.jar",
          "size": 89500,
          "sha512": "036c717c886c7f2c66b568ad3f05a1cb159fa5c07ee64235fbe6c226562682e11c912094acbd57cc82fa03b81919ca35c59763c042e88d3d5c74138950020ff7",
          "sha256": "51e2b29d585dbda1123cca39bc5e65c2495759858466323d67a5c02fd1fb998b",
          "sha1": "4d74b3fac1961c3b7cf671023c4d8af87873ec17",
          "md5": "e33355a59f03ba7232f002d0d24d31e2"
        }
      ]
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.2"
          }
        }
      ],
      "files": [
        {
          "name": "pbandk-runtime-watchosarm64-0.16.1-SNAPSHOT-metadata.jar",
          "url": "pbandk-runtime-watchosarm64-0.16.1-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "f95109f7a00492b5558cd6c47a947ef16743c821fbbed021985b67a32aece9103aa3dd73e9e342bb701c80a475d8d1600a7e37d3c7d3894dcb9b0e4011e3a0d6",
          "sha256": "c810c72df4c2f84ce412481d6d9e7088d1791b77260af9ad022f5e55e0c331b5",
          "sha1": "c2c0aff3a8cba00f879a7209a039ec72f776409b",
          "md5": "627182aa9d37c01b36b479f07b97e05b"
        }
      ]
    }
  ]
}
