{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-host-common/3.1.2-SNAPSHOT/ktor-server-host-common-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-server-host-common",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-host-common-watchosArm32Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-host-common-watchosarm32-3.1.2-SNAPSHOT.klib",
          "size": 3465,
          "sha512": "13dbe10ac9db587a9859b8f0ab560e016b5991b3611f0adac2d513d598b70d3d06c9b529b6137cc485cc23efece872c87b6dc6d67e5a3c0ecc38ee3d1f6f4c60",
          "sha256": "973dc0d3204108e637a12a9acb392938c952816c5a91ece254f96d754612cb88",
          "sha1": "29f936d000b466823c879235e0d10c542aa5a8c7",
          "md5": "4d248177cd4e12fa7e299565e59557df"
        }
      ]
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-server-host-common-watchosarm32-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-server-host-common-watchosarm32-3.1.2-SNAPSHOT-sources.jar",
          "size": 621,
          "sha512": "f04f945d6a7d30a53537aa03c5b9ff5f72e60e4150cc04bec3114161649c0177f6ef2d801ca541f66ae5e2a12a40c6f5560f6c166f14e70f3731a9b77361aced",
          "sha256": "8f1b77aa660fed1302454fd2a303ab07ab29a5d52029c98850cedff554c454f0",
          "sha1": "ee19f777cd0f857f7e5bccd5eacb04c7496d9a13",
          "md5": "5b14dfc1ec7145751b60a8479edee37d"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-host-common-watchosarm32-3.1.2-SNAPSHOT-metadata.jar",
          "url": "ktor-server-host-common-watchosarm32-3.1.2-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "ba3605052bba68ba0e8f2d61bfe9477f255be434567d8214546939c9212fb30d7f65fbbef645e236810e7954a64c9ae8d5f026bc13d03b8ec369a77df296390d",
          "sha256": "ea4ee68e65e6bc4e80ecdff85bd484d4f16e742ce8d4ab041646ab0e1e7bf831",
          "sha1": "e148bed6c709ed789b8576c74fe2d9476e25ed8c",
          "md5": "196509cc7b63aa78b665c04aa87fe291"
        }
      ]
    }
  ]
}
