{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-core/3.1.2-SNAPSHOT/ktor-server-core-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-server-core",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-utils",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-serialization",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-events",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-http-cio",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-websockets",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-core-linuxX64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-core-linuxx64-3.1.2-SNAPSHOT.klib",
          "size": 441377,
          "sha512": "0d054b889fa9d3bb2b4711778fd156ca3418a34104e51d7be137fd38fb8c64ac413b308577f730d92b6459164d8cf1a3d8e2958718a7db84c3b862f907e2d1da",
          "sha256": "5500d00f5c7c10a39500c31a0d4cc11cacba7a2135d5124db9b83644d6183d1c",
          "sha1": "fc409e17ea270aa20fca0f85f4b468b26c3cedba",
          "md5": "99bd7c9486a1ff0ce7efcb710b436db4"
        },
        {
          "name": "ktor-server-core-linuxX64Cinterop-host_commonMain-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-core-linuxx64-3.1.2-SNAPSHOT-cinterop-host_common.klib",
          "size": 6266,
          "sha512": "b8be23b8b56e6481b0e0e91cbaeea8a653512a5aa45efac086b63469cea111bee3fd1bb55157a67f5bb71201bde5e61c6c54e3d21f5ff9ecb8ada90325ed7391",
          "sha256": "ecb2ae14a14cf5c95a53eed449539677248f42076e5a9121f65aaf61c6aefba3",
          "sha1": "240c7419f94beb79116a9c5c4895045541bc7870",
          "md5": "e892bd47f430cf306b80708fc3da776a"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-server-core-linuxx64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-server-core-linuxx64-3.1.2-SNAPSHOT-sources.jar",
          "size": 118184,
          "sha512": "3954a0402e48412c976eac690b449da7e00574a9208578aad5e16344875f3989bd04aaf3191481605855b648c08f650e5406998cac79cd3c5354ff194db14ea9",
          "sha256": "c6c2fb9c28a5a23297ea55815de1a6edb2dd38308e5cf3825b2ceb18141c16cc",
          "sha1": "7cf6719011753c1c649b70251351eba85af08300",
          "md5": "38c7f2c8265bbd690f532f905b9d3e56"
        }
      ]
    }
  ]
}
