{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-call-id/3.1.2-SNAPSHOT/ktor-call-id-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-call-id",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-call-id-macosX64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-call-id-macosx64-3.1.2-SNAPSHOT.klib",
          "size": 5466,
          "sha512": "e0baa5f9e6689719cce43341e054713ea752798020a73f1aaa66cc08322b8bc44ef5544c3400f85b698f392cb640cdc6c89988aedba75771e2c653362ab3c711",
          "sha256": "4a965bd19266d4693aa54e6f12b5d8718aa7923938c9eb1feb9d645b5e0830f8",
          "sha1": "eeec126a5c40ac707fdf03a89fd92a8b1095bead",
          "md5": "99899d43ddc1f9f218e1ffe6324e8910"
        }
      ]
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-call-id-macosx64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-call-id-macosx64-3.1.2-SNAPSHOT-sources.jar",
          "size": 1414,
          "sha512": "65d139b76c81b7698762646c6d7b77f9abdf4d40135f376dc6ef454332adcfdd4e73b4f78f2bb47b496d6091ce0b986ff7b8666900f499350756c86a60627a6f",
          "sha256": "0271d192d924e609c6b5e25de6deba80e6384ed0f4bf8cd2a33b26cd3d52e9dd",
          "sha1": "ff8d4cf17a592129db6fad5ae7e8a64712b75d35",
          "md5": "bc3a005c746c04911cd0981ded54df9e"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-call-id-macosx64-3.1.2-SNAPSHOT-metadata.jar",
          "url": "ktor-call-id-macosx64-3.1.2-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "b9510ff4d41a9211ec5477e1a5d365d37716db07756e0b55ceee988cb70ee96955d66131f269a118436dfa221268f3af0892fb8adfc555803faa1d965e6fe65e",
          "sha256": "f5e9472d2d6fb3a1cb40015041c1edeb56e2f529785d1c165bce62247f005601",
          "sha1": "bfb9a6b4170f8d036d2fba37a74815c962845065",
          "md5": "d972c3269c989dda098928f308edd4e9"
        }
      ]
    }
  ]
}
