{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-rpc-krpc-test/0.5.1/kotlinx-rpc-krpc-test-0.5.1.module",
    "group": "com.vickyleu.kotlinx",
    "module": "kotlinx-rpc-krpc-test",
    "version": "0.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-rpc-krpc-test-linuxArm64Main-0.5.1.klib",
          "url": "kotlinx-rpc-krpc-test-linuxarm64-0.5.1.klib",
          "size": 3487,
          "sha512": "e9f9cd339d33ac1e8ca60ca332002f4abae4cd0b3a2811581ec1be004b51aaf001480a1b5b80108302d11e84da680ed289cc1f8d312a69519cf583092a5c6894",
          "sha256": "b4f2b391067b8cf3a4ab622043c118272c181678fb5d9d64db9d3ff39cc4f58c",
          "sha1": "9da30692e96c3998628fe2c6461bd6b039bb631e",
          "md5": "8000c3bd63e4506f1c1521ee7dd81ba2"
        }
      ]
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-rpc-krpc-test-linuxarm64-0.5.1-sources.jar",
          "url": "kotlinx-rpc-krpc-test-linuxarm64-0.5.1-sources.jar",
          "size": 644,
          "sha512": "16b83ce79591b095adf720df482abb2e14da3f3fd40a3c1a46ba59becf28f1d094aaf1ff99fc772f864e59e8b105e930693159fd80ae6d94f9eb24806a9ce020",
          "sha256": "b3145b4e01e1f3412d297a56c86209350d08be1ba36a31a6126e98de2a006f25",
          "sha1": "4c87a2cd579bf018fe4db89f467db3a78d0bbf97",
          "md5": "fcbb59b898de6c68f8351d4bebbb2bfd"
        }
      ]
    }
  ]
}
