{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-rpc-grpc-core/0.5.1/kotlinx-rpc-grpc-core-0.5.1.module",
    "group": "com.vickyleu.kotlinx",
    "module": "kotlinx-rpc-grpc-core",
    "version": "0.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.vickyleu.kotlinx",
          "module": "kotlinx-rpc-core",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "com.vickyleu.kotlinx",
          "module": "kotlinx-rpc-utils",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-rpc-grpc-core-linuxX64Main-0.5.1.klib",
          "url": "kotlinx-rpc-grpc-core-linuxx64-0.5.1.klib",
          "size": 27118,
          "sha512": "397344cb48cc0ad7c9dcbbfcc26176787815e9aac3eaa0e99e771e552f22d7eb3182959325ff84afae63514a96b2ecbec23462b08e8a36756a916b1bc82ae1e4",
          "sha256": "dcafa090c7c2b176d2cf3d4eb212c345b9e179f257ed9edec405a3df48ea4214",
          "sha1": "f27c51d3e26b8f59277282e5fcad44d692f11e75",
          "md5": "cb8946479bfaa30282ca9410367de41e"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-rpc-grpc-core-linuxx64-0.5.1-sources.jar",
          "url": "kotlinx-rpc-grpc-core-linuxx64-0.5.1-sources.jar",
          "size": 12685,
          "sha512": "1c028a19fcfe6aa96896f204810f2073d503f0d030843f776c7affbe138fb776ff48e5d6af12a8cd273c3a54c356bc036812279d381c7bab02b5df0cc6f4c4e4",
          "sha256": "5069a1611d0c6a54088696a489c52ca25f1c8783b0271f3c22903cf05dfbce9a",
          "sha1": "ef560803272fe29a47d3260da2b2b1680534a72a",
          "md5": "fc8a57bd8f4e13920a47454c0b84ba7e"
        }
      ]
    }
  ]
}
