{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-serialization-kotlinx-xml/3.1.2-SNAPSHOT/ktor-serialization-kotlinx-xml-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-serialization-kotlinx-xml",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-serialization-kotlinx",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "io.github.pdvrieze.xmlutil",
          "module": "serialization",
          "version": {
            "requires": "0.90.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-serialization-kotlinx-xml-linuxArm64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-serialization-kotlinx-xml-linuxarm64-3.1.2-SNAPSHOT.klib",
          "size": 5468,
          "sha512": "85c35a6ce109a3132bca4bb3d150b9fe595451801fa2167faa15d8f0053528170bd9269e2d353944f45c98f0a1094d1c18a70d1d85c00ca9763a9cea105eb992",
          "sha256": "5187e59eb8e80fecb7c3d78bb36236c997758d10a081bf043b586bdca599e2b1",
          "sha1": "44f53428551367259bd885c0d901e5b9af8b5519",
          "md5": "6a9f30e5b542f901b49337bd164a0e48"
        }
      ]
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-serialization-kotlinx-xml-linuxarm64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-serialization-kotlinx-xml-linuxarm64-3.1.2-SNAPSHOT-sources.jar",
          "size": 1979,
          "sha512": "9aeeb7fd7a99a42bb8fc12361313ec8b33177f610db3aefbc58ec4e0e698642dad6c2d2a9d2acd98cc6e72bac7b50790f6102ea9aa95623d490824e787cc1434",
          "sha256": "06d3f51b2b8f577df6d04f8a0bbc5d3653666f1834672941b87734824b2c67e6",
          "sha1": "2d19e6c70429404897b572b2bf182973c645bbec",
          "md5": "3058ef2254c9096c9ab3776df05857ff"
        }
      ]
    }
  ]
}
