{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-client-content-negotiation/3.1.2-SNAPSHOT/ktor-client-content-negotiation-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-client-content-negotiation",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-serialization",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-content-negotiation-iosX64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-client-content-negotiation-iosx64-3.1.2-SNAPSHOT.klib",
          "size": 22792,
          "sha512": "69d29409e5b0d188d6d887fd2c55c0dcec6a3b5809325349a9efbe94a8853f99a88197fdcf98bd37651abd81205d8973b38d929680cd2644a2eb1b5fd88687fe",
          "sha256": "113cfbf8f35944a1e4cea38d104a191976ad58bf7f47af4f267b0f2bfd8dfeeb",
          "sha1": "844baa53c1a46465509b4e15ec424aa400e06cc5",
          "md5": "42f0e6b384a382785c665d8befe24030"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-client-content-negotiation-iosx64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-client-content-negotiation-iosx64-3.1.2-SNAPSHOT-sources.jar",
          "size": 5541,
          "sha512": "166ecb1486c61188e275e5e7a33d3bcf6f43e048bccafc145e8c9e0a819750065e4ab45cbbee056bdb12ec14cf2c91429becc261925c46a7692df450752c4fa2",
          "sha256": "5787bc15d42038cad551b274b6c88b9672470c408e27db6a035ae1d42e3fdc7f",
          "sha1": "f3c1785f9e9a969fdcb56943e51f8aa05e33aa3b",
          "md5": "d2d8489404addc6f624e366a8b77ef34"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-serialization",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-content-negotiation-iosx64-3.1.2-SNAPSHOT-metadata.jar",
          "url": "ktor-client-content-negotiation-iosx64-3.1.2-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "ee66636b429c0d715fd337471473d2a061beac193c8b38884a1f49c3976e6be6d93be0ccfae5c78d51ed020c23298b96a22cd841b90bbb7bef03fdb5b4020ffd",
          "sha256": "ca6410e759095b9df817993e6c891c513de0b2a257e2915a59be88cc877c7af2",
          "sha1": "b20bd81d3bfa513a315923a7f52e7c4a7722a158",
          "md5": "1d74e1ee3dc4ecc5897a0abf581c0a82"
        }
      ]
    }
  ]
}
