{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-resources/3.1.2-SNAPSHOT/ktor-resources-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-resources",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-utils",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-resources-androidNativeArm64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-resources-androidnativearm64-3.1.2-SNAPSHOT.klib",
          "size": 31429,
          "sha512": "ef913ec09c336a8a53122f98e7579710171e9536bcfed9d8bdf7ff42ec336a2b73f4171758b1c8d5557c7d60c3d0f13bb3745827f73fab948f912ec1ea33f0ab",
          "sha256": "5736c88d26097ad90fd74d53e594b26b5a76e3f6db985ee8d3ea0e9ea2bbf516",
          "sha1": "22e6c39cfca3cd81b4066278fc26d2b41b0c6057",
          "md5": "04874b64481801c377a78944eaa306c0"
        }
      ]
    },
    {
      "name": "androidNativeArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-resources-androidnativearm64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-resources-androidnativearm64-3.1.2-SNAPSHOT-sources.jar",
          "size": 7352,
          "sha512": "67c11afcdce02a947eccb437cc0c144535506e38924f7f4c52a03ddadfebab135c3e8e662d0f9541136fa7b3e5a458f709c83012d79e6b78bc63776b4d0e0656",
          "sha256": "836b34e90ae980c60d258f5f02ddcb85d495190632ca4efb85a4e3c62f3e7aa4",
          "sha1": "d57c8e6c873e41e78cc0ba50344e50cb68743c5f",
          "md5": "bbcde504ca4d38d95a268ddbc41af6ef"
        }
      ]
    }
  ]
}
