{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-html-builder/3.1.2-SNAPSHOT/ktor-server-html-builder-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-server-html-builder",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-html-builder-tvosX64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-html-builder-tvosx64-3.1.2-SNAPSHOT.klib",
          "size": 16133,
          "sha512": "4a5092516f307d3a94a3b1aff9da7f7d450177b34349582766b6c7a792f3cc94f13bb9fadf2a958ecce1eea34d5ea85606cebaa4b2cf0bd20b2ebcc889e6328b",
          "sha256": "27ecf14b32805f01dad0076c8a731b5c9265dc2816cd02abc7e9859d05d14485",
          "sha1": "69ac94f25b6d26d897d9bc2623941efb196e830f",
          "md5": "f2f1a83a6c2f90126d1cf7686f5bc93b"
        }
      ]
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-server-html-builder-tvosx64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-server-html-builder-tvosx64-3.1.2-SNAPSHOT-sources.jar",
          "size": 3624,
          "sha512": "ae49215733d475fb2907f74f88eb3a35d19aa7c1d551ead30ccd2d249fe7c7f6202b56f068d0c446585d364c73dc6a5d4a3f40c3f6db5b4a8aacb7e68e620324",
          "sha256": "a99b379ad0a12c0b88263bed2344f4912bafc8b2a1fad50426b7af85dbd6a831",
          "sha1": "ba1b0434aaade1511092dd908b61086894bdf31e",
          "md5": "a33f6166580925e7c3c33680a951369b"
        }
      ]
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-html-builder-tvosx64-3.1.2-SNAPSHOT-metadata.jar",
          "url": "ktor-server-html-builder-tvosx64-3.1.2-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "d1b31eec6c05bcd2192e84ea403e7fc1576d7c7109c098f719e4a8b8946ccc9922bfa996f84690ff13b6925aa14846aa9489cdda67a7b52d6737fa6a8cd03d52",
          "sha256": "372778609a380207c3268ca7757493ea299e29278095ef3dfd910447e23979c0",
          "sha1": "ec0a2292cae0f3ca2630acab5d78d32de8a23c67",
          "md5": "0005c0e2366bc4726f8801e6c5530af1"
        }
      ]
    }
  ]
}
