{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-http-cio/3.1.2-SNAPSHOT/ktor-http-cio-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-http-cio",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-io",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-http-cio-iosSimulatorArm64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-http-cio-iossimulatorarm64-3.1.2-SNAPSHOT.klib",
          "size": 131254,
          "sha512": "f24d7538ed174348ece07172f456dec129fe8c8102907bdb2c4626159a47756f5143f5e93c610237397c22f690c125591f69d2b5548e38df992edf9dbbad2f38",
          "sha256": "1f4b68f4d3d10bd7e6d8ff7d241b8a95d8bd9ef27cb57917488df0e4cfb525b0",
          "sha1": "f0b99d66af448d6270fbb6950e195bae887ea6a8",
          "md5": "539df31279b34fa3751d0ee4cca7693d"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-http-cio-iossimulatorarm64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-http-cio-iossimulatorarm64-3.1.2-SNAPSHOT-sources.jar",
          "size": 28012,
          "sha512": "eeb1e5f41eaea9d570e2adf80131ce15fdb6ff7b485161e918b5307ddecf61639d983d5085b81afc80570d615410c340633ddf326be4ccf6895cf5949f9037d4",
          "sha256": "354c235d3b5e2c1b658a98372fa714e879f1cc6a7b68ff5e0ad0dbdb8f27a2b9",
          "sha1": "5e1f9da60d6952c974b3958af3c6761c307d2761",
          "md5": "92216b961edd779fabbaea1a5ad7a1a6"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-io",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-http-cio-iossimulatorarm64-3.1.2-SNAPSHOT-metadata.jar",
          "url": "ktor-http-cio-iossimulatorarm64-3.1.2-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "cff7f964933e81b0a6a70576c885d0550198c44236cdde4e496208a6d1986cd6f1973f672df1f90c5f4e40dbd92bed22e7551c20b00c4fb989dd340866c13826",
          "sha256": "ae173aa223ea1f53d97ba4d3ae4907354e5d197725459d7030f3534f9efcc187",
          "sha1": "bd84392acb94689964b497aabebc1e79e867d263",
          "md5": "d71fc0feb322d17e50849d75bb9eb5cb"
        }
      ]
    }
  ]
}
