{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-data-conversion/3.1.2-SNAPSHOT/ktor-server-data-conversion-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-server-data-conversion",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-data-conversion-iosArm64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-data-conversion-iosarm64-3.1.2-SNAPSHOT.klib",
          "size": 5792,
          "sha512": "8258588f510b6041b37d21780442e7ffe4e185a785cb4ea5bf0004242f64b75b685540992b81f59bcdfc10142fe1631d5c03d441e2dbe6373626049b9bc0215f",
          "sha256": "ee9f39eafa784c7f11edd42c1f5852befe18e3207f247bb5f8b52be7eb3b99c7",
          "sha1": "e127fb45ea82e3ef6313a1feb1906e9e984e9a59",
          "md5": "ac890915b0ed7f5a4503b606ab954cba"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-server-data-conversion-iosarm64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-server-data-conversion-iosarm64-3.1.2-SNAPSHOT-sources.jar",
          "size": 1782,
          "sha512": "2ff57d536c9be84fccc877003df07119317b8dd33b443d78785c72c4cc2eba967743937f5b062b166a792836747cae6b9f810ff888664b148f2d910404f96cff",
          "sha256": "a6d9710261dd2448519c7fe4dbe020a5c903270d4d1bcd83c5adbf322909e1f8",
          "sha1": "38acec474a03563944b2137996b9cb0634f8df94",
          "md5": "705b84a0b2dcce15e9264010650192ac"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-data-conversion-iosarm64-3.1.2-SNAPSHOT-metadata.jar",
          "url": "ktor-server-data-conversion-iosarm64-3.1.2-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "6c90b8f19e0163727666aacc01c29ecbb936212b3664c2d875d5b10c54029bb047c23d6e5a87b6586eef8933a45ea2fe630910aa35bc8e874b8bec6582c04f15",
          "sha256": "0a31af3624da2de34a566e6a613fc9553aad5bfc6e564b0cfc2957215b5e4caf",
          "sha1": "7aeefa3a5d03a14efbab7b6d5fc8beca0f259d2c",
          "md5": "050c5bb704e158c4878afca802cb62d8"
        }
      ]
    }
  ]
}
