{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-io/3.1.2-SNAPSHOT/ktor-io-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-io",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-io-tvosSimulatorArm64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-io-tvossimulatorarm64-3.1.2-SNAPSHOT.klib",
          "size": 190333,
          "sha512": "f60bbc6e6342aef74281216ef9bc8718b717cb64dc900c8979ed940d6e6aa1864ae2a218eb27011320fb1c87c4cf968d0bdb4f743c6f594317e34e1fcd60c673",
          "sha256": "f8cd8cad37f8d4b164fa9d551b8abf8e3a33760ad4277003c878f6e05d43e82d",
          "sha1": "14dd1a549b93a099f6a43764102510ba67a1cd3f",
          "md5": "df249f1fe94f14f40f40754c0e1f96bb"
        },
        {
          "name": "ktor-io-tvosSimulatorArm64Cinterop-mutexMain-3.1.2-SNAPSHOT.klib",
          "url": "ktor-io-tvossimulatorarm64-3.1.2-SNAPSHOT-cinterop-mutex.klib",
          "size": 9424,
          "sha512": "f0c3dddba48b5357d19a362efb0a974436f7538a78fbdcd7368708f566183f66b1c8477e6bd0b29908d192c5eadb026f457cfa205d7aed261703f1a3859b10fa",
          "sha256": "2406bf923dce92b7807b7386d35a78315cd53c9a9d35920a4f64aab0464989ec",
          "sha1": "41e20a14160e8d2e4dc3025005c8efd907a86932",
          "md5": "4018c10e9d2281dac02c8010c69b37e3"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-io-tvossimulatorarm64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-io-tvossimulatorarm64-3.1.2-SNAPSHOT-sources.jar",
          "size": 56548,
          "sha512": "364038ace161ec52a09197938119b0e73db218a93a1531782e02524f74d617e202fb44d2fa667dac70a6edb738e1434a9f2be2bad908457fbec768fe39369418",
          "sha256": "da359d7f7d8476b066b11d77ae77ba9e39e3ff82679d7fc65fe6a90ddc50af29",
          "sha1": "0f58bd7e7edc9d63c3afb7b9853bfeb0557a95a1",
          "md5": "ccf496779c326b304985c149c99b138b"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-io-tvossimulatorarm64-3.1.2-SNAPSHOT-metadata.jar",
          "url": "ktor-io-tvossimulatorarm64-3.1.2-SNAPSHOT-metadata.jar",
          "size": 32815,
          "sha512": "913c8030c98157afdf25ba8625a56624f4e8f9832c03e32955785bd122f1c1f97c2357055c7462a32303c8c483c6b7f272ee6130b18b3c9bc41971b81f8849c5",
          "sha256": "7e1b7738c3937aab6339155820fc5ca7fa4d0bc6db0842c0ba58bc37c44794c7",
          "sha1": "2cb1cf79c4200133b86518334e55960d7a758d5c",
          "md5": "23a3e31c23add9ebacd6091d59296813"
        }
      ]
    }
  ]
}
