{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-client-serialization/3.1.2-SNAPSHOT/ktor-client-serialization-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-client-serialization",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-json",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-serialization-mingwX64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-client-serialization-mingwx64-3.1.2-SNAPSHOT.klib",
          "size": 14254,
          "sha512": "3de86e371e777e74265472377641e488ad7411d6b0976cc926c0f41e9c6fb1b37052ebb7e8d2735102c018eddb9536dd8dcb199adc73cd9b82d9d473f4673974",
          "sha256": "6c54bf310a62a1e71c197276e31a43759b4c53ffdfa4bbcad0aae9763aa25ba0",
          "sha1": "bc09e8667da6009eb9613e199b48ba712e406f54",
          "md5": "1280eaf88ddefe849bfd5c8255ab0997"
        }
      ]
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-client-serialization-mingwx64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-client-serialization-mingwx64-3.1.2-SNAPSHOT-sources.jar",
          "size": 3394,
          "sha512": "eea49ae1a94a5d00db16695a67180ed24f798e17c2c81504c3e2dcd90db917049269f10755edd6def16aa2e5aed2522d8217075c379d1aeeb680a037487e04f5",
          "sha256": "9f9285d261c3855649a0c4514451321a043edcafa3489c64e61ee0f2388f63d3",
          "sha1": "216426f0558308f7c9c460f10e29ee50bb4feca8",
          "md5": "a739bed8bcf9bb4951030df82e403d35"
        }
      ]
    }
  ]
}
