{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-request-validation/3.1.2-SNAPSHOT/ktor-server-request-validation-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-server-request-validation",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-request-validation-linuxX64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-request-validation-linuxx64-3.1.2-SNAPSHOT.klib",
          "size": 17132,
          "sha512": "91dde52ef72cf441995963ba7ef9179f1ca36e4e20a994e8a673d01f4d682c9e60167c3e7922485fa30f973a05a61cbb64c5e7f3624b754fa739d01997985eeb",
          "sha256": "9052ae9c945c38efda547032a41b7c9f259e0c090e49bcf3e2168e4f38d68a71",
          "sha1": "c86fef3b75355a613c66f966ea6539a14252a32d",
          "md5": "5115aafbb19606b0e22519dfadab867e"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-server-request-validation-linuxx64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-server-request-validation-linuxx64-3.1.2-SNAPSHOT-sources.jar",
          "size": 3915,
          "sha512": "29fcbe444f845595152fc5b8ececdfc55a7730f0511addb49420407152e14dd73b7d7c9637cd2798b93e0afd295b3ac1f00f787341c3528604501fdf03040a1c",
          "sha256": "00b4640b67a99489554b5944bf4a62742a2a58815298d32eb2a14e22f9572660",
          "sha1": "479e7626d150c49eac816b296b91ce2593cf20f7",
          "md5": "11c93c5d61e36d931515d34fa0f4726b"
        }
      ]
    }
  ]
}
