{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-client-auth/3.1.2-SNAPSHOT/ktor-client-auth-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-client-auth",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-auth-watchosX64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-client-auth-watchosx64-3.1.2-SNAPSHOT.klib",
          "size": 53511,
          "sha512": "2f181f8fcceddc2761cef5cdabaa4ae96ad6c9050584e806b6a240bd53d99c6b5a1db077fc255e3c8e14856243af92014661c00d6669fe28716ea2eae2b23959",
          "sha256": "c8a214cb626c6320cb1518a76a0b573d0abd2e0cf7c38bb98c62a54e15cec5cc",
          "sha1": "4e41b252728d58d3b6309b746a0eb7272315f2d6",
          "md5": "5da95838c879170bfd3456708dd0d20a"
        }
      ]
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-client-auth-watchosx64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-client-auth-watchosx64-3.1.2-SNAPSHOT-sources.jar",
          "size": 12670,
          "sha512": "565278687b8b7d6d0f81174a538e3e36bec2abc6aae7e78283d0afc83759396844cf5d8c19c815bc0e43b87aa0523a92c06107eb6d310400f13ab25534298066",
          "sha256": "d547799a79c9a25bae79fa8ac8322a7eb5a6f44867f2be7a925bf9d4a894f922",
          "sha1": "7425b17152bc668e37ee3e15c572de3d4d5ac339",
          "md5": "b6d07b98246acd355ac78681c561888d"
        }
      ]
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-auth-watchosx64-3.1.2-SNAPSHOT-metadata.jar",
          "url": "ktor-client-auth-watchosx64-3.1.2-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "5d1e3c751d0660a6003b5ccb7c56db0bd1f801be3761a16f65745aba2ec60dd4ff74fdf7c58300b7f72258b5ed0b0487ac3c0a79f97b1c2688865c9fd788397d",
          "sha256": "502ba5268d28aba518d921644fb006532d37033563b5baff94ebdc789c82c877",
          "sha1": "64d39f469e71db060698900161c8a0c1e2a374f0",
          "md5": "e04dbf3fe4027abb7050991eae2a4d25"
        }
      ]
    }
  ]
}
