{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-client-websockets/3.1.2-SNAPSHOT/ktor-client-websockets-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-client-websockets",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-websockets-iosSimulatorArm64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-client-websockets-iossimulatorarm64-3.1.2-SNAPSHOT.klib",
          "size": 3799,
          "sha512": "80d029f576c60905b811e62ed00afdcb364e7a71cb84b82c15ac4ea4b14515121d78facc909226c0b980236d5fddd618c0caebd7dae05ea5290bf379d6b1d06b",
          "sha256": "b2ff7ce0e529a7630c6721c81bd5c673099850a0f1d74ab8a44fc4dab49bd36d",
          "sha1": "0e01f8956b94fe04f69f7a6fee112c1f33d350d2",
          "md5": "c736e7064ee9e01cee837846e7af8129"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-client-websockets-iossimulatorarm64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-client-websockets-iossimulatorarm64-3.1.2-SNAPSHOT-sources.jar",
          "size": 666,
          "sha512": "650a692ac4cd6f78ef41dae8b3a928357b0dac4f313bbf08f31fecf8548ddd8c4fe65d1cfadad9d09c0e597190e6a4be0d09a2ef04af2796d783e73343592b25",
          "sha256": "75d7ca238e3c1dd7fcc8929934521558abe14de2c3643766b9354b61fb8af5b6",
          "sha1": "d2442500ed8df341322651a00b716cf873a2373d",
          "md5": "65de3258033d8237cefbef68a927643d"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-websockets-iossimulatorarm64-3.1.2-SNAPSHOT-metadata.jar",
          "url": "ktor-client-websockets-iossimulatorarm64-3.1.2-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "29bae3c9cb2f44f910f464e62844a5004c581cee218f371cd41836720c6c3af111cb549231245db8a54f34cbc3018e95c366b38b3d8a22230f64ae953a084651",
          "sha256": "c63f6304fc1564dd08ad69d1c87fa06ac7a88020b2fb1e5409d4702f462a1481",
          "sha1": "83244a14e3453ce135e0e4014ab09c9bccacca05",
          "md5": "fd7a39622a907d91152f497039703479"
        }
      ]
    }
  ]
}
