{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-http-cio/3.1.2-SNAPSHOT/ktor-http-cio-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-http-cio",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-io",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-http-cio-wasm-js-3.1.2-SNAPSHOT.klib",
          "url": "ktor-http-cio-wasm-js-3.1.2-SNAPSHOT.klib",
          "size": 130871,
          "sha512": "a7196dbcd24bdcc718a7836566a4658947ec711a9307812b3cf15deaee1c7513f916ffe8438a4fb9feafcce239d191f0674bfaca1b773caf26bbceac139a2026",
          "sha256": "56b844f927b8742ac7de004399b1a94d001ab14bf724ef4127c2362f59350382",
          "sha1": "939715dc33e9469a0fae16d18b1303ef450d3e34",
          "md5": "43e64f49f776afdfc8bef897337d97ce"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-io",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-browser",
          "version": {
            "requires": "0.3"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-http-cio-wasm-js-3.1.2-SNAPSHOT.klib",
          "url": "ktor-http-cio-wasm-js-3.1.2-SNAPSHOT.klib",
          "size": 130871,
          "sha512": "a7196dbcd24bdcc718a7836566a4658947ec711a9307812b3cf15deaee1c7513f916ffe8438a4fb9feafcce239d191f0674bfaca1b773caf26bbceac139a2026",
          "sha256": "56b844f927b8742ac7de004399b1a94d001ab14bf724ef4127c2362f59350382",
          "sha1": "939715dc33e9469a0fae16d18b1303ef450d3e34",
          "md5": "43e64f49f776afdfc8bef897337d97ce"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "ktor-http-cio-wasm-js-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-http-cio-wasm-js-3.1.2-SNAPSHOT-sources.jar",
          "size": 28066,
          "sha512": "16a8438754abc4ef1c7fe35bb3bcbe50ad90f6c7e7ef54ad39f54611665b083659e220c95421619d7601db2c71e6612538fe2721c768b24134d8e5c43f160a60",
          "sha256": "4008d55c9472834a507c5dfbe0ddf1e111be9622155b813e4f80dacf57133e43",
          "sha1": "c1ed4daea496b8f1c4146a9427d912470d8528b8",
          "md5": "33afe9b6d0c368159b51b8d5d77eb7ae"
        }
      ]
    }
  ]
}
