{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-serialization-kotlinx-protobuf/3.1.2-SNAPSHOT/ktor-serialization-kotlinx-protobuf-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-serialization-kotlinx-protobuf",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-serialization-kotlinx",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-protobuf",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-serialization-kotlinx-protobuf-macosX64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-serialization-kotlinx-protobuf-macosx64-3.1.2-SNAPSHOT.klib",
          "size": 5233,
          "sha512": "53a2d63fb5f3c8d739c5232911a541cd9cb180bb745fcbb2734d7203245363ed48dc4c982fed273e3835678e3ec32546fdc0c4bf08af2e557016e0ff8456303d",
          "sha256": "14a1983253c45daa25b49bea4af3d9e42f48be15452d341e5045a727d44cf4a5",
          "sha1": "5133adac39687ea7cb7f0608c0991b53b33dc175",
          "md5": "f581f852e7d5919a67430221a2a88c82"
        }
      ]
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-serialization-kotlinx-protobuf-macosx64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-serialization-kotlinx-protobuf-macosx64-3.1.2-SNAPSHOT-sources.jar",
          "size": 1883,
          "sha512": "ccd4a4956796e1a9fc47ac2c6a00a0def3ae5e0196b9713b68b6d2683bcc0a9e1a8b3e8b0563d5ef9afceb7c611f83331bdd8c395f00f81e79839b0446ad6006",
          "sha256": "288e80b0ef85987639a638f55e01003c702d465d5f4eb4190ad40fa21068c719",
          "sha1": "eb22a47313447a98eb7fa43797da478ebd732a97",
          "md5": "ed9f6db16d0e72c9875230e24cef0358"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-serialization-kotlinx",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-protobuf",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-serialization-kotlinx-protobuf-macosx64-3.1.2-SNAPSHOT-metadata.jar",
          "url": "ktor-serialization-kotlinx-protobuf-macosx64-3.1.2-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "68dda16e0fbbd6b871aca24e7bf998c3fac0ec0f1a90f8db0a978a2f2644ace561160164d0ec58ad5cba19b1cf9e67a042725e6b6d18da7193a500a9724aa552",
          "sha256": "43d2fa780c25ed1539611d140e469f6b41c24e275002cf62e0f951bd871450dd",
          "sha1": "c2956241dc0a2e5a7a11bf31bac7560b1861f64e",
          "md5": "97977cd8535ec2ffe7bb06480bc501a8"
        }
      ]
    }
  ]
}
