{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-sse/3.1.2-SNAPSHOT/ktor-sse-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-sse",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-utils",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-sse-tvosArm64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-sse-tvosarm64-3.1.2-SNAPSHOT.klib",
          "size": 12192,
          "sha512": "f0d664214465b11d836253c194bc635a8c80b29563d6f378400fc0c584950353bd418b2f0b7b8c640ff379403d1351051bbf1075117b38599c251e87f6ed0443",
          "sha256": "db125aa4a830acc040b3a93dc886c8e3e9ab082822f4fbcd6d27cafc1465f033",
          "sha1": "e16770f7f61af33779d89fee40cec2b9769431e8",
          "md5": "436096b1468cab15c65cbf6c5b330a92"
        }
      ]
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-sse-tvosarm64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-sse-tvosarm64-3.1.2-SNAPSHOT-sources.jar",
          "size": 1802,
          "sha512": "41429733cbafadd03cbb1831acf3e488832be89324942330849c333c39b46801d273bd1cc324d90db2cdc5ab1e3ab7acfe37552d2c3d6bcf4d60d07eddd7dc1a",
          "sha256": "c68c47d49e1faab58785b6646363a0c634e641c866c7030edc3f44be4c85ec9c",
          "sha1": "ceaf6f378fa7c0005625aff6a95e975bcea932e5",
          "md5": "0d6f9b4c42ca260589a9cc8387193271"
        }
      ]
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-utils",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-sse-tvosarm64-3.1.2-SNAPSHOT-metadata.jar",
          "url": "ktor-sse-tvosarm64-3.1.2-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "82b376efb1ef1489e39dd1c2e4d7a9b736554181221db493daabe103e0724886e05d37424e81842c49b265992ce31f9053c2579a1f6e7706fccc29fb9a532746",
          "sha256": "c8fdbbe6c0e54e8e555b492facf469b592652a192bcd9f67048c95777f0f8feb",
          "sha1": "a21aaf59e085f03cc25f07fd94bcab40b465126c",
          "md5": "35c8a6ceb46e43d32453cc2563b9815e"
        }
      ]
    }
  ]
}
