{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-utils/3.1.2-SNAPSHOT/ktor-utils-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-utils",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-io",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-utils-iosSimulatorArm64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-utils-iossimulatorarm64-3.1.2-SNAPSHOT.klib",
          "size": 303937,
          "sha512": "7496ad11e5b97c6776e1860fccc61e2f9cf32a005c86baa8018fd2abf6396449b6403ac864f9c8105b03753c4d37ab8b637c53a3f3339a5464f28e1773928117",
          "sha256": "dc01fa11a87f281008ffccdb77a3c49dd3c39150eaeba278757c99f2cde8cf6e",
          "sha1": "86f796618a70d0ba27e9506beddead5907859e9b",
          "md5": "af71714f913cff9bc2fae34ed4eadab6"
        },
        {
          "name": "ktor-utils-iosSimulatorArm64Cinterop-threadUtilsMain-3.1.2-SNAPSHOT.klib",
          "url": "ktor-utils-iossimulatorarm64-3.1.2-SNAPSHOT-cinterop-threadUtils.klib",
          "size": 6935,
          "sha512": "cbb2097408df7c8770708581d0ecd1477ef91af1bde3532fdd483d23a0dddcd25a2a9055a21991e10a3a8f0f942356dcf24d12228b0df0929e982a2d4b667286",
          "sha256": "78cce71648ad17e34a276f89ac5c5da8e3cf6327ce13cda30c865983f31d0d98",
          "sha1": "d0ef168669b181564ba7f99c2fb5108965759a5f",
          "md5": "e166fe67c9622a90ae260750de6a1144"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-utils-iossimulatorarm64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-utils-iossimulatorarm64-3.1.2-SNAPSHOT-sources.jar",
          "size": 79276,
          "sha512": "2577dd5624fef52f225bf2bbe72ca11ddb97901eced70d30a79567709158928483bd490a0ca5e90b9b14c98f413a061dbbcddf30222a1c2e9a92ec382f414bc2",
          "sha256": "d70693069dceeac71482dc21a956fff610ae652a609cc4e195fc0059ce882aac",
          "sha1": "bd61f9bf0c441895db38ae51c3e9f4b6dcafc5d5",
          "md5": "614485d73f17d9599e31b5ed5be3c445"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-io",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-utils-iossimulatorarm64-3.1.2-SNAPSHOT-metadata.jar",
          "url": "ktor-utils-iossimulatorarm64-3.1.2-SNAPSHOT-metadata.jar",
          "size": 17505,
          "sha512": "bcc9e2805de9043de437b62f7aad683a7bd2ad393961dde86f6667ff50bf286d7c1f776d1e328a8f6eb2fe03accd891b801085bbd657736cd1e3a2faee256a70",
          "sha256": "46bcfe6a93a21e1221129ce9d9ac4176790a4a629edae97f0f58bfedfee38a5c",
          "sha1": "1a79ec8309fb531e6340dafd632f73f99baef452",
          "md5": "86d3a198ef6f83c19afdad186a2cf0b9"
        }
      ]
    }
  ]
}
