{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-client-websockets/3.1.2-SNAPSHOT/ktor-client-websockets-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-client-websockets",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-websockets-jvm-3.1.2-SNAPSHOT.jar",
          "url": "ktor-client-websockets-jvm-3.1.2-SNAPSHOT.jar",
          "size": 1908,
          "sha512": "cda118e218edaccd03f429337ae36c839d84e1c5ecf3ac45ce223932ca9814054108ee285de7d92f035137b88f49e3d6683331ab72e53d3b80b4c392c80163ea",
          "sha256": "07f7b0babaf8616dcbcba5886e700d9ee68713897d10301e5c0c2bd6c95f7991",
          "sha1": "5f06afcb8a478932893846cd524d3f662ac49b44",
          "md5": "e7ba8d88e7651629bc3286a43017898d"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-websockets-jvm-3.1.2-SNAPSHOT.jar",
          "url": "ktor-client-websockets-jvm-3.1.2-SNAPSHOT.jar",
          "size": 1908,
          "sha512": "cda118e218edaccd03f429337ae36c839d84e1c5ecf3ac45ce223932ca9814054108ee285de7d92f035137b88f49e3d6683331ab72e53d3b80b4c392c80163ea",
          "sha256": "07f7b0babaf8616dcbcba5886e700d9ee68713897d10301e5c0c2bd6c95f7991",
          "sha1": "5f06afcb8a478932893846cd524d3f662ac49b44",
          "md5": "e7ba8d88e7651629bc3286a43017898d"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ktor-client-websockets-jvm-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-client-websockets-jvm-3.1.2-SNAPSHOT-sources.jar",
          "size": 666,
          "sha512": "650a692ac4cd6f78ef41dae8b3a928357b0dac4f313bbf08f31fecf8548ddd8c4fe65d1cfadad9d09c0e597190e6a4be0d09a2ef04af2796d783e73343592b25",
          "sha256": "75d7ca238e3c1dd7fcc8929934521558abe14de2c3643766b9354b61fb8af5b6",
          "sha1": "d2442500ed8df341322651a00b716cf873a2373d",
          "md5": "65de3258033d8237cefbef68a927643d"
        }
      ]
    }
  ]
}
