{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-serialization-kotlinx-protobuf/3.1.2-SNAPSHOT/ktor-serialization-kotlinx-protobuf-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-serialization-kotlinx-protobuf",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "linuxArm32HfpApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm32_hfp",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-serialization-kotlinx",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-protobuf",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-serialization-kotlinx-protobuf-linuxArm32HfpMain-3.1.2-SNAPSHOT.klib",
          "url": "ktor-serialization-kotlinx-protobuf-linuxarm32hfp-3.1.2-SNAPSHOT.klib",
          "size": 5284,
          "sha512": "0a893012b1f7e3a6601695c58a41734d12caa6a64068fbd2e90f7c27383a47cdeefde4d9d17aaea0d868aa7d8ca55ecd8aa439fb93725650665b39dc9c7767bc",
          "sha256": "cf55b2bc954bc26059d750c51a11eb41f0d1a7b54c97021d80f97c355822d12f",
          "sha1": "b0917a62de1a9df4d7f49e95aba52356f2065f14",
          "md5": "be2ba007c31eae76e9081ec63a4e4007"
        }
      ]
    },
    {
      "name": "linuxArm32HfpSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm32_hfp",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-serialization-kotlinx-protobuf-linuxarm32hfp-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-serialization-kotlinx-protobuf-linuxarm32hfp-3.1.2-SNAPSHOT-sources.jar",
          "size": 1883,
          "sha512": "ccd4a4956796e1a9fc47ac2c6a00a0def3ae5e0196b9713b68b6d2683bcc0a9e1a8b3e8b0563d5ef9afceb7c611f83331bdd8c395f00f81e79839b0446ad6006",
          "sha256": "288e80b0ef85987639a638f55e01003c702d465d5f4eb4190ad40fa21068c719",
          "sha1": "eb22a47313447a98eb7fa43797da478ebd732a97",
          "md5": "ed9f6db16d0e72c9875230e24cef0358"
        }
      ]
    }
  ]
}
