{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-client/3.1.2-SNAPSHOT/ktor-client-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-client",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-jvm-3.1.2-SNAPSHOT.jar",
          "url": "ktor-client-jvm-3.1.2-SNAPSHOT.jar",
          "size": 341,
          "sha512": "260ebafda6717cf090508dceae707f40c29358aab85fdf6aeda2e862bdb8a240a6d92571290438fa056161f961895cb086e7937d2def510bda8a34b7348a8d09",
          "sha256": "4bf63c18b63f9c907624bc707a60cabc2e3da41a815f9a71c1e4133b75383395",
          "sha1": "88e29e5b7b51b3dbfd878d2f98f29319dd2da353",
          "md5": "858d6c41c7fd4784c1faae20a4069c9e"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-jvm-3.1.2-SNAPSHOT.jar",
          "url": "ktor-client-jvm-3.1.2-SNAPSHOT.jar",
          "size": 341,
          "sha512": "260ebafda6717cf090508dceae707f40c29358aab85fdf6aeda2e862bdb8a240a6d92571290438fa056161f961895cb086e7937d2def510bda8a34b7348a8d09",
          "sha256": "4bf63c18b63f9c907624bc707a60cabc2e3da41a815f9a71c1e4133b75383395",
          "sha1": "88e29e5b7b51b3dbfd878d2f98f29319dd2da353",
          "md5": "858d6c41c7fd4784c1faae20a4069c9e"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ktor-client-jvm-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-client-jvm-3.1.2-SNAPSHOT-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
