{
  "formatVersion": "1.1",
  "component": {
    "group": "com.vickyleu.kotlinx",
    "module": "kotlinx-rpc-gradle-plugin",
    "version": "0.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlinx-rpc-gradle-plugin-0.6.1.jar",
          "url": "kotlinx-rpc-gradle-plugin-0.6.1.jar",
          "size": 67526,
          "sha512": "86a82ccf0e67ea4f98a2c334f407cb9313fe0e8a4cf20c1938009192b0a9eb67ed41f410a72f893e9990dea379cc2ee4dc47ac2d2ca0de0101eb256dac119445",
          "sha256": "c18abdb6720f346ca512ab1c8f7b1b160bdbc3d2b5c90a73fa8dd013ba7bffed",
          "sha1": "2a2dda9b08460628330c4f131b7f14973f12fe25",
          "md5": "2629eef92ec07a49ab207da06c6aab0f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.protobuf",
          "module": "protobuf-gradle-plugin",
          "version": {
            "requires": "0.9.4"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-rpc-gradle-plugin-0.6.1.jar",
          "url": "kotlinx-rpc-gradle-plugin-0.6.1.jar",
          "size": 67526,
          "sha512": "86a82ccf0e67ea4f98a2c334f407cb9313fe0e8a4cf20c1938009192b0a9eb67ed41f410a72f893e9990dea379cc2ee4dc47ac2d2ca0de0101eb256dac119445",
          "sha256": "c18abdb6720f346ca512ab1c8f7b1b160bdbc3d2b5c90a73fa8dd013ba7bffed",
          "sha1": "2a2dda9b08460628330c4f131b7f14973f12fe25",
          "md5": "2629eef92ec07a49ab207da06c6aab0f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlinx-rpc-gradle-plugin-0.6.1-sources.jar",
          "url": "kotlinx-rpc-gradle-plugin-0.6.1-sources.jar",
          "size": 7337,
          "sha512": "005b2743efdbe7c11428389fe3a7636724669931ca546065c89c6c45a5dffb59d59a1d7ce9c866087cfd2bbc05556f6b02e3385e76ccf678f0db3904ade59171",
          "sha256": "3f8716656a60a400614bb24f825b3e63da7f9146fbd38d3f7b63663038e11ced",
          "sha1": "87d0a0cc3cdca8c9152089d197a8f27de66871e3",
          "md5": "51f17a49396268cba4018ea533fbcc9f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlinx-rpc-gradle-plugin-0.6.1-javadoc.jar",
          "url": "kotlinx-rpc-gradle-plugin-0.6.1-javadoc.jar",
          "size": 261,
          "sha512": "7e88268a6d1488dbc3857903067aa8d2f81bb03fd2ec50318be4fe45645544144b8623606f5b16f6640e5707f8b942d207762de959bc5f6e32d53ea9d26ba4bd",
          "sha256": "682bcb77c4ad3f63877aafe11c22d35d7a35823b58d24e14a802ed25e45df8a4",
          "sha1": "6ef8afc5ccb6dd99301b2f24938ff7b92d49245e",
          "md5": "5970f6f97bbf6808381f9abb67c7f415"
        }
      ]
    }
  ]
}
