{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-test-host/3.1.2-SNAPSHOT/ktor-server-test-host-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-server-test-host",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-test-dispatcher",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-test-host-js-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-test-host-js-3.1.2-SNAPSHOT.klib",
          "size": 71775,
          "sha512": "372637cde1632ee51654708d65e8b2ae64c12d14b64de1565718cb81d5598f482261e184c133256f93623b4d83ba50e94a240481bebb2f60c88d98e37897aa38",
          "sha256": "6f8948ead8181ea91ea0633b35f50348aa84fcf9860481f281593db0d94aea39",
          "sha1": "0b66fc0da2a189c3707e1aefcbb22f2d8c88b73e",
          "md5": "92c4ce760be9e54ff5bf41a3cd544377"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-test-dispatcher",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-test-host-js-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-test-host-js-3.1.2-SNAPSHOT.klib",
          "size": 71775,
          "sha512": "372637cde1632ee51654708d65e8b2ae64c12d14b64de1565718cb81d5598f482261e184c133256f93623b4d83ba50e94a240481bebb2f60c88d98e37897aa38",
          "sha256": "6f8948ead8181ea91ea0633b35f50348aa84fcf9860481f281593db0d94aea39",
          "sha1": "0b66fc0da2a189c3707e1aefcbb22f2d8c88b73e",
          "md5": "92c4ce760be9e54ff5bf41a3cd544377"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "ktor-server-test-host-js-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-server-test-host-js-3.1.2-SNAPSHOT-sources.jar",
          "size": 20577,
          "sha512": "6ca2d4e02f7eba3268edad550b4ce943d58d41b06abddc831ad93f48a08feb6edf31774a87fe80155c5615c8710af6718112665acddd924e7bc377312810940f",
          "sha256": "ea82d11ba6c34dd7b418353304eb21737f0de4483d30afc96733e29a4cedb6ff",
          "sha1": "86eebeffc233d80becac80b7920caa490d74f075",
          "md5": "2b2bf20593b688880eeb5ee853a0499f"
        }
      ]
    }
  ]
}
