{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-client-logging/3.1.2-SNAPSHOT/ktor-client-logging-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-client-logging",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-logging-androidNativeArm64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-client-logging-androidnativearm64-3.1.2-SNAPSHOT.klib",
          "size": 65395,
          "sha512": "40a45251b63b07b480addbfd3ce3426008a0eb5608c1359c455000ada7a959034b4b4555cb651dd970e00bc461445ed6649114e46fb04ba62ff6a9ff757d4586",
          "sha256": "ac55e76578b8472e40930aa171a6af634941e89c2f462dc9da72f57d2191518d",
          "sha1": "8c6b94b7bd795e65f3e01e266e62e3b7e9c62edd",
          "md5": "24cae60bf22a5d38cc9f79fef081e216"
        }
      ]
    },
    {
      "name": "androidNativeArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-client-logging-androidnativearm64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-client-logging-androidnativearm64-3.1.2-SNAPSHOT-sources.jar",
          "size": 12884,
          "sha512": "d6c655e54a0140f79a081c3894fbbed45bb11b789e253bb89da518460ab7bc7a24d7fefe2f09f78e638f9ecab50faf3920b5db7ca2e4ef77614a05ea54dbdb1e",
          "sha256": "c1b5e42a0f62aba40eb6e1b7be3b14b3b8e7a1faed66b70809d20ccf126dab5f",
          "sha1": "7665416d5f350b1f050645318d6d500c49c0771f",
          "md5": "58abd29cbd75848178782c0133745b8c"
        }
      ]
    }
  ]
}
