{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-http-cio/3.1.2-SNAPSHOT/ktor-http-cio-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-http-cio",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-io",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-http-cio-linuxX64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-http-cio-linuxx64-3.1.2-SNAPSHOT.klib",
          "size": 131169,
          "sha512": "45dceba78e056cf0ad0fd3b3e5cfe169aee7104beda939ea1f7140caaad8b17b21e3b50f17cd204f2f49c1838b97234345623c7ea4fa842f80692f8b94492bf7",
          "sha256": "6ee02f9fe3a9e11fa29ca55ed05d7230a148c6ea4c1db267fcbfec47bbe407b9",
          "sha1": "a881b1269c475287d62c2070923e1c0c56cddbed",
          "md5": "37468e71abd8f0fc20c45718ed73b285"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-http-cio-linuxx64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-http-cio-linuxx64-3.1.2-SNAPSHOT-sources.jar",
          "size": 28012,
          "sha512": "eeb1e5f41eaea9d570e2adf80131ce15fdb6ff7b485161e918b5307ddecf61639d983d5085b81afc80570d615410c340633ddf326be4ccf6895cf5949f9037d4",
          "sha256": "354c235d3b5e2c1b658a98372fa714e879f1cc6a7b68ff5e0ad0dbdb8f27a2b9",
          "sha1": "5e1f9da60d6952c974b3958af3c6761c307d2761",
          "md5": "92216b961edd779fabbaea1a5ad7a1a6"
        }
      ]
    }
  ]
}
