{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-sse/3.1.2-SNAPSHOT/ktor-server-sse-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-server-sse",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-sse",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-sse-androidNativeX64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-sse-androidnativex64-3.1.2-SNAPSHOT.klib",
          "size": 23311,
          "sha512": "23b69dc423afd55334d7c59af8d02c0246a2f2cdc435e8a0db1cfe44321f854dc71619f3ee10cf0c347bfb11f26905525732e152fe8b4f457c58e1c13fb5d102",
          "sha256": "8b77ee8990bd47c1019bf6d2b006f6aea6330bab8863b1807efa2d57df045cf1",
          "sha1": "e017ca13b543c441553f456f7e2dd078698b75fc",
          "md5": "1d8f680461fb3284aec7cb1559cd2871"
        }
      ]
    },
    {
      "name": "androidNativeX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-server-sse-androidnativex64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-server-sse-androidnativex64-3.1.2-SNAPSHOT-sources.jar",
          "size": 6935,
          "sha512": "2c60830cbfd64fdfe911bf6596423bf094ca25deaa77cdd05fd9b32fba0e03bf4e182187b3bc49f7841a94bada60934b9c6a726018b3d4b186da30c21572f8bc",
          "sha256": "513c0f6d91cdb398573389889266a510caee1f0b119540317d64758b2f815e87",
          "sha1": "1da279d6d7eaecc69e64e993585290081a3530b5",
          "md5": "f30f88f85270b7ada2d49798e4f33cac"
        }
      ]
    }
  ]
}
