{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-client-content-negotiation/3.1.2-SNAPSHOT/ktor-client-content-negotiation-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-client-content-negotiation",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-serialization",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-content-negotiation-tvosSimulatorArm64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-client-content-negotiation-tvossimulatorarm64-3.1.2-SNAPSHOT.klib",
          "size": 22904,
          "sha512": "0e91ba680efc0f14207b665ed93c7f7192af2337ad5e2fee0437e8697e9eb035cca8df8c7376e20b3057660f5031602ca2e9f0456c2a44522ae697b3d0abf8e2",
          "sha256": "46d83812becd8d3f0d11a8c521119d083ffb7b4e432baf5930fa4b15e123c1cc",
          "sha1": "01c6a22ba66daddabee1d100a3207e2fff7d1cdf",
          "md5": "bf6ef8812e3e678f688e075f89096227"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-client-content-negotiation-tvossimulatorarm64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-client-content-negotiation-tvossimulatorarm64-3.1.2-SNAPSHOT-sources.jar",
          "size": 5541,
          "sha512": "166ecb1486c61188e275e5e7a33d3bcf6f43e048bccafc145e8c9e0a819750065e4ab45cbbee056bdb12ec14cf2c91429becc261925c46a7692df450752c4fa2",
          "sha256": "5787bc15d42038cad551b274b6c88b9672470c408e27db6a035ae1d42e3fdc7f",
          "sha1": "f3c1785f9e9a969fdcb56943e51f8aa05e33aa3b",
          "md5": "d2d8489404addc6f624e366a8b77ef34"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-serialization",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-content-negotiation-tvossimulatorarm64-3.1.2-SNAPSHOT-metadata.jar",
          "url": "ktor-client-content-negotiation-tvossimulatorarm64-3.1.2-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "5d1e3c751d0660a6003b5ccb7c56db0bd1f801be3761a16f65745aba2ec60dd4ff74fdf7c58300b7f72258b5ed0b0487ac3c0a79f97b1c2688865c9fd788397d",
          "sha256": "502ba5268d28aba518d921644fb006532d37033563b5baff94ebdc789c82c877",
          "sha1": "64d39f469e71db060698900161c8a0c1e2a374f0",
          "md5": "e04dbf3fe4027abb7050991eae2a4d25"
        }
      ]
    }
  ]
}
