{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-config-yaml/3.1.2-SNAPSHOT/ktor-server-config-yaml-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-server-config-yaml",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "linuxArm32HfpApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm32_hfp",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "net.mamoe.yamlkt",
          "module": "yamlkt",
          "version": {
            "requires": "0.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-config-yaml-linuxArm32HfpMain-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-config-yaml-linuxarm32hfp-3.1.2-SNAPSHOT.klib",
          "size": 22535,
          "sha512": "fd406b6c169cf32a14b6045adf48240d160c9e73eb5747aa4ec3f2783e745760e7171892697bdda02d387c87ba1a804102aa0f5e4ac9434a0eb7dcf83e0b2863",
          "sha256": "aec3984ac97a97436f44da7b80843f22c3a8cbad8e331f4b38f73e1fbd7f41de",
          "sha1": "d666662609d180ee167dd28ed6128ec5fdcb376a",
          "md5": "ae9c461eff468c6bcb000aee1023b765"
        }
      ]
    },
    {
      "name": "linuxArm32HfpSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm32_hfp",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-server-config-yaml-linuxarm32hfp-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-server-config-yaml-linuxarm32hfp-3.1.2-SNAPSHOT-sources.jar",
          "size": 5329,
          "sha512": "d68e916f46059fc19312ae15f89dfc17e8a6ca898954fb8e0208f1b40828ab4450abe79ee3d8efd3e14dae48007ef19de3f07be7d491d682762aa3fe8bbdcc4c",
          "sha256": "289357a3e424d746e6e9c07c38fcc3eb578c1a0226aa896a07350ab620297275",
          "sha1": "20f198e992dad7fd662a65010cfce5c0b1ae52a3",
          "md5": "d810bb79f92c547396cd093e1b77c622"
        }
      ]
    }
  ]
}
