{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-serialization/3.1.2-SNAPSHOT/ktor-serialization-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-serialization",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-websockets",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-serialization-jvm-3.1.2-SNAPSHOT.jar",
          "url": "ktor-serialization-jvm-3.1.2-SNAPSHOT.jar",
          "size": 22037,
          "sha512": "4aea1d0685ab0d90d93c2096229e08a4f2a46c073a38312859db0a882a587ed1d2936b4ba0855a09102fc146a465b412a6b1986c367765a8698c0b46f1d35e0c",
          "sha256": "17e82f83bd8001c19e04086193d4c50d554f5817bae871801adc445185052010",
          "sha1": "41f67158e2464ea274c86391577858b03b592451",
          "md5": "2e35d92a6ed23633ae9a2f117dc3fbad"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-websockets",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-serialization-jvm-3.1.2-SNAPSHOT.jar",
          "url": "ktor-serialization-jvm-3.1.2-SNAPSHOT.jar",
          "size": 22037,
          "sha512": "4aea1d0685ab0d90d93c2096229e08a4f2a46c073a38312859db0a882a587ed1d2936b4ba0855a09102fc146a465b412a6b1986c367765a8698c0b46f1d35e0c",
          "sha256": "17e82f83bd8001c19e04086193d4c50d554f5817bae871801adc445185052010",
          "sha1": "41f67158e2464ea274c86391577858b03b592451",
          "md5": "2e35d92a6ed23633ae9a2f117dc3fbad"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ktor-serialization-jvm-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-serialization-jvm-3.1.2-SNAPSHOT-sources.jar",
          "size": 3585,
          "sha512": "b4f3ee4444748661cb4af8adb4119570d4b06abb622e7f3926156684e8d70610a7e2422b46dec88ee6d27dbb72f2950d8d6991132d6122042057477ba4b7a098",
          "sha256": "ddc84dd1f279b1c7cd2e476a2b214c1960577116e7abe15c469f8b37fbb46483",
          "sha1": "9947206077a04db4904641c7324fcdc5e5b49ca8",
          "md5": "38a4b496744ca0e47c3a656adb7c0580"
        }
      ]
    }
  ]
}
