{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-partial-content/3.1.2-SNAPSHOT/ktor-server-partial-content-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-server-partial-content",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-conditional-headers",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-partial-content-js-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-partial-content-js-3.1.2-SNAPSHOT.klib",
          "size": 35865,
          "sha512": "68427480b0f29944a917786868de6da38fdccb8704e02b658e588b3a3e679b51450fdbff94584e024b4bd2c7f5cbf4138d0a668079c7c672607f13b90c3f868c",
          "sha256": "d60386e40be1a037a7e26718d9cfccbf3b8ad58cfe338fed1d44f8fb98caaec2",
          "sha1": "c534040421495f9d0603eb56a1618d2f663f3172",
          "md5": "a7ff20deffe7ee72df891c255a85c26f"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-conditional-headers",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-partial-content-js-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-partial-content-js-3.1.2-SNAPSHOT.klib",
          "size": 35865,
          "sha512": "68427480b0f29944a917786868de6da38fdccb8704e02b658e588b3a3e679b51450fdbff94584e024b4bd2c7f5cbf4138d0a668079c7c672607f13b90c3f868c",
          "sha256": "d60386e40be1a037a7e26718d9cfccbf3b8ad58cfe338fed1d44f8fb98caaec2",
          "sha1": "c534040421495f9d0603eb56a1618d2f663f3172",
          "md5": "a7ff20deffe7ee72df891c255a85c26f"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "ktor-server-partial-content-js-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-server-partial-content-js-3.1.2-SNAPSHOT-sources.jar",
          "size": 8479,
          "sha512": "a8c759d02217e3f3e9a3700a6f1c42656e2a23d54cf196be5c1791d51cf2c791151bc3dd20092f50982b45eaa46b21f21e8c08d35189260c09744d31cc87d30e",
          "sha256": "09cf7c4742f17b43abc80e8d3b8c747cd165f79023e47a35d6f6400721a404e5",
          "sha1": "ca387faff2179a65a96e8f8d3c9b5b40d8c92a80",
          "md5": "124c5429e26961d9bf59ab9324336c6c"
        }
      ]
    }
  ]
}
