{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-websockets/3.1.2-SNAPSHOT/ktor-websockets-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-websockets",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-utils",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-websockets-mingwX64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-websockets-mingwx64-3.1.2-SNAPSHOT.klib",
          "size": 80806,
          "sha512": "4dba469e7954ec0e4b6fbe149278483d2402774fb734d0f64d5bf69de49065bbac51db50a7ed41cf95a98a9e1f19295ddc7c2ebb08dc14add7912e957e67a325",
          "sha256": "00a00ad7093ee550f900638a6461eff4435118fbf5a782534849bcaac3ce3fc3",
          "sha1": "2bc73547045c5bc4f6de26b5a6da363c3b30a85b",
          "md5": "537402d946fb7cd92e392cca2bc0d49b"
        }
      ]
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-websockets-mingwx64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-websockets-mingwx64-3.1.2-SNAPSHOT-sources.jar",
          "size": 22517,
          "sha512": "17310a80b992d7521157b511cabede739e63351cf15409a1fe7eab1785aa952834b310d222e546f1df73b6a53fa9a833cb0dfe3a1bf21d7635e85bc3a41c3158",
          "sha256": "1fb0a916b326441833905a3001d9f9ead5cf786aa47fc93ee327da0c046885c4",
          "sha1": "4377deafb26380e886431d1851d2af0c581e57f7",
          "md5": "19f80aad00d806e3fa2f41d27d66c47d"
        }
      ]
    }
  ]
}
