{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-rpc-grpc-core/0.5.1/kotlinx-rpc-grpc-core-0.5.1.module",
    "group": "com.vickyleu.kotlinx",
    "module": "kotlinx-rpc-grpc-core",
    "version": "0.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.vickyleu.kotlinx",
          "module": "kotlinx-rpc-core",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "com.vickyleu.kotlinx",
          "module": "kotlinx-rpc-utils",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-rpc-grpc-core-watchosArm64Main-0.5.1.klib",
          "url": "kotlinx-rpc-grpc-core-watchosarm64-0.5.1.klib",
          "size": 27153,
          "sha512": "2ad530cf0d29aee489ddd3b4f51d8228bc3501d5da08b903f9ba57d95d074f5725a48a2e910a1965a4d0199dfaf7836370e972a078b83eaa78c54836f23a62e4",
          "sha256": "8ea881255a6275d33c4287c349fa5b79a9cf30ae7d2357fedadd11091b370e5b",
          "sha1": "313cc0f14e336fd083ee634c33f6dc416c40e5af",
          "md5": "28f2fd299e202fb82aa413e9db501d1f"
        }
      ]
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-rpc-grpc-core-watchosarm64-0.5.1-sources.jar",
          "url": "kotlinx-rpc-grpc-core-watchosarm64-0.5.1-sources.jar",
          "size": 12685,
          "sha512": "1c028a19fcfe6aa96896f204810f2073d503f0d030843f776c7affbe138fb776ff48e5d6af12a8cd273c3a54c356bc036812279d381c7bab02b5df0cc6f4c4e4",
          "sha256": "5069a1611d0c6a54088696a489c52ca25f1c8783b0271f3c22903cf05dfbce9a",
          "sha1": "ef560803272fe29a47d3260da2b2b1680534a72a",
          "md5": "fc8a57bd8f4e13920a47454c0b84ba7e"
        }
      ]
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.vickyleu.kotlinx",
          "module": "kotlinx-rpc-core",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "com.vickyleu.kotlinx",
          "module": "kotlinx-rpc-utils",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-rpc-grpc-core-watchosarm64-0.5.1-metadata.jar",
          "url": "kotlinx-rpc-grpc-core-watchosarm64-0.5.1-metadata.jar",
          "size": 261,
          "sha512": "a98104e2071bacfd0228f211c7e96fb5456b6cb6b61f76ae5400a669dcfbb88cd6033638bb6f0f461a39aa940a0634eb871f4a8945935c852411ab2262d8e24f",
          "sha256": "a3f3366a72e35894887877d8f217cc988461867edfa95fea44aa1479c1a2053f",
          "sha1": "a3315221d528b0caed80752c0cdeb355e60f77a6",
          "md5": "1f2ad5b7e5c8eceb213508e17b8c7134"
        }
      ]
    }
  ]
}
