{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-client-resources/3.1.2-SNAPSHOT/ktor-client-resources-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-client-resources",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-resources",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-resources-tvosX64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-client-resources-tvosx64-3.1.2-SNAPSHOT.klib",
          "size": 14264,
          "sha512": "6d3c46a2af953a7d6a621546558b714b69057d4c747712ead81538f0f533664af11473a7c675f87e71f739bfe0c76e5e4c63e47202875e2baf1e765cba65dc94",
          "sha256": "7f5915d226df9fd2c2cb4f1cc03d8ade127c7328aa113d1d1750e58bcc429968",
          "sha1": "8d5a84e3550fa3b63d08c1585a7035071b0bf497",
          "md5": "e4714d34d18baf21b7e78d5d7573fbbd"
        }
      ]
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-client-resources-tvosx64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-client-resources-tvosx64-3.1.2-SNAPSHOT-sources.jar",
          "size": 3136,
          "sha512": "706189f301591d972aa8d0ed6392494c089803514a937e2e668ef5ae18fef05f321aae528be5aab14c6fcfb349fdde59e70fd09cd7b097c205c2926e0a2da141",
          "sha256": "def50199f4a4d61ba1815b9a92c095bd40e597c89bb457cc54ac66ba7a913056",
          "sha1": "7956bf2805277930998cb19d49cb0213cac76ee7",
          "md5": "61513bf3a8fa40b702835573d042ac52"
        }
      ]
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-resources",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-resources-tvosx64-3.1.2-SNAPSHOT-metadata.jar",
          "url": "ktor-client-resources-tvosx64-3.1.2-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "db318ac1d96bd7ebce75f12369a7ab94349af34068843eec42087754001094a32dd529552af6c76bf35169f029a777de4f4832c987459e16d95001980fddd7f1",
          "sha256": "8bda73d26474f041d50ffebf84f329352756af286876a7d31e8f7e3646c2bc92",
          "sha1": "0e47d7067ae868219ee180b1701d2f946f10792b",
          "md5": "243eaa913d4457e531787756f5590efa"
        }
      ]
    }
  ]
}
