{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-csrf/3.1.2-SNAPSHOT/ktor-server-csrf-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-server-csrf",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-csrf-linuxX64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-csrf-linuxx64-3.1.2-SNAPSHOT.klib",
          "size": 17884,
          "sha512": "4f3453a8d916a9b40ac02ca98f6adc046f8903e8b10cff3f964c594a5861b78bca11ac01d1eaa8b822c940aaea5dff9c83aefca1f181f7d6ddae0735f9d30f84",
          "sha256": "ac31547483bb307332471eb98817667362786814362598ba47509b6143b9b2e3",
          "sha1": "fc8c08c8dc15dd8186265eca004cf46452b41a71",
          "md5": "e5b8071a710723c808a83697975e9b11"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-server-csrf-linuxx64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-server-csrf-linuxx64-3.1.2-SNAPSHOT-sources.jar",
          "size": 4424,
          "sha512": "60fcb4ddb39380b51f361d616127a8d7b101932a515d97453096add7202c3235d99e8a4258390595bc938c53ac0eff00a01b046ec80ef2257d9504bd8d52b0e5",
          "sha256": "e28717c81150f938ca6cf9b202f3e35d706365758c3f07de4b329ec3f51127de",
          "sha1": "6bb5678adf5d1a517b8ba757b767cd545e028594",
          "md5": "fabc639b295497ce9e8fd186c3468e17"
        }
      ]
    }
  ]
}
