{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-http/3.1.2-SNAPSHOT/ktor-http-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-http",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "linuxArm32HfpApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm32_hfp",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-utils",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-http-linuxArm32HfpMain-3.1.2-SNAPSHOT.klib",
          "url": "ktor-http-linuxarm32hfp-3.1.2-SNAPSHOT.klib",
          "size": 397968,
          "sha512": "39fc1568c7a78df0532196599fa1abfc4a7a89d6918c7a10bab04365b3d0e847b97a1df53c1b039d6467b602e017d29eeb72cad7bfd0c9a37de58eb4a08d11a3",
          "sha256": "14647c7df77f43b96ff52e4809885c736e83a4c800b85ad4b8ae44d830586ebc",
          "sha1": "6d817eafad11c61b9d78e5ac7fe6a34c06ee347c",
          "md5": "58d98ec3d3e5228984878d4d7ff76169"
        }
      ]
    },
    {
      "name": "linuxArm32HfpSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm32_hfp",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-http-linuxarm32hfp-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-http-linuxarm32hfp-3.1.2-SNAPSHOT-sources.jar",
          "size": 88187,
          "sha512": "c643a94f0720cb2d499b38e0c384e929d976b7becbbbe771ebc65852b59bba4c1268c32e52ac06dce1eed64c0b11297170b856619f0df326e698fac5b3a84566",
          "sha256": "3a2ccc35b4cae3370861cf34f506dd2c85af1e4cbd34ff563f1b19efd9f82c36",
          "sha1": "fd340df2b5c3ee4286a2cb8f1860b35a54ebf331",
          "md5": "3ba0cbcd501b20e35666ce00cdb915ea"
        }
      ]
    }
  ]
}
