{
  "formatVersion": "1.1",
  "component": {
    "url": "../../pbandk-runtime/0.16.1-SNAPSHOT/pbandk-runtime-0.16.1-SNAPSHOT.module",
    "group": "com.vickyleu.pbandk",
    "module": "pbandk-runtime",
    "version": "0.16.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.2"
          }
        }
      ],
      "files": [
        {
          "name": "pbandk-runtime.klib",
          "url": "pbandk-runtime-androidnativex86-0.16.1-SNAPSHOT.klib",
          "size": 678459,
          "sha512": "272b400dfc59e1fbcb90cbb2c9b979e9ec27b230e097ce98c0a7718efafba5096e17bc89a8ca21dd1f7a0a85bc22af3e0af3ddf3904b078d754a4f57b4fc16c9",
          "sha256": "e80f7d113619a592572a2e0176d6300853d337960813140b2d722e5243d3924a",
          "sha1": "8e564827b001a384babda87b2cbca1e5dfd4c507",
          "md5": "13d5bb098321a6c227972636da331174"
        }
      ]
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "pbandk-runtime-androidnativex86-0.16.1-SNAPSHOT-sources.jar",
          "url": "pbandk-runtime-androidnativex86-0.16.1-SNAPSHOT-sources.jar",
          "size": 89500,
          "sha512": "036c717c886c7f2c66b568ad3f05a1cb159fa5c07ee64235fbe6c226562682e11c912094acbd57cc82fa03b81919ca35c59763c042e88d3d5c74138950020ff7",
          "sha256": "51e2b29d585dbda1123cca39bc5e65c2495759858466323d67a5c02fd1fb998b",
          "sha1": "4d74b3fac1961c3b7cf671023c4d8af87873ec17",
          "md5": "e33355a59f03ba7232f002d0d24d31e2"
        }
      ]
    }
  ]
}
