{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-rpc-krpc-serialization-cbor/0.5.1/kotlinx-rpc-krpc-serialization-cbor-0.5.1.module",
    "group": "com.vickyleu.kotlinx",
    "module": "kotlinx-rpc-krpc-serialization-cbor",
    "version": "0.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.vickyleu.kotlinx",
          "module": "kotlinx-rpc-krpc-serialization-core",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-cbor",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-rpc-krpc-serialization-cbor-linuxX64Main-0.5.1.klib",
          "url": "kotlinx-rpc-krpc-serialization-cbor-linuxx64-0.5.1.klib",
          "size": 6008,
          "sha512": "e5cc9db7d2eebffdab032502a8ef5cbf6c5e679db77245f63a1407d699a60f75717168c4cbf29e4b0d3959a4488acb031f406ebe35e327d1d9c015a2cf2203d2",
          "sha256": "80513e7fe45b5ab2b7d9df8caa5362551eb4cb9a7badb05d8f83d55dff1e5769",
          "sha1": "ca7cf9f138ddf8ff29711bdb74fd190b75737fe2",
          "md5": "c707060ab4f9f75729e2f20be50b5fa3"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-rpc-krpc-serialization-cbor-linuxx64-0.5.1-sources.jar",
          "url": "kotlinx-rpc-krpc-serialization-cbor-linuxx64-0.5.1-sources.jar",
          "size": 1837,
          "sha512": "e1a38ea3dd9b0bfe95c4f50514efdf90abc77141251c922725b74d64db4aec0dd0a402dc4b3a66f3589deb3f894aaa1857aee02ba6a1d3e67650ffa697f4dfa8",
          "sha256": "408e0301990ed0177e9be4300d03b26199cf1ec08006e2345823d3764afd4ee5",
          "sha1": "8482660a6af8728c37763eb361700b106fc46559",
          "md5": "c49b02ce05e3078bad387bcc627f9214"
        }
      ]
    }
  ]
}
