{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-serialization-kotlinx-xml/3.1.2-SNAPSHOT/ktor-serialization-kotlinx-xml-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-serialization-kotlinx-xml",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-serialization-kotlinx",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "io.github.pdvrieze.xmlutil",
          "module": "serialization",
          "version": {
            "requires": "0.90.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-serialization-kotlinx-xml-watchosArm64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-serialization-kotlinx-xml-watchosarm64-3.1.2-SNAPSHOT.klib",
          "size": 5485,
          "sha512": "3d8100ccc16aaf3366140d056a6323c9aedcbd8e3204f5e9add91ff8b65c8bad5e30a5f60ffbc69f16949263cb7cab634f9a5f5cb4623742fcf3ffbaf4412a00",
          "sha256": "a0710912824358837e876f981858b0600cba986145d7e35803dff5f10acbae13",
          "sha1": "225a3a6828e50753435e2819b136a30d35171300",
          "md5": "43b52a2c44ae22fc73871845da4fdbf5"
        }
      ]
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-serialization-kotlinx-xml-watchosarm64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-serialization-kotlinx-xml-watchosarm64-3.1.2-SNAPSHOT-sources.jar",
          "size": 1979,
          "sha512": "9aeeb7fd7a99a42bb8fc12361313ec8b33177f610db3aefbc58ec4e0e698642dad6c2d2a9d2acd98cc6e72bac7b50790f6102ea9aa95623d490824e787cc1434",
          "sha256": "06d3f51b2b8f577df6d04f8a0bbc5d3653666f1834672941b87734824b2c67e6",
          "sha1": "2d19e6c70429404897b572b2bf182973c645bbec",
          "md5": "3058ef2254c9096c9ab3776df05857ff"
        }
      ]
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-serialization-kotlinx",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "io.github.pdvrieze.xmlutil",
          "module": "serialization",
          "version": {
            "requires": "0.90.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-serialization-kotlinx-xml-watchosarm64-3.1.2-SNAPSHOT-metadata.jar",
          "url": "ktor-serialization-kotlinx-xml-watchosarm64-3.1.2-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "27123f1e26c4255847a640b87f759e140e709cc04b6acf4bf87c2fc93c10cce29754259c1887fde9dd941ed58ffc1e7d35753beb382ca5e4c61627373093b72d",
          "sha256": "a770409be027d2d28049df7a8a400428c51e580b4941a1f426c02bff46b7c8c9",
          "sha1": "83d35969a118468fb8ddcaf04e03956833c9417f",
          "md5": "939a28a8f2fede2711b61fde804aae8e"
        }
      ]
    }
  ]
}
