{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-caching-headers/3.1.2-SNAPSHOT/ktor-server-caching-headers-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-server-caching-headers",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-caching-headers-wasm-js-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-caching-headers-wasm-js-3.1.2-SNAPSHOT.klib",
          "size": 15207,
          "sha512": "d767d0f621be7ae918a5d740cdd1182e4311a5cf3a528af2d23c5c5d9b01b8879e817b2c937f278f5f64dc93677e4e2d00edce52801c1ed693396411ab01d292",
          "sha256": "1b80c36e58e05b8c977a1f61293ff915d89481281fab0e6513860f71b39f9d4b",
          "sha1": "c86af5c923e9ef69137a3347433f35b8022a6d23",
          "md5": "8370e0c8fab0920fa683738c71bbb0eb"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-browser",
          "version": {
            "requires": "0.3"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-caching-headers-wasm-js-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-caching-headers-wasm-js-3.1.2-SNAPSHOT.klib",
          "size": 15207,
          "sha512": "d767d0f621be7ae918a5d740cdd1182e4311a5cf3a528af2d23c5c5d9b01b8879e817b2c937f278f5f64dc93677e4e2d00edce52801c1ed693396411ab01d292",
          "sha256": "1b80c36e58e05b8c977a1f61293ff915d89481281fab0e6513860f71b39f9d4b",
          "sha1": "c86af5c923e9ef69137a3347433f35b8022a6d23",
          "md5": "8370e0c8fab0920fa683738c71bbb0eb"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "ktor-server-caching-headers-wasm-js-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-server-caching-headers-wasm-js-3.1.2-SNAPSHOT-sources.jar",
          "size": 3764,
          "sha512": "58343a5fc9e812f9deb65c82653a1601c3c960ac9435649ff674fa583b5554399be5222884569806c764d597a7689f6164b92fd33f1d2e24d5f8d4bca664475e",
          "sha256": "7e62d7c4439346be094e988839b8dc58b0432f1e8257827dc0e257d536d9982b",
          "sha1": "652163fa0c69e2349eb7e812300555005889109d",
          "md5": "03c222a2c8a458caaaa14bf1046328f9"
        }
      ]
    }
  ]
}
