{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-rpc-krpc-serialization-protobuf/0.6.1/kotlinx-rpc-krpc-serialization-protobuf-0.6.1.module",
    "group": "com.vickyleu.kotlinx",
    "module": "kotlinx-rpc-krpc-serialization-protobuf",
    "version": "0.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.vickyleu.kotlinx",
          "module": "kotlinx-rpc-krpc-serialization-core",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-protobuf",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-rpc-krpc-serialization-protobuf-tvosX64Main-0.6.1.klib",
          "url": "kotlinx-rpc-krpc-serialization-protobuf-tvosx64-0.6.1.klib",
          "size": 6051,
          "sha512": "dd0ded5fa731faf4478fe8338b8ee8761c9bf47a38411917e48e824af7fff96d067e25a79d07641e4a98065d59dfbd57177ec7eb82043e85250b7711fac5e863",
          "sha256": "fd25f9c2612d400d43e15a677ecc8983aacc9a318b0789ab1da6086ed2004912",
          "sha1": "e32d2cb8316f7e31bf6a182a1986a179930529b7",
          "md5": "60c044220aa5cf749d1ddfc23e0b6b81"
        }
      ]
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-rpc-krpc-serialization-protobuf-tvosx64-0.6.1-sources.jar",
          "url": "kotlinx-rpc-krpc-serialization-protobuf-tvosx64-0.6.1-sources.jar",
          "size": 1873,
          "sha512": "e9209f4cf666a4cf8edf6f7fa2532f7658ee28a96d1db5084cfad28bde3eea4abf92ab5d0052fac4af52dbd24ec16ee2498b534fb72da8ca1f8f313d5c52a537",
          "sha256": "cf4fbd9c6889287af2dd983a3d478b0b1e1440e824a93c119c4a1355d069e58c",
          "sha1": "991b37a09103cabb1c76cb78ae3b8128d73f88c1",
          "md5": "d39b8e13e9f676f9ac005fdc9fdd0578"
        }
      ]
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.vickyleu.kotlinx",
          "module": "kotlinx-rpc-krpc-serialization-core",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-protobuf",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-rpc-krpc-serialization-protobuf-tvosx64-0.6.1-metadata.jar",
          "url": "kotlinx-rpc-krpc-serialization-protobuf-tvosx64-0.6.1-metadata.jar",
          "size": 261,
          "sha512": "0c39f3335a38ad496fd8e67ea7c6270326c1eb595f6400d7ac0375924e8c143eb73fc11d5964278f0d25af36f7262c66562d705eb716bf25e7cf9ec2a56072be",
          "sha256": "125f22e17d545e92609f4d50b13da8de326cde01e27b37d1fbf14fd5a5633ba5",
          "sha1": "06cb875c62ffd5ce327fa9a96d6cc9efc67e6114",
          "md5": "275fadfc94394b1908c4f9b6c3771192"
        }
      ]
    }
  ]
}
