{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-client-bom-remover/3.1.2-SNAPSHOT/ktor-client-bom-remover-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-client-bom-remover",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-bom-remover-macosX64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-client-bom-remover-macosx64-3.1.2-SNAPSHOT.klib",
          "size": 10228,
          "sha512": "e7014e4bfb6ea2fdb5c36f029989c63f808677628270e7d0315302609823c3e3d1a17addc418caec78c041e15601a3b2944298d5b759342925cfd8139131a410",
          "sha256": "598ba188f18e09c4b2286e039dc8d2ff0046f66147b534b4d13da762b3b01428",
          "sha1": "4404d52b1269b653783613199caaa34f5c6e763f",
          "md5": "2b649f13fa9ca1575d4ed65d5765c5d2"
        }
      ]
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-client-bom-remover-macosx64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-client-bom-remover-macosx64-3.1.2-SNAPSHOT-sources.jar",
          "size": 2250,
          "sha512": "601d1b60ba994ecee1d35c9029023c73b7150c6dd9ba4144e00013972be24ae7ab903003720c2b7349b0d3bb98041e819e9c70c6ea5bcd5a18af97106c3f2e53",
          "sha256": "5afb89a510b8d286b3287f61e18b9d473f518cb05d09db82a95894bf9d00866e",
          "sha1": "63bf5f9eb5e0c5fe653543ebe814bf5a8d3f37f6",
          "md5": "ef474c89c65a2d83b9ecbef2a413b7c1"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-bom-remover-macosx64-3.1.2-SNAPSHOT-metadata.jar",
          "url": "ktor-client-bom-remover-macosx64-3.1.2-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "ee66636b429c0d715fd337471473d2a061beac193c8b38884a1f49c3976e6be6d93be0ccfae5c78d51ed020c23298b96a22cd841b90bbb7bef03fdb5b4020ffd",
          "sha256": "ca6410e759095b9df817993e6c891c513de0b2a257e2915a59be88cc877c7af2",
          "sha1": "b20bd81d3bfa513a315923a7f52e7c4a7722a158",
          "md5": "1d74e1ee3dc4ecc5897a0abf581c0a82"
        }
      ]
    }
  ]
}
