{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-client-websockets/3.1.2-SNAPSHOT/ktor-client-websockets-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-client-websockets",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-websockets-wasm-js-3.1.2-SNAPSHOT.klib",
          "url": "ktor-client-websockets-wasm-js-3.1.2-SNAPSHOT.klib",
          "size": 3335,
          "sha512": "d7d2ed9caba10451e1f57688b555121dcfd15dececa7e0435b2ed91bc48836d07589134ebb8bd2970d02ee318fe530cdee72a710f58a2b137c5a89834f9804e7",
          "sha256": "2d3e51f7fa47d67a6d79729f56c3ddbb68edbb4ae80145e1768d587e79c8bf59",
          "sha1": "9f1e15640cb84ae536fa921d578889f7093af7f0",
          "md5": "c79b6cdd6ccbe1d8f601d38f32db6237"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-browser",
          "version": {
            "requires": "0.3"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-websockets-wasm-js-3.1.2-SNAPSHOT.klib",
          "url": "ktor-client-websockets-wasm-js-3.1.2-SNAPSHOT.klib",
          "size": 3335,
          "sha512": "d7d2ed9caba10451e1f57688b555121dcfd15dececa7e0435b2ed91bc48836d07589134ebb8bd2970d02ee318fe530cdee72a710f58a2b137c5a89834f9804e7",
          "sha256": "2d3e51f7fa47d67a6d79729f56c3ddbb68edbb4ae80145e1768d587e79c8bf59",
          "sha1": "9f1e15640cb84ae536fa921d578889f7093af7f0",
          "md5": "c79b6cdd6ccbe1d8f601d38f32db6237"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "ktor-client-websockets-wasm-js-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-client-websockets-wasm-js-3.1.2-SNAPSHOT-sources.jar",
          "size": 666,
          "sha512": "650a692ac4cd6f78ef41dae8b3a928357b0dac4f313bbf08f31fecf8548ddd8c4fe65d1cfadad9d09c0e597190e6a4be0d09a2ef04af2796d783e73343592b25",
          "sha256": "75d7ca238e3c1dd7fcc8929934521558abe14de2c3643766b9354b61fb8af5b6",
          "sha1": "d2442500ed8df341322651a00b716cf873a2373d",
          "md5": "65de3258033d8237cefbef68a927643d"
        }
      ]
    }
  ]
}
