{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-call-id/3.1.2-SNAPSHOT/ktor-server-call-id-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-server-call-id",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-call-id",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-call-id-androidNativeX86Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-call-id-androidnativex86-3.1.2-SNAPSHOT.klib",
          "size": 18666,
          "sha512": "0fad863ade4bb4ef75bb67a282090a030534417f35564259438f1dd839b802a66329381c656ebd2aecd917027087083f8e19ec3ddebc13040cae1b9ad24fc933",
          "sha256": "cbc4037e8677c2f98430dcd50741497aeed6c25bd359f2b85f05dd39833d9b78",
          "sha1": "31258e32a16cbe57bccf3436a6830e1623b9af23",
          "md5": "8ea2eacbb75a984270ac26967edf6ee5"
        }
      ]
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-server-call-id-androidnativex86-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-server-call-id-androidnativex86-3.1.2-SNAPSHOT-sources.jar",
          "size": 4479,
          "sha512": "a4324e60c773617e0c4534077cf0af86e3eba25a65638ddffd6cf9c7cceecba4302702a1d6aaee30f71033920c22bc54ec16e39b4c50e33ba40179f3cf71d5fc",
          "sha256": "9b1252ffa010418087fbff88dd1845345773f7fafbafef83f44a80df6ec98d1e",
          "sha1": "060756a9ed48db76942b9d69afa21c8e563a62f5",
          "md5": "5bf555c140d0f68a79d8f10f4b48a167"
        }
      ]
    }
  ]
}
