{
  "formatVersion": "1.1",
  "component": {
    "group": "com.vickyleu.ktor",
    "module": "ktor-server-call-id",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-call-id",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-call-id-metadata-3.1.2-SNAPSHOT.jar",
          "url": "ktor-server-call-id-3.1.2-SNAPSHOT.jar",
          "size": 3837,
          "sha512": "debf302062211f53a83e1f5c2fe5ad3b03101ec20a1b93bf8c11834de196189aa1d56cd615e32893731c37a8fccad85fe265e3e0661181b2419f34412d537a87",
          "sha256": "3e9fec311c3c489fec3e33079bc22dca83376a0f339e1ce1971f39d43a322eea",
          "sha1": "b7f3922d8ad892c95d03ac812711845289904c50",
          "md5": "a0bdfdfdad9098aa878e3e1fd5ecc933"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "ktor-server-call-id-kotlin-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-server-call-id-3.1.2-SNAPSHOT-sources.jar",
          "size": 4479,
          "sha512": "a4324e60c773617e0c4534077cf0af86e3eba25a65638ddffd6cf9c7cceecba4302702a1d6aaee30f71033920c22bc54ec16e39b4c50e33ba40179f3cf71d5fc",
          "sha256": "9b1252ffa010418087fbff88dd1845345773f7fafbafef83f44a80df6ec98d1e",
          "sha1": "060756a9ed48db76942b9d69afa21c8e563a62f5",
          "md5": "5bf555c140d0f68a79d8f10f4b48a167"
        }
      ]
    },
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-call-id-androidnativearm32/3.1.2-SNAPSHOT/ktor-server-call-id-androidnativearm32-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-call-id-androidnativearm32",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-call-id-androidnativearm32/3.1.2-SNAPSHOT/ktor-server-call-id-androidnativearm32-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-call-id-androidnativearm32",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-call-id-androidnativearm64/3.1.2-SNAPSHOT/ktor-server-call-id-androidnativearm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-call-id-androidnativearm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "androidNativeArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-call-id-androidnativearm64/3.1.2-SNAPSHOT/ktor-server-call-id-androidnativearm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-call-id-androidnativearm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-call-id-androidnativex64/3.1.2-SNAPSHOT/ktor-server-call-id-androidnativex64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-call-id-androidnativex64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "androidNativeX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-call-id-androidnativex64/3.1.2-SNAPSHOT/ktor-server-call-id-androidnativex64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-call-id-androidnativex64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-call-id-androidnativex86/3.1.2-SNAPSHOT/ktor-server-call-id-androidnativex86-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-call-id-androidnativex86",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-call-id-androidnativex86/3.1.2-SNAPSHOT/ktor-server-call-id-androidnativex86-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-call-id-androidnativex86",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-call-id-iosarm64/3.1.2-SNAPSHOT/ktor-server-call-id-iosarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-call-id-iosarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-call-id-iosarm64/3.1.2-SNAPSHOT/ktor-server-call-id-iosarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-call-id-iosarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-call-id-iosarm64/3.1.2-SNAPSHOT/ktor-server-call-id-iosarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-call-id-iosarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-call-id-iossimulatorarm64/3.1.2-SNAPSHOT/ktor-server-call-id-iossimulatorarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-call-id-iossimulatorarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-call-id-iossimulatorarm64/3.1.2-SNAPSHOT/ktor-server-call-id-iossimulatorarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-call-id-iossimulatorarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-call-id-iossimulatorarm64/3.1.2-SNAPSHOT/ktor-server-call-id-iossimulatorarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-call-id-iossimulatorarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-call-id-iosx64/3.1.2-SNAPSHOT/ktor-server-call-id-iosx64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-call-id-iosx64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-call-id-iosx64/3.1.2-SNAPSHOT/ktor-server-call-id-iosx64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-call-id-iosx64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-call-id-iosx64/3.1.2-SNAPSHOT/ktor-server-call-id-iosx64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-call-id-iosx64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../ktor-server-call-id-js/3.1.2-SNAPSHOT/ktor-server-call-id-js-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-call-id-js",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../ktor-server-call-id-js/3.1.2-SNAPSHOT/ktor-server-call-id-js-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-call-id-js",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../ktor-server-call-id-js/3.1.2-SNAPSHOT/ktor-server-call-id-js-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-call-id-js",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktor-server-call-id-jvm/3.1.2-SNAPSHOT/ktor-server-call-id-jvm-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-call-id-jvm",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktor-server-call-id-jvm/3.1.2-SNAPSHOT/ktor-server-call-id-jvm-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-call-id-jvm",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktor-server-call-id-jvm/3.1.2-SNAPSHOT/ktor-server-call-id-jvm-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-call-id-jvm",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "linuxArm32HfpApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm32_hfp",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-call-id-linuxarm32hfp/3.1.2-SNAPSHOT/ktor-server-call-id-linuxarm32hfp-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-call-id-linuxarm32hfp",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "linuxArm32HfpSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm32_hfp",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-call-id-linuxarm32hfp/3.1.2-SNAPSHOT/ktor-server-call-id-linuxarm32hfp-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-call-id-linuxarm32hfp",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-call-id-linuxarm64/3.1.2-SNAPSHOT/ktor-server-call-id-linuxarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-call-id-linuxarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-call-id-linuxarm64/3.1.2-SNAPSHOT/ktor-server-call-id-linuxarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-call-id-linuxarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-call-id-linuxx64/3.1.2-SNAPSHOT/ktor-server-call-id-linuxx64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-call-id-linuxx64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-call-id-linuxx64/3.1.2-SNAPSHOT/ktor-server-call-id-linuxx64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-call-id-linuxx64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-call-id-macosarm64/3.1.2-SNAPSHOT/ktor-server-call-id-macosarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-call-id-macosarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-call-id-macosarm64/3.1.2-SNAPSHOT/ktor-server-call-id-macosarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-call-id-macosarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-call-id-macosarm64/3.1.2-SNAPSHOT/ktor-server-call-id-macosarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-call-id-macosarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-call-id-macosx64/3.1.2-SNAPSHOT/ktor-server-call-id-macosx64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-call-id-macosx64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-call-id-macosx64/3.1.2-SNAPSHOT/ktor-server-call-id-macosx64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-call-id-macosx64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-call-id-macosx64/3.1.2-SNAPSHOT/ktor-server-call-id-macosx64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-call-id-macosx64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-call-id-mingwx64/3.1.2-SNAPSHOT/ktor-server-call-id-mingwx64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-call-id-mingwx64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-call-id-mingwx64/3.1.2-SNAPSHOT/ktor-server-call-id-mingwx64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-call-id-mingwx64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-call-id-tvosarm64/3.1.2-SNAPSHOT/ktor-server-call-id-tvosarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-call-id-tvosarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-call-id-tvosarm64/3.1.2-SNAPSHOT/ktor-server-call-id-tvosarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-call-id-tvosarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-call-id-tvosarm64/3.1.2-SNAPSHOT/ktor-server-call-id-tvosarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-call-id-tvosarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-call-id-tvossimulatorarm64/3.1.2-SNAPSHOT/ktor-server-call-id-tvossimulatorarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-call-id-tvossimulatorarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-call-id-tvossimulatorarm64/3.1.2-SNAPSHOT/ktor-server-call-id-tvossimulatorarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-call-id-tvossimulatorarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-call-id-tvossimulatorarm64/3.1.2-SNAPSHOT/ktor-server-call-id-tvossimulatorarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-call-id-tvossimulatorarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-call-id-tvosx64/3.1.2-SNAPSHOT/ktor-server-call-id-tvosx64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-call-id-tvosx64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-call-id-tvosx64/3.1.2-SNAPSHOT/ktor-server-call-id-tvosx64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-call-id-tvosx64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-call-id-tvosx64/3.1.2-SNAPSHOT/ktor-server-call-id-tvosx64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-call-id-tvosx64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../ktor-server-call-id-wasm-js/3.1.2-SNAPSHOT/ktor-server-call-id-wasm-js-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-call-id-wasm-js",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../ktor-server-call-id-wasm-js/3.1.2-SNAPSHOT/ktor-server-call-id-wasm-js-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-call-id-wasm-js",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../ktor-server-call-id-wasm-js/3.1.2-SNAPSHOT/ktor-server-call-id-wasm-js-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-call-id-wasm-js",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-call-id-watchosarm32/3.1.2-SNAPSHOT/ktor-server-call-id-watchosarm32-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-call-id-watchosarm32",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-call-id-watchosarm32/3.1.2-SNAPSHOT/ktor-server-call-id-watchosarm32-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-call-id-watchosarm32",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-call-id-watchosarm32/3.1.2-SNAPSHOT/ktor-server-call-id-watchosarm32-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-call-id-watchosarm32",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-call-id-watchosarm64/3.1.2-SNAPSHOT/ktor-server-call-id-watchosarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-call-id-watchosarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-call-id-watchosarm64/3.1.2-SNAPSHOT/ktor-server-call-id-watchosarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-call-id-watchosarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-call-id-watchosarm64/3.1.2-SNAPSHOT/ktor-server-call-id-watchosarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-call-id-watchosarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "watchosDeviceArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-call-id-watchosdevicearm64/3.1.2-SNAPSHOT/ktor-server-call-id-watchosdevicearm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-call-id-watchosdevicearm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "watchosDeviceArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-call-id-watchosdevicearm64/3.1.2-SNAPSHOT/ktor-server-call-id-watchosdevicearm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-call-id-watchosdevicearm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "watchosDeviceArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-call-id-watchosdevicearm64/3.1.2-SNAPSHOT/ktor-server-call-id-watchosdevicearm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-call-id-watchosdevicearm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-call-id-watchossimulatorarm64/3.1.2-SNAPSHOT/ktor-server-call-id-watchossimulatorarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-call-id-watchossimulatorarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-call-id-watchossimulatorarm64/3.1.2-SNAPSHOT/ktor-server-call-id-watchossimulatorarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-call-id-watchossimulatorarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-call-id-watchossimulatorarm64/3.1.2-SNAPSHOT/ktor-server-call-id-watchossimulatorarm64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-call-id-watchossimulatorarm64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-call-id-watchosx64/3.1.2-SNAPSHOT/ktor-server-call-id-watchosx64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-call-id-watchosx64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-call-id-watchosx64/3.1.2-SNAPSHOT/ktor-server-call-id-watchosx64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-call-id-watchosx64",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-call-id-watchosx64/3.1.2-SNAPSHOT/ktor-server-call-id-watchosx64-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-call-id-watchosx64",
        "version": "3.1.2-SNAPSHOT"
      }
    }
  ]
}
