{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-rate-limit/3.1.2-SNAPSHOT/ktor-server-rate-limit-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-server-rate-limit",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "watchosDeviceArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-rate-limit-watchosDeviceArm64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-rate-limit-watchosdevicearm64-3.1.2-SNAPSHOT.klib",
          "size": 38400,
          "sha512": "e8585143a4c8de2b695e14a6f7cd0473b25014712d6e465efe80d1867cbb6c1632b0050f31ac4afe627d31e34ff9d2d51bdba5fde1a9a8b7b9d46e44e8d68c20",
          "sha256": "66f3a78eb6205367e2db2c976f1871ea3be8f0b3cf4be20d58dde9f9e18089aa",
          "sha1": "1ba11dd1ca0bbaca359f13c332fe4ee54afac9ae",
          "md5": "7d2ba3b71e6959599c723ff443595e2e"
        }
      ]
    },
    {
      "name": "watchosDeviceArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-server-rate-limit-watchosdevicearm64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-server-rate-limit-watchosdevicearm64-3.1.2-SNAPSHOT-sources.jar",
          "size": 8310,
          "sha512": "90d0b0885afa86210770363d2926d6b8d8fce0255977c1b157491828bd52f5d6d056fafa27722b4b268e4b5f658b193213466fc18c3b35063f2135d3328da44f",
          "sha256": "6ed1e53e18b95e4b80292189555fc52b577590d51301183d5552c87236997d8a",
          "sha1": "fe7920800c23b690c2cb98ce7dee355d1617ac3d",
          "md5": "6a8acf20261a1bc905baf9d15bf9257d"
        }
      ]
    },
    {
      "name": "watchosDeviceArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-rate-limit-watchosdevicearm64-3.1.2-SNAPSHOT-metadata.jar",
          "url": "ktor-server-rate-limit-watchosdevicearm64-3.1.2-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "ab46aea64c4b7864169d10f3fb1e53e53a8ceb161a937d5dde14e183f7800c683381295cddad49ef40304dd236fd14cd373b3c97674a153e358cd259b9c06e27",
          "sha256": "be6922bde47ddc88814307b24f54c2147cd8bbd974f3bf5185f29ad9b370a277",
          "sha1": "ccd2a247857f9cd03ae4f3808e70e12eaf585001",
          "md5": "18de08c232ffd72c68eea605403a4a7d"
        }
      ]
    }
  ]
}
