{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-sse/3.1.2-SNAPSHOT/ktor-sse-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-sse",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-utils",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-sse-androidNativeX64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-sse-androidnativex64-3.1.2-SNAPSHOT.klib",
          "size": 12201,
          "sha512": "bb88203c28fca5f2349dc7e6670f8035ed51fcc5677df2b22082608b1ea9f641a1cc497b967fca2609553805fc37f773ed9b66c462086717aa7db87447e90b32",
          "sha256": "4caa9c5882ef7d10755e29edb2ef2a0ea6d071756fa95d09de7e2904b634ccf5",
          "sha1": "8634f7a2f8b59be9e2c278d7339d54938330e339",
          "md5": "a95e3e06989a97808425ee5dfce5129a"
        }
      ]
    },
    {
      "name": "androidNativeX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-sse-androidnativex64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-sse-androidnativex64-3.1.2-SNAPSHOT-sources.jar",
          "size": 1802,
          "sha512": "41429733cbafadd03cbb1831acf3e488832be89324942330849c333c39b46801d273bd1cc324d90db2cdc5ab1e3ab7acfe37552d2c3d6bcf4d60d07eddd7dc1a",
          "sha256": "c68c47d49e1faab58785b6646363a0c634e641c866c7030edc3f44be4c85ec9c",
          "sha1": "ceaf6f378fa7c0005625aff6a95e975bcea932e5",
          "md5": "0d6f9b4c42ca260589a9cc8387193271"
        }
      ]
    }
  ]
}
