{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-client-mock/3.1.2-SNAPSHOT/ktor-client-mock-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-client-mock",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-mock-iosX64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-client-mock-iosx64-3.1.2-SNAPSHOT.klib",
          "size": 19411,
          "sha512": "8da4abcfdd1bca15342d73b4fc6716971a6a608782f9116be14a43490cd26cd16942dca761d15ccbb6188c51cec821603ddcc2bc0bd1b7be187ff56db3810228",
          "sha256": "d5f344d914da3159c5d2991cec04766e49ccb1f8357c9a42d531fef5cf6e447c",
          "sha1": "fa8c5bd40b9732c8d80aeddd1a14cad85d548ebc",
          "md5": "ce876f2e63d1e13b14573360a623440e"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-client-mock-iosx64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-client-mock-iosx64-3.1.2-SNAPSHOT-sources.jar",
          "size": 4335,
          "sha512": "659eae04da34cd1c8342ca545ad5ad774492ddaf211eb0814406ac63196e043340a15ae0798af6c5d3e0fa4c0cb29a1aa7a12cd6def3c94a4fa9c3482788f4ad",
          "sha256": "8c47ed0e7a044a368ee139db4d9e372ab295931b8091fcc6027c6124de8eb7ef",
          "sha1": "7fbff87081316babe6b26a885d2f4d5c4ad4f3b0",
          "md5": "92895bd2f661401e157a3abc4d0b3f11"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-mock-iosx64-3.1.2-SNAPSHOT-metadata.jar",
          "url": "ktor-client-mock-iosx64-3.1.2-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "01b6a8b0f2831d1b5146f43bfd4b7c2d5a834a5d0f361608b858318499a5e3ffc720829c9e14658cc8a6eaf56d61e3f2d204fb1b66c58ebcec7118d462a70c26",
          "sha256": "5018d8c1f7a89836b3e5d1d5adbedd0bec4748c00254f05d9087c2f081d9de95",
          "sha1": "f706e6bf1c377431328285027f63acd33f238264",
          "md5": "488d24719ce5c74f44e4f2fcd050a8a3"
        }
      ]
    }
  ]
}
