{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-conditional-headers/3.1.2-SNAPSHOT/ktor-server-conditional-headers-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-server-conditional-headers",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-conditional-headers-linuxX64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-conditional-headers-linuxx64-3.1.2-SNAPSHOT.klib",
          "size": 12644,
          "sha512": "3fa8acfd17772e4fe76cc891acef447ca886f72751651e2b61e4d80f18d7f0808a9833349227c5eb7a9bbeea5320387f4dc2f84d564b975b680bcd692331b90d",
          "sha256": "e780214396baa6bf96d72009b521e1c48cb3dcb99a3240852db642618034d1d3",
          "sha1": "5f836f8f0ba2955acb45dc92b87cf555d2b6c9da",
          "md5": "39157850af9700d282d2a8250ecdfe10"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-server-conditional-headers-linuxx64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-server-conditional-headers-linuxx64-3.1.2-SNAPSHOT-sources.jar",
          "size": 3012,
          "sha512": "1bc25c28c688d815af04b2a904e0bc529973a4598817dbfc08fa4330286c748d06e169f96998aeda2da5530482d32ec563617c0d869a8d689cb73fd14894526a",
          "sha256": "df404c6f6c0e957120cf20a9aa04255d56a95e7e655dc6f3dac2263c034532ef",
          "sha1": "5a68ff5619ddc990a456b3ae260e49876e042af0",
          "md5": "f73366c4698e40cb75a23709ff53b932"
        }
      ]
    }
  ]
}
