{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-auth-ldap/3.1.2-SNAPSHOT/ktor-server-auth-ldap-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-server-auth-ldap",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-auth",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-auth-ldap-jvm-3.1.2-SNAPSHOT.jar",
          "url": "ktor-server-auth-ldap-jvm-3.1.2-SNAPSHOT.jar",
          "size": 5317,
          "sha512": "dc3629b5957fc7035b59764f0da4a83255aaa6acae98e6a43ecf319c1b4a1d40c226100a2606b677f7931708978c0cd79e1f650fa5840266e4d71ceeb8ccc86e",
          "sha256": "1108a17d07efb918dde997331853a1f28c5d8a699c63b4422a5b92c8c1973cdb",
          "sha1": "c59ee2d63a5d2c2b1fcc2f9f1940322e8cdff42f",
          "md5": "1ec98e825e1c1d165fff27118c060ff6"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-auth",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-auth-ldap-jvm-3.1.2-SNAPSHOT.jar",
          "url": "ktor-server-auth-ldap-jvm-3.1.2-SNAPSHOT.jar",
          "size": 5317,
          "sha512": "dc3629b5957fc7035b59764f0da4a83255aaa6acae98e6a43ecf319c1b4a1d40c226100a2606b677f7931708978c0cd79e1f650fa5840266e4d71ceeb8ccc86e",
          "sha256": "1108a17d07efb918dde997331853a1f28c5d8a699c63b4422a5b92c8c1973cdb",
          "sha1": "c59ee2d63a5d2c2b1fcc2f9f1940322e8cdff42f",
          "md5": "1ec98e825e1c1d165fff27118c060ff6"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ktor-server-auth-ldap-jvm-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-server-auth-ldap-jvm-3.1.2-SNAPSHOT-sources.jar",
          "size": 2549,
          "sha512": "3e3cb409a340d4f0a747b7bd2ca4a8f5a5c36e077663ac50327dd54b4953dcc6c48d81aebe6bfe29e5df564567ae738ec5187e7b7228799191bdbaab43d8d6e4",
          "sha256": "1c8b8814a23558c2c08d4382ad3ff0974da5f285d52bb609598403a1ebe0fddd",
          "sha1": "6919a966603ce171dbee759de087c9d8460655c9",
          "md5": "f464f3625055c4bb90b39febc94d5b6e"
        }
      ]
    }
  ]
}
