{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-test-dispatcher/3.1.2-SNAPSHOT/ktor-test-dispatcher-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-test-dispatcher",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-utils",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-test-dispatcher-watchosArm32Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-test-dispatcher-watchosarm32-3.1.2-SNAPSHOT.klib",
          "size": 5985,
          "sha512": "b2f058c01faadd7092d4dda6d07d40d649a2c545ee96460f4fe597cae00629fd1c133ebd7bfd6b2a7bf7435af405d32de2544ab1a7edbe523d4e61f4adf9eb90",
          "sha256": "df052aa9d1340e54e8c9ce1db0b23a19142a7af3bc55c0b4c00c8b249bed7a1a",
          "sha1": "19c0d8b29b06e0082d5ae80d5f159b87e95d65da",
          "md5": "23c699921d6724e8bd5a0cc943f4756e"
        }
      ]
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-test-dispatcher-watchosarm32-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-test-dispatcher-watchosarm32-3.1.2-SNAPSHOT-sources.jar",
          "size": 1709,
          "sha512": "ac3abfd7db39f52d4cb36aa151c218fdf5edc8030b1c2c6f10f95e5f64f96f2d2d1f3adcfa1152a7f0b014b6768f41fbb956453103dbcac2056a6cf64228e90f",
          "sha256": "cea9fab28f6912c524793f5b574b7d9a1388ccd4b31cc1e843b3569162285527",
          "sha1": "43f9cbe6bf3389e8a12756d365996462d103a724",
          "md5": "a2a060a98587c8a9d7ca1edb432b045c"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-utils",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-test-dispatcher-watchosarm32-3.1.2-SNAPSHOT-metadata.jar",
          "url": "ktor-test-dispatcher-watchosarm32-3.1.2-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "a758e844d9c4dc1fa8701e9d6cf3e0f9efb244b58c7b901bab34b6c5f408e934cb2a7234c473179c06199dcae8da6003564b679e4cd97e1342add87997da09cb",
          "sha256": "82dbe4e14aed1403cc57b9203d5554d89636aca5726e66f5cd46bea4f4bcb02a",
          "sha1": "e1a9b762f3f2026f0d4d0fd8e748e14613fa75bf",
          "md5": "1c8a430648495a4b145e3f5744816fdd"
        }
      ]
    }
  ]
}
