{
  "formatVersion": "1.1",
  "component": {
    "url": "../../pbandk-runtime/0.16.1-SNAPSHOT/pbandk-runtime-0.16.1-SNAPSHOT.module",
    "group": "com.vickyleu.pbandk",
    "module": "pbandk-runtime",
    "version": "0.16.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.2"
          }
        }
      ],
      "files": [
        {
          "name": "pbandk-runtime.klib",
          "url": "pbandk-runtime-androidnativearm32-0.16.1-SNAPSHOT.klib",
          "size": 678508,
          "sha512": "7aa5a989424863f2a165ef367b26a654969d77ecc2ea574c0afcd9ec1ce6a0452597306903228732a090e63e3054afe84fcc820e38fab097aedc19c41a7ede93",
          "sha256": "ab3f12af4d6be0ebeccdb925f71027a24b18c8558da8de0c85d5f7d7e5ef46a3",
          "sha1": "6d87b41a7483fd497adb94020c2cbe3c92a643e4",
          "md5": "4ac40aab91592946c8d3676dbf10a7ee"
        }
      ]
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "pbandk-runtime-androidnativearm32-0.16.1-SNAPSHOT-sources.jar",
          "url": "pbandk-runtime-androidnativearm32-0.16.1-SNAPSHOT-sources.jar",
          "size": 89500,
          "sha512": "036c717c886c7f2c66b568ad3f05a1cb159fa5c07ee64235fbe6c226562682e11c912094acbd57cc82fa03b81919ca35c59763c042e88d3d5c74138950020ff7",
          "sha256": "51e2b29d585dbda1123cca39bc5e65c2495759858466323d67a5c02fd1fb998b",
          "sha1": "4d74b3fac1961c3b7cf671023c4d8af87873ec17",
          "md5": "e33355a59f03ba7232f002d0d24d31e2"
        }
      ]
    }
  ]
}
