{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-request-validation/3.1.2-SNAPSHOT/ktor-server-request-validation-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-server-request-validation",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-request-validation-jvm-3.1.2-SNAPSHOT.jar",
          "url": "ktor-server-request-validation-jvm-3.1.2-SNAPSHOT.jar",
          "size": 25278,
          "sha512": "61ac52a0ea43333caaf46ed42afb8b0ae9966e983fa3aacfc59eebfc78a6598d819f16383a7142308d227596b62bdbbd5ac721f2efed141ed35e25c9fef7c62b",
          "sha256": "8ecb640b3ca63f81d04adf4439a91d34b0d24e55622f92021ed42f54d7e3fc24",
          "sha1": "28792d2206e78544524ac3cb489445a52471d855",
          "md5": "5880ddda8339802c85067af3e4f1ae9a"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-request-validation-jvm-3.1.2-SNAPSHOT.jar",
          "url": "ktor-server-request-validation-jvm-3.1.2-SNAPSHOT.jar",
          "size": 25278,
          "sha512": "61ac52a0ea43333caaf46ed42afb8b0ae9966e983fa3aacfc59eebfc78a6598d819f16383a7142308d227596b62bdbbd5ac721f2efed141ed35e25c9fef7c62b",
          "sha256": "8ecb640b3ca63f81d04adf4439a91d34b0d24e55622f92021ed42f54d7e3fc24",
          "sha1": "28792d2206e78544524ac3cb489445a52471d855",
          "md5": "5880ddda8339802c85067af3e4f1ae9a"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ktor-server-request-validation-jvm-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-server-request-validation-jvm-3.1.2-SNAPSHOT-sources.jar",
          "size": 3915,
          "sha512": "29fcbe444f845595152fc5b8ececdfc55a7730f0511addb49420407152e14dd73b7d7c9637cd2798b93e0afd295b3ac1f00f787341c3528604501fdf03040a1c",
          "sha256": "00b4640b67a99489554b5944bf4a62742a2a58815298d32eb2a14e22f9572660",
          "sha1": "479e7626d150c49eac816b296b91ce2593cf20f7",
          "md5": "11c93c5d61e36d931515d34fa0f4726b"
        }
      ]
    }
  ]
}
