{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-client-websockets/3.1.2-SNAPSHOT/ktor-client-websockets-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-client-websockets",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-websockets-watchosX64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-client-websockets-watchosx64-3.1.2-SNAPSHOT.klib",
          "size": 3731,
          "sha512": "6d9e30869c3de3898e4927decb7deba749f2f1e10125315fd3d8e9f5f6edd0a0aef76c25f0fc90bfc97c7c329282886caa33a3be0a8bb89782834aa140ee8a85",
          "sha256": "b3383598227126e020be2e4eb9e1488adf62dc88cadb79322147bb87cb1bfaaa",
          "sha1": "3ced3facc888327ffd08bd64a00ac450a00c93d5",
          "md5": "07ca51ec3ff847aa6b782e2960dd274d"
        }
      ]
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-client-websockets-watchosx64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-client-websockets-watchosx64-3.1.2-SNAPSHOT-sources.jar",
          "size": 666,
          "sha512": "650a692ac4cd6f78ef41dae8b3a928357b0dac4f313bbf08f31fecf8548ddd8c4fe65d1cfadad9d09c0e597190e6a4be0d09a2ef04af2796d783e73343592b25",
          "sha256": "75d7ca238e3c1dd7fcc8929934521558abe14de2c3643766b9354b61fb8af5b6",
          "sha1": "d2442500ed8df341322651a00b716cf873a2373d",
          "md5": "65de3258033d8237cefbef68a927643d"
        }
      ]
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-websockets-watchosx64-3.1.2-SNAPSHOT-metadata.jar",
          "url": "ktor-client-websockets-watchosx64-3.1.2-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "fe55b821de7868ef36b3b6100d7562d76216a2a566c263181ec354d2489b71a37a97168daef3bd7682d86fa640efda5cdfc98eb5eee5995878992e75e8606450",
          "sha256": "8560e56a51626c595b0225a2bec92a6b22bad5eda9e9691e8a4a49395e010586",
          "sha1": "f5a9733767bc8d45ef5c8adeaacab1804cdd1981",
          "md5": "8be0889f8c837bea30fc526042f4e625"
        }
      ]
    }
  ]
}
