{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-client-call-id/3.1.2-SNAPSHOT/ktor-client-call-id-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-client-call-id",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-call-id",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-call-id-watchosArm64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-client-call-id-watchosarm64-3.1.2-SNAPSHOT.klib",
          "size": 9327,
          "sha512": "9cbca2bc1a69647c6e4196055ec95e14c728ec5cdc005fbfff70438512adb7f68ebad8389fd015a9d9a409b3d1876a479d17fcb21988edfe02596dfe6f6e5fd1",
          "sha256": "0ded2645c83816c1bc155ef6ed16213d780ae30224be08fe5e4a47681413bb33",
          "sha1": "f685f25004e52bbbfb87bbe98ea95d73be571a41",
          "md5": "e2b14396dd3572da429ef26efd1de719"
        }
      ]
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-client-call-id-watchosarm64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-client-call-id-watchosarm64-3.1.2-SNAPSHOT-sources.jar",
          "size": 2506,
          "sha512": "27e738a52f49027777d268ffc9681b6d77bfb24491339d64c40e86f52b923966e14244e25da1b7247549e3d9ec1f2400c67295656cbfaf123e436cebec8af3ca",
          "sha256": "1826e0e98aacdef554a0f28d7652f8ba2c9d5a750ef370030916dde285c5ef58",
          "sha1": "6afdf7bce3ec1ac79956ecd9404c3f826b18cc2f",
          "md5": "c1ad4529a5cb057b40ed86a0ca7440dd"
        }
      ]
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-call-id",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-call-id-watchosarm64-3.1.2-SNAPSHOT-metadata.jar",
          "url": "ktor-client-call-id-watchosarm64-3.1.2-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "7a66e6fb9c971706bd4694068f99d46501b118d5efc5bfad231b21f7583d799c1966171d6a9b98d9721325ab1e46a42d53d4576a20a13a4f64fb20ea9d83d808",
          "sha256": "52755dd976daf928196b594ea19334fae2f2bdff6d70c036c38272f9351a736f",
          "sha1": "abdd36c90d5c46081f991862e98f654e53a2aadc",
          "md5": "212de3753a892eb24ad49f974237c2e4"
        }
      ]
    }
  ]
}
