{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-partial-content/3.1.2-SNAPSHOT/ktor-server-partial-content-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-server-partial-content",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-conditional-headers",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-partial-content-androidNativeX64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-partial-content-androidnativex64-3.1.2-SNAPSHOT.klib",
          "size": 36164,
          "sha512": "0c8ba3fe41b680c93f238bed5686f5aa2563b5efa9899e34aed9c6d8f3e57a79a79cfa4aac42a939b23f7eccfdd30cd2265c8d0d63e0ac6faacb439fa9b4f003",
          "sha256": "b94c3d67e94ff54c9d498fa4b5f965f7c3255b8aeb10c6f075f3316b2378daa7",
          "sha1": "06abbbb8c14dbaf355952efeac519a0f2f3c16bf",
          "md5": "e1e50ce87a8145667c59eb71d197bb1b"
        }
      ]
    },
    {
      "name": "androidNativeX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-server-partial-content-androidnativex64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-server-partial-content-androidnativex64-3.1.2-SNAPSHOT-sources.jar",
          "size": 8313,
          "sha512": "3c28628d36fbacfcadcd9586baca4dcef8281c134056877cd7411f8c370e4835d9b708ef676ac36a37dd3d1bbf6016ff0c735799f8e56a7afebb8314111877a9",
          "sha256": "8953db2e324693cb88dd15a6d61c1121c704668a2e2b4c5dc69d302c233be25a",
          "sha1": "0782c8734fb24bb9bfb88c632667a96147c4702e",
          "md5": "1e7a99ef238ae8ce68ef8a5850b5a114"
        }
      ]
    }
  ]
}
