{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-sse/3.1.2-SNAPSHOT/ktor-server-sse-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-server-sse",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-sse",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-sse-jvm-3.1.2-SNAPSHOT.jar",
          "url": "ktor-server-sse-jvm-3.1.2-SNAPSHOT.jar",
          "size": 35013,
          "sha512": "ac5594d1b6beb0b25ad3aae0f946c0e11661d1d9d9bf3c4d42ca440362a839a2370ae8b9c3af3a6f217abf8d32a744190fb4e094e374f91eb6b530f9b2e59895",
          "sha256": "2e0a3ad0acbc2e1de23a82745f6c162a2689205fb1b8bd1baf7367d37273a485",
          "sha1": "7de8126a6aa15ea5ed871119915b98196c5ba420",
          "md5": "9cdb1ab971f8a4b913e362521f670b66"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-sse",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-sse-jvm-3.1.2-SNAPSHOT.jar",
          "url": "ktor-server-sse-jvm-3.1.2-SNAPSHOT.jar",
          "size": 35013,
          "sha512": "ac5594d1b6beb0b25ad3aae0f946c0e11661d1d9d9bf3c4d42ca440362a839a2370ae8b9c3af3a6f217abf8d32a744190fb4e094e374f91eb6b530f9b2e59895",
          "sha256": "2e0a3ad0acbc2e1de23a82745f6c162a2689205fb1b8bd1baf7367d37273a485",
          "sha1": "7de8126a6aa15ea5ed871119915b98196c5ba420",
          "md5": "9cdb1ab971f8a4b913e362521f670b66"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ktor-server-sse-jvm-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-server-sse-jvm-3.1.2-SNAPSHOT-sources.jar",
          "size": 6935,
          "sha512": "2c60830cbfd64fdfe911bf6596423bf094ca25deaa77cdd05fd9b32fba0e03bf4e182187b3bc49f7841a94bada60934b9c6a726018b3d4b186da30c21572f8bc",
          "sha256": "513c0f6d91cdb398573389889266a510caee1f0b119540317d64758b2f815e87",
          "sha1": "1da279d6d7eaecc69e64e993585290081a3530b5",
          "md5": "f30f88f85270b7ada2d49798e4f33cac"
        }
      ]
    }
  ]
}
