{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-sse/3.1.2-SNAPSHOT/ktor-sse-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-sse",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-utils",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-sse-androidNativeX86Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-sse-androidnativex86-3.1.2-SNAPSHOT.klib",
          "size": 12202,
          "sha512": "b3cebb471ce1d45b09acc54de17af17f8a8857254f529352021aec406ac88b0157c1c96454689c825e373fdaa739da8eaaba1c2c9554a84dcf141d6625f522c5",
          "sha256": "e5becafb57bfd8e2d052cf50072aa518903dfb1a12e163c38c32d96e0192eb99",
          "sha1": "d1d9e279b678cd0cde0612866c04aa71d0d6da2e",
          "md5": "37f249f70742fc4171b590144aa45edd"
        }
      ]
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-sse-androidnativex86-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-sse-androidnativex86-3.1.2-SNAPSHOT-sources.jar",
          "size": 1802,
          "sha512": "41429733cbafadd03cbb1831acf3e488832be89324942330849c333c39b46801d273bd1cc324d90db2cdc5ab1e3ab7acfe37552d2c3d6bcf4d60d07eddd7dc1a",
          "sha256": "c68c47d49e1faab58785b6646363a0c634e641c866c7030edc3f44be4c85ec9c",
          "sha1": "ceaf6f378fa7c0005625aff6a95e975bcea932e5",
          "md5": "0d6f9b4c42ca260589a9cc8387193271"
        }
      ]
    }
  ]
}
