{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-serialization/3.1.2-SNAPSHOT/ktor-serialization-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-serialization",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-websockets",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-serialization-androidNativeArm32Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-serialization-androidnativearm32-3.1.2-SNAPSHOT.klib",
          "size": 12226,
          "sha512": "e018a843123ec7c8098193be09a1f3fb854776d788ef3f305aec77aa89a8512584a79d90fd56b793512e00be4e65fd2d71ac967bf6a4575f860ee427df964209",
          "sha256": "16500ea6e6dd780387134b4a2d5904880e646510c96d8739b24a0734776d01b0",
          "sha1": "dc5c555768d5cfaa74b9a5aa85dd4d06daf7e5aa",
          "md5": "72709ace01b83a7f60d572bbc203f54d"
        }
      ]
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-serialization-androidnativearm32-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-serialization-androidnativearm32-3.1.2-SNAPSHOT-sources.jar",
          "size": 3585,
          "sha512": "b4f3ee4444748661cb4af8adb4119570d4b06abb622e7f3926156684e8d70610a7e2422b46dec88ee6d27dbb72f2950d8d6991132d6122042057477ba4b7a098",
          "sha256": "ddc84dd1f279b1c7cd2e476a2b214c1960577116e7abe15c469f8b37fbb46483",
          "sha1": "9947206077a04db4904641c7324fcdc5e5b49ca8",
          "md5": "38a4b496744ca0e47c3a656adb7c0580"
        }
      ]
    }
  ]
}
