{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-http/3.1.2-SNAPSHOT/ktor-http-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-http",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-utils",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-http-androidNativeX64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-http-androidnativex64-3.1.2-SNAPSHOT.klib",
          "size": 397934,
          "sha512": "903c342760cc1cc33273d697f196a6dd8cea062e7a0bbf63687964609cd048c24558fc6e730440d0ccd8f34382c20975f59a64e69c47379eef35555c2bdff719",
          "sha256": "3b8578d9d477011cbb54a287d35e3e689476abe9b6b302ab2b536ccc589eb778",
          "sha1": "3862aca64d81cc6aaa467f4c26ac84b62721e285",
          "md5": "98ec26559a16dd342ad75d457c80956b"
        }
      ]
    },
    {
      "name": "androidNativeX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-http-androidnativex64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-http-androidnativex64-3.1.2-SNAPSHOT-sources.jar",
          "size": 88187,
          "sha512": "c643a94f0720cb2d499b38e0c384e929d976b7becbbbe771ebc65852b59bba4c1268c32e52ac06dce1eed64c0b11297170b856619f0df326e698fac5b3a84566",
          "sha256": "3a2ccc35b4cae3370861cf34f506dd2c85af1e4cbd34ff563f1b19efd9f82c36",
          "sha1": "fd340df2b5c3ee4286a2cb8f1860b35a54ebf331",
          "md5": "3ba0cbcd501b20e35666ce00cdb915ea"
        }
      ]
    }
  ]
}
