{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-call-id/3.1.2-SNAPSHOT/ktor-call-id-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-call-id",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-call-id-watchosArm32Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-call-id-watchosarm32-3.1.2-SNAPSHOT.klib",
          "size": 5500,
          "sha512": "7575f16d10762394bda7ceeb9a3331f10055ee1d1e0111183c32fbd5f71a800a7cc75e5cd65535a42448f20f85490ef021edf693dad6c99c62bee34803c66f98",
          "sha256": "2a24390bd95f0aede0fd46d8efe85ce801e9bbdb6b07dc3da5831d4a9e51a969",
          "sha1": "2b3efa0474812ea2b1bcd3becfd67bc7b2b4c1d7",
          "md5": "ba72cc1953593ab665410d1b2825279b"
        }
      ]
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-call-id-watchosarm32-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-call-id-watchosarm32-3.1.2-SNAPSHOT-sources.jar",
          "size": 1414,
          "sha512": "65d139b76c81b7698762646c6d7b77f9abdf4d40135f376dc6ef454332adcfdd4e73b4f78f2bb47b496d6091ce0b986ff7b8666900f499350756c86a60627a6f",
          "sha256": "0271d192d924e609c6b5e25de6deba80e6384ed0f4bf8cd2a33b26cd3d52e9dd",
          "sha1": "ff8d4cf17a592129db6fad5ae7e8a64712b75d35",
          "md5": "bc3a005c746c04911cd0981ded54df9e"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-call-id-watchosarm32-3.1.2-SNAPSHOT-metadata.jar",
          "url": "ktor-call-id-watchosarm32-3.1.2-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "b9510ff4d41a9211ec5477e1a5d365d37716db07756e0b55ceee988cb70ee96955d66131f269a118436dfa221268f3af0892fb8adfc555803faa1d965e6fe65e",
          "sha256": "f5e9472d2d6fb3a1cb40015041c1edeb56e2f529785d1c165bce62247f005601",
          "sha1": "bfb9a6b4170f8d036d2fba37a74815c962845065",
          "md5": "d972c3269c989dda098928f308edd4e9"
        }
      ]
    }
  ]
}
