{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-rpc-krpc-core/0.5.1/kotlinx-rpc-krpc-core-0.5.1.module",
    "group": "com.vickyleu.kotlinx",
    "module": "kotlinx-rpc-krpc-core",
    "version": "0.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "com.vickyleu.kotlinx",
          "module": "kotlinx-rpc-core",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "com.vickyleu.kotlinx",
          "module": "kotlinx-rpc-krpc-serialization-core",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "com.vickyleu.kotlinx",
          "module": "kotlinx-rpc-krpc-logging",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-rpc-krpc-core-mingwX64Main-0.5.1.klib",
          "url": "kotlinx-rpc-krpc-core-mingwx64-0.5.1.klib",
          "size": 177014,
          "sha512": "094e6fc9bc28c1e6e382113dd363f5d24f304a49d7376287f4afb697a5536624c58e772190728aae704045999e672f048aa55502a7dee09a98f2e6fcab9629e3",
          "sha256": "808ba934f507e587b887f9ff22bd63406f6e20d49e23bf74ad263679d11a94d2",
          "sha1": "76f66481411bee6f2b82ea22d1128f54f5b62f0c",
          "md5": "3afd92a3a00721407dce0277b73e3fa3"
        }
      ]
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-rpc-krpc-core-mingwx64-0.5.1-sources.jar",
          "url": "kotlinx-rpc-krpc-core-mingwx64-0.5.1-sources.jar",
          "size": 26459,
          "sha512": "52fdb382d7291a2bc9d5e362d5ea9a2ff0cd1bd76adf0b2dfdeb53114fab8d0e0d316af2cc85ff631acce4a4538db11f7dbf4a22ebcd14e309510b0d4d98161e",
          "sha256": "86a7d94c4c3233043df04687f3ee9c39484d9ebbe1730918d785475f1c313b7d",
          "sha1": "01992c0bb8964642d41c4880a8593e1025e2da3e",
          "md5": "8a54de899c290edd1a6b35bf94315c70"
        }
      ]
    }
  ]
}
