{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-client-serialization/3.1.2-SNAPSHOT/ktor-client-serialization-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-client-serialization",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-json",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-serialization-iosX64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-client-serialization-iosx64-3.1.2-SNAPSHOT.klib",
          "size": 14247,
          "sha512": "3f41416f3a73dc71d4d108d3fef59b69cac42a19dbb6fad7b8e41a06ba318fd791abf94f5207ba357aa00512a066f24534b9bcea8bba549cbcc154c2890a6f9c",
          "sha256": "5d42b567f824230033fd232e4e32d8168cb1590a2dee2d497a87d0487d960470",
          "sha1": "411a763ee0a1a68325ff3dc11667c47a675619ea",
          "md5": "9445a7c3fc9c042f256591531a0e087f"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-client-serialization-iosx64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-client-serialization-iosx64-3.1.2-SNAPSHOT-sources.jar",
          "size": 3394,
          "sha512": "eea49ae1a94a5d00db16695a67180ed24f798e17c2c81504c3e2dcd90db917049269f10755edd6def16aa2e5aed2522d8217075c379d1aeeb680a037487e04f5",
          "sha256": "9f9285d261c3855649a0c4514451321a043edcafa3489c64e61ee0f2388f63d3",
          "sha1": "216426f0558308f7c9c460f10e29ee50bb4feca8",
          "md5": "a739bed8bcf9bb4951030df82e403d35"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-json",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-serialization-iosx64-3.1.2-SNAPSHOT-metadata.jar",
          "url": "ktor-client-serialization-iosx64-3.1.2-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "518bd30dd6bad167db471270e83492f0d9d6cc5c4579fdecdbdf8a50f635e004dc76f3532d99353663d681fe17ccb0d42eeed481aa893d3bc7fe52036729f0dd",
          "sha256": "1d3a8c61a8e4ac15be4b68744f337a5d21866d6e3a5d956b4c83a7da3f62075a",
          "sha1": "66c79769dbd6a2340939c4235bd0f4d6705322f9",
          "md5": "cf3ff541be59efde035d78b4dcc380b2"
        }
      ]
    }
  ]
}
