{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-html/0.12.0/kotlinx-html-0.12.0.module",
    "group": "com.vickyleu.kotlinx",
    "module": "kotlinx-html",
    "version": "0.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "linuxArm32HfpApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm32_hfp",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-html.klib",
          "url": "kotlinx-html-linuxarm32hfp-0.12.0.klib",
          "size": 474249,
          "sha512": "879eba196915f1cd1ac6afab4864db4e5253fbfc83d096419eda1fda457168ab8c32a0f3da43b0143cb82990515d4cdabb2dfda711902204c9b217f80138f791",
          "sha256": "72afa787369fba9ebb4508505e850587da0eb8215f823150647eeadfca18143f",
          "sha1": "c63fe5f1ac1fa501ac74f99240d93144e8018f80",
          "md5": "34e6931bfcea5ff5380a30361f5e3d76"
        }
      ]
    },
    {
      "name": "linuxArm32HfpSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm32_hfp",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-html-linuxarm32hfp-0.12.0-sources.jar",
          "url": "kotlinx-html-linuxarm32hfp-0.12.0-sources.jar",
          "size": 55168,
          "sha512": "629a6a5b08800f9382a4df5188ea8e6c413cdb5074b7c4e119f83f165c6243e2f28df27546def18e0e9c2f0bf84e96cf262c8db28d753a990797a10201ee1da2",
          "sha256": "f6a09275546d8ad23d08aaee028fb28a990bb1030d039016633ef618e3ec36a2",
          "sha1": "10527b70184b7ebe1807d471eacb550c98e2e362",
          "md5": "8f2db0811ea4f1b7b0a792845dfdd05d"
        }
      ]
    }
  ]
}
