{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-rpc-grpc-core/0.5.1/kotlinx-rpc-grpc-core-0.5.1.module",
    "group": "com.vickyleu.kotlinx",
    "module": "kotlinx-rpc-grpc-core",
    "version": "0.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.vickyleu.kotlinx",
          "module": "kotlinx-rpc-core",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "com.vickyleu.kotlinx",
          "module": "kotlinx-rpc-utils",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-rpc-grpc-core-tvosX64Main-0.5.1.klib",
          "url": "kotlinx-rpc-grpc-core-tvosx64-0.5.1.klib",
          "size": 27095,
          "sha512": "165e47489e362e1f00682f3919756cac4b6907c5a4e04038330f25b03479fb667a91bce18a364fd4b84e14fb28c49f23ff79ce3380a1d1b12cdca7a06598ee45",
          "sha256": "cedeccbb478557f01cc6fb23309bb06ae309ee9a0d75e6c4802b85f341ce7ba6",
          "sha1": "683c5a615e9cf0939dc1d4e8033d530e2c82b83b",
          "md5": "e853ec5fafc4faf9cdd9ab98e1e08c9f"
        }
      ]
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-rpc-grpc-core-tvosx64-0.5.1-sources.jar",
          "url": "kotlinx-rpc-grpc-core-tvosx64-0.5.1-sources.jar",
          "size": 12685,
          "sha512": "1c028a19fcfe6aa96896f204810f2073d503f0d030843f776c7affbe138fb776ff48e5d6af12a8cd273c3a54c356bc036812279d381c7bab02b5df0cc6f4c4e4",
          "sha256": "5069a1611d0c6a54088696a489c52ca25f1c8783b0271f3c22903cf05dfbce9a",
          "sha1": "ef560803272fe29a47d3260da2b2b1680534a72a",
          "md5": "fc8a57bd8f4e13920a47454c0b84ba7e"
        }
      ]
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.vickyleu.kotlinx",
          "module": "kotlinx-rpc-core",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "com.vickyleu.kotlinx",
          "module": "kotlinx-rpc-utils",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-rpc-grpc-core-tvosx64-0.5.1-metadata.jar",
          "url": "kotlinx-rpc-grpc-core-tvosx64-0.5.1-metadata.jar",
          "size": 261,
          "sha512": "51eb14568047b0a8a7afda88b1fe094895dee2d9d0834605a91932bd60d15b6ad3601d7034e7b294405cad64c768bf90859d9737ca473536024d7d3aa21707bf",
          "sha256": "0a74ee9922c13345a4857803cc7cbd3f458965833bb2f967e5f5963cd3df038c",
          "sha1": "404d77d6f55d13d20f63720557a959436c524ad1",
          "md5": "567d818499d73cbb9ae5d0436999e279"
        }
      ]
    }
  ]
}
