{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-request-validation/3.1.2-SNAPSHOT/ktor-server-request-validation-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-server-request-validation",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-request-validation-watchosX64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-request-validation-watchosx64-3.1.2-SNAPSHOT.klib",
          "size": 17149,
          "sha512": "cdfd445ad5af832674046f50a57e53d982e39ea94ac0dc368d490e331a8d40dae0f4c418b8689dea66b3eb1643ffbe6f3122fd31e97809f8b70b29734948ed4b",
          "sha256": "2c2f9b9389ccf5e1d614a1f9247e35b48d17146c502492996039a0417d223d08",
          "sha1": "a2c349113c6ca4221e8f6ed05c14684e8debf31f",
          "md5": "5f949ba87e0301e5f2e4c31f57e275d6"
        }
      ]
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-server-request-validation-watchosx64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-server-request-validation-watchosx64-3.1.2-SNAPSHOT-sources.jar",
          "size": 3915,
          "sha512": "29fcbe444f845595152fc5b8ececdfc55a7730f0511addb49420407152e14dd73b7d7c9637cd2798b93e0afd295b3ac1f00f787341c3528604501fdf03040a1c",
          "sha256": "00b4640b67a99489554b5944bf4a62742a2a58815298d32eb2a14e22f9572660",
          "sha1": "479e7626d150c49eac816b296b91ce2593cf20f7",
          "md5": "11c93c5d61e36d931515d34fa0f4726b"
        }
      ]
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-request-validation-watchosx64-3.1.2-SNAPSHOT-metadata.jar",
          "url": "ktor-server-request-validation-watchosx64-3.1.2-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "7145a0e5231f399ac240b8d0f89fb958259621dc5f24348605381378a2f21a7a614ac272015b303ee4a66c5540f010ce1003c467a1dd72df5cd0046ffacc9935",
          "sha256": "aecb99d8acb9ecd16ef2b62e4206d4d6851052eb68fe9a03f549f9796696d050",
          "sha1": "52425bba6a33ee5c4256f4f19a44a467a2cf3d7c",
          "md5": "ccd51c2d447a0936448ac25ad99a7851"
        }
      ]
    }
  ]
}
