{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-client-json/3.1.2-SNAPSHOT/ktor-client-json-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-client-json",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "linuxArm32HfpApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm32_hfp",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-json-linuxArm32HfpMain-3.1.2-SNAPSHOT.klib",
          "url": "ktor-client-json-linuxarm32hfp-3.1.2-SNAPSHOT.klib",
          "size": 20970,
          "sha512": "8d0ada0ee45b89807dd0349421e209d9382457ec0eb932fb88f7148f84017974f0f17b0ccd5f04d926e2a47cd0029dd5433f4ce4ea08368b5411fc85d52032b6",
          "sha256": "e46c155f6ce3a8be28bddba156fd626ab2429525dd30a7adaee567204fa8119f",
          "sha1": "e2e678b60ffa4bd5e6fd2eb8a6eb1e7d36a7fe71",
          "md5": "59b2ece0f027f312d81e2c6ebd7b7661"
        }
      ]
    },
    {
      "name": "linuxArm32HfpSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm32_hfp",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-client-json-linuxarm32hfp-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-client-json-linuxarm32hfp-3.1.2-SNAPSHOT-sources.jar",
          "size": 6671,
          "sha512": "0949ac750b6561d37b9726f73d195152834b7bb51d427c75f664bd5e7fc17b4f8d2b58ef3de1a1de3ef8afaee3a5136471d846062d7074bbdd8f83b43c198f4c",
          "sha256": "b19ea5224717044ca8b54efee9a4aefd77bed2442761d68c1c54d0ca88a16172",
          "sha1": "6bfe9d319f114e982e3eeaa18451a07131eab82a",
          "md5": "fa340d1d8eb189f8cb81992a75a7c0dc"
        }
      ]
    }
  ]
}
