{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-body-limit/3.1.2-SNAPSHOT/ktor-server-body-limit-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-server-body-limit",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-body-limit-iosSimulatorArm64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-body-limit-iossimulatorarm64-3.1.2-SNAPSHOT.klib",
          "size": 10657,
          "sha512": "1d50ccdba4d14a28a1f265f574d9ae0cc9657db499ad562c52ebf83feeb83565fce90686c1a05450fe1a9804eb09a785e2e577f21e36f91ecb52d6c59f805088",
          "sha256": "baeb671c1198a8b968cefa6d85052032b74ef4b58a2cfdc80ba269b046ea1af1",
          "sha1": "346d2a6ae69e54e294211c97f088c1d21e88d5f6",
          "md5": "a472f975c0be3816002c3e119c50fa80"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-server-body-limit-iossimulatorarm64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-server-body-limit-iossimulatorarm64-3.1.2-SNAPSHOT-sources.jar",
          "size": 2302,
          "sha512": "1fe49fe1e96d0841045bb151fc8490f761c5c575cb7acad2a5bf076e41e418f7029490236ef35f81dfa0d15187fccb77f80a894aea42ea16b8ed7171b9b2f7a3",
          "sha256": "826cb7e25738122cd5bbc4a6b31bcaea147fd77d806e27211858dc6bc1bc3158",
          "sha1": "407d1eb0bf5b46fac46965247f4f147c5d6ec0fb",
          "md5": "84968e6e84e9497c4ef4155c8e3b5e68"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-body-limit-iossimulatorarm64-3.1.2-SNAPSHOT-metadata.jar",
          "url": "ktor-server-body-limit-iossimulatorarm64-3.1.2-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "4c710234a0196ea39189a64d4f05422a7336ae7f06805d988342d30377055e30e07e32b32529a6fb8c734a659a5ffd7e53127111ec534c1ba80aa6afe1f74f34",
          "sha256": "0ad91c530838a55c584e58976bd52a402785e0ce8977dc12f32695eb54552d07",
          "sha1": "34cd439ac540b083599e7bb25103e5c1c1465c21",
          "md5": "e092a194a260d22905bb88b17e8eeadd"
        }
      ]
    }
  ]
}
