{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-network-tls/3.1.2-SNAPSHOT/ktor-network-tls-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-network-tls",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-network",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-utils",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-network-tls-linuxArm64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-network-tls-linuxarm64-3.1.2-SNAPSHOT.klib",
          "size": 46148,
          "sha512": "bdb94ddabfb24baf3a0bb40da3fb17da2f86362161b8a7d08ced3b67dd98c49ef12d2fb168718a59356cd92d74bbe40d7590314663c3a8f9cc5022a9788f0cfc",
          "sha256": "03cb157b960782b05e022e1c56b9dca06764ccd27ccf53350542cce8c31dd6b9",
          "sha1": "b1ca4583e30c99bc1090b3fba38a4b7d5f3bebdc",
          "md5": "864a865c8543eb5551641b684571a020"
        }
      ]
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-network-tls-linuxarm64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-network-tls-linuxarm64-3.1.2-SNAPSHOT-sources.jar",
          "size": 13552,
          "sha512": "c59b5bc3771060ae1578df061892f94adf516b256e22473a7fc409a44c5f8ef0ced4dabe4d64d45b512193767562c6cc781fa80b240528e60a8999cc0b80ea3b",
          "sha256": "ae935e2b6bce9e926d47fe914396c3fba80b6870f120114096f84e8cc167a417",
          "sha1": "706a588f69e804e863262a38ec6d5b91aeff4965",
          "md5": "87f52d18ed0cc84bc1b7c86d2fbf4d37"
        }
      ]
    }
  ]
}
