{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-body-limit/3.1.2-SNAPSHOT/ktor-server-body-limit-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-server-body-limit",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-body-limit-watchosArm64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-body-limit-watchosarm64-3.1.2-SNAPSHOT.klib",
          "size": 10606,
          "sha512": "0550564a09bb7e0fb4cefdc18b6d4759e68cd1c49e6bab496a437773771b7e616abf75719bee45af50987214b2211747cc531995dabf37d3e5438bad77113e52",
          "sha256": "5f0dcf65bf4914c78e97f3d1c3dcf0d484857b422e73c58f2ba5ab6e38d4feb1",
          "sha1": "0fbdeaad9ff88e2452c3cb227d297981f322ee2c",
          "md5": "4164c28442348efa5e30b3c26885a3c0"
        }
      ]
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-server-body-limit-watchosarm64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-server-body-limit-watchosarm64-3.1.2-SNAPSHOT-sources.jar",
          "size": 2302,
          "sha512": "1fe49fe1e96d0841045bb151fc8490f761c5c575cb7acad2a5bf076e41e418f7029490236ef35f81dfa0d15187fccb77f80a894aea42ea16b8ed7171b9b2f7a3",
          "sha256": "826cb7e25738122cd5bbc4a6b31bcaea147fd77d806e27211858dc6bc1bc3158",
          "sha1": "407d1eb0bf5b46fac46965247f4f147c5d6ec0fb",
          "md5": "84968e6e84e9497c4ef4155c8e3b5e68"
        }
      ]
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-body-limit-watchosarm64-3.1.2-SNAPSHOT-metadata.jar",
          "url": "ktor-server-body-limit-watchosarm64-3.1.2-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "3d3b8b5e80bbae05e59a934eede55d3df9d427fb3ea7314a3820176031e2bc72fc67777d50f8122b283b2f4f2289e464a0e4757a07d992fb6f5aa5541736ec6c",
          "sha256": "5a41cb48ffa862cb8f70e76db42341f22355e9abb11b8a1f7afe1fefc5b2b789",
          "sha1": "f8516b5813686bb93f690ac06c71d5ea61838a5f",
          "md5": "965a0e38d968bd02b38aa1535dba7357"
        }
      ]
    }
  ]
}
