{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-websocket-serialization/3.1.2-SNAPSHOT/ktor-websocket-serialization-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-websocket-serialization",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-serialization",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-websocket-serialization-wasm-js-3.1.2-SNAPSHOT.klib",
          "url": "ktor-websocket-serialization-wasm-js-3.1.2-SNAPSHOT.klib",
          "size": 7014,
          "sha512": "c82bd2268bf8ce798416a96be106baf51cee04bb1e94137a7b080e12157b35e540c2d11c066d24c28076ce5f1feeb299c371e678889dfe3b188323523ad3a72b",
          "sha256": "52b87f760942c3868e036a036ebee7d5768e2e496ca17643fdbd55cfd73a1b72",
          "sha1": "ec7c979cb084cd37f5e6a53e52918903b50135e7",
          "md5": "69ec12434a875c8f56c3aebadbe4fb75"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-serialization",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-browser",
          "version": {
            "requires": "0.3"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-websocket-serialization-wasm-js-3.1.2-SNAPSHOT.klib",
          "url": "ktor-websocket-serialization-wasm-js-3.1.2-SNAPSHOT.klib",
          "size": 7014,
          "sha512": "c82bd2268bf8ce798416a96be106baf51cee04bb1e94137a7b080e12157b35e540c2d11c066d24c28076ce5f1feeb299c371e678889dfe3b188323523ad3a72b",
          "sha256": "52b87f760942c3868e036a036ebee7d5768e2e496ca17643fdbd55cfd73a1b72",
          "sha1": "ec7c979cb084cd37f5e6a53e52918903b50135e7",
          "md5": "69ec12434a875c8f56c3aebadbe4fb75"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "ktor-websocket-serialization-wasm-js-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-websocket-serialization-wasm-js-3.1.2-SNAPSHOT-sources.jar",
          "size": 2326,
          "sha512": "e7fe8c5d0f1bab74755507fcfc8214bec60935736c0dc1ad54f1076115ca58f63d40702f38503b3b2a3b9d8d02ba55b91d62f5d4e326b9bcb5c454859258e3f8",
          "sha256": "e186e6ac4d88ce296ef51d91684444ca0002b4b7761a8dcd2fe55ef1dc8a7b75",
          "sha1": "4a023f031c84e174cfcb56892d01b37de32011e9",
          "md5": "0dca7e417fd69fd93f87b73d37846741"
        }
      ]
    }
  ]
}
