{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-cors/3.1.2-SNAPSHOT/ktor-server-cors-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-server-cors",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-cors-androidNativeX86Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-cors-androidnativex86-3.1.2-SNAPSHOT.klib",
          "size": 43026,
          "sha512": "c103be2f463daf0243016129dc70c5ac35ca4ed7d48b1758db0b9dc4d8aa4a7c9b03d686ab47edb0723bfb19cc69a9b18883172da8615225585558eac5524666",
          "sha256": "5e70530b23c157e42dcfc8fa37a509c2157960463c13495a5fd70e19cf6f9ca6",
          "sha1": "06ee5fb9fd3af5c6b4227e2b655bf6da3f6c52eb",
          "md5": "093d6bb38f9816774594ea30714b4118"
        }
      ]
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-server-cors-androidnativex86-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-server-cors-androidnativex86-3.1.2-SNAPSHOT-sources.jar",
          "size": 9609,
          "sha512": "8341aabbc37f7e16ff43a8770b539a130bc94f427898f7732a089373fc01275319980b3c9174249035ce57904424d5de445224a809c93136e6c944c8d8f9856c",
          "sha256": "a928ddf08065f081c80fd7eef7239722a7d1ffcdc95a383c1cf4307893f210e6",
          "sha1": "137b0080c54c588e426fe682cabe39a34e504472",
          "md5": "2013d1b85fe96d730eea94f4de402b03"
        }
      ]
    }
  ]
}
