{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-rpc-krpc-logging/0.6.1/kotlinx-rpc-krpc-logging-0.6.1.module",
    "group": "com.vickyleu.kotlinx",
    "module": "kotlinx-rpc-krpc-logging",
    "version": "0.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-rpc-krpc-logging-jvm-0.6.1.jar",
          "url": "kotlinx-rpc-krpc-logging-jvm-0.6.1.jar",
          "size": 10202,
          "sha512": "f2171f5336419c18d0bbef0a9c515c2bc139e797c7d474cfe77e0eb47a251464178932502fa0a39deea3e50c1878d8c77f2bf77561673460d8fbf130b5806ccb",
          "sha256": "940be01773fc20eeabca5f65f0518ae8bd10569423a1e03ed05a44728bf2181a",
          "sha1": "b3e46191ef957bfe21add1389051fcaf60d5472e",
          "md5": "db5713235f7301aeacb510dd9bfe570e"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.6"
          }
        },
        {
          "group": "com.vickyleu.kotlinx",
          "module": "kotlinx-rpc-utils",
          "version": {
            "requires": "0.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-rpc-krpc-logging-jvm-0.6.1.jar",
          "url": "kotlinx-rpc-krpc-logging-jvm-0.6.1.jar",
          "size": 10202,
          "sha512": "f2171f5336419c18d0bbef0a9c515c2bc139e797c7d474cfe77e0eb47a251464178932502fa0a39deea3e50c1878d8c77f2bf77561673460d8fbf130b5806ccb",
          "sha256": "940be01773fc20eeabca5f65f0518ae8bd10569423a1e03ed05a44728bf2181a",
          "sha1": "b3e46191ef957bfe21add1389051fcaf60d5472e",
          "md5": "db5713235f7301aeacb510dd9bfe570e"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlinx-rpc-krpc-logging-jvm-0.6.1-sources.jar",
          "url": "kotlinx-rpc-krpc-logging-jvm-0.6.1-sources.jar",
          "size": 3229,
          "sha512": "e36b85fcc5688731538388bf4d650c193949ea6fb9a17be0885307c29e800027e16922a4f3bb122240814a7cdc45fd05cf142be45f7c9387c71bb8ba248abcd0",
          "sha256": "ddd60f836a0fc7a4dee15f2cafb2db9be6467e1edc63431a56e613f9823a801c",
          "sha1": "6f1774cfc2cc5973b8ec30826900eea5cffea0c0",
          "md5": "167be9061aa6d05310bb5855afb440b9"
        }
      ]
    }
  ]
}
