{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-request-validation/3.1.2-SNAPSHOT/ktor-server-request-validation-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-server-request-validation",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-request-validation-linuxArm64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-request-validation-linuxarm64-3.1.2-SNAPSHOT.klib",
          "size": 17149,
          "sha512": "64635a93835a3cdeccae5ea1be6bee2c44cdd3b9f682e3369a34d8dbfb446f6dca9e3fe0f3524ac054ad26aefcb18af1f7c0a51a118200078b050b5678a084db",
          "sha256": "e125f52c1dd9116518ecae6e36e78a25be409ae4a43d3976366c930f81794625",
          "sha1": "e29161fd8cc0b04a7cedb9869f14a849eed45877",
          "md5": "736b0aa05c1325e4336396546bf85f5b"
        }
      ]
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-server-request-validation-linuxarm64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-server-request-validation-linuxarm64-3.1.2-SNAPSHOT-sources.jar",
          "size": 3915,
          "sha512": "29fcbe444f845595152fc5b8ececdfc55a7730f0511addb49420407152e14dd73b7d7c9637cd2798b93e0afd295b3ac1f00f787341c3528604501fdf03040a1c",
          "sha256": "00b4640b67a99489554b5944bf4a62742a2a58815298d32eb2a14e22f9572660",
          "sha1": "479e7626d150c49eac816b296b91ce2593cf20f7",
          "md5": "11c93c5d61e36d931515d34fa0f4726b"
        }
      ]
    }
  ]
}
