{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-client-content-negotiation/3.1.2-SNAPSHOT/ktor-client-content-negotiation-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-client-content-negotiation",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-serialization",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-content-negotiation-macosX64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-client-content-negotiation-macosx64-3.1.2-SNAPSHOT.klib",
          "size": 22810,
          "sha512": "cfcfe4334f01f9f51daecdde47d39d05cff117e5b0809b6f2f2c774d29d8014df1fd622790b6da0839212790823b4442a82f816ca04129085775abd54658187d",
          "sha256": "899f16c9a004541b31bfd89ca82dc7fca9e1f2b1e964c4b2f688a44ea32fdb42",
          "sha1": "4140bab6fed828ce1d7a797a6bc43f5359872963",
          "md5": "2a5147da89aa071a7a113a44fc07b7a8"
        }
      ]
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-client-content-negotiation-macosx64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-client-content-negotiation-macosx64-3.1.2-SNAPSHOT-sources.jar",
          "size": 5541,
          "sha512": "166ecb1486c61188e275e5e7a33d3bcf6f43e048bccafc145e8c9e0a819750065e4ab45cbbee056bdb12ec14cf2c91429becc261925c46a7692df450752c4fa2",
          "sha256": "5787bc15d42038cad551b274b6c88b9672470c408e27db6a035ae1d42e3fdc7f",
          "sha1": "f3c1785f9e9a969fdcb56943e51f8aa05e33aa3b",
          "md5": "d2d8489404addc6f624e366a8b77ef34"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-serialization",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-content-negotiation-macosx64-3.1.2-SNAPSHOT-metadata.jar",
          "url": "ktor-client-content-negotiation-macosx64-3.1.2-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "835bf9b69c5e7a1ad864d7055f1c958f26c0cc0c6bcf6e70ff49ee3c15f938234f2146bf68eb73c349203fc06570cbd4d1269ee9a1ac60473476b4797f3ad0ed",
          "sha256": "c819f0629642e7d656d315d2553fc431b2ea8e4353bf23dddad9b24ca66f52b7",
          "sha1": "614a0846117cc008f94080299bb5fd889693105d",
          "md5": "1e7556022b69794d055c37c4a0352d8a"
        }
      ]
    }
  ]
}
