{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-network/3.1.2-SNAPSHOT/ktor-network-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-network",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "watchosDeviceArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-utils",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-network-watchosDeviceArm64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-network-watchosdevicearm64-3.1.2-SNAPSHOT.klib",
          "size": 150283,
          "sha512": "50cebeace6e30871ad97d3c934f32c2716f1cdeec6ff2ad1605f0b6baf23f99c7d0f8c8ac964320a93af6bb93b978f9df5c0bae1ce898f13b33181d9921c6dab",
          "sha256": "6b9544954fcd42939118815a19c05aaf2dddc35775f3466118b1578d194767bc",
          "sha1": "f894de4080b6d6949e5ec2ad63fdec1de1e5c8a3",
          "md5": "84c9c9b6327be8bf6ae4c3fae2263af8"
        },
        {
          "name": "ktor-network-watchosDeviceArm64Cinterop-networkMain-3.1.2-SNAPSHOT.klib",
          "url": "ktor-network-watchosdevicearm64-3.1.2-SNAPSHOT-cinterop-network.klib",
          "size": 8959,
          "sha512": "1ea851d930bab5e1119dee48d0ca4f4adc6be6b1dfc5ba1ae1f7f77cadd79f58b4badb445ea58bdbfa79590deef29c7767d551915771ea8a7a9688d8c547d037",
          "sha256": "3508ed7e6440f76153de5d41897c28e59c8b8816b5c6aea80dbda6f71ddc9dff",
          "sha1": "85d427d1d8c7c0dda307647fa03b9d27901cc539",
          "md5": "0972d8e540ef2c580ecf66c67079ff46"
        },
        {
          "name": "ktor-network-watchosDeviceArm64Cinterop-unMain-3.1.2-SNAPSHOT.klib",
          "url": "ktor-network-watchosdevicearm64-3.1.2-SNAPSHOT-cinterop-un.klib",
          "size": 6021,
          "sha512": "e07843f51f86a8bd87323adaf3a31282cb83fb9be85a6a5cdd82935d79560f4cd78982700345688c57ecfde7312a67ed4177fef01cf4f9b40cdff9092b598543",
          "sha256": "b26e80cbce812ef963d545dc939374e6d0dcb16a9fcc688d86ab66747741a8f8",
          "sha1": "ec215e7ba223aa8bc2268f402b731b4d3cc8ed32",
          "md5": "3ad852e9a84ed33fb368a874853832d3"
        }
      ]
    },
    {
      "name": "watchosDeviceArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-network-watchosdevicearm64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-network-watchosdevicearm64-3.1.2-SNAPSHOT-sources.jar",
          "size": 43835,
          "sha512": "788ab80c8767e0cc87788e13fb1ec62362cd983c4a815766d0973f64db2f9251f9bd0570fd4b56b9b1e547144e5a3d7bb76f0c62cdb0241c8e3b13ef666a7223",
          "sha256": "dcbaf409b0afa348e9b92f68fa241c05f1cc3878a3cc76f203b813a97bdfe0c8",
          "sha1": "5c8c2c62e3f3ef449ed556125cd8eb5bb7a58371",
          "md5": "b51c88aebcc2332e99c46197b3a452a8"
        }
      ]
    },
    {
      "name": "watchosDeviceArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-utils",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-network-watchosdevicearm64-3.1.2-SNAPSHOT-metadata.jar",
          "url": "ktor-network-watchosdevicearm64-3.1.2-SNAPSHOT-metadata.jar",
          "size": 64049,
          "sha512": "9ac262eec2a8745a641d15066593b8009635157c164031e17bb891cf50d15aac8c899097ee332f7a99a32a7aea00b008afe2ab43913cec76d7be1a04e05fd002",
          "sha256": "f7dd48e4a7e88021118d06d42cff5c2e481cc519bb65ea0f808d9129350dad2c",
          "sha1": "51b65cc865969e948de4b02a7b953480272f45ee",
          "md5": "b6c61d1c1116b595fd4901d75ecd5af4"
        }
      ]
    }
  ]
}
