{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-test-dispatcher/3.1.2-SNAPSHOT/ktor-test-dispatcher-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-test-dispatcher",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-utils",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-test-dispatcher-mingwX64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-test-dispatcher-mingwx64-3.1.2-SNAPSHOT.klib",
          "size": 5941,
          "sha512": "6915e71e34c1deecd4415e93a6046c3bb2b3f8a9837ae2948782fdaa264fee2d4cb622af8d28173aced955f5be599d3d570551fd0747a240fe7b66cf8a44c2d5",
          "sha256": "ea935c2a424e18a50ba6df5bf80ddfa7eb91fdce7f682f46451f61b29266f325",
          "sha1": "7e72a26a11d3b2053acf1033437e2ccd3f3c9321",
          "md5": "96770b80868adf8448bc465eaf73821f"
        }
      ]
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-test-dispatcher-mingwx64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-test-dispatcher-mingwx64-3.1.2-SNAPSHOT-sources.jar",
          "size": 1709,
          "sha512": "ac3abfd7db39f52d4cb36aa151c218fdf5edc8030b1c2c6f10f95e5f64f96f2d2d1f3adcfa1152a7f0b014b6768f41fbb956453103dbcac2056a6cf64228e90f",
          "sha256": "cea9fab28f6912c524793f5b574b7d9a1388ccd4b31cc1e843b3569162285527",
          "sha1": "43f9cbe6bf3389e8a12756d365996462d103a724",
          "md5": "a2a060a98587c8a9d7ca1edb432b045c"
        }
      ]
    }
  ]
}
