{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-serialization-kotlinx-cbor/3.1.2-SNAPSHOT/ktor-serialization-kotlinx-cbor-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-serialization-kotlinx-cbor",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-serialization-kotlinx",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-cbor",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-serialization-kotlinx-cbor-iosArm64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-serialization-kotlinx-cbor-iosarm64-3.1.2-SNAPSHOT.klib",
          "size": 5159,
          "sha512": "b57d351cadf3005e03a016122018e202aaddd340c955f8591545fef2bbf35476d32fd1eef42c9917d3d30b74858b13c9ffcf711309f3ef86ed664ced5e15ba08",
          "sha256": "0fa05e38e2ebfe7148436842ffd0511b777b8d0048443e2903fa5a6ac1f49ede",
          "sha1": "f41551502a53a9348636f4e49ba3d1a65ae9fdde",
          "md5": "109e171427faabe5d7db1e03099b48b7"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-serialization-kotlinx-cbor-iosarm64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-serialization-kotlinx-cbor-iosarm64-3.1.2-SNAPSHOT-sources.jar",
          "size": 1870,
          "sha512": "6527ba6b86a11193af0974c540bcd1153547c67ca907b3f669e620b95f121efe55a4c9add5935df90079b7c56419e572f4357298da1087183803e527463b4065",
          "sha256": "e2f73880e358d8e66a29281ba5e2c3f36753ab6d6e055ac2c47b18faa226b06f",
          "sha1": "20f0173fafbc1c6b72488a503626e2dcc77f65cf",
          "md5": "4ea1beebfdfdba67e54875899da0c7fc"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-serialization-kotlinx",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-cbor",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-serialization-kotlinx-cbor-iosarm64-3.1.2-SNAPSHOT-metadata.jar",
          "url": "ktor-serialization-kotlinx-cbor-iosarm64-3.1.2-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "8c74905187b8c0c0c04ebfb512f4df5b2302e07eb1a7bd92882253feafaeed0886de2accbd3969487416c2767c924310d7a303906c342e763cf3b0eccac37b02",
          "sha256": "bf90c797d6e529306fae63afcb4d1c2b907afe1a134c0f026837b061ab423a06",
          "sha1": "819e0733093939c9f4362f312e4fdf44ebdb97ec",
          "md5": "c1398f5b5dba4020bad110e7ba713dab"
        }
      ]
    }
  ]
}
