{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-data-conversion/3.1.2-SNAPSHOT/ktor-server-data-conversion-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-server-data-conversion",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-data-conversion-tvosSimulatorArm64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-data-conversion-tvossimulatorarm64-3.1.2-SNAPSHOT.klib",
          "size": 5887,
          "sha512": "e826ea793220972aa8040f100472b51fc8f1f7c3e7d61a867c1ffc00c8aed36264ae0db72885028ed06624b69ce5577cf2841967139482cc2c399dadae8282c4",
          "sha256": "afa4648ed7ec7aee6339c09136d122aabe7505b05d9989e4760d37edc432d096",
          "sha1": "ce47ce3e621d79908d3928f67c5e168da8a187de",
          "md5": "0e130392aad6f2d8dba57b171f31bf18"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-server-data-conversion-tvossimulatorarm64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-server-data-conversion-tvossimulatorarm64-3.1.2-SNAPSHOT-sources.jar",
          "size": 1782,
          "sha512": "2ff57d536c9be84fccc877003df07119317b8dd33b443d78785c72c4cc2eba967743937f5b062b166a792836747cae6b9f810ff888664b148f2d910404f96cff",
          "sha256": "a6d9710261dd2448519c7fe4dbe020a5c903270d4d1bcd83c5adbf322909e1f8",
          "sha1": "38acec474a03563944b2137996b9cb0634f8df94",
          "md5": "705b84a0b2dcce15e9264010650192ac"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-data-conversion-tvossimulatorarm64-3.1.2-SNAPSHOT-metadata.jar",
          "url": "ktor-server-data-conversion-tvossimulatorarm64-3.1.2-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "6c90b8f19e0163727666aacc01c29ecbb936212b3664c2d875d5b10c54029bb047c23d6e5a87b6586eef8933a45ea2fe630910aa35bc8e874b8bec6582c04f15",
          "sha256": "0a31af3624da2de34a566e6a613fc9553aad5bfc6e564b0cfc2957215b5e4caf",
          "sha1": "7aeefa3a5d03a14efbab7b6d5fc8beca0f259d2c",
          "md5": "050c5bb704e158c4878afca802cb62d8"
        }
      ]
    }
  ]
}
