{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-rpc-krpc-ktor-client/0.5.1/kotlinx-rpc-krpc-ktor-client-0.5.1.module",
    "group": "com.vickyleu.kotlinx",
    "module": "kotlinx-rpc-krpc-ktor-client",
    "version": "0.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.vickyleu.kotlinx",
          "module": "kotlinx-rpc-krpc-client",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "com.vickyleu.kotlinx",
          "module": "kotlinx-rpc-krpc-ktor-core",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-websockets",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-rpc-krpc-ktor-client-watchosX64Main-0.5.1.klib",
          "url": "kotlinx-rpc-krpc-ktor-client-watchosx64-0.5.1.klib",
          "size": 11925,
          "sha512": "913b1df8e9c8509b89c3c927f39949733f36272befff7c009aa61ba8e8941feb076c58c101634af6ecbae5f65ec4de31bd74a873d0cf59a929f5f6efa569c379",
          "sha256": "9c6678c1fa6fd650e7cae764cf804d08701c6ccd19c0a1716d86cd6f46bed2a6",
          "sha1": "c55b93e46a750f95aea05c2aa7ad33f4725680f4",
          "md5": "fb8f59c6f60aa2b4433486e79784bffa"
        }
      ]
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-rpc-krpc-ktor-client-watchosx64-0.5.1-sources.jar",
          "url": "kotlinx-rpc-krpc-ktor-client-watchosx64-0.5.1-sources.jar",
          "size": 3324,
          "sha512": "2a29469277d9872d798ddc91c27d0f6737621c12a29d3c87c29525951eba56b0b97ba0c6cc894316d4776050b912f1c64d3b32738daa4f74ce1de7449cbc4de4",
          "sha256": "1e15015e92429743b18c7a242a42e3fa38971d9034cf6979d6c5cc199bc6d53d",
          "sha1": "c5269cc3aa65e334361c11a8e28df375f0d1d237",
          "md5": "a246d63fe8d1dc585d2f8585d00ec781"
        }
      ]
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.vickyleu.kotlinx",
          "module": "kotlinx-rpc-krpc-client",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "com.vickyleu.kotlinx",
          "module": "kotlinx-rpc-krpc-ktor-core",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-websockets",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-rpc-krpc-ktor-client-watchosx64-0.5.1-metadata.jar",
          "url": "kotlinx-rpc-krpc-ktor-client-watchosx64-0.5.1-metadata.jar",
          "size": 261,
          "sha512": "2560e34751e0226dfb0916ed386fbc825c2fd31178717a1cd20ced89935f49f1d169756fc1235a43ceca0e583eab790f0a15dffb2738ea990a87ce5303708078",
          "sha256": "52855f42bc71f2ceb983dc053592307d81e738441aa5b6303fb46aca84bee4bc",
          "sha1": "354e3b98264b236d03286250f7de526cd74c6b43",
          "md5": "4bf60993a33c3bba84250a4ff87eaab0"
        }
      ]
    }
  ]
}
