{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-client-auth/3.1.2-SNAPSHOT/ktor-client-auth-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-client-auth",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-auth-androidNativeX64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-client-auth-androidnativex64-3.1.2-SNAPSHOT.klib",
          "size": 53510,
          "sha512": "0ad506349eca5dabf212d8a38722aca366bf7fb35464948df773e73faa0143bea1a3363c4b6f4d6db246967ac22135675ce7f1ef852b9837b778df7989e9a99f",
          "sha256": "b88ccbb015dbf82a37fbebfb67b90f650e5cf2682f31282e4dffc1a55c89fa34",
          "sha1": "8359165fdd43df4c354c8fe74566536e99b4e97a",
          "md5": "ea93737de39f9ef75264127151c5b843"
        }
      ]
    },
    {
      "name": "androidNativeX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-client-auth-androidnativex64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-client-auth-androidnativex64-3.1.2-SNAPSHOT-sources.jar",
          "size": 12670,
          "sha512": "565278687b8b7d6d0f81174a538e3e36bec2abc6aae7e78283d0afc83759396844cf5d8c19c815bc0e43b87aa0523a92c06107eb6d310400f13ab25534298066",
          "sha256": "d547799a79c9a25bae79fa8ac8322a7eb5a6f44867f2be7a925bf9d4a894f922",
          "sha1": "7425b17152bc668e37ee3e15c572de3d4d5ac339",
          "md5": "b6d07b98246acd355ac78681c561888d"
        }
      ]
    }
  ]
}
