{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-method-override/3.1.2-SNAPSHOT/ktor-server-method-override-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-server-method-override",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-method-override-linuxArm64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-method-override-linuxarm64-3.1.2-SNAPSHOT.klib",
          "size": 6818,
          "sha512": "4402fb0d31db281d627e52a3548de01959e449556cd9b6e4c19cd7a0ad0ab47d3b3b95faa447971d545ebac100f9bc0a47473c0b26670b8f9a2123b179a955b1",
          "sha256": "c7dd8cebf1733f823077b193c72359b902db95d89c984e8598e965701c79d90f",
          "sha1": "fceb1c5e161824b546b7b317588f6eaf90885541",
          "md5": "e450eb7976d6eead38942e9c9856d822"
        }
      ]
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-server-method-override-linuxarm64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-server-method-override-linuxarm64-3.1.2-SNAPSHOT-sources.jar",
          "size": 2076,
          "sha512": "afc801d002869e568c4b161067f927345d3309599fa2e817341901aed806dca5517c1bfefd08f5e863cbb32007d6ed4f5610de27e8c53562bac4f15d32b7d01a",
          "sha256": "6603e7b86c97043ea34a248208feaf3708a30ae2626f0bcc81ce97e7c9c574e1",
          "sha1": "f7ba979af0b51b1ed0a4e242615073c938dfc354",
          "md5": "c5c4f724c9a5250d5935327d4516e740"
        }
      ]
    }
  ]
}
