{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-client-curl/3.1.2-SNAPSHOT/ktor-client-curl-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-client-curl",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-http-cio",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-curl-linuxArm64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-client-curl-linuxarm64-3.1.2-SNAPSHOT.klib",
          "size": 81827,
          "sha512": "e1e49005913feb1ddaad3b0685736a57fe4f17a8e191dc246a727ab0607f73480bfdcf5e29bcf1952301a8721ed4bbfe6934cd87aa21c854e635eec06a9404f4",
          "sha256": "36fb1a83439f86e45f53c8d3d47340bb33cda0d36d957142ca463ae97b14176d",
          "sha1": "835a783f8a7969cd40f245863e2a1b5c4dbc8aac",
          "md5": "5b905cf82db84caba39022d52d8efd2a"
        },
        {
          "name": "ktor-client-curl-linuxArm64Cinterop-libcurlMain-3.1.2-SNAPSHOT.klib",
          "url": "ktor-client-curl-linuxarm64-3.1.2-SNAPSHOT-cinterop-libcurl.klib",
          "size": 4539328,
          "sha512": "0eb0178b126ecfa3bb5a91be26cdee9a87dbb827e5397b3d8096858ce5a4609eaf4702d0a769280595b045bc9e05e82c09d035d68c3e0ca53ba26a3abdd73202",
          "sha256": "c29c1068600fdded1112380e8dda3d243a71bf890a55556c7cda72dc10f3f771",
          "sha1": "4de18bde925ca5581bf754a03493abefb6afcb3e",
          "md5": "f6378dcb1867047cb1c92a530f431b88"
        }
      ]
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-client-curl-linuxarm64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-client-curl-linuxarm64-3.1.2-SNAPSHOT-sources.jar",
          "size": 17431,
          "sha512": "6b8c36dde71c7e31362996ab8946c599ed783d504297ef0871ada375e1719e3bcad4366f42424a550a233ed3631c94e705c43b30675500fa9e4e0366f2dd69b3",
          "sha256": "e4a473788e24d20ea17d9164a657140a76c027642b98b464adabf7d2f3417d86",
          "sha1": "ac789b266dd22c087ce792a4ee0e17e827986f93",
          "md5": "fc26ea2b4dab9d6f503ac4bef27b2e64"
        }
      ]
    }
  ]
}
