{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-rpc-krpc-ktor-core/0.5.1/kotlinx-rpc-krpc-ktor-core-0.5.1.module",
    "group": "com.vickyleu.kotlinx",
    "module": "kotlinx-rpc-krpc-ktor-core",
    "version": "0.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.vickyleu.kotlinx",
          "module": "kotlinx-rpc-krpc-core",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-rpc-krpc-ktor-core-jvm-0.5.1.jar",
          "url": "kotlinx-rpc-krpc-ktor-core-jvm-0.5.1.jar",
          "size": 4376,
          "sha512": "836e6af00534135664e6d1394cc39580f4019248295801dd0c283924e922df3ce73060b870265b64efcdef528e82cba6d98519063f1a34f93c79881c2a6cc8ca",
          "sha256": "1d43d5f0840c095f632c4146b09a03fa2cf29a72241b823f8f3d7b4dbb16592e",
          "sha1": "7bf102792be66158418bc089a1efe822cbe75ea4",
          "md5": "c160bbae6e4898c4ffc43fdefc76069a"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.vickyleu.kotlinx",
          "module": "kotlinx-rpc-krpc-core",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-websockets",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-rpc-krpc-ktor-core-jvm-0.5.1.jar",
          "url": "kotlinx-rpc-krpc-ktor-core-jvm-0.5.1.jar",
          "size": 4376,
          "sha512": "836e6af00534135664e6d1394cc39580f4019248295801dd0c283924e922df3ce73060b870265b64efcdef528e82cba6d98519063f1a34f93c79881c2a6cc8ca",
          "sha256": "1d43d5f0840c095f632c4146b09a03fa2cf29a72241b823f8f3d7b4dbb16592e",
          "sha1": "7bf102792be66158418bc089a1efe822cbe75ea4",
          "md5": "c160bbae6e4898c4ffc43fdefc76069a"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlinx-rpc-krpc-ktor-core-jvm-0.5.1-sources.jar",
          "url": "kotlinx-rpc-krpc-ktor-core-jvm-0.5.1-sources.jar",
          "size": 1686,
          "sha512": "44a6419ceeecc94824e017b415f80765af8cc82ace7dbba25d407260aa1f6546e5dd8a9e15c6c2b27edc556796806416ca68703a672c6e50506675500e897dd9",
          "sha256": "aa04308edf1ce343ee7e2a5cb3d1ea2beb1ab591731d87a71e47c7b54722b900",
          "sha1": "dc97cf7530cf4d5450e912d6cf9e0d58199ee9bc",
          "md5": "6d8d30484c72ad16bc70dcdb8c6a7a16"
        }
      ]
    }
  ]
}
