{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-conditional-headers/3.1.2-SNAPSHOT/ktor-server-conditional-headers-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-server-conditional-headers",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-conditional-headers-linuxArm64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-conditional-headers-linuxarm64-3.1.2-SNAPSHOT.klib",
          "size": 12661,
          "sha512": "46ecd2109df7042bf80beff7a21f72702910f311529570b68413df19f18fedc1e40370edaeab87537e3837626f0910315cda2f968491ea240d912655f2a756d1",
          "sha256": "2477e2e9484a96fe4fde833804efc7c9487faf88a18774aa2c1d46ee8cbda666",
          "sha1": "12ece0113cbeda191d17e3a0235d9af719f85782",
          "md5": "016c5631ce0fdfab57fd9c8cff1cb1a6"
        }
      ]
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-server-conditional-headers-linuxarm64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-server-conditional-headers-linuxarm64-3.1.2-SNAPSHOT-sources.jar",
          "size": 3012,
          "sha512": "1bc25c28c688d815af04b2a904e0bc529973a4598817dbfc08fa4330286c748d06e169f96998aeda2da5530482d32ec563617c0d869a8d689cb73fd14894526a",
          "sha256": "df404c6f6c0e957120cf20a9aa04255d56a95e7e655dc6f3dac2263c034532ef",
          "sha1": "5a68ff5619ddc990a456b3ae260e49876e042af0",
          "md5": "f73366c4698e40cb75a23709ff53b932"
        }
      ]
    }
  ]
}
