{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-servlet-jakarta/3.1.2-SNAPSHOT/ktor-server-servlet-jakarta-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-server-servlet-jakarta",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-servlet-jakarta-jvm-3.1.2-SNAPSHOT.jar",
          "url": "ktor-server-servlet-jakarta-jvm-3.1.2-SNAPSHOT.jar",
          "size": 123071,
          "sha512": "bd2eb232bd9cad6166c5148be44b427ddd6fa5b30fb2870c0556d6654cba823007b19fe2110eb9880e869af292b8d452053f4cf0a505afb926b99b4a6c9f9756",
          "sha256": "109b3ade5e4259d7c83e9570dce54d9aaa04e5ff998e0802c2b687a034109307",
          "sha1": "591b1b6de4dd2a0de56f0776238d1608ed61d3f5",
          "md5": "a47eb5732dc5605f8636a4cb81da0ece"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-servlet-jakarta-jvm-3.1.2-SNAPSHOT.jar",
          "url": "ktor-server-servlet-jakarta-jvm-3.1.2-SNAPSHOT.jar",
          "size": 123071,
          "sha512": "bd2eb232bd9cad6166c5148be44b427ddd6fa5b30fb2870c0556d6654cba823007b19fe2110eb9880e869af292b8d452053f4cf0a505afb926b99b4a6c9f9756",
          "sha256": "109b3ade5e4259d7c83e9570dce54d9aaa04e5ff998e0802c2b687a034109307",
          "sha1": "591b1b6de4dd2a0de56f0776238d1608ed61d3f5",
          "md5": "a47eb5732dc5605f8636a4cb81da0ece"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ktor-server-servlet-jakarta-jvm-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-server-servlet-jakarta-jvm-3.1.2-SNAPSHOT-sources.jar",
          "size": 20124,
          "sha512": "c5d41e9f5f765284c8b4a66f816e645260e5ba52eaed99501e2bcc217e4e6d54fb3d6e1b48620227e34e9bac67cddda8d0eabc32ee836dd3527ba19a96938729",
          "sha256": "9c8597f571e550014eab942ff3adf664e9b2067e61730635451b9272f83fe4aa",
          "sha1": "0e23c60e1fba5bc18da005f56cb18493df697eed",
          "md5": "78f43470be7830f4169136ac368e27bc"
        }
      ]
    }
  ]
}
