{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-test-dispatcher/3.1.2-SNAPSHOT/ktor-test-dispatcher-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-test-dispatcher",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-utils",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-test-dispatcher-macosArm64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-test-dispatcher-macosarm64-3.1.2-SNAPSHOT.klib",
          "size": 5967,
          "sha512": "dd5806eb3e6ad9fa0518e77a3dcf36b56d7a448b0bee9df1edb7543a34bd97c3e768939e28eced789078d9bfa02ef449decc23696148dc3d08a78a76660bf723",
          "sha256": "15c788d2968844c317e0c8e5f02f8735ee6610d0fe40c88fbbd4dc8eeed7ae11",
          "sha1": "877d9abde40983cc33f3809d94862991586b2ed1",
          "md5": "badaa5b9090e3841c54c029ccf2c69a2"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-test-dispatcher-macosarm64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-test-dispatcher-macosarm64-3.1.2-SNAPSHOT-sources.jar",
          "size": 1709,
          "sha512": "ac3abfd7db39f52d4cb36aa151c218fdf5edc8030b1c2c6f10f95e5f64f96f2d2d1f3adcfa1152a7f0b014b6768f41fbb956453103dbcac2056a6cf64228e90f",
          "sha256": "cea9fab28f6912c524793f5b574b7d9a1388ccd4b31cc1e843b3569162285527",
          "sha1": "43f9cbe6bf3389e8a12756d365996462d103a724",
          "md5": "a2a060a98587c8a9d7ca1edb432b045c"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-utils",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-test-dispatcher-macosarm64-3.1.2-SNAPSHOT-metadata.jar",
          "url": "ktor-test-dispatcher-macosarm64-3.1.2-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "82b376efb1ef1489e39dd1c2e4d7a9b736554181221db493daabe103e0724886e05d37424e81842c49b265992ce31f9053c2579a1f6e7706fccc29fb9a532746",
          "sha256": "c8fdbbe6c0e54e8e555b492facf469b592652a192bcd9f67048c95777f0f8feb",
          "sha1": "a21aaf59e085f03cc25f07fd94bcab40b465126c",
          "md5": "35c8a6ceb46e43d32453cc2563b9815e"
        }
      ]
    }
  ]
}
