{
  "formatVersion": "1.1",
  "component": {
    "url": "../../pbandk-runtime/0.16.1-SNAPSHOT/pbandk-runtime-0.16.1-SNAPSHOT.module",
    "group": "com.vickyleu.pbandk",
    "module": "pbandk-runtime",
    "version": "0.16.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.2"
          }
        }
      ],
      "files": [
        {
          "name": "pbandk-runtime.klib",
          "url": "pbandk-runtime-androidnativearm64-0.16.1-SNAPSHOT.klib",
          "size": 678509,
          "sha512": "b65b27372936f9ca694c74ca31ef01bb5b165062e7c3a48284ffb293e4919622671753d958a84ac2b2d5e9455dc5be0d813489806a91dbefd581247e9813ca5f",
          "sha256": "46603d51c15b512bfaa22abfa39bf0ec6202804a9b91e43140e695d97b83f3e2",
          "sha1": "5fafdc55f871083036779741914a72067e926193",
          "md5": "298c8ce5857ed1dc372bf223d6ef7435"
        }
      ]
    },
    {
      "name": "androidNativeArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "pbandk-runtime-androidnativearm64-0.16.1-SNAPSHOT-sources.jar",
          "url": "pbandk-runtime-androidnativearm64-0.16.1-SNAPSHOT-sources.jar",
          "size": 89500,
          "sha512": "036c717c886c7f2c66b568ad3f05a1cb159fa5c07ee64235fbe6c226562682e11c912094acbd57cc82fa03b81919ca35c59763c042e88d3d5c74138950020ff7",
          "sha256": "51e2b29d585dbda1123cca39bc5e65c2495759858466323d67a5c02fd1fb998b",
          "sha1": "4d74b3fac1961c3b7cf671023c4d8af87873ec17",
          "md5": "e33355a59f03ba7232f002d0d24d31e2"
        }
      ]
    }
  ]
}
