{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-config-yaml/3.1.2-SNAPSHOT/ktor-server-config-yaml-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-server-config-yaml",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "net.mamoe.yamlkt",
          "module": "yamlkt",
          "version": {
            "requires": "0.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-config-yaml-macosX64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-config-yaml-macosx64-3.1.2-SNAPSHOT.klib",
          "size": 22492,
          "sha512": "bd1b6638996bacc13c2373826aedb58a3160bfbb4b1b4b817d4e20fd1a224ce637f9fff99d01819821bcc72191f6e60503ab7015e663687c7c7043ea3a48e9e5",
          "sha256": "b671c996724b49727cc96f5c23aec5aad44b18e5229cfe7993276e10cd6f1c36",
          "sha1": "0ceb11c2964604fce0cfc071433716a1e6884dd1",
          "md5": "525f8227bed84595fd62f27250685497"
        }
      ]
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-server-config-yaml-macosx64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-server-config-yaml-macosx64-3.1.2-SNAPSHOT-sources.jar",
          "size": 5329,
          "sha512": "d68e916f46059fc19312ae15f89dfc17e8a6ca898954fb8e0208f1b40828ab4450abe79ee3d8efd3e14dae48007ef19de3f07be7d491d682762aa3fe8bbdcc4c",
          "sha256": "289357a3e424d746e6e9c07c38fcc3eb578c1a0226aa896a07350ab620297275",
          "sha1": "20f198e992dad7fd662a65010cfce5c0b1ae52a3",
          "md5": "d810bb79f92c547396cd093e1b77c622"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "net.mamoe.yamlkt",
          "module": "yamlkt",
          "version": {
            "requires": "0.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-config-yaml-macosx64-3.1.2-SNAPSHOT-metadata.jar",
          "url": "ktor-server-config-yaml-macosx64-3.1.2-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "6756e4f4d75e0a5439ee31eec1dc50634e7a1395ecfafa2a611311e4c4217f894d598a4964416a8324dade2ef3adb8e35d9a2f006cdfc6935d8c4ab1736d0f54",
          "sha256": "4ae9538557db631c64d81d1caf258bbee59e839dd9825504d12aa1b6507c6357",
          "sha1": "941afe4f2da1ecaf724a316c0d1e040c0d326185",
          "md5": "7ee9936e9a8bff63d993877e94076199"
        }
      ]
    }
  ]
}
