{
  "formatVersion": "1.1",
  "component": {
    "group": "com.vickyleu.kotlinx",
    "module": "kotlinx-html",
    "version": "0.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-html-metadata-0.12.0.jar",
          "url": "kotlinx-html-0.12.0.jar",
          "size": 65606,
          "sha512": "e691b57d85c9b0f28397c3ef6bf633c83c30f1ac3a723d02ed5ae0bbe68624e45ad860effbe5df2893db9fb7338f9895928c86362dfbc5600b69398cfc7b75c9",
          "sha256": "966fd5edc13bd18a8782fcc56f901bc3ae6801903c3057ebd9206e5eb097faae",
          "sha1": "547b67f32f0544124542455271a7c7dab5a9a59d",
          "md5": "91c90f531225886bc5c6cd58a58aa61d"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kotlinx-html-kotlin-0.12.0-sources.jar",
          "url": "kotlinx-html-0.12.0-sources.jar",
          "size": 55168,
          "sha512": "9d54e5d64d1e4c437c6c1268a7ac55a2b5a111ad7ca50697e137d380b74c2125f122a254ce058130245f51a5933278fe6187ff5cfd8b844263b1b22774ddfe8f",
          "sha256": "3a4e0976e7281109ab9967840e38e9e8328bcd76541a0cc3ccd42928015201e6",
          "sha1": "1df30e10aae63945471656853d97447f68649160",
          "md5": "e4c0f9dc06465f5dd4ccc37e28c838af"
        }
      ]
    },
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-html-androidnativearm32/0.12.0/kotlinx-html-androidnativearm32-0.12.0.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-html-androidnativearm32",
        "version": "0.12.0"
      }
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-html-androidnativearm32/0.12.0/kotlinx-html-androidnativearm32-0.12.0.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-html-androidnativearm32",
        "version": "0.12.0"
      }
    },
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-html-androidnativearm64/0.12.0/kotlinx-html-androidnativearm64-0.12.0.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-html-androidnativearm64",
        "version": "0.12.0"
      }
    },
    {
      "name": "androidNativeArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-html-androidnativearm64/0.12.0/kotlinx-html-androidnativearm64-0.12.0.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-html-androidnativearm64",
        "version": "0.12.0"
      }
    },
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-html-androidnativex64/0.12.0/kotlinx-html-androidnativex64-0.12.0.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-html-androidnativex64",
        "version": "0.12.0"
      }
    },
    {
      "name": "androidNativeX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-html-androidnativex64/0.12.0/kotlinx-html-androidnativex64-0.12.0.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-html-androidnativex64",
        "version": "0.12.0"
      }
    },
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-html-androidnativex86/0.12.0/kotlinx-html-androidnativex86-0.12.0.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-html-androidnativex86",
        "version": "0.12.0"
      }
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-html-androidnativex86/0.12.0/kotlinx-html-androidnativex86-0.12.0.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-html-androidnativex86",
        "version": "0.12.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-html-iosarm64/0.12.0/kotlinx-html-iosarm64-0.12.0.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-html-iosarm64",
        "version": "0.12.0"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-html-iosarm64/0.12.0/kotlinx-html-iosarm64-0.12.0.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-html-iosarm64",
        "version": "0.12.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-html-iosarm64/0.12.0/kotlinx-html-iosarm64-0.12.0.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-html-iosarm64",
        "version": "0.12.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-html-iossimulatorarm64/0.12.0/kotlinx-html-iossimulatorarm64-0.12.0.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-html-iossimulatorarm64",
        "version": "0.12.0"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-html-iossimulatorarm64/0.12.0/kotlinx-html-iossimulatorarm64-0.12.0.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-html-iossimulatorarm64",
        "version": "0.12.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-html-iossimulatorarm64/0.12.0/kotlinx-html-iossimulatorarm64-0.12.0.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-html-iossimulatorarm64",
        "version": "0.12.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-html-iosx64/0.12.0/kotlinx-html-iosx64-0.12.0.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-html-iosx64",
        "version": "0.12.0"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-html-iosx64/0.12.0/kotlinx-html-iosx64-0.12.0.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-html-iosx64",
        "version": "0.12.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-html-iosx64/0.12.0/kotlinx-html-iosx64-0.12.0.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-html-iosx64",
        "version": "0.12.0"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-html-js/0.12.0/kotlinx-html-js-0.12.0.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-html-js",
        "version": "0.12.0"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-html-js/0.12.0/kotlinx-html-js-0.12.0.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-html-js",
        "version": "0.12.0"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-html-js/0.12.0/kotlinx-html-js-0.12.0.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-html-js",
        "version": "0.12.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlinx-html-jvm/0.12.0/kotlinx-html-jvm-0.12.0.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-html-jvm",
        "version": "0.12.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlinx-html-jvm/0.12.0/kotlinx-html-jvm-0.12.0.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-html-jvm",
        "version": "0.12.0"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlinx-html-jvm/0.12.0/kotlinx-html-jvm-0.12.0.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-html-jvm",
        "version": "0.12.0"
      }
    },
    {
      "name": "linuxArm32HfpApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm32_hfp",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-html-linuxarm32hfp/0.12.0/kotlinx-html-linuxarm32hfp-0.12.0.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-html-linuxarm32hfp",
        "version": "0.12.0"
      }
    },
    {
      "name": "linuxArm32HfpSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm32_hfp",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-html-linuxarm32hfp/0.12.0/kotlinx-html-linuxarm32hfp-0.12.0.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-html-linuxarm32hfp",
        "version": "0.12.0"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-html-linuxarm64/0.12.0/kotlinx-html-linuxarm64-0.12.0.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-html-linuxarm64",
        "version": "0.12.0"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-html-linuxarm64/0.12.0/kotlinx-html-linuxarm64-0.12.0.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-html-linuxarm64",
        "version": "0.12.0"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-html-linuxx64/0.12.0/kotlinx-html-linuxx64-0.12.0.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-html-linuxx64",
        "version": "0.12.0"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-html-linuxx64/0.12.0/kotlinx-html-linuxx64-0.12.0.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-html-linuxx64",
        "version": "0.12.0"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-html-macosarm64/0.12.0/kotlinx-html-macosarm64-0.12.0.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-html-macosarm64",
        "version": "0.12.0"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-html-macosarm64/0.12.0/kotlinx-html-macosarm64-0.12.0.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-html-macosarm64",
        "version": "0.12.0"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-html-macosarm64/0.12.0/kotlinx-html-macosarm64-0.12.0.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-html-macosarm64",
        "version": "0.12.0"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-html-macosx64/0.12.0/kotlinx-html-macosx64-0.12.0.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-html-macosx64",
        "version": "0.12.0"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-html-macosx64/0.12.0/kotlinx-html-macosx64-0.12.0.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-html-macosx64",
        "version": "0.12.0"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-html-macosx64/0.12.0/kotlinx-html-macosx64-0.12.0.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-html-macosx64",
        "version": "0.12.0"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-html-mingwx64/0.12.0/kotlinx-html-mingwx64-0.12.0.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-html-mingwx64",
        "version": "0.12.0"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-html-mingwx64/0.12.0/kotlinx-html-mingwx64-0.12.0.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-html-mingwx64",
        "version": "0.12.0"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-html-tvosarm64/0.12.0/kotlinx-html-tvosarm64-0.12.0.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-html-tvosarm64",
        "version": "0.12.0"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-html-tvosarm64/0.12.0/kotlinx-html-tvosarm64-0.12.0.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-html-tvosarm64",
        "version": "0.12.0"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-html-tvosarm64/0.12.0/kotlinx-html-tvosarm64-0.12.0.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-html-tvosarm64",
        "version": "0.12.0"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-html-tvossimulatorarm64/0.12.0/kotlinx-html-tvossimulatorarm64-0.12.0.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-html-tvossimulatorarm64",
        "version": "0.12.0"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-html-tvossimulatorarm64/0.12.0/kotlinx-html-tvossimulatorarm64-0.12.0.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-html-tvossimulatorarm64",
        "version": "0.12.0"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-html-tvossimulatorarm64/0.12.0/kotlinx-html-tvossimulatorarm64-0.12.0.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-html-tvossimulatorarm64",
        "version": "0.12.0"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-html-tvosx64/0.12.0/kotlinx-html-tvosx64-0.12.0.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-html-tvosx64",
        "version": "0.12.0"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-html-tvosx64/0.12.0/kotlinx-html-tvosx64-0.12.0.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-html-tvosx64",
        "version": "0.12.0"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-html-tvosx64/0.12.0/kotlinx-html-tvosx64-0.12.0.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-html-tvosx64",
        "version": "0.12.0"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlinx-html-wasm-js/0.12.0/kotlinx-html-wasm-js-0.12.0.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-html-wasm-js",
        "version": "0.12.0"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlinx-html-wasm-js/0.12.0/kotlinx-html-wasm-js-0.12.0.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-html-wasm-js",
        "version": "0.12.0"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlinx-html-wasm-js/0.12.0/kotlinx-html-wasm-js-0.12.0.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-html-wasm-js",
        "version": "0.12.0"
      }
    },
    {
      "name": "wasmWasiApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "available-at": {
        "url": "../../kotlinx-html-wasm-wasi/0.12.0/kotlinx-html-wasm-wasi-0.12.0.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-html-wasm-wasi",
        "version": "0.12.0"
      }
    },
    {
      "name": "wasmWasiRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "available-at": {
        "url": "../../kotlinx-html-wasm-wasi/0.12.0/kotlinx-html-wasm-wasi-0.12.0.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-html-wasm-wasi",
        "version": "0.12.0"
      }
    },
    {
      "name": "wasmWasiSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "available-at": {
        "url": "../../kotlinx-html-wasm-wasi/0.12.0/kotlinx-html-wasm-wasi-0.12.0.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-html-wasm-wasi",
        "version": "0.12.0"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-html-watchosarm32/0.12.0/kotlinx-html-watchosarm32-0.12.0.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-html-watchosarm32",
        "version": "0.12.0"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-html-watchosarm32/0.12.0/kotlinx-html-watchosarm32-0.12.0.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-html-watchosarm32",
        "version": "0.12.0"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-html-watchosarm32/0.12.0/kotlinx-html-watchosarm32-0.12.0.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-html-watchosarm32",
        "version": "0.12.0"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-html-watchosarm64/0.12.0/kotlinx-html-watchosarm64-0.12.0.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-html-watchosarm64",
        "version": "0.12.0"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-html-watchosarm64/0.12.0/kotlinx-html-watchosarm64-0.12.0.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-html-watchosarm64",
        "version": "0.12.0"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-html-watchosarm64/0.12.0/kotlinx-html-watchosarm64-0.12.0.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-html-watchosarm64",
        "version": "0.12.0"
      }
    },
    {
      "name": "watchosDeviceArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-html-watchosdevicearm64/0.12.0/kotlinx-html-watchosdevicearm64-0.12.0.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-html-watchosdevicearm64",
        "version": "0.12.0"
      }
    },
    {
      "name": "watchosDeviceArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-html-watchosdevicearm64/0.12.0/kotlinx-html-watchosdevicearm64-0.12.0.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-html-watchosdevicearm64",
        "version": "0.12.0"
      }
    },
    {
      "name": "watchosDeviceArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-html-watchosdevicearm64/0.12.0/kotlinx-html-watchosdevicearm64-0.12.0.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-html-watchosdevicearm64",
        "version": "0.12.0"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-html-watchossimulatorarm64/0.12.0/kotlinx-html-watchossimulatorarm64-0.12.0.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-html-watchossimulatorarm64",
        "version": "0.12.0"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-html-watchossimulatorarm64/0.12.0/kotlinx-html-watchossimulatorarm64-0.12.0.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-html-watchossimulatorarm64",
        "version": "0.12.0"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-html-watchossimulatorarm64/0.12.0/kotlinx-html-watchossimulatorarm64-0.12.0.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-html-watchossimulatorarm64",
        "version": "0.12.0"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-html-watchosx64/0.12.0/kotlinx-html-watchosx64-0.12.0.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-html-watchosx64",
        "version": "0.12.0"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-html-watchosx64/0.12.0/kotlinx-html-watchosx64-0.12.0.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-html-watchosx64",
        "version": "0.12.0"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-html-watchosx64/0.12.0/kotlinx-html-watchosx64-0.12.0.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-html-watchosx64",
        "version": "0.12.0"
      }
    }
  ]
}
