{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-call-id/3.1.2-SNAPSHOT/ktor-call-id-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-call-id",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-call-id-iosArm64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-call-id-iosarm64-3.1.2-SNAPSHOT.klib",
          "size": 5466,
          "sha512": "a585ca39b178001970e8a7d75916c75033043d3c598e407a89e3f2cf9851e1a11692e5cf7ecfeacd6413aec1cdf1d96d5b8ec0114f49511856bcc367a5793d1f",
          "sha256": "bf45ba0398de6979f13ac0328d0906ec834d0a5f99b20a58a1026a6191856fb7",
          "sha1": "3759688f384befacb2c2f69a4c71674312657d08",
          "md5": "46dfb2f1dabb3ad4b908da87d50c2d94"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-call-id-iosarm64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-call-id-iosarm64-3.1.2-SNAPSHOT-sources.jar",
          "size": 1414,
          "sha512": "65d139b76c81b7698762646c6d7b77f9abdf4d40135f376dc6ef454332adcfdd4e73b4f78f2bb47b496d6091ce0b986ff7b8666900f499350756c86a60627a6f",
          "sha256": "0271d192d924e609c6b5e25de6deba80e6384ed0f4bf8cd2a33b26cd3d52e9dd",
          "sha1": "ff8d4cf17a592129db6fad5ae7e8a64712b75d35",
          "md5": "bc3a005c746c04911cd0981ded54df9e"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-call-id-iosarm64-3.1.2-SNAPSHOT-metadata.jar",
          "url": "ktor-call-id-iosarm64-3.1.2-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "b9510ff4d41a9211ec5477e1a5d365d37716db07756e0b55ceee988cb70ee96955d66131f269a118436dfa221268f3af0892fb8adfc555803faa1d965e6fe65e",
          "sha256": "f5e9472d2d6fb3a1cb40015041c1edeb56e2f529785d1c165bce62247f005601",
          "sha1": "bfb9a6b4170f8d036d2fba37a74815c962845065",
          "md5": "d972c3269c989dda098928f308edd4e9"
        }
      ]
    }
  ]
}
