{
  "formatVersion": "1.1",
  "component": {
    "group": "com.vickyleu.kotlinx",
    "module": "kotlinx-rpc-krpc-ktor-core",
    "version": "0.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "com.vickyleu.kotlinx",
          "module": "kotlinx-rpc-krpc-core",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-websockets",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-rpc-krpc-ktor-core-metadata-0.5.1.jar",
          "url": "kotlinx-rpc-krpc-ktor-core-0.5.1.jar",
          "size": 2761,
          "sha512": "6ebe09f8c4b5e9291feba091a227f7fd5a666b8f310e0d2a4f4be0569d9318b8301b85e764888ff9313f80c4c8cc40580e5509634bc27b3a0eb23224237f2742",
          "sha256": "0c38842dcf54c679d9da75cc0ecc6d9112f24dadb714fb5fb615ec2ada1f4de6",
          "sha1": "be0d34c9b531f1140194b905e5a44ac88c940d81",
          "md5": "e8b2bceef000f109a8b5c77763979dcf"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kotlinx-rpc-krpc-ktor-core-kotlin-0.5.1-sources.jar",
          "url": "kotlinx-rpc-krpc-ktor-core-0.5.1-sources.jar",
          "size": 1686,
          "sha512": "44a6419ceeecc94824e017b415f80765af8cc82ace7dbba25d407260aa1f6546e5dd8a9e15c6c2b27edc556796806416ca68703a672c6e50506675500e897dd9",
          "sha256": "aa04308edf1ce343ee7e2a5cb3d1ea2beb1ab591731d87a71e47c7b54722b900",
          "sha1": "dc97cf7530cf4d5450e912d6cf9e0d58199ee9bc",
          "md5": "6d8d30484c72ad16bc70dcdb8c6a7a16"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-iosarm64/0.5.1/kotlinx-rpc-krpc-ktor-core-iosarm64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-iosarm64",
        "version": "0.5.1"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-iosarm64/0.5.1/kotlinx-rpc-krpc-ktor-core-iosarm64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-iosarm64",
        "version": "0.5.1"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-iosarm64/0.5.1/kotlinx-rpc-krpc-ktor-core-iosarm64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-iosarm64",
        "version": "0.5.1"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-iossimulatorarm64/0.5.1/kotlinx-rpc-krpc-ktor-core-iossimulatorarm64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-iossimulatorarm64",
        "version": "0.5.1"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-iossimulatorarm64/0.5.1/kotlinx-rpc-krpc-ktor-core-iossimulatorarm64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-iossimulatorarm64",
        "version": "0.5.1"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-iossimulatorarm64/0.5.1/kotlinx-rpc-krpc-ktor-core-iossimulatorarm64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-iossimulatorarm64",
        "version": "0.5.1"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-iosx64/0.5.1/kotlinx-rpc-krpc-ktor-core-iosx64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-iosx64",
        "version": "0.5.1"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-iosx64/0.5.1/kotlinx-rpc-krpc-ktor-core-iosx64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-iosx64",
        "version": "0.5.1"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-iosx64/0.5.1/kotlinx-rpc-krpc-ktor-core-iosx64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-iosx64",
        "version": "0.5.1"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-js/0.5.1/kotlinx-rpc-krpc-ktor-core-js-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-js",
        "version": "0.5.1"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-js/0.5.1/kotlinx-rpc-krpc-ktor-core-js-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-js",
        "version": "0.5.1"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-js/0.5.1/kotlinx-rpc-krpc-ktor-core-js-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-js",
        "version": "0.5.1"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-jvm/0.5.1/kotlinx-rpc-krpc-ktor-core-jvm-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-jvm",
        "version": "0.5.1"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-jvm/0.5.1/kotlinx-rpc-krpc-ktor-core-jvm-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-jvm",
        "version": "0.5.1"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-jvm/0.5.1/kotlinx-rpc-krpc-ktor-core-jvm-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-jvm",
        "version": "0.5.1"
      }
    },
    {
      "name": "linuxArm32HfpApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm32_hfp",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-linuxarm32hfp/0.5.1/kotlinx-rpc-krpc-ktor-core-linuxarm32hfp-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-linuxarm32hfp",
        "version": "0.5.1"
      }
    },
    {
      "name": "linuxArm32HfpSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm32_hfp",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-linuxarm32hfp/0.5.1/kotlinx-rpc-krpc-ktor-core-linuxarm32hfp-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-linuxarm32hfp",
        "version": "0.5.1"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-linuxarm64/0.5.1/kotlinx-rpc-krpc-ktor-core-linuxarm64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-linuxarm64",
        "version": "0.5.1"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-linuxarm64/0.5.1/kotlinx-rpc-krpc-ktor-core-linuxarm64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-linuxarm64",
        "version": "0.5.1"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-linuxx64/0.5.1/kotlinx-rpc-krpc-ktor-core-linuxx64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-linuxx64",
        "version": "0.5.1"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-linuxx64/0.5.1/kotlinx-rpc-krpc-ktor-core-linuxx64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-linuxx64",
        "version": "0.5.1"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-macosarm64/0.5.1/kotlinx-rpc-krpc-ktor-core-macosarm64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-macosarm64",
        "version": "0.5.1"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-macosarm64/0.5.1/kotlinx-rpc-krpc-ktor-core-macosarm64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-macosarm64",
        "version": "0.5.1"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-macosarm64/0.5.1/kotlinx-rpc-krpc-ktor-core-macosarm64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-macosarm64",
        "version": "0.5.1"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-macosx64/0.5.1/kotlinx-rpc-krpc-ktor-core-macosx64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-macosx64",
        "version": "0.5.1"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-macosx64/0.5.1/kotlinx-rpc-krpc-ktor-core-macosx64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-macosx64",
        "version": "0.5.1"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-macosx64/0.5.1/kotlinx-rpc-krpc-ktor-core-macosx64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-macosx64",
        "version": "0.5.1"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-mingwx64/0.5.1/kotlinx-rpc-krpc-ktor-core-mingwx64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-mingwx64",
        "version": "0.5.1"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-mingwx64/0.5.1/kotlinx-rpc-krpc-ktor-core-mingwx64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-mingwx64",
        "version": "0.5.1"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-tvosarm64/0.5.1/kotlinx-rpc-krpc-ktor-core-tvosarm64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-tvosarm64",
        "version": "0.5.1"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-tvosarm64/0.5.1/kotlinx-rpc-krpc-ktor-core-tvosarm64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-tvosarm64",
        "version": "0.5.1"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-tvosarm64/0.5.1/kotlinx-rpc-krpc-ktor-core-tvosarm64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-tvosarm64",
        "version": "0.5.1"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-tvossimulatorarm64/0.5.1/kotlinx-rpc-krpc-ktor-core-tvossimulatorarm64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-tvossimulatorarm64",
        "version": "0.5.1"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-tvossimulatorarm64/0.5.1/kotlinx-rpc-krpc-ktor-core-tvossimulatorarm64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-tvossimulatorarm64",
        "version": "0.5.1"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-tvossimulatorarm64/0.5.1/kotlinx-rpc-krpc-ktor-core-tvossimulatorarm64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-tvossimulatorarm64",
        "version": "0.5.1"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-tvosx64/0.5.1/kotlinx-rpc-krpc-ktor-core-tvosx64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-tvosx64",
        "version": "0.5.1"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-tvosx64/0.5.1/kotlinx-rpc-krpc-ktor-core-tvosx64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-tvosx64",
        "version": "0.5.1"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-tvosx64/0.5.1/kotlinx-rpc-krpc-ktor-core-tvosx64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-tvosx64",
        "version": "0.5.1"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-wasm-js/0.5.1/kotlinx-rpc-krpc-ktor-core-wasm-js-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-wasm-js",
        "version": "0.5.1"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-wasm-js/0.5.1/kotlinx-rpc-krpc-ktor-core-wasm-js-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-wasm-js",
        "version": "0.5.1"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-wasm-js/0.5.1/kotlinx-rpc-krpc-ktor-core-wasm-js-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-wasm-js",
        "version": "0.5.1"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-watchosarm32/0.5.1/kotlinx-rpc-krpc-ktor-core-watchosarm32-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-watchosarm32",
        "version": "0.5.1"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-watchosarm32/0.5.1/kotlinx-rpc-krpc-ktor-core-watchosarm32-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-watchosarm32",
        "version": "0.5.1"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-watchosarm32/0.5.1/kotlinx-rpc-krpc-ktor-core-watchosarm32-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-watchosarm32",
        "version": "0.5.1"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-watchosarm64/0.5.1/kotlinx-rpc-krpc-ktor-core-watchosarm64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-watchosarm64",
        "version": "0.5.1"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-watchosarm64/0.5.1/kotlinx-rpc-krpc-ktor-core-watchosarm64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-watchosarm64",
        "version": "0.5.1"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-watchosarm64/0.5.1/kotlinx-rpc-krpc-ktor-core-watchosarm64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-watchosarm64",
        "version": "0.5.1"
      }
    },
    {
      "name": "watchosDeviceArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-watchosdevicearm64/0.5.1/kotlinx-rpc-krpc-ktor-core-watchosdevicearm64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-watchosdevicearm64",
        "version": "0.5.1"
      }
    },
    {
      "name": "watchosDeviceArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-watchosdevicearm64/0.5.1/kotlinx-rpc-krpc-ktor-core-watchosdevicearm64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-watchosdevicearm64",
        "version": "0.5.1"
      }
    },
    {
      "name": "watchosDeviceArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-watchosdevicearm64/0.5.1/kotlinx-rpc-krpc-ktor-core-watchosdevicearm64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-watchosdevicearm64",
        "version": "0.5.1"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-watchossimulatorarm64/0.5.1/kotlinx-rpc-krpc-ktor-core-watchossimulatorarm64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-watchossimulatorarm64",
        "version": "0.5.1"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-watchossimulatorarm64/0.5.1/kotlinx-rpc-krpc-ktor-core-watchossimulatorarm64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-watchossimulatorarm64",
        "version": "0.5.1"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-watchossimulatorarm64/0.5.1/kotlinx-rpc-krpc-ktor-core-watchossimulatorarm64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-watchossimulatorarm64",
        "version": "0.5.1"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-watchosx64/0.5.1/kotlinx-rpc-krpc-ktor-core-watchosx64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-watchosx64",
        "version": "0.5.1"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-watchosx64/0.5.1/kotlinx-rpc-krpc-ktor-core-watchosx64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-watchosx64",
        "version": "0.5.1"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-rpc-krpc-ktor-core-watchosx64/0.5.1/kotlinx-rpc-krpc-ktor-core-watchosx64-0.5.1.module",
        "group": "com.vickyleu.kotlinx",
        "module": "kotlinx-rpc-krpc-ktor-core-watchosx64",
        "version": "0.5.1"
      }
    }
  ]
}
