{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-status-pages/3.1.2-SNAPSHOT/ktor-server-status-pages-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-server-status-pages",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-status-pages-jvm-3.1.2-SNAPSHOT.jar",
          "url": "ktor-server-status-pages-jvm-3.1.2-SNAPSHOT.jar",
          "size": 32706,
          "sha512": "0816b4bd3ef47219b40f99c78558f7615f23e255fe3e563f27676dfbf1826762fa4cb5dc88d5f97157d257664dc0cc103953b681b0185a423db3c3c4183d700d",
          "sha256": "1cbaedffd1b90872fae9a230918481020b2e74f2888fd8460ce4fe082746726e",
          "sha1": "d6f500f0f4fe77a4903c6b6eed4623952ac53756",
          "md5": "e74749152bf9448a5b8473a083e46e53"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-status-pages-jvm-3.1.2-SNAPSHOT.jar",
          "url": "ktor-server-status-pages-jvm-3.1.2-SNAPSHOT.jar",
          "size": 32706,
          "sha512": "0816b4bd3ef47219b40f99c78558f7615f23e255fe3e563f27676dfbf1826762fa4cb5dc88d5f97157d257664dc0cc103953b681b0185a423db3c3c4183d700d",
          "sha256": "1cbaedffd1b90872fae9a230918481020b2e74f2888fd8460ce4fe082746726e",
          "sha1": "d6f500f0f4fe77a4903c6b6eed4623952ac53756",
          "md5": "e74749152bf9448a5b8473a083e46e53"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ktor-server-status-pages-jvm-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-server-status-pages-jvm-3.1.2-SNAPSHOT-sources.jar",
          "size": 5743,
          "sha512": "e8dcb5a5db4fd8b64cc4cf69206894e8b652932e6d1e41628a31e4aed440411558118c38b8b5f5ab1d21e89462c88bad8d764cdfc9622bff4f3295b94a7f3d3a",
          "sha256": "4616fed8edea0233833fe003833b6a7f9c1c37ae93d65a3180d92b4e55222bf1",
          "sha1": "3d6a0c01278c1e7598ed24e227f9250509a26c25",
          "md5": "8e1b14fbb92604165830618c9c035c98"
        }
      ]
    }
  ]
}
