{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-rpc-grpc-core/0.5.1/kotlinx-rpc-grpc-core-0.5.1.module",
    "group": "com.vickyleu.kotlinx",
    "module": "kotlinx-rpc-grpc-core",
    "version": "0.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "com.vickyleu.kotlinx",
          "module": "kotlinx-rpc-core",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "com.vickyleu.kotlinx",
          "module": "kotlinx-rpc-utils",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-rpc-grpc-core-js-0.5.1.klib",
          "url": "kotlinx-rpc-grpc-core-js-0.5.1.klib",
          "size": 26974,
          "sha512": "6fb23c6d6e36bd8a793eef3b46bc646c6dfaa196f9821467769c24e5ccec057e7f4e7caeb075d970853c7fdb8862b1115ebe5667f42326a02ca57bacdf631b19",
          "sha256": "83c0cbacd85d4c2939f0cec5788bb1ce1989f104922c79a32d14c152c90253d9",
          "sha1": "7e497ff08de3540f41fc0889e34fd5a5f62e347d",
          "md5": "e7089686bc14e1dbbc8385f782fc6509"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "com.vickyleu.kotlinx",
          "module": "kotlinx-rpc-core",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "com.vickyleu.kotlinx",
          "module": "kotlinx-rpc-utils",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-rpc-grpc-core-js-0.5.1.klib",
          "url": "kotlinx-rpc-grpc-core-js-0.5.1.klib",
          "size": 26974,
          "sha512": "6fb23c6d6e36bd8a793eef3b46bc646c6dfaa196f9821467769c24e5ccec057e7f4e7caeb075d970853c7fdb8862b1115ebe5667f42326a02ca57bacdf631b19",
          "sha256": "83c0cbacd85d4c2939f0cec5788bb1ce1989f104922c79a32d14c152c90253d9",
          "sha1": "7e497ff08de3540f41fc0889e34fd5a5f62e347d",
          "md5": "e7089686bc14e1dbbc8385f782fc6509"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "kotlinx-rpc-grpc-core-js-0.5.1-sources.jar",
          "url": "kotlinx-rpc-grpc-core-js-0.5.1-sources.jar",
          "size": 12561,
          "sha512": "d611c7f78e2493bb3b5fa8cefedacc81cf369ca805d0062f51ada87d1672355157c5b5a6a6fd92bca7e25d202c39b7c1b36d2df9358abe89be9f5bc18b142631",
          "sha256": "44ea0c70ca04b72dbf30f1f3b12b6c623d69d581247ce8c9c9e59785bfd43778",
          "sha1": "4ee5de35978cb56eb2dfb2ecdc82741430d0779e",
          "md5": "29ee36a4d32aebb5c5320f5bd7ff1db6"
        }
      ]
    }
  ]
}
