{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-websocket-serialization/3.1.2-SNAPSHOT/ktor-websocket-serialization-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-websocket-serialization",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-serialization",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-websocket-serialization-macosX64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-websocket-serialization-macosx64-3.1.2-SNAPSHOT.klib",
          "size": 7403,
          "sha512": "e094dbec85e922853d2bceec497f8f121e17d11889a1e9768397a04191a1dc5a851ac02aefab6d1595c98e01845a914c9d616ad698958ad6a3e011a107ffdf13",
          "sha256": "a8b9f5c4f7928c3050bf8c8febc615ed5538cf09f4bbcd73f6f1924796ae780e",
          "sha1": "4759e3631b2d7e5fbf8f203e9bdd4729615492d4",
          "md5": "6f0886d8396bfccae44f9bd8fb9b4508"
        }
      ]
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-websocket-serialization-macosx64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-websocket-serialization-macosx64-3.1.2-SNAPSHOT-sources.jar",
          "size": 2326,
          "sha512": "e7fe8c5d0f1bab74755507fcfc8214bec60935736c0dc1ad54f1076115ca58f63d40702f38503b3b2a3b9d8d02ba55b91d62f5d4e326b9bcb5c454859258e3f8",
          "sha256": "e186e6ac4d88ce296ef51d91684444ca0002b4b7761a8dcd2fe55ef1dc8a7b75",
          "sha1": "4a023f031c84e174cfcb56892d01b37de32011e9",
          "md5": "0dca7e417fd69fd93f87b73d37846741"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-serialization",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-websocket-serialization-macosx64-3.1.2-SNAPSHOT-metadata.jar",
          "url": "ktor-websocket-serialization-macosx64-3.1.2-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "7b4de75e6a13c952f0d8e75528ae9245248572c888f03a5b40dac7b7e58095eb218f702d8cb069282c44a533b4eb2a8d6720aab41b66c35c35fe4bea9d37781c",
          "sha256": "3170d27fc7f7fb510f4d848fecf5f9935de4bd7be19e28ed9a95120c4130a719",
          "sha1": "2e7637201c5ae71f207c0889be11ffc200dd8547",
          "md5": "25cbc07f5cd951b099525eee3de8e10f"
        }
      ]
    }
  ]
}
