{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-test-host/3.1.2-SNAPSHOT/ktor-server-test-host-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-server-test-host",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-test-dispatcher",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-test-host-wasm-js-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-test-host-wasm-js-3.1.2-SNAPSHOT.klib",
          "size": 71792,
          "sha512": "25ef63244cf8ecc2ae305710024d5d953d74b44fc67f11c53f7df564b6939b4a3560a8577a8ff3447678ac7b6b90c400514c9afd4675ad4741815cdca42eb64f",
          "sha256": "48be923e1fe7fd350f5abf0de6cbd35794ee15a6a619ad070150f29cbf647ad5",
          "sha1": "af43e90baeaa18a6dfbbc7736e913f7dba3a9c7f",
          "md5": "9ee099196119c88689f4707e0722d7c5"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-test-dispatcher",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-browser",
          "version": {
            "requires": "0.3"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-test-host-wasm-js-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-test-host-wasm-js-3.1.2-SNAPSHOT.klib",
          "size": 71792,
          "sha512": "25ef63244cf8ecc2ae305710024d5d953d74b44fc67f11c53f7df564b6939b4a3560a8577a8ff3447678ac7b6b90c400514c9afd4675ad4741815cdca42eb64f",
          "sha256": "48be923e1fe7fd350f5abf0de6cbd35794ee15a6a619ad070150f29cbf647ad5",
          "sha1": "af43e90baeaa18a6dfbbc7736e913f7dba3a9c7f",
          "md5": "9ee099196119c88689f4707e0722d7c5"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "ktor-server-test-host-wasm-js-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-server-test-host-wasm-js-3.1.2-SNAPSHOT-sources.jar",
          "size": 20577,
          "sha512": "6ca2d4e02f7eba3268edad550b4ce943d58d41b06abddc831ad93f48a08feb6edf31774a87fe80155c5615c8710af6718112665acddd924e7bc377312810940f",
          "sha256": "ea82d11ba6c34dd7b418353304eb21737f0de4483d30afc96733e29a4cedb6ff",
          "sha1": "86eebeffc233d80becac80b7920caa490d74f075",
          "md5": "2b2bf20593b688880eeb5ee853a0499f"
        }
      ]
    }
  ]
}
