{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-serialization-kotlinx-cbor/3.1.2-SNAPSHOT/ktor-serialization-kotlinx-cbor-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-serialization-kotlinx-cbor",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-serialization-kotlinx",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-cbor",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-serialization-kotlinx-cbor-wasm-js-3.1.2-SNAPSHOT.klib",
          "url": "ktor-serialization-kotlinx-cbor-wasm-js-3.1.2-SNAPSHOT.klib",
          "size": 4785,
          "sha512": "349102241505ac24bad69c5edc30825eb07a67f85a32d4241e6a51798ebf87bf070c4607e21423d5351462222c2dac40167753d26d80959a37eb29e2a43144c7",
          "sha256": "b2fad3d1cbe24ae92c6c6b8f919459ee656157fcffdc2264cf780f9eed49abfb",
          "sha1": "ae6262df7c2f5ef31bd43bafce71139ba819636a",
          "md5": "bc80e0cf83bb5898ca6cf60aab387213"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-serialization-kotlinx",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-cbor",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-browser",
          "version": {
            "requires": "0.3"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-serialization-kotlinx-cbor-wasm-js-3.1.2-SNAPSHOT.klib",
          "url": "ktor-serialization-kotlinx-cbor-wasm-js-3.1.2-SNAPSHOT.klib",
          "size": 4785,
          "sha512": "349102241505ac24bad69c5edc30825eb07a67f85a32d4241e6a51798ebf87bf070c4607e21423d5351462222c2dac40167753d26d80959a37eb29e2a43144c7",
          "sha256": "b2fad3d1cbe24ae92c6c6b8f919459ee656157fcffdc2264cf780f9eed49abfb",
          "sha1": "ae6262df7c2f5ef31bd43bafce71139ba819636a",
          "md5": "bc80e0cf83bb5898ca6cf60aab387213"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "ktor-serialization-kotlinx-cbor-wasm-js-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-serialization-kotlinx-cbor-wasm-js-3.1.2-SNAPSHOT-sources.jar",
          "size": 1870,
          "sha512": "6527ba6b86a11193af0974c540bcd1153547c67ca907b3f669e620b95f121efe55a4c9add5935df90079b7c56419e572f4357298da1087183803e527463b4065",
          "sha256": "e2f73880e358d8e66a29281ba5e2c3f36753ab6d6e055ac2c47b18faa226b06f",
          "sha1": "20f0173fafbc1c6b72488a503626e2dcc77f65cf",
          "md5": "4ea1beebfdfdba67e54875899da0c7fc"
        }
      ]
    }
  ]
}
