{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-rpc-utils/0.5.1/kotlinx-rpc-utils-0.5.1.module",
    "group": "com.vickyleu.kotlinx",
    "module": "kotlinx-rpc-utils",
    "version": "0.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-rpc-utils-linuxArm64Main-0.5.1.klib",
          "url": "kotlinx-rpc-utils-linuxarm64-0.5.1.klib",
          "size": 28468,
          "sha512": "43832c573d0d447780ca51ecd2b186d541bd429f1d50cfe7f7b0a8884b84d8b94669692ffe8f6e496fb7f2ee4a5241cf1b41ccc6bf9d6b49c6cf196c0f818e89",
          "sha256": "4eb1e3df229b88e9aaf4736d726afe701daca40b0e54aebd98c4ee54cb65c963",
          "sha1": "4f98112bb42c92bbda0713625120f6b6a3192ac6",
          "md5": "dd5a210726689f33992c77c80627620b"
        }
      ]
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-rpc-utils-linuxarm64-0.5.1-sources.jar",
          "url": "kotlinx-rpc-utils-linuxarm64-0.5.1-sources.jar",
          "size": 7752,
          "sha512": "7fad39a6c20adcf4041b2db58f8b8a92638574d5b3686ee4f51863a9150f2c6ce1907c48386424c9542414268ae6ae4c0dc66f31c2dea563e83f03c13446fd5e",
          "sha256": "c5c87127d49690814af31b1b1cb42362cf6348256fd8ebb1719efe892c576072",
          "sha1": "86211be509882f463b68e2a9c41e6e691c3d8998",
          "md5": "50d8d6cbb0502696f86338ced7cc4ac9"
        }
      ]
    }
  ]
}
