{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-serialization-kotlinx-xml/3.1.2-SNAPSHOT/ktor-serialization-kotlinx-xml-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-serialization-kotlinx-xml",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-serialization-kotlinx",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "io.github.pdvrieze.xmlutil",
          "module": "serialization",
          "version": {
            "requires": "0.90.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-serialization-kotlinx-xml-macosArm64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-serialization-kotlinx-xml-macosarm64-3.1.2-SNAPSHOT.klib",
          "size": 5468,
          "sha512": "341645f64b7c7f21b46e59006a85376698175077b18c8ae29400334180ca9f8413f459e7baa9785145343ec7357c502f67db11b511a8a5b146e6b83272962198",
          "sha256": "b4a1fc6e73746335142b452c0c7af1029fdabb3ada1620e4930641193118b705",
          "sha1": "e97eb7d95d447c97b19528d72822bd353d1a26e1",
          "md5": "3b9cd44720c1a5d41cf17af61aad78ea"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-serialization-kotlinx-xml-macosarm64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-serialization-kotlinx-xml-macosarm64-3.1.2-SNAPSHOT-sources.jar",
          "size": 1979,
          "sha512": "9aeeb7fd7a99a42bb8fc12361313ec8b33177f610db3aefbc58ec4e0e698642dad6c2d2a9d2acd98cc6e72bac7b50790f6102ea9aa95623d490824e787cc1434",
          "sha256": "06d3f51b2b8f577df6d04f8a0bbc5d3653666f1834672941b87734824b2c67e6",
          "sha1": "2d19e6c70429404897b572b2bf182973c645bbec",
          "md5": "3058ef2254c9096c9ab3776df05857ff"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-serialization-kotlinx",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "io.github.pdvrieze.xmlutil",
          "module": "serialization",
          "version": {
            "requires": "0.90.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-serialization-kotlinx-xml-macosarm64-3.1.2-SNAPSHOT-metadata.jar",
          "url": "ktor-serialization-kotlinx-xml-macosarm64-3.1.2-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "68dda16e0fbbd6b871aca24e7bf998c3fac0ec0f1a90f8db0a978a2f2644ace561160164d0ec58ad5cba19b1cf9e67a042725e6b6d18da7193a500a9724aa552",
          "sha256": "43d2fa780c25ed1539611d140e469f6b41c24e275002cf62e0f951bd871450dd",
          "sha1": "c2956241dc0a2e5a7a11bf31bac7560b1861f64e",
          "md5": "97977cd8535ec2ffe7bb06480bc501a8"
        }
      ]
    }
  ]
}
