{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-utils/3.1.2-SNAPSHOT/ktor-utils-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-utils",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-io",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-utils-androidNativeX64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-utils-androidnativex64-3.1.2-SNAPSHOT.klib",
          "size": 302975,
          "sha512": "d1ea7bbd84f6a12ba02daa67306fc532c25c4ace917b096f60e877dd3e207fd452628023a42cd46e52a160b9b832ab566be44dcb4fd8fcc1132c2aa62f00ab3b",
          "sha256": "d4c8ca4d879dbaaa534d4a4d17b9fa846cb5ed6f0516003e9da679824b6f2dca",
          "sha1": "90a659e14ed7afc3263fa504d9c1b124b01644ef",
          "md5": "f6015f3497eb1c684720160064b79fd5"
        },
        {
          "name": "ktor-utils-androidNativeX64Cinterop-threadUtilsMain-3.1.2-SNAPSHOT.klib",
          "url": "ktor-utils-androidnativex64-3.1.2-SNAPSHOT-cinterop-threadUtils.klib",
          "size": 3602,
          "sha512": "2888ed6e3b1c029296ebc4ef7a81c73deab382ce78b7870a87fee8218cf85034760df5b62fd29be62b3c30239c58326ee3d1c650a08a525a64bc6c10fca1940e",
          "sha256": "310e6bdf8c3541b0a0afd0a787b885f473311fac54ab23a3506a88881c76d89b",
          "sha1": "e3e3c40af216886aaa9bd9d05ed0aa3478542363",
          "md5": "18d647bbda91d0bddd328e379cef202f"
        }
      ]
    },
    {
      "name": "androidNativeX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-utils-androidnativex64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-utils-androidnativex64-3.1.2-SNAPSHOT-sources.jar",
          "size": 79218,
          "sha512": "f3f6ef880e26439eeaacc8ef12eca1e4e1a9890f95b6de0bab6e929d1cb0d5934effd23fcfc0a709c0a8ad46f1841968167ed83107c81b77d1e71a261593b8c2",
          "sha256": "8e37de852133c8e41b7e02c6d233d4944819372434221175e06ebba97880bcd6",
          "sha1": "dabd10b3fea69addafe3174d2849b43f7d4f32fd",
          "md5": "1e00290f4817176c8ab39e5f08f39564"
        }
      ]
    }
  ]
}
