{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-rpc-grpc-core/0.5.1/kotlinx-rpc-grpc-core-0.5.1.module",
    "group": "com.vickyleu.kotlinx",
    "module": "kotlinx-rpc-grpc-core",
    "version": "0.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.vickyleu.kotlinx",
          "module": "kotlinx-rpc-core",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "com.vickyleu.kotlinx",
          "module": "kotlinx-rpc-utils",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-rpc-grpc-core-tvosArm64Main-0.5.1.klib",
          "url": "kotlinx-rpc-grpc-core-tvosarm64-0.5.1.klib",
          "size": 27112,
          "sha512": "2abd3c567cd8405c8d7987696dbf1b998d871b72d89da4cb538df52303a352bf35fa69daac36cc1088bf6472ed2a6d929e2f1db1c2e503dd7275a297a65cbbac",
          "sha256": "7132a7bb633500954e4f7674a673687c14227a748985abd52000927263e9ce26",
          "sha1": "aa66555a95a15789342fafb19deefd6db031ffe2",
          "md5": "6b4b9cd64d5b4fdb75252f0053187db9"
        }
      ]
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-rpc-grpc-core-tvosarm64-0.5.1-sources.jar",
          "url": "kotlinx-rpc-grpc-core-tvosarm64-0.5.1-sources.jar",
          "size": 12685,
          "sha512": "1c028a19fcfe6aa96896f204810f2073d503f0d030843f776c7affbe138fb776ff48e5d6af12a8cd273c3a54c356bc036812279d381c7bab02b5df0cc6f4c4e4",
          "sha256": "5069a1611d0c6a54088696a489c52ca25f1c8783b0271f3c22903cf05dfbce9a",
          "sha1": "ef560803272fe29a47d3260da2b2b1680534a72a",
          "md5": "fc8a57bd8f4e13920a47454c0b84ba7e"
        }
      ]
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.vickyleu.kotlinx",
          "module": "kotlinx-rpc-core",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "com.vickyleu.kotlinx",
          "module": "kotlinx-rpc-utils",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-rpc-grpc-core-tvosarm64-0.5.1-metadata.jar",
          "url": "kotlinx-rpc-grpc-core-tvosarm64-0.5.1-metadata.jar",
          "size": 261,
          "sha512": "d9a1b8d49c349effd1fcb337059e58ebe34b9d5f10a4de3d4559d9b126e92ce3b5f988e8e26fea4b6136b10e4011d56f52807154466824c9046b4b8718720094",
          "sha256": "20a8baa3fd7c4dc78cb4ea09ef5f7ad259891495da96493fe6d201a96b4896ac",
          "sha1": "5fb84c6cc9a0a129edb9f7b90a873d17e7ccba0d",
          "md5": "c08bd473ddbf908ad04a4b9834de6251"
        }
      ]
    }
  ]
}
