{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-http/3.1.2-SNAPSHOT/ktor-http-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-http",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-utils",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-http-androidNativeArm64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-http-androidnativearm64-3.1.2-SNAPSHOT.klib",
          "size": 397951,
          "sha512": "4f9ae255965a90eb8089a08090161e6dbfa0324a0b90c7865fb2e1415074b239760907edec89083b32bec42fc29ae848172c05707861edcba2d6af9e3a57adb0",
          "sha256": "afe0d71d78390e5b3ac3f06424cca51e8e0298cf52d6eae0e72ae9a75cf7625e",
          "sha1": "e907809832512255378cb48e14b2933d91b79ec9",
          "md5": "7e317fa660da5d87e24d7e014dc47d24"
        }
      ]
    },
    {
      "name": "androidNativeArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-http-androidnativearm64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-http-androidnativearm64-3.1.2-SNAPSHOT-sources.jar",
          "size": 88187,
          "sha512": "c643a94f0720cb2d499b38e0c384e929d976b7becbbbe771ebc65852b59bba4c1268c32e52ac06dce1eed64c0b11297170b856619f0df326e698fac5b3a84566",
          "sha256": "3a2ccc35b4cae3370861cf34f506dd2c85af1e4cbd34ff563f1b19efd9f82c36",
          "sha1": "fd340df2b5c3ee4286a2cb8f1860b35a54ebf331",
          "md5": "3ba0cbcd501b20e35666ce00cdb915ea"
        }
      ]
    }
  ]
}
