{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-serialization-kotlinx-xml/3.1.2-SNAPSHOT/ktor-serialization-kotlinx-xml-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-serialization-kotlinx-xml",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-serialization-kotlinx",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "io.github.pdvrieze.xmlutil",
          "module": "serialization",
          "version": {
            "requires": "0.90.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-serialization-kotlinx-xml-macosX64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-serialization-kotlinx-xml-macosx64-3.1.2-SNAPSHOT.klib",
          "size": 5451,
          "sha512": "4c4fc6ca813bc8a4f76300c09e2cb77b2b6c46242ccdb87eef3f6620d2efe062797ae0cd8db9633b2ee10d5c902a8bdf0160972eba184a80cd8d36be2e7ca2ee",
          "sha256": "d8d3d520091f39316a201eb5770ad8694a83cff2379aac33953d88ae8685da3f",
          "sha1": "d452def9669eed6a2207ef436cc32f8dc6a3936e",
          "md5": "6b474708c2fc5b0304cdf4556afbcd5b"
        }
      ]
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-serialization-kotlinx-xml-macosx64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-serialization-kotlinx-xml-macosx64-3.1.2-SNAPSHOT-sources.jar",
          "size": 1979,
          "sha512": "9aeeb7fd7a99a42bb8fc12361313ec8b33177f610db3aefbc58ec4e0e698642dad6c2d2a9d2acd98cc6e72bac7b50790f6102ea9aa95623d490824e787cc1434",
          "sha256": "06d3f51b2b8f577df6d04f8a0bbc5d3653666f1834672941b87734824b2c67e6",
          "sha1": "2d19e6c70429404897b572b2bf182973c645bbec",
          "md5": "3058ef2254c9096c9ab3776df05857ff"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-serialization-kotlinx",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "io.github.pdvrieze.xmlutil",
          "module": "serialization",
          "version": {
            "requires": "0.90.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-serialization-kotlinx-xml-macosx64-3.1.2-SNAPSHOT-metadata.jar",
          "url": "ktor-serialization-kotlinx-xml-macosx64-3.1.2-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "83ff20db75f0fb791ab60df50657a7f63e9f819d7f9e167f1880c6206c04a6dd08c478f2a21c5dbbfffda6e77ee5452d43d8bc7b83b8cb8f52d388c70a2bd726",
          "sha256": "d2caa0aa2b4ce6149cd4661a42c557a02f32efbc274351c1eb1a466b862f6b5d",
          "sha1": "7dc82a589a5913deca710d7ab4126db812d9fa80",
          "md5": "6e5d1ef2d67a916d3817e62f765a3e4e"
        }
      ]
    }
  ]
}
