{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-rpc-krpc-logging/0.5.1/kotlinx-rpc-krpc-logging-0.5.1.module",
    "group": "com.vickyleu.kotlinx",
    "module": "kotlinx-rpc-krpc-logging",
    "version": "0.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "linuxArm32HfpApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm32_hfp",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.6"
          }
        },
        {
          "group": "com.vickyleu.kotlinx",
          "module": "kotlinx-rpc-utils",
          "version": {
            "requires": "0.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-rpc-krpc-logging-linuxArm32HfpMain-0.5.1.klib",
          "url": "kotlinx-rpc-krpc-logging-linuxarm32hfp-0.5.1.klib",
          "size": 12436,
          "sha512": "ecc1f953fcbe23441b5e8067c9f2b797dacda5428b5ba96c6105fbe647efaeb683586df8f0598d49d5f6e039922dd978a34b9da2d7ba3db81c6e9d347413716c",
          "sha256": "3b544d5a283f0cde3b86f536c3321b62d5fb9e46c26a2d4a976bac46148ff26b",
          "sha1": "0d53870507cf70d49d5dba7281343e1b036f010c",
          "md5": "62ed32409838e62f66968b3ecb7f756c"
        }
      ]
    },
    {
      "name": "linuxArm32HfpSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm32_hfp",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-rpc-krpc-logging-linuxarm32hfp-0.5.1-sources.jar",
          "url": "kotlinx-rpc-krpc-logging-linuxarm32hfp-0.5.1-sources.jar",
          "size": 3141,
          "sha512": "02123f3be3ee56a880ea0742c1ea34d5e0e61f63530f12524c374fcf6f5f083a687f36115fbdac268315f88b26e6132ab5b514b88d71dbf081e7127f8912f6d6",
          "sha256": "8e48b530ee5752910707bf402ff89d304e9cd21d60d6b841a0b29bd4b6413cf0",
          "sha1": "9a949afff48ebd85331320e4b8d5a8da07bb1f66",
          "md5": "1da329d6bc94828d33ab4607a09699a0"
        }
      ]
    }
  ]
}
