{
  "formatVersion": "1.1",
  "component": {
    "group": "com.vickyleu.ktor",
    "module": "ktor-server-openapi",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-openapi-metadata-3.1.2-SNAPSHOT.jar",
          "url": "ktor-server-openapi-3.1.2-SNAPSHOT.jar",
          "size": 706,
          "sha512": "de218952a708817036586113e86855ad2030b31752cdf57f04eff111a43d6f106149368e964a0125f548cac689b4ad6aafa922b8c86323222793fca36c03330c",
          "sha256": "2ada642fdf3b95c5dbe9fc485e8437f393d24656c2065103479662829bb0bf08",
          "sha1": "97784df915b27ac7050812e63f952083c59aab3f",
          "md5": "596c96e7ed0c1bd868fb02d900faa2cb"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "ktor-server-openapi-kotlin-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-server-openapi-3.1.2-SNAPSHOT-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktor-server-openapi-jvm/3.1.2-SNAPSHOT/ktor-server-openapi-jvm-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-openapi-jvm",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktor-server-openapi-jvm/3.1.2-SNAPSHOT/ktor-server-openapi-jvm-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-openapi-jvm",
        "version": "3.1.2-SNAPSHOT"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktor-server-openapi-jvm/3.1.2-SNAPSHOT/ktor-server-openapi-jvm-3.1.2-SNAPSHOT.module",
        "group": "com.vickyleu.ktor",
        "module": "ktor-server-openapi-jvm",
        "version": "3.1.2-SNAPSHOT"
      }
    }
  ]
}
