{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-serialization-kotlinx/3.1.2-SNAPSHOT/ktor-serialization-kotlinx-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-serialization-kotlinx",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-serialization",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-serialization-kotlinx-wasm-js-3.1.2-SNAPSHOT.klib",
          "url": "ktor-serialization-kotlinx-wasm-js-3.1.2-SNAPSHOT.klib",
          "size": 23316,
          "sha512": "afae5ed2aed8be8d020dcfd9ce9faf2e7cc5b37632552a5f186083deb0dad16caea1c1328fea9a3082bcec4e1f4e524aa3eb474f9401269057c77b1869adfad4",
          "sha256": "b21979fd9419e4c851a5dcbd410a217956800517f99bc8d4bd256d672615990b",
          "sha1": "ba1e0a61d8ee3aa147546193489aae73aa4fff6a",
          "md5": "099cd55731bbf166b1a048ad320489a0"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-serialization",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-browser",
          "version": {
            "requires": "0.3"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-serialization-kotlinx-wasm-js-3.1.2-SNAPSHOT.klib",
          "url": "ktor-serialization-kotlinx-wasm-js-3.1.2-SNAPSHOT.klib",
          "size": 23316,
          "sha512": "afae5ed2aed8be8d020dcfd9ce9faf2e7cc5b37632552a5f186083deb0dad16caea1c1328fea9a3082bcec4e1f4e524aa3eb474f9401269057c77b1869adfad4",
          "sha256": "b21979fd9419e4c851a5dcbd410a217956800517f99bc8d4bd256d672615990b",
          "sha1": "ba1e0a61d8ee3aa147546193489aae73aa4fff6a",
          "md5": "099cd55731bbf166b1a048ad320489a0"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "ktor-serialization-kotlinx-wasm-js-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-serialization-kotlinx-wasm-js-3.1.2-SNAPSHOT-sources.jar",
          "size": 6810,
          "sha512": "23afc65cb684213648ea478ad1904fef96ec800c1ad51326d7d398cdeab0ba5f773ae1b8f1e9e88ddf4e9a13dc7a7edf609340fd01eb1d945b3c03fb065f1bf5",
          "sha256": "6c914a56613c75c0f989a101783dc863868e4312bbdc2e3a505dc90c9c3bfa2c",
          "sha1": "46676e880fbf7df45537136cd11336531d8ceae0",
          "md5": "64e7447a3964e08c64dd7df184719455"
        }
      ]
    }
  ]
}
