{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-rpc-krpc-serialization-json/0.6.1/kotlinx-rpc-krpc-serialization-json-0.6.1.module",
    "group": "com.vickyleu.kotlinx",
    "module": "kotlinx-rpc-krpc-serialization-json",
    "version": "0.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.vickyleu.kotlinx",
          "module": "kotlinx-rpc-krpc-serialization-core",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-rpc-krpc-serialization-json-macosArm64Main-0.6.1.klib",
          "url": "kotlinx-rpc-krpc-serialization-json-macosarm64-0.6.1.klib",
          "size": 5819,
          "sha512": "2b29125a011dac4774fc244266e68000527f36c902069cb4cdcf58fa9915791b4fe73c989656a08c8c057fe0cd5d00dda7b491980272d3534b038a38ecb81902",
          "sha256": "2dc447999e68ea2e2044060fe1beb029b0cd82b8a4d30fe081032532ace287e1",
          "sha1": "be8170f1171222e71434b16e60c929f86a69c905",
          "md5": "524e84b3f68be4cf3f1caca3c3959ce8"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-rpc-krpc-serialization-json-macosarm64-0.6.1-sources.jar",
          "url": "kotlinx-rpc-krpc-serialization-json-macosarm64-0.6.1-sources.jar",
          "size": 1798,
          "sha512": "2086cb1b4aa13165230f4850920c3783e81ec5b7d6d05eebec712926fceae449d210fd1dd28c6f59389ca75cf2e5a0fa7bb39ed0a41349f4891530b2b0d1dccb",
          "sha256": "3b20394fe01bd912868a137d96fe034c69bfc12f367bd9bacfc3347bb79f65b7",
          "sha1": "83fe9f452dc22cdb84ef05410f92df7278351cea",
          "md5": "a5805796c60dcf233c8fd6b4187ac2a3"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.vickyleu.kotlinx",
          "module": "kotlinx-rpc-krpc-serialization-core",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-rpc-krpc-serialization-json-macosarm64-0.6.1-metadata.jar",
          "url": "kotlinx-rpc-krpc-serialization-json-macosarm64-0.6.1-metadata.jar",
          "size": 261,
          "sha512": "32b560855943a290f051d9bf25976e0d8ab66fb15916de2bb095666c16cb7abd72040ca96dbf08bd34898a3bf37925d01d13c6d0d82dfcb11909139a87698079",
          "sha256": "d35b1944d4ef854454b6e54396e7363123ca5b9e2759776ccdcf2da2ace11d8f",
          "sha1": "6f87c186a59fd1d36c046340bb9f15cec86d91a7",
          "md5": "dae85714f941d400ca2b65337f0e11fb"
        }
      ]
    }
  ]
}
