{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-auto-head-response/3.1.2-SNAPSHOT/ktor-server-auto-head-response-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-server-auto-head-response",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-auto-head-response-androidNativeArm64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-auto-head-response-androidnativearm64-3.1.2-SNAPSHOT.klib",
          "size": 8594,
          "sha512": "83b285dbf6e124471e1ec6dcce90425c8298ec859f2cdc652ed60ce79af39bd92744ec639a519a4f666083d2647b21ee53496918ad85ce3945c825cfa2f6dd8b",
          "sha256": "2074c20d1df92e78e3cc319c3cc478aa74f42320c5c8059fdda8f50dbf97da98",
          "sha1": "3925330c107e188b4588e554d6ac3b7e28836527",
          "md5": "5277fb97713b1f3a6537a21cdbdb8746"
        }
      ]
    },
    {
      "name": "androidNativeArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-server-auto-head-response-androidnativearm64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-server-auto-head-response-androidnativearm64-3.1.2-SNAPSHOT-sources.jar",
          "size": 2047,
          "sha512": "07995b089bf9365a232699cc86359f9068cb1265816943f421ad2eb37dd2e2bace2519bf7b0913c69ba4363bc14474b732552f7c93626c550802579b1967b530",
          "sha256": "561ccd5f736e5397a51c1d076cac900331d69176e5fab54db4f1cb45747fce3c",
          "sha1": "10284cbff643086f949494e7698256b3e1f6569a",
          "md5": "ccb90f8a40d6e4e990fdf7aab05a9894"
        }
      ]
    }
  ]
}
