{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-rpc-krpc-serialization-protobuf/0.6.1/kotlinx-rpc-krpc-serialization-protobuf-0.6.1.module",
    "group": "com.vickyleu.kotlinx",
    "module": "kotlinx-rpc-krpc-serialization-protobuf",
    "version": "0.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "linuxArm32HfpApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm32_hfp",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.vickyleu.kotlinx",
          "module": "kotlinx-rpc-krpc-serialization-core",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-protobuf",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-rpc-krpc-serialization-protobuf-linuxArm32HfpMain-0.6.1.klib",
          "url": "kotlinx-rpc-krpc-serialization-protobuf-linuxarm32hfp-0.6.1.klib",
          "size": 6110,
          "sha512": "aaaaffcb66d4e475f1ae390b3dbbc46fef5968029db96acdd6c4b12b64ae38a21efe20ea457205e5bc285492f3268f9f2cfbf8cd52f69ba65f23d3c3c0690629",
          "sha256": "988d368cdc4183e9ffc27d5ae42a7be5861648ef09d48e025ca6fe7a24b94600",
          "sha1": "8117a1fd7a4b7c3bde31df7ab1ad64c9116a518e",
          "md5": "ab790de97c1db69c82d36baea3f2f283"
        }
      ]
    },
    {
      "name": "linuxArm32HfpSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm32_hfp",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-rpc-krpc-serialization-protobuf-linuxarm32hfp-0.6.1-sources.jar",
          "url": "kotlinx-rpc-krpc-serialization-protobuf-linuxarm32hfp-0.6.1-sources.jar",
          "size": 1873,
          "sha512": "e9209f4cf666a4cf8edf6f7fa2532f7658ee28a96d1db5084cfad28bde3eea4abf92ab5d0052fac4af52dbd24ec16ee2498b534fb72da8ca1f8f313d5c52a537",
          "sha256": "cf4fbd9c6889287af2dd983a3d478b0b1e1440e824a93c119c4a1355d069e58c",
          "sha1": "991b37a09103cabb1c76cb78ae3b8128d73f88c1",
          "md5": "d39b8e13e9f676f9ac005fdc9fdd0578"
        }
      ]
    }
  ]
}
