{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-config-yaml/3.1.2-SNAPSHOT/ktor-server-config-yaml-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-server-config-yaml",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "net.mamoe.yamlkt",
          "module": "yamlkt",
          "version": {
            "requires": "0.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-config-yaml-iosArm64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-config-yaml-iosarm64-3.1.2-SNAPSHOT.klib",
          "size": 22492,
          "sha512": "c7e81a4fbf4f8f57a33d0ec69306f35ffc14dd10c264f11ff6958e23e7a84d085480a3a3675fb30f0e8f953f012864b3f5a8dc58354f8b19eea2e9866c558584",
          "sha256": "0e449b643d54d9530e7d79eabec0e866669a825a40881007144d89dd047bef62",
          "sha1": "06291a54e649767663c6dc8018bd4c9d09c4114f",
          "md5": "3fa9f8f3d1258bf489998c9bb3faabf2"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-server-config-yaml-iosarm64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-server-config-yaml-iosarm64-3.1.2-SNAPSHOT-sources.jar",
          "size": 5329,
          "sha512": "d68e916f46059fc19312ae15f89dfc17e8a6ca898954fb8e0208f1b40828ab4450abe79ee3d8efd3e14dae48007ef19de3f07be7d491d682762aa3fe8bbdcc4c",
          "sha256": "289357a3e424d746e6e9c07c38fcc3eb578c1a0226aa896a07350ab620297275",
          "sha1": "20f198e992dad7fd662a65010cfce5c0b1ae52a3",
          "md5": "d810bb79f92c547396cd093e1b77c622"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "net.mamoe.yamlkt",
          "module": "yamlkt",
          "version": {
            "requires": "0.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-config-yaml-iosarm64-3.1.2-SNAPSHOT-metadata.jar",
          "url": "ktor-server-config-yaml-iosarm64-3.1.2-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "62ba2c339fc538c4095cfc9850239253dd814579bcd2cceb7b7bce95589d8464eacc07dba21ccfa465bacda142661f63eeb49d1c924db7dd152dcde5a3cbe791",
          "sha256": "7014d0eed8c61f9249ed5f686af008e727e69323c8e808980fccf0876680f09f",
          "sha1": "3cb22452ceed459587860f2ea7e822e489a61f5f",
          "md5": "05c43e1ae0e13bb88daca9a61a22844b"
        }
      ]
    }
  ]
}
