{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-websockets/3.1.2-SNAPSHOT/ktor-websockets-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-websockets",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-utils",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-websockets-js-3.1.2-SNAPSHOT.klib",
          "url": "ktor-websockets-js-3.1.2-SNAPSHOT.klib",
          "size": 80663,
          "sha512": "bdea5a157a762b1c8fb1b7e676f135718b260c7fa94c016f99a02511afa423d600dac1a3d7b211f8fbfa7495e4bbdfefe86fb1b0c1000d0916ae3637080b6f71",
          "sha256": "47769876592304ebd88c56742b5354595e552a0fb3b787e5052cde3b06289e6b",
          "sha1": "bea9336335302ddaabf16cc4f178a7b3345a5268",
          "md5": "54ce605c4e6cffc19fcfc518751db72d"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-utils",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-websockets-js-3.1.2-SNAPSHOT.klib",
          "url": "ktor-websockets-js-3.1.2-SNAPSHOT.klib",
          "size": 80663,
          "sha512": "bdea5a157a762b1c8fb1b7e676f135718b260c7fa94c016f99a02511afa423d600dac1a3d7b211f8fbfa7495e4bbdfefe86fb1b0c1000d0916ae3637080b6f71",
          "sha256": "47769876592304ebd88c56742b5354595e552a0fb3b787e5052cde3b06289e6b",
          "sha1": "bea9336335302ddaabf16cc4f178a7b3345a5268",
          "md5": "54ce605c4e6cffc19fcfc518751db72d"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "ktor-websockets-js-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-websockets-js-3.1.2-SNAPSHOT-sources.jar",
          "size": 22640,
          "sha512": "324cdf2c01ade21772ddf7282d9a9e46bcf18916e53607fa6206a684c99cc3d01a06bfb1218f3d35cdfbee59dee09031247ed358fa085215659c527005802c8f",
          "sha256": "680428ce34cd73aca55a9ffe2893234505d6563059f8a242728961fb2570ec02",
          "sha1": "3b2376463e2af31f3faeb830ac04bf3fb1266054",
          "md5": "5314473950d22b5e989214ffaad5dd5b"
        }
      ]
    }
  ]
}
