{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-rpc-krpc-serialization-protobuf/0.6.1/kotlinx-rpc-krpc-serialization-protobuf-0.6.1.module",
    "group": "com.vickyleu.kotlinx",
    "module": "kotlinx-rpc-krpc-serialization-protobuf",
    "version": "0.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.vickyleu.kotlinx",
          "module": "kotlinx-rpc-krpc-serialization-core",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-protobuf",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-rpc-krpc-serialization-protobuf-jvm-0.6.1.jar",
          "url": "kotlinx-rpc-krpc-serialization-protobuf-jvm-0.6.1.jar",
          "size": 4533,
          "sha512": "8e7abd626e3ed0fe86f2b9d22c8413df4598a5801dc3599577edae5297f363e60385d99f341206a29a0a7c637f72b15b4addb7eb047fca33fc5b50f11a31d319",
          "sha256": "660b40c4bf320c34030847ec5a0dd682480b319999ea729ec7319a76fb6d5d49",
          "sha1": "5115104ad89cdd3cb33fc11dba0a2712119cf602",
          "md5": "edb86a4ecdd0d96e6563b5048a664d7f"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.vickyleu.kotlinx",
          "module": "kotlinx-rpc-krpc-serialization-core",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-protobuf",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-rpc-krpc-serialization-protobuf-jvm-0.6.1.jar",
          "url": "kotlinx-rpc-krpc-serialization-protobuf-jvm-0.6.1.jar",
          "size": 4533,
          "sha512": "8e7abd626e3ed0fe86f2b9d22c8413df4598a5801dc3599577edae5297f363e60385d99f341206a29a0a7c637f72b15b4addb7eb047fca33fc5b50f11a31d319",
          "sha256": "660b40c4bf320c34030847ec5a0dd682480b319999ea729ec7319a76fb6d5d49",
          "sha1": "5115104ad89cdd3cb33fc11dba0a2712119cf602",
          "md5": "edb86a4ecdd0d96e6563b5048a664d7f"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlinx-rpc-krpc-serialization-protobuf-jvm-0.6.1-sources.jar",
          "url": "kotlinx-rpc-krpc-serialization-protobuf-jvm-0.6.1-sources.jar",
          "size": 1873,
          "sha512": "e9209f4cf666a4cf8edf6f7fa2532f7658ee28a96d1db5084cfad28bde3eea4abf92ab5d0052fac4af52dbd24ec16ee2498b534fb72da8ca1f8f313d5c52a537",
          "sha256": "cf4fbd9c6889287af2dd983a3d478b0b1e1440e824a93c119c4a1355d069e58c",
          "sha1": "991b37a09103cabb1c76cb78ae3b8128d73f88c1",
          "md5": "d39b8e13e9f676f9ac005fdc9fdd0578"
        }
      ]
    }
  ]
}
