{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-rpc-krpc-serialization-cbor/0.5.1/kotlinx-rpc-krpc-serialization-cbor-0.5.1.module",
    "group": "com.vickyleu.kotlinx",
    "module": "kotlinx-rpc-krpc-serialization-cbor",
    "version": "0.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.vickyleu.kotlinx",
          "module": "kotlinx-rpc-krpc-serialization-core",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-cbor",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-rpc-krpc-serialization-cbor-watchosArm64Main-0.5.1.klib",
          "url": "kotlinx-rpc-krpc-serialization-cbor-watchosarm64-0.5.1.klib",
          "size": 6032,
          "sha512": "2a79bb14ee56dfe92570bcf0ce95a2ce027b893b1621572e0da0024c5ff47236b360b6d2ad10e378bfec9bb6d05b4daf68ed2f36deb28ebae0e234017ad19499",
          "sha256": "424bf0b49800a5c67215fafb8b5e6536b991f63bc31a9b269223ed5c30388db7",
          "sha1": "4be01b35625cdba84b9125e923d72cda76286518",
          "md5": "a68b01b3739461144b8df6fccc9f7c3a"
        }
      ]
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-rpc-krpc-serialization-cbor-watchosarm64-0.5.1-sources.jar",
          "url": "kotlinx-rpc-krpc-serialization-cbor-watchosarm64-0.5.1-sources.jar",
          "size": 1837,
          "sha512": "e1a38ea3dd9b0bfe95c4f50514efdf90abc77141251c922725b74d64db4aec0dd0a402dc4b3a66f3589deb3f894aaa1857aee02ba6a1d3e67650ffa697f4dfa8",
          "sha256": "408e0301990ed0177e9be4300d03b26199cf1ec08006e2345823d3764afd4ee5",
          "sha1": "8482660a6af8728c37763eb361700b106fc46559",
          "md5": "c49b02ce05e3078bad387bcc627f9214"
        }
      ]
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.vickyleu.kotlinx",
          "module": "kotlinx-rpc-krpc-serialization-core",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-cbor",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-rpc-krpc-serialization-cbor-watchosarm64-0.5.1-metadata.jar",
          "url": "kotlinx-rpc-krpc-serialization-cbor-watchosarm64-0.5.1-metadata.jar",
          "size": 261,
          "sha512": "cf81e762d07422acf94f938385f5fc49c137124458da3d2e94ae7bbdb7961e00656f7a6da896a52afa0882aae6090857bb6998005f6e161cfcb6fdd1affe87e1",
          "sha256": "fd20ea4b77971d67c4a38cea85db2301e371d9a94b07c7d8283bf0fc8802a9ef",
          "sha1": "adf5382f25b22fe8188fed560a737dd78694cdb5",
          "md5": "a15621734b0e44a82989b6b0cd2ff86e"
        }
      ]
    }
  ]
}
