{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-http/3.1.2-SNAPSHOT/ktor-http-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-http",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-utils",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-http-js-3.1.2-SNAPSHOT.klib",
          "url": "ktor-http-js-3.1.2-SNAPSHOT.klib",
          "size": 399320,
          "sha512": "ccf2a9932f456820069c4881f131cf6b912984ad9c1b70d0c0bfe67136ed026970c3759fbf41fc124ff427a2bb6960cd708b9f51e581718cf46defc786d4b96a",
          "sha256": "ea695ae173d650f6581f6210c06e5af5da6cd2315e8c5c449c84b998b08b80e9",
          "sha1": "fc50440c8bc630b858a2e9c61f532a8e1a64a9a4",
          "md5": "39c5a0e16a4b3fac543e3805b7c7f0e5"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-utils",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-http-js-3.1.2-SNAPSHOT.klib",
          "url": "ktor-http-js-3.1.2-SNAPSHOT.klib",
          "size": 399320,
          "sha512": "ccf2a9932f456820069c4881f131cf6b912984ad9c1b70d0c0bfe67136ed026970c3759fbf41fc124ff427a2bb6960cd708b9f51e581718cf46defc786d4b96a",
          "sha256": "ea695ae173d650f6581f6210c06e5af5da6cd2315e8c5c449c84b998b08b80e9",
          "sha1": "fc50440c8bc630b858a2e9c61f532a8e1a64a9a4",
          "md5": "39c5a0e16a4b3fac543e3805b7c7f0e5"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "ktor-http-js-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-http-js-3.1.2-SNAPSHOT-sources.jar",
          "size": 88489,
          "sha512": "d393dbd01efb12f4a954f1829aa46013b16e5aaa2e41d6b66f7a73e9546c5606b79a9570b7e755a701285b8d02783ecef2a87b1dd1ff339bc3915621b633b90a",
          "sha256": "42c7d5c1cac58f36c1cdfd878966c3be9fd903f8440cb42f47354970fa911b84",
          "sha1": "f0b86216d2e4add2c7ff9851c57ff3b6ba9f3069",
          "md5": "1b203b1806204f423e3ed79af9f2726c"
        }
      ]
    }
  ]
}
