{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-client-call-id/3.1.2-SNAPSHOT/ktor-client-call-id-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-client-call-id",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-call-id",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-call-id-watchosSimulatorArm64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-client-call-id-watchossimulatorarm64-3.1.2-SNAPSHOT.klib",
          "size": 9413,
          "sha512": "4cddf77576ae18b8f8a42bc273f5e3a4fdcda928877308c7d5cf8f4eca3c6501485f0bb2ee59b423e0f95c26cb5d2192ea1d96faf07c2710773a19a90da6cc55",
          "sha256": "a60eec6c3b6b1ea31b44f8ea153028035e3f083fc9e453bc9bbe5810033f5f2f",
          "sha1": "946c70e6945b4dac7ca7de1ac622288981f2805d",
          "md5": "e5ec27b96fb4cd4803235edf2238fb1d"
        }
      ]
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-client-call-id-watchossimulatorarm64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-client-call-id-watchossimulatorarm64-3.1.2-SNAPSHOT-sources.jar",
          "size": 2506,
          "sha512": "27e738a52f49027777d268ffc9681b6d77bfb24491339d64c40e86f52b923966e14244e25da1b7247549e3d9ec1f2400c67295656cbfaf123e436cebec8af3ca",
          "sha256": "1826e0e98aacdef554a0f28d7652f8ba2c9d5a750ef370030916dde285c5ef58",
          "sha1": "6afdf7bce3ec1ac79956ecd9404c3f826b18cc2f",
          "md5": "c1ad4529a5cb057b40ed86a0ca7440dd"
        }
      ]
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-call-id",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-call-id-watchossimulatorarm64-3.1.2-SNAPSHOT-metadata.jar",
          "url": "ktor-client-call-id-watchossimulatorarm64-3.1.2-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "5f5be5743ed66bc4fe33b9a73f718838a89e4d564f12934c60469c2fcde978bb337b639c9bc4a2a46a906f03f944052740ce937a08f007fa29e2f06a19eb8925",
          "sha256": "3f3e328f4fdfeeee63535110810f5a91c3b7f13264912506d2a1d8b79e4b7bef",
          "sha1": "d0905b219271fb1c2c9d8d5fc15addaa27628657",
          "md5": "803464039072e06c15e465481ca16d20"
        }
      ]
    }
  ]
}
