{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-serialization-kotlinx-protobuf/3.1.2-SNAPSHOT/ktor-serialization-kotlinx-protobuf-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-serialization-kotlinx-protobuf",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-serialization-kotlinx",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-protobuf",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-serialization-kotlinx-protobuf-iosArm64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-serialization-kotlinx-protobuf-iosarm64-3.1.2-SNAPSHOT.klib",
          "size": 5232,
          "sha512": "4af3dbec302e0f2e80b34d4a27d06036feb7fdff5bdd0809cb5bc2dfe8762322444b1a0133b1fde0195d187057ef39d3a9de8ea1532b78fbb36fbfd709934acd",
          "sha256": "73fa134160d782f2b0a534d30bfdc0855130884b35272be61de1905d6742213f",
          "sha1": "3d166a5c10a0daadcc09002105a4aa3d80bda036",
          "md5": "7a09ea50b02b88b9d638250b7cd63e2f"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-serialization-kotlinx-protobuf-iosarm64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-serialization-kotlinx-protobuf-iosarm64-3.1.2-SNAPSHOT-sources.jar",
          "size": 1883,
          "sha512": "ccd4a4956796e1a9fc47ac2c6a00a0def3ae5e0196b9713b68b6d2683bcc0a9e1a8b3e8b0563d5ef9afceb7c611f83331bdd8c395f00f81e79839b0446ad6006",
          "sha256": "288e80b0ef85987639a638f55e01003c702d465d5f4eb4190ad40fa21068c719",
          "sha1": "eb22a47313447a98eb7fa43797da478ebd732a97",
          "md5": "ed9f6db16d0e72c9875230e24cef0358"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-serialization-kotlinx",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-protobuf",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-serialization-kotlinx-protobuf-iosarm64-3.1.2-SNAPSHOT-metadata.jar",
          "url": "ktor-serialization-kotlinx-protobuf-iosarm64-3.1.2-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "2aa09a2de96b06b53b9f59bb7dcffb9c56b120554a6a825b3675ff37461e848fd7a2ebe31e1e138f838a087fe757762b8045b8a8813fd34219082aabb7f04b83",
          "sha256": "befa2c1c58dab5c2ae19fdc2e70f4c2434ee30c39516639b1938e18a535b5da5",
          "sha1": "e698bc9f3e43e08c9ecc80ca22b9b6bb22bb0296",
          "md5": "1f79e75174fd22f9bbb54cb147fba103"
        }
      ]
    }
  ]
}
