{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-client-resources/3.1.2-SNAPSHOT/ktor-client-resources-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-client-resources",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-resources",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-resources-macosArm64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-client-resources-macosarm64-3.1.2-SNAPSHOT.klib",
          "size": 14289,
          "sha512": "26e1163903e5be5baf04ad9eea72a9b4b61bf84b0b58abfc6f8f856d635ee66d39b65bef269e516f86175a591d20a179fb0c40aeb460d9da5c9bdc4689f73f93",
          "sha256": "71e4f3bf33c6a7f8a0e973f955dd38afab0665b0fc0196577522309aac860837",
          "sha1": "31d8340aef9607dfc829899adfb7f588b118ffb0",
          "md5": "190ec614576cc59676e7f10306a2bf14"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-client-resources-macosarm64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-client-resources-macosarm64-3.1.2-SNAPSHOT-sources.jar",
          "size": 3136,
          "sha512": "706189f301591d972aa8d0ed6392494c089803514a937e2e668ef5ae18fef05f321aae528be5aab14c6fcfb349fdde59e70fd09cd7b097c205c2926e0a2da141",
          "sha256": "def50199f4a4d61ba1815b9a92c095bd40e597c89bb457cc54ac66ba7a913056",
          "sha1": "7956bf2805277930998cb19d49cb0213cac76ee7",
          "md5": "61513bf3a8fa40b702835573d042ac52"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-resources",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-resources-macosarm64-3.1.2-SNAPSHOT-metadata.jar",
          "url": "ktor-client-resources-macosarm64-3.1.2-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "7a6c7cf995ffe56499098130a46ba5da42eaaf405d10b4a6d35c0a155aaa8e79b8264464f18e5b132a3409c78bbd293f89876ed93d9a9a849407d2a4aa22da76",
          "sha256": "b9e853967aae7356ae17b4ce08597f8c29956f74a1b7771161f810d49c1f4d9c",
          "sha1": "dd59d6f2bc0262bf0d749d609818c398b440f6b6",
          "md5": "70f6bb6ce449cc02228776a43057b853"
        }
      ]
    }
  ]
}
