{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-client-content-negotiation/3.1.2-SNAPSHOT/ktor-client-content-negotiation-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-client-content-negotiation",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-serialization",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-content-negotiation-js-3.1.2-SNAPSHOT.klib",
          "url": "ktor-client-content-negotiation-js-3.1.2-SNAPSHOT.klib",
          "size": 22472,
          "sha512": "d706084aeb608272fc6ddc0f435a765a72ad306e5f1cd0ed5f2eae041c57bfcb739dec23a27e40c25b5837184996847a94b1e6046e69c5b608442e7a5f36e79c",
          "sha256": "f81c17b574bc32b7fe8bbe286b2f953d3a6056000d7df748704fe244f54cba2b",
          "sha1": "ba5ea350dc6d2e8925cc8013be4e9195501f94f2",
          "md5": "4022a45c55c1c6ef830b6423028dc582"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-serialization",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-content-negotiation-js-3.1.2-SNAPSHOT.klib",
          "url": "ktor-client-content-negotiation-js-3.1.2-SNAPSHOT.klib",
          "size": 22472,
          "sha512": "d706084aeb608272fc6ddc0f435a765a72ad306e5f1cd0ed5f2eae041c57bfcb739dec23a27e40c25b5837184996847a94b1e6046e69c5b608442e7a5f36e79c",
          "sha256": "f81c17b574bc32b7fe8bbe286b2f953d3a6056000d7df748704fe244f54cba2b",
          "sha1": "ba5ea350dc6d2e8925cc8013be4e9195501f94f2",
          "md5": "4022a45c55c1c6ef830b6423028dc582"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "ktor-client-content-negotiation-js-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-client-content-negotiation-js-3.1.2-SNAPSHOT-sources.jar",
          "size": 5599,
          "sha512": "80866f50727a5867002741697e3d72292ffbafaadcdfb64d14baf2fb226b8690fe46a9d65f6b7111ac1b553629b1755a94eed8898cdcaa05952c1409bfa2caba",
          "sha256": "1f095f5a9ab293dd38a10b5d76b97509c65c8a0b2cbcf7f5e0fd315919134c8c",
          "sha1": "4690a5c6f563475c51f568d04188e8c29e19587a",
          "md5": "3c4c023f83b28fb6f4b276d602e78c6a"
        }
      ]
    }
  ]
}
