{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-client-darwin/3.1.2-SNAPSHOT/ktor-client-darwin-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-client-darwin",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-network-tls",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-darwin-watchosSimulatorArm64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-client-darwin-watchossimulatorarm64-3.1.2-SNAPSHOT.klib",
          "size": 111817,
          "sha512": "373acc27894ad7a25dc207da11d20019641bd341ada463f0bf425a57f9a6e73465110cc0585fbfa11ff877155b701645e9759bea0f088c3d12d6516d6d093288",
          "sha256": "17ee1b8d98e706aba8168db6d2d31ace7900fcb3831ab57b1193042d5761c2cc",
          "sha1": "799e4dc212b4341405a763bb4da8c4b97722cff9",
          "md5": "4e67ff6f8cdb773b9defe9728e73eb4e"
        }
      ]
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-client-darwin-watchossimulatorarm64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-client-darwin-watchossimulatorarm64-3.1.2-SNAPSHOT-sources.jar",
          "size": 25756,
          "sha512": "6a79a18326d64480f49a4b28afa8068aab391d8414e33107f2ee18adcf4c5d6cdf2f58c66db7dfd7ce143b288abf091bf04117eb420b571ab6ec73181eb375fe",
          "sha256": "94e655fe3ec0a92636a4f92d9ad06d7f7b56913e1b40552a92e543d294024cfe",
          "sha1": "f9e5bf929004fbb9ac5c1f78dd11c80ee7ca3137",
          "md5": "a48e87b79ff187f2a2b1e3a2dc37816f"
        }
      ]
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-network-tls",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-darwin-watchossimulatorarm64-3.1.2-SNAPSHOT-metadata.jar",
          "url": "ktor-client-darwin-watchossimulatorarm64-3.1.2-SNAPSHOT-metadata.jar",
          "size": 17906,
          "sha512": "f235acf1d97fa25bbe2d7f64e9d9958a4146695131f73e2d91cdc9edb7ba83dba2407a027e43a271f0587e8c118054e05a169afb20c0ef234031571a031565cc",
          "sha256": "71747ce937a653b4fd2bbd883c99598e2c2435d9e930bce6c6f3de73906e7aa6",
          "sha1": "ddf9744ac0e0933422db37c7f2913a5cdc918205",
          "md5": "d98bfcfe94d90fb9df3d77941379d323"
        }
      ]
    }
  ]
}
