{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-client-cio/3.1.2-SNAPSHOT/ktor-client-cio-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-client-cio",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-http-cio",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-websockets",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-network-tls",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-cio-androidNativeArm32Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-client-cio-androidnativearm32-3.1.2-SNAPSHOT.klib",
          "size": 70702,
          "sha512": "a447038fdad9221e53d5f023bd0ed4dc7d6bf670a40759ba7ebf4722c5c8e0207d0d28694930d9dd1e6c14208b7366da1f771389a2d5163d48a121cc70f5e71e",
          "sha256": "5aceae18fa7905f79e5c8751214d4213d77b19c75aca452b13ef7b62f72b42c3",
          "sha1": "efe74c3434785136a237dd6b784544682818bacc",
          "md5": "b81e06013e6ab62cbcb297abec7d0281"
        }
      ]
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-client-cio-androidnativearm32-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-client-cio-androidnativearm32-3.1.2-SNAPSHOT-sources.jar",
          "size": 15985,
          "sha512": "e7c59c75df5229e8bc521b447b17a3acded61e885ac7514992d7200ea0fd2ea62ecbb06d5ae99c1f9a9faf851ba683e121fadcd5081203fe31b64e2485a041b9",
          "sha256": "fc95d95d571b6502e05f1fa2a3e94bddc88034c78c64fbd8ce850cdff910ccda",
          "sha1": "8d61e6c44b169aea23c9fc6fcf128ec0058700cf",
          "md5": "cfdf105d59b25045788ce77af2911f98"
        }
      ]
    }
  ]
}
