{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-method-override/3.1.2-SNAPSHOT/ktor-server-method-override-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-server-method-override",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-method-override-androidNativeX86Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-method-override-androidnativex86-3.1.2-SNAPSHOT.klib",
          "size": 6817,
          "sha512": "9222a442cb149da72cb6043abd90e4331414f87372f08c345737755c359c1510dec4b6bdc44ff57bb28c2d371e1d8a164a21a7aa3210e5767a51a3fa6c409e5e",
          "sha256": "f056a757e3bdcc3e86a39b937fa8545a29f2bd7918bb424a892c3670b675be86",
          "sha1": "35b8da780959daa1a32ec262b5d31ee6e9694bc4",
          "md5": "ba0ccbfba4be4f9b3c893625c483ffe4"
        }
      ]
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-server-method-override-androidnativex86-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-server-method-override-androidnativex86-3.1.2-SNAPSHOT-sources.jar",
          "size": 2076,
          "sha512": "afc801d002869e568c4b161067f927345d3309599fa2e817341901aed806dca5517c1bfefd08f5e863cbb32007d6ed4f5610de27e8c53562bac4f15d32b7d01a",
          "sha256": "6603e7b86c97043ea34a248208feaf3708a30ae2626f0bcc81ce97e7c9c574e1",
          "sha1": "f7ba979af0b51b1ed0a4e242615073c938dfc354",
          "md5": "c5c4f724c9a5250d5935327d4516e740"
        }
      ]
    }
  ]
}
