{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-status-pages/3.1.2-SNAPSHOT/ktor-server-status-pages-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-server-status-pages",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "watchosDeviceArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-status-pages-watchosDeviceArm64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-status-pages-watchosdevicearm64-3.1.2-SNAPSHOT.klib",
          "size": 18145,
          "sha512": "f823c8fee54b6bb071aebc6028cb971afd8698c622475a935ab2e39c48d9d7b3fff06d18b24af72868b0397c31486bdc0920f18d7078a4a0d75e634b61484ec2",
          "sha256": "f53d323703088d7e6d394dfa71c7d30ffdea0f6534c58cc7634ad760f7e00ab6",
          "sha1": "116e87d7b4c8c7faf936dc44d9e314c6f769b29a",
          "md5": "b76e5bd771a891fb6a3e51aa0600305c"
        }
      ]
    },
    {
      "name": "watchosDeviceArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-server-status-pages-watchosdevicearm64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-server-status-pages-watchosdevicearm64-3.1.2-SNAPSHOT-sources.jar",
          "size": 4758,
          "sha512": "6b1a6e1606534e11002bc47a2d5ed94b186a4e02a2f868ff3c3687b7bba676b323c77d45847a5acdc9a27433e4546f781db9ad4f09eb431a48370d31e1d3a03d",
          "sha256": "ba3d5d42cdc12b18d9c449179b9ed4c0ef3d0b020ac641fe0eae9742a84dce08",
          "sha1": "e314d526d0e34a6fef84635936faec5915fa9554",
          "md5": "f58150dbe90df72f4f2741c8447d9c34"
        }
      ]
    },
    {
      "name": "watchosDeviceArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-status-pages-watchosdevicearm64-3.1.2-SNAPSHOT-metadata.jar",
          "url": "ktor-server-status-pages-watchosdevicearm64-3.1.2-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "6a9d004b7b1dbe705338ab536e104e89b0c862c50f44e0cab2ff6041e46cba33ef3f92575c5bf0fdc4942568bd734a128b7fb9d6562f654c6ec08838fcdaa4b2",
          "sha256": "8e5a91cf6a6a8c101028b864ce58545222eac0d8f09cefd157a43eff5ebfff8b",
          "sha1": "3c8053787b0e3743f462f67f349fa71610295352",
          "md5": "48cc397b0448d1e872e818ca2efd11f8"
        }
      ]
    }
  ]
}
