{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-logging/7.0.6/kotlin-logging-7.0.6.module",
    "group": "com.vickyleu.oshai",
    "module": "kotlin-logging",
    "version": "7.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-logging.klib",
          "url": "kotlin-logging-watchosx64-7.0.6.klib",
          "size": 53082,
          "sha512": "34bf4816ee24ee3ae6499eb43741bc6fe73139775af2580b4c6c58bbad000475c8b64796deab3b936c3f68e8ef663cd4601918777e393c503a7b78b8de1e143b",
          "sha256": "49e6fa2c41bbbdf57d90e6a2c0140c00624944988964c5c06902f963a30c414b",
          "sha1": "9cf989996cf1b8bfe3ab5364f559d6479d2504b4",
          "md5": "2346cf33170c5b05d80fc84f6c5616dd"
        }
      ]
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlin-logging-watchosx64-7.0.6-sources.jar",
          "url": "kotlin-logging-watchosx64-7.0.6-sources.jar",
          "size": 16496,
          "sha512": "bd1dab8709b1a2d3cc798bf285bf936216e5ea5759f80e89e8af56bcf76e52d30352deaf335e0dc0fe8bb230482e02b022c7c872377418038668a3f372015996",
          "sha256": "4e273ad46eff6f1878a64f6b6ff98477709223dfecaa6d63fd3019fbb4da6162",
          "sha1": "2bfe758ad68d35ee3131001cd5dff984e52c890b",
          "md5": "50ce16cbbf7a625e8b862c29d87b3b79"
        }
      ]
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-logging-watchosx64-7.0.6-metadata.jar",
          "url": "kotlin-logging-watchosx64-7.0.6-metadata.jar",
          "size": 9248,
          "sha512": "a874084ebc1867e7b12966f0517b17fea8ffe1fe8ab0cfc5c8901ff6fc9257b2a277d7772fd2a18567b1aa4c5c3e61565b9d330ff580ba6be6c85d8d2ceacbd9",
          "sha256": "78d71a372dda60efef045b41bf317b98d7c18a7a9d26004f715d715e78200fa2",
          "sha1": "90c066c5a561ce793e86528b160108f3e1e1708d",
          "md5": "70495cb6d2f9b1aef9472abdddee4fd1"
        }
      ]
    }
  ]
}
