{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-http/3.1.2-SNAPSHOT/ktor-http-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-http",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-utils",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-http-linuxArm64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-http-linuxarm64-3.1.2-SNAPSHOT.klib",
          "size": 397934,
          "sha512": "1a9369b868e82ac52d0437e73764f1c43939d50452cef9a891ee9021db4c3e6fd24f7972e730de53b37eacb9c92c0206eefc9a5beca772b0f5eafb5bc58eb7cc",
          "sha256": "953179b2282a6f62b1bbdab6713a0861d6a922fd2a0e4a44ed7b011c1015dbbf",
          "sha1": "20ba0735f4c59a92223936fcb9859d6a22286bba",
          "md5": "7b368a20aa43e6b63510e4a6118eb940"
        }
      ]
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-http-linuxarm64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-http-linuxarm64-3.1.2-SNAPSHOT-sources.jar",
          "size": 88187,
          "sha512": "c643a94f0720cb2d499b38e0c384e929d976b7becbbbe771ebc65852b59bba4c1268c32e52ac06dce1eed64c0b11297170b856619f0df326e698fac5b3a84566",
          "sha256": "3a2ccc35b4cae3370861cf34f506dd2c85af1e4cbd34ff563f1b19efd9f82c36",
          "sha1": "fd340df2b5c3ee4286a2cb8f1860b35a54ebf331",
          "md5": "3ba0cbcd501b20e35666ce00cdb915ea"
        }
      ]
    }
  ]
}
