{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-client-auth/3.1.2-SNAPSHOT/ktor-client-auth-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-client-auth",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-auth-mingwX64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-client-auth-mingwx64-3.1.2-SNAPSHOT.klib",
          "size": 53484,
          "sha512": "939f227c1e2b48e9a08549529501e95db8d5f556336984f13d1717c21cd4077bb71a6b68adaf3752cb32716ddb11927dbf6f9290eff4d495bf00f57c725ec61e",
          "sha256": "0bd32475a42d41491ed4a7ee4d6ecaef79775699eca52e0649133f942b6a88de",
          "sha1": "6243e72fc9cf0c71bdcd33c48f4b63578f01b86b",
          "md5": "d82afd2467f5cf9b3580f53602265967"
        }
      ]
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-client-auth-mingwx64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-client-auth-mingwx64-3.1.2-SNAPSHOT-sources.jar",
          "size": 12670,
          "sha512": "565278687b8b7d6d0f81174a538e3e36bec2abc6aae7e78283d0afc83759396844cf5d8c19c815bc0e43b87aa0523a92c06107eb6d310400f13ab25534298066",
          "sha256": "d547799a79c9a25bae79fa8ac8322a7eb5a6f44867f2be7a925bf9d4a894f922",
          "sha1": "7425b17152bc668e37ee3e15c572de3d4d5ac339",
          "md5": "b6d07b98246acd355ac78681c561888d"
        }
      ]
    }
  ]
}
