{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-body-limit/3.1.2-SNAPSHOT/ktor-server-body-limit-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-server-body-limit",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-body-limit-linuxArm64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-server-body-limit-linuxarm64-3.1.2-SNAPSHOT.klib",
          "size": 10589,
          "sha512": "8d16fd7409299a252b5278419b708d1299c8ee5dc59ce4b0104bf7b4a492d157f791843e19b559d2718658fd5f5b2aad4c196b0586eb59a439984f4006e601c7",
          "sha256": "c543ba716d12b008df0d873bf2f1065f29cf1b76c0bceda50f4670e76645a6ca",
          "sha1": "38b66a24b30a464da7bc1e2ca07fff90bead1f7f",
          "md5": "8500ab9b761db85537fe87264db567f6"
        }
      ]
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-server-body-limit-linuxarm64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-server-body-limit-linuxarm64-3.1.2-SNAPSHOT-sources.jar",
          "size": 2302,
          "sha512": "1fe49fe1e96d0841045bb151fc8490f761c5c575cb7acad2a5bf076e41e418f7029490236ef35f81dfa0d15187fccb77f80a894aea42ea16b8ed7171b9b2f7a3",
          "sha256": "826cb7e25738122cd5bbc4a6b31bcaea147fd77d806e27211858dc6bc1bc3158",
          "sha1": "407d1eb0bf5b46fac46965247f4f147c5d6ec0fb",
          "md5": "84968e6e84e9497c4ef4155c8e3b5e68"
        }
      ]
    }
  ]
}
