{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-client-darwin/3.1.2-SNAPSHOT/ktor-client-darwin-3.1.2-SNAPSHOT.module",
    "group": "com.vickyleu.ktor",
    "module": "ktor-client-darwin",
    "version": "3.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-network-tls",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-darwin-iosArm64Main-3.1.2-SNAPSHOT.klib",
          "url": "ktor-client-darwin-iosarm64-3.1.2-SNAPSHOT.klib",
          "size": 111693,
          "sha512": "4cc775aacec69be16b92bd616a0984dca34127d29d1ea73f7da535157cf8ddab98664d012053cb9d6ffb7d379361ef53d07710cca2205ac020a04d25fc6302b8",
          "sha256": "e293b17df529f4c88f66341eb075c3bbbd1cd62e37dfdcc3d830b44423bc9abc",
          "sha1": "21ae1fc7b4974ad3678e2bbfbb377fd690ba0d46",
          "md5": "e4a088bb147e4ba7a9f4e32773843343"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktor-client-darwin-iosarm64-3.1.2-SNAPSHOT-sources.jar",
          "url": "ktor-client-darwin-iosarm64-3.1.2-SNAPSHOT-sources.jar",
          "size": 25756,
          "sha512": "6a79a18326d64480f49a4b28afa8068aab391d8414e33107f2ee18adcf4c5d6cdf2f58c66db7dfd7ce143b288abf091bf04117eb420b571ab6ec73181eb375fe",
          "sha256": "94e655fe3ec0a92636a4f92d9ad06d7f7b56913e1b40552a92e543d294024cfe",
          "sha1": "f9e5bf929004fbb9ac5c1f78dd11c80ee7ca3137",
          "md5": "a48e87b79ff187f2a2b1e3a2dc37816f"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.vickyleu.ktor",
          "module": "ktor-network-tls",
          "version": {
            "requires": "3.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-darwin-iosarm64-3.1.2-SNAPSHOT-metadata.jar",
          "url": "ktor-client-darwin-iosarm64-3.1.2-SNAPSHOT-metadata.jar",
          "size": 17906,
          "sha512": "25f74cbf99d1d1bc445d7c17c73c566dbd6e22cc4b507a8fc7d4e322dd23a0738c3de2d0184c10656b6991f4de555715f8a3b6fb1284c100a334dbfea21b580c",
          "sha256": "ff6c1d76f8cdfb5b16c028bd53338f4ac41a537e41ee12185e5e75d96b0d984d",
          "sha1": "c2714f2094389391d4de608c9c3fad5dbe7faaa2",
          "md5": "5583a7c755f90958a82e63d5343a1e53"
        }
      ]
    }
  ]
}
